### ISSUE TITLE
First steps toward minimal A/B system for UX

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#1838]
## Enhancement

It would be nice to have a way to experiment with new UI and UX behind an A/B type system. It could be similar to the release flag system. Ideally there would be a simple way to automatically assign by org or by team (undecided) but then override that in a minimal admin. The goal is to know who is using what UX, and the results of the experiments (what is better, worse, same, etc.) Discussion points:

### Acceptance Criteria
- Researched ways folks are A/B testing
- Designed IA of SUPER scrappy admin view
- Scoped SUPER scrappy admin view from backend perspective

### Estimated Effort
- 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
A minimal affordance would be nice to test UX of the demo (came up today in sprint planning).

**Comment by jordanh** [comment]
I've been thinking about this, and I think we might just start here:

1) We render / take action different depending on the presence or absence of a user flag
2) A/B test measurement is performed via segment events (i.e. funnel toward a goal)

Viola! We're done.

I _think_ we have nearly everything we need to do this today save a client-side pattern. What do you all think?

**Comment by ackernaut** [comment]
I like that approach, feature flag + segment events.

**Comment by avivapinchas** [comment]
From prev work with AB testing, the Q's that I think we ought to address here are: 
- What's our process for setting up the AB test? I imagine we'll have quite a few of these coming from the Growth side, so we should define how we ask for or propose a test, how we track what tests are running, and how we make sure tests don't conflict with one another 
- What's our process for reviewing test results? My recommendation would be pulling this into Amplitude, because that already has an easy way for me and other Growth folks to compare behavior differences among folks 
- How do we make sure the data presents a valid outcome? What I mean by this is: we may have relatively small user numbers, which might mean it takes forever to run a statistically-relevant AB test, and small non-significant tests can lead us astray. I have a vague memory that there are ways to adjust how different treatments are served to account for smaller sizes and let you run tests more easily and quickly, but sadly I can't find anything on the internets about this 😭 Regardless, this is a thing we should consider.

**Comment by jordanh** [comment]
Iceboxing for now
