### ISSUE TITLE
Diagnose issue adding private Slack channels

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#2120]
## Bug

It seems that you can indeed add a private channel but that the UI view may look like it didn’t work. Also, the Slack auth view only mentions public channels

![screenshot 2018-05-09 11 52 04](https://user-images.githubusercontent.com/307286/39835672-7841b666-5396-11e8-9bf9-cdc040ca9c46.png)

### AC
- Users can add private channels. The Parabol UI updates correctly to show the added channel.
- Do we have the option to configure the Slack auth view so that it allows and states the ability to add both private and public channels?
- It looks like the channel name loses the first character? `t_exco_talent` becomes `_exco_talent`?

### EE
- 10.5 points

**Comment by ackernaut** [comment]
Iceboxing per policy

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10352351/) 🔒  writes: 

> Although I can select the private channel when adding the app, I cannot find (or search for) it when going to the Team Notifications drop-down.
> 
> So, I guess push notifications don't work for private channels. 
> 

Notes: push notifications don't seem to work for private channels. Steps to reproduce - connect slack integration > add a private channel > start a new meeting. The notification is pushed to the Parabol app on slack but not to the private channel, the UI also shows notifications set to go to @ Parabol instead of the selected channel

![Free_Online_Retrospectives___Parabol](https://user-images.githubusercontent.com/60167404/101798260-e688bd00-3ad8-11eb-9bb0-033d347a31fd.png)

**Comment by gcrickman** [comment]
Comment to re-open issue

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10915451) 🔒  writes: 

> I can't send slack notifications to private channels

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10352351) 🔒  says:

> Integration with Slack doesn’t work if it’s a private channel
