### ISSUE TITLE
Meeting notepad / team takeaways

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3337]
We get a lot of customer feedback about the following:
- private notes during meeting
- public notepad
- Meeting takeaways (as part of summary)

A few ideas:
- There is a notes tab in the future right drawer.
- The is an additional private notes tab in the future right drawer
- The last phase of a meeting is a "How'd it go" text area. we could include a star rating here & it'd make sense. the only probably is how to get people to go from discussion item 3/25 to this phase. I assume the "end meeting" button would have to actually redirect to this phase.
- A collaborative notes component would be a good excuse to introduce atlaskit as we move away from draftjs

**Comment by jordanh** [comment]
Removing from Sprint board until this issue has AC and EE (but I want to contribute to the discussion)

**Comment by jordanh** [comment]
Notes are so general purpose, I'd like to understand the individual needs that cause a user to want to take a note in the first place. Brainstorming things I've heard:

## Public Notes

* When we are doing a incident port-mortem, we want to collaborate on writing a note that details our root cause analysis, so that we can share what we've learned with others
* When we are doing a retro, we want to collaborate on a working agreement, so that we can change our behavior

## Public discussion
* When we are running an async retro, we want to jot messages to each other (i.e. not TODO items), so that we can hold a discussion

## Private notes
* When we are holding a discussion, I want my own space to take notes that is private from the team, so I can make my own reflections

Here's what my gut says: private notes _could_ be fudged using the #private tag today, so they are the least interesting. This leaves public discussion and public notes.

Where this leads me is a "note" object that can be created by anybody on a discussion thread. Shitty prototype:

> ### Discussion topic "Pull requests"
> 
> #### Reflections
> 
> * We should stop requiring code reviews for trivial changes
> * We should continue requiring code reviews for anything complicated
> * Code reviews take too long
> * Do we really need 2 people to review each PR???
> 
> #### Discussion
> 
> *  **Add new: [☑️ Task]** or **[🗒 Note]**

# Publishing

If we took this approach, Note objects could have their own Publish integrations. For example: Publish to Notion, Google Docs, Office 365, Atlassian Confluence, Guru...

# Templating

We could also allow a team to make note templates (5 whys, root cause analysis, working agreement/policy, role description).

# Tagging

Notes could be tagged, like any object in Parabol. A special notes tab on the dashboard would let you filter notes by tag or date created.

Perhaps every meeting has its own tag?

**Comment by mattkrick** [comment]
> Templating
this is _very_ similar to what taskade is doing (and they've got $5MM until they get it right). I think it absolutely is the end goal, but it'd be nice to avoid fighting them until we have the manpower to fight

- I agree, a "Note" object is the right course, but I don't think a Note belongs in the threaded discussion. I think that's a `Comment` object that has an `anonymous` boolean on it.
- I think a `Note` is collaborative. I think a Task should _never_ be collaborative
- My biggest fear with a `Note` object is that people don't understand the difference between `Note` and `Task`. It happened before with our private `Action` cards. I think the only way to minimize confusion is to never give them a choice between a Task or a Note. E.g. we can have a `Note` field in different meeting phases, but we're careful to never have one next to a task.

**Comment by ackernaut** [comment]
Working on notes [here](https://docs.google.com/document/d/1i2wuLJkTpkHAF-jLNytU3dDB21Kcgvlgp5SQiBxXmHU/edit#) for editing affordances and completeness

**Comment by ackernaut** [comment]
I’m digging in deeper in the linked doc in the [comment above](https://github.com/ParabolInc/action/issues/3337#issuecomment-553521600) but here’s my TL;DR
### Object system
The object system favors flexibility and compostability over constraint.

- Objects (not exhaustive):
  - Topics (e.g. agenda items, reflection group topics)
  - Comments (limited to 2 levels deep)
  - Tasks (can have a thread on it)
  - Notes (can have a thread on it)
- Threads exists on objects (topics, comments, tasks, notes)
- Threads can have any objects in them

### UI and UX implementation
We add friction and constraints in the interface depending on the job stories we are solving for. E.g. if we learn that a thread in a specific meeting phase (e.g. retro group discussion) should only allow for notes, not tasks, then we build it that way.

**Comment by mattkrick** [comment]
iceboxing, we'll need to be smart about this so as not to try and compete with notion, et al.
