### ISSUE TITLE
Meeting participation without signup

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3371]
Collecting user feedback here:

[A user](https://app.hubspot.com/contacts/3888472/contact/5397101/) says:

> ...it would be too cumbersome to make people sign up to the tool, especially when you're dealing with busy CXO level meeting participants, that would be a blocker in our company."

We've heard variations on this before. A theory we've got (h/t @mattkrick) is SSO would reduce this friction for new enterprise users. Going to keep this user feedback thread open to see how frequent the report is and ask after SSO.

**Comment by mattkrick** [comment]
worth noting that with auth0 out of the way, we _could_ create a user & team member, stick a flag on em saying they're anonymous, stick em on a team, and then let them in the meeting. Technologically, it's not impossible.

However, I think it's a huuuuuge footgun. 
- People are going to log in anonymously because they don't remember their password
- they'll keep logging in anonymously & the team will be full of anonymous users. 
- they won't see tasks created for them  from the meeting before making the meeting less productive
- tasks created for them will go stale if they don't create a user immediately after the meeting, meaning action won't be taken on them
- no one will know who exactly is the creepy anonymous guy in the meeting

I think it's our job to give folks a productive meeting & a temporary user prevents that. If they want a signup free experience, there's always SAML, and that means we get $. win-win!
