### ISSUE TITLE
flagOverLimit not removed when organization left

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3377]
## Issue - Bug

Reproduction steps:

1. Create a new team and org
2. As `su`, run `flagOverLimit` mutation on new org
3. Reload Parabol, note that `flagOverLimit` banner displayed
4. Invite other user, User B, to team
5. Leave team
6. Navigate to Organizations, promote other user to BIlling Leader
7. Leave Organization
8. Reload Parabol, note Over Limit banner still displayed

- **Estimated effort:** 10.5 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - Leave org, see `flagOverLimit` disappear

**Comment by mattkrick** [comment]
there's no great way to do this, since the over limit copy is tied to the user directly. for that reason, i'd flag this as working as intended.

- if we put the copy on the organization user, where it belongs, then we have to do an additional lookup for every single user, and that initial query is already a crazy large bottleneck.
- we could store `overLimitCopyOrgId` on the user object to reduce the extra lookup
- if we just wipe it when removed from org, then someone could create a new org, leave it & get the notification to get away

in practice, i don't see someone leaving an org for any other reason than escaping this message.

**Comment by jordanh** [comment]
Scrubbed, iceboxing for now
