### ISSUE TITLE
Some clients don't get all the Reflections after load of Group phase

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3433]
## Issue - Bug

@mattkrick, remember when you saw this one during our retro? [A user](https://app.hubspot.com/contacts/3888472/contact/1274051) just reported it too:

> some people don't see every idea in group phase

- **OS:** macOS
- **Browser:** Chrome
- **Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/action/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - always load the Group phase and sell all the reflections, without needing to refresh

**Comment by mattkrick** [comment]
I got lucky & managed to reproduce this locally, but not sure I can do it again.
What i know:
- when the `createReflection` mutation returns, the `reflections` array is empty
- that empty array causes the group to get filtered out
- what i think is happening is that the subsequent fetch is reusing an old dataloader, one that doesn't have the new reflection in it, but that's a new pattern, so there must be something else

**Comment by mattkrick** [comment]
OK so this has happened before my dataloader changes, so the above couldn't be the cause.

it'd be impossible to miss a createReflection message but get the navigateMeeting message after that without an explicit disconnect because TCP would keep resending the createReflection packet and if it couldn't it'd register a disconnect, so that can't be it (i don't recall seeing a disconnect message)

really not sure about this one, will just have to keep monitoring it & see if it shows its face again

**Comment by mattkrick** [comment]
haven't seen this one since the big server changes, i think it may be gone?
