### ISSUE TITLE
Retro Templates as UGC

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3465]
## Issue - Enhancement

Over the holiday break, we received some interesting user feedback from [this user](https://app.hubspot.com/contacts/3888472/contact/6592301):

> I just created a new retrospective format “The Learning Matrix” (https://www.tastycupcakes.org/2011/08/learning-matrix/). The problem I had is that I had to add this format 3 times, one per team I am currently working with. It would be great to save some new formats in my user profile, and quickly add them to each of the teams that I have. I know it can be a lot of work, just leaving the suggestion there 😉

There are two JTBD I can think of here:

_From a user's perspective:_

   - When I am a scrum master and I lead the same sort of custom retrospective for all of my teams, I want to be able publish this format across my entire org, so that I can input the template once and use it everywhere

_From our perspective:_

   - When a user creates a valuable retrospective template, we want them to be able to publish it publically to the internet, so that we benefit from the SEO and more value can be built on top of the product as more users use it

I'm going to open this issue as a discussion to track user feedback and iterate on the idea to define a set AC/next steps.

**Comment by jordanh** [comment]
An idea i've got is that each template has a permission level:

1. **Team**: private to team
1. **Org**: make available to my entire org
1. **Public**: make available to the public

Only templates with **Team**-level can be edited. However, each template could have a "Fork" or "Copy" button that allows somebody to create a copy, customize it, and potentially re-publish it by changing the permission level.

**Comment by ackernaut** [comment]
I think whatever we learn here may be useful for marketing a 1:1 meeting. Some manager is looking for a post on good formats, finds our templates, tries and likes a demo/video, and shares a link to a real meeting space with their report for their next/first 1:1.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/10555451) 🔒  writes:

>Would it be possible to add an above/below line retrospective format?

**Comment by ackernaut** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/8749601/) 🔒 writes:
>Thought for a feature - be able to use customized meeting templates to multiple teams. For example, I made a "Marketing Tech Template" that I use for all 4 of my teams. As we expand with more teams, it would be nice to have not have to remake that template for every new team I add.

**Comment by mattkrick** [comment]
Here's how I think this works:
- A template has 1 of 3 scopes: `team`, `org`, or `public`.
  - team means it's only visible to the team
  - org means it's only visible to the org
  - public means anyone on the platform can see it. this is the first step to becoming a social network 🙈 
- If you belong to the team that owns the template, you are an OWNER, else VIEWER
- The owner can read, update, and delete the template
  - deleting a template hides it. if it has no subscribers, it may also be deleted (or marked inactive)
  - updating a template causes the template to change for all viewers, since they all use the same one
- The viewer can read the template. if they want to edit it, they must fork it.
 - forking a template clones it and adds the parentId. it unsubscribes from the upstream template.  The forker is the owner of the new fork.

**Comment by ackernaut** [comment]
Via @shawneeatparabol 

A [customer](https://app.hubspot.com/contacts/3888472/contact/9633201)🔒reported that the following feature would save them time as they expanded their footprint within the platform:

>When we find that a specific template works really well it would be great if we could make them available templates to the other teams instead of having to manually recreate it in each team.

**Comment by gcrickman** [comment]
A user writes via chat:

> I created a template for one my teams, how can i reuse it for another team ?

**Comment by jordanh** [comment]
Prioritizing for design & implementation
