### ISSUE TITLE
Spotify integration

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3555]
### Issue - Enhancement

During retro meetings, when folks are adding reflections, there's ~5 mins of silence, which can feel awkward. It would be nice to have some background music during this time. With Spotify, team leads could either select a list we create, curate their own list that reflects their team, or ask team members to contribute songs to a shared list. 

### Acceptance Criteria (optional)
Users can:
   - Select a Spotify playlist to play during quiet times in meetings

**Comment by ackernaut** [comment]
This is what I really want. The only timer option is 2:41 and this plays in the background: https://youtu.be/kLp_Hh6DKWc

Repeat ad nauseam

**Comment by shawneeatparabol** [comment]
My client [https://app.hubspot.com/contacts/3888472/company/3223836226](url) would also like the inclusion of music for creative thinking purposes

**Comment by jordanh** [comment]
While giving a demo to [a partner](https://app.hubspot.com/contacts/3888472/company/2328103455) today there was a request for background music during the reflect phase

**Comment by jordanh** [comment]
Questions and thoughts.

How would a Spotify integration work? Surely, we can't rely on a single user to add Spotify and then re-stream music. Spotify's own [remote DJ mode requires that up to 5 users](https://www.engadget.com/spotify-remote-listening-party-group-sessions-162131360.html) all have Spotify premium in order to use the future.

Would we simply be listening to that users music picked up by their mic? That seems legally dubious, and a bad user experience.

Instead, do we lead with audio conferencing instead of video conferencing?

How does [JQBX](https://www.jqbx.fm/) work? (answer: I think all users have to have a Spotify Premium account too)

As an alternative to streaming, perhaps we'd add our own tracks and stream them to each user? How would we manage the mics and prevent echo?

**Comment by jordanh** [comment]
Is it a Spotify integration or is it sound design?

Going to icebox this discussion for now and wait for the tension to pop up again.

**Comment by avivapinchas** [comment]
> Is it a Spotify integration or is it sound design?

I think they serve two different needs. Sound design creates a richer app experience. A Spotify integration lets the user set the tone of their experience, possibly inject some personality or unique flavor into their experience. In my mind, it's the sound version of letting people upload a team profile pic or set a color scheme.
