### ISSUE TITLE
Frag a video

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3599]
I think this is the future.

Loom: begin recording a snapshot with the intent to share.
Zoom: have a video call
Parabol: begin a sync call, then when you're hitting on something profound, hit the record button, snap a segment, push it to a thread. it's like the video camera on your cell phone. you see exactly what you could be recording, but you don't hit that record button until you're ready. 

the magic is going to be the UX. How do we incentivize folks to make short video segments? We limit the time to 10-20 seconds. It's the same UX that made twitter, vine, etc. so popular. Video segments should live in cards. they can be threaded on. they can live in threads. I'm willing to bet a fair amount of chips that this is the 1 killer feature that we need.

**Comment by ackernaut** [comment]
I’d like to riff on this! I think we:
- add the ability to comment via video in addition to text comments in a thread
- threads can be on any topic (aka agenda topic, retro topic, etc.) in any meeting type including the simple agenda-only meeting type. Threads, like tasks, have a continued lifespan outside of the meeting of origination. Therefore video comments can be in any meeting type.
- add threads to tasks, accessible via expanded task view. Now tasks can have video comments. These threads probably include replies to tasks if and when they’re created in a meeting thread for all the background and context.
- anytime there is a diff (new text or video comment) on a thread that I haven’t seen, we give a collapsed highlight at the top of the timeline (in the time-based event stream), tapping through takes the user to that context. We need a razor for what I am automatically subscribed to (e.g. I participated in a topic in a meeting, I become subscribed to that thread) and we wait for folks to ask for the ability to mute a thread
- we make it easy to start a bring-your-own-agenda meeting with another person in the async (topic + thread + video comment or text comment) it’s a thread that’s elevated in order to get their attention (makes elements hot like the meeting menu, timeline, and maybe something in the team view or user view—their avatar probably gets stuck to the side of my chrome in certain cases), they can upgrade to realtime sync video if needed
