### ISSUE TITLE
Invoice proration display fixed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3621]
# Bug

Refer to this invoice for [this user](https://app.hubspot.com/contacts/3888472/contact/4393101) 🔒 :

![image](https://user-images.githubusercontent.com/103000/75805533-dd431680-5d36-11ea-89cb-b1e05271df03.png)

(Parabol userId `google-oauth2|103130973285055993760`)

## Acceptance criteria are:

Invoice calculated for user​ where:
   - Last month's adjustments new users added calculation is correct

**Comment by mattkrick** [comment]
- the autopause function should check for how long the person has existed. in the case above, autopause happened the same second that a user was added. crazy!

- there are a bunch of items that come in on the same second. we weren't prepared to distinguish amongst all these.

**Comment by mattkrick** [comment]
we need a system that can handle multiple signups that occur in the same second. I'm not sure why (maybe 20 people seated around a conference table?) but that's what has happened & it totally borked the invoices (not the final amount, thankfully, but it looked bad)

first & foremost, the quantity must be correct.
second, we must be able to contribute a change in quantity to a particular user.

we can't just throttle quantity changes. if we did that, then the 20th user to join in the same second would take 40 seconds to join.

 - so, when a quantity change happens, we need to log that to the DB with the same info that we do with invoice item hooks today. additionally, we add a createdAt timestamp and do not have a proration date yet. 
- then, we call a debouncer function that tries to talk to stripe. if it has talked to stripe in the last 3 seconds, it queues itself. then, for a given subscriptionId, it looks up everything without a prorationDate. it then calculates the new quantity. it asks stripe for the current quantity. if the stripe quantity + hooks !== new quantity, then it's (probably) because an extra hook was added, so we try again in another 3 seconds. if it's a reattempt at the point, we forward on the old & new quantities. if they still don't match in 3 seconds but they're the same, then we should just go with the smaller of the 2, log it to have a human look at it & move on. next, we create a prorationDate to send to stripe & log that prorationDate to all the hooks. that date is used as a fuzzy batch ID (fuzzy because the date returned from stripe could be up to 3 seconds off)
- when stripe calls our invoice item created webhook, we then look up all the hooks. we add the invoice item to the hooks. then, we update the stripe metadata to being an array of hooks: `hooks: [{type: 'addUser', userId: 'foo', hookId: 'bar'}]`
- when we create the invoice, we see if the metadata has a hooks prop. if it does, we handle the new version, else, we handle the old version.
- we manually adjust the old invoices that have errors

**Comment by mattkrick** [comment]
OK, atomic system designed.

when a quantity adjustment occurs, we adjust everything in our system (add OrganizationUser, create InvoiceItemHooks, etc) but we DO NOT tell Stripe yet. This is because stripe has the following shortcomings:
- quantity adjustments are not atomic
- they combine invoice items that occur in the same second
- the proration_date is not always the period.start

After our system has been updated, we then queue a call to stripe.
- we put a lock on the subscriptionId so nothing else can modify it for the next 3 seconds
- if the call encounters a lock, it tries again when the lock expires
- once locked, we grab the first hook & process it
- we lookup the quantity according to stripe
- we update the quantity according to the type of hook (add_user, remove_user, etc)
- we unlock the subscriptionId
- if another call encounters the locked 

Updating the quantity triggers 2 webhooks with invoice items. both refer to a single event
- we match the invoice item to the hook by the proration_date and quantity
- if more than 1 is found, we pick the earliest
- we attach the invoiceItemId to the hook in our system (atomic)
- if the hook already has an invoiceItemId attached to it, we start over from the beginning of the webhook handler
- we update the invoice item in stripe with the user, type, and hookId
