### ISSUE TITLE
With many reflections, move to 2-column display in Discuss phase

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3676]
## Issue - Enhancement

With the new threaded discussion feature, reflections stack in one column. When you have many reflections, the column becomes long and you need to scroll, making it harder to see some of the lower reflections. 

When there are enough cards that they'd requires a scroll, could we put this into two columns? 

![Screen Shot 2020-03-20 at 2 54 12 PM](https://user-images.githubusercontent.com/11621016/77209064-4b276600-6acb-11ea-91ba-1f67dbb9897a.png)

### Acceptance Criteria (optional)
Users can:
   - See the majority of reflections in the Discuss phase without scrolling, even when there are many 

- **Estimated effort:** 11 points

**Comment by ackernaut** [comment]
Thanks for capturing. That falls just short of the breakpoint where the card grid would lay out in 2 columns. We have a fixed width on reflection cards in this grid to reduce complexity. Closing the left navigation can afford the necessary space at some breakpoints. If you have a large enough display you’ll see the cards start to form a grid, too. I’ll definitely be on the lookout for improving these layouts, so that it’s better at more widths.

**Comment by jordanh** [comment]
This is already how the product works, @avivapinchas you just got unlucky with the screen width you chose. Scrubbed this today, closing.
