### ISSUE TITLE
Allow for regrouping of cards until vote phase completed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3701]
We're continuing to get user feedback that our linear nature gives anxiety, _especially_ when people are dry running the product or running their first few meetings.

We'll continue to add feedback here until this resolves into new Issue(s) or is closed because it goes stale.

### Related
   * #2948
   * #3312

**Comment by jordanh** [comment]
A user writes (via cha):

> As a facilitator, how do I ungroup cards?
> [...]
> I tried that, but nothing happens when I click on a group, nor can I drag a card from a group.
> [...]
> I am staging/prepping for our retrospect
> I clicked the Vote view
> There is no way to back up?

Me:

> Not at present. We made a design decision that once a vote had been cast, the groups become locked so folks who’ve voted aren’t voting on a set of changing things

The user:

> Yeah, I can see the need for that functionality, but it seems like there would be a need for some sort of reset.
> I can make this work for now. I just wanted to make sure that I wasn't missing something.

**Comment by gcrickman** [comment]
A user writes via chat: 

Is it possible reopen an step?
My page was refreshed and i'ts close de Group step
so i can't organize my cards =/

**Comment by gcrickman** [comment]
A user writes via chat:

> Is there a way to "re-open" the reflection part of the retro?
> The reflection portion closed (I think after a certain time) but people are still adding their feedback.

**Comment by gcrickman** [comment]
A user writes via chat: 

> I wanna go back to Group again
> I need to group the tickets
> but it doesn't let me
> it says Phase completed

**Comment by gcrickman** [comment]
A user writes via chat: 

> Hello, my team have used this for the first time and we really enjoy it. One thing I am looking for help though is undoing an action I've done: I clicked "discuss" before everybody had a fair chance to vote; now it just says "phase completed" is there any way to go back a phase to allow everybody to vote please?

**Comment by gcrickman** [comment]
A user writes via chat:

> Hi. Is it possible to "unmark" a phase as complete. It was done by accident and now we can't properly complete our retro

**Comment by gcrickman** [comment]
A user writes via chat: 

> Hi - we are doing a retro now and by mistake we completed a phase around grouping, can we unlock it?

**Comment by luebbert42** [comment]
Same problem here ... we had to start a new retro to overcome this "issue"...

**Comment by jordanh** [comment]
More feedback from [an enterprise prospect](https://app.hubspot.com/contacts/3888472/contact/11987551) 🔒:

> Main piece of feedback we have from a retro yesterday is somehow we closed the phase when we were about to group the feedback items, there was no way to open it back up again and we had to step through verbally which complicated. There was an option for 'Next' and 'End Meeting' no back or reopen phase. Maybe we were missing something but if not you need to implement this feature.

**Comment by jordanh** [comment]
@ackernaut @mattkrick we've got a boat-load of tension around this single issue—I think this warrants a design exploration.

The root tension is not being able to group or regroup cards after advancing. Yes, phase advance confirmation should address a bit of this tension, but I surmise not entirely. I suggest the following for exploration:

1. We allow folks to group / regroup cards irrespective of votes have been cast on them already (blame your team if you break the rules! just one more thing to talk about during the retro)

or,

2. If one navigates back to the group phase and regroups a card, the votes in the voting phase are reset and a snack bar message or other UI prompt lets you know it's happened

**Comment by gcrickman** [comment]
A user writes via chat:

> How do we go back to a previous phase?

**Comment by mattkrick** [comment]
IMO there are other more pressing design issues. I say we give the confirmation pattern a couple weeks and see if the number of complaints decreases.

**Comment by gcrickman** [comment]
A user writes via chat:

> Hello! a quick question - is there a way to "uncomplete" a phase of a retro meeting? I've hit the button accidentally..
> 
> grayson:  
> If you're in the grouping phase then you can still add reflections
> 
> grayson 
> but if the grouping or voting phases have been marked as "completed" we don't currently have a way to go back
> 
> Unknown visitorAPP 
> so that "Phase Completed" message doesn't change anything at grouping vs reflections stage?
> 
> grayson  
> If you've completed the reflections phase, you can still add reflection cards during the grouping phase
> 
> Unknown visitorAPP  
> cool. thank you very much!
> 
> grayson  
> You're welcome! Let me know if you have any more questions
> 
> Unknown visitorAPP  
> only issue is that it's already revealed, so in some situations it's worth re-creating the meeting :)
> 
> grayson  
> Yes it's definitely been an issue not being able to re-open phases, we're working on rolling out a fix soon

**Comment by gcrickman** [comment]
A user writes via chat:

> There is one thing that's frustrating. When we group our cards, if we don't group one of them, it uses a random title based on the words the card has. Most of the times we want to change that title and we want to do that while we are discussing it. For some reason, there is no edit function in the Discuss section (it has it only in Group and Vote) and we can't also go back
> 
> Is there any way to do that before we press the End Meeting button? if not, can you added as a functionality in future releases?

**Comment by jordanh** [comment]
In a [G2 Review](https://www.g2.com/products/parabol/reviews/parabol-review-4191804):

> If you proceed to the vote or discuss section on accident you cannot go back.

**Comment by is24-sascha** [comment]
Hey @jordanh 

As I see a lot of people struggling with the "phase completed" issue. I just had to reopen a new meeting as well, as we were not able to go back. This bug is quite annoying and I would appreciate when it gets fixed asap. As a quick fix you e.g. could remove the navigation links - this was where I jumped to the next phase by accident.

Nevertheless, I look forward to having our first retrospective in your tool :-)

Best Sascha

**Comment by shawneeatparabol** [comment]
I have consistently received this piece of feedback on all client calls including, this one today
[1](https://app.hubspot.com/contacts/3888472/deal/2065668335🔐

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11184901) 🔒  provided feedback:

> I would like the ability to go backward, if someone makes a mistake we want to go back, especially in the grouping phase, maybe just the facilitator has this access

**Comment by mattkrick** [comment]
for future feedback can you please ask the clients what phase they want to go back to? e.g. do they want to go back from group to reflect? from vote to group?

**Comment by shawneeatparabol** [comment]
[An enterprise level user ](https://app.hubspot.com/contacts/3888472/contact/16813551) 🔐 wrote into support asking for the ability to go back from the voting stage to the grouping stage. 

She was running an async retro, had about 20 reflection cards she was grouping before the meeting, accidentally hit next and proceeded to the voting phase. She would have liked the ability to go back to the grouping phase and barring that, would have appreciated the ability to upload the CSV data back into Parabol to start a new meeting with the same reflection cards so she could begin grouping there.

**Comment by shawneeatparabol** [comment]
User🔐 [Here](https://app.hubspot.com/contacts/3888472/contact/16449051) was accidentally progressed past grouping phase, wrote into support wanting to be able to go back. Had to restart meeting which was not desireable.

**Comment by gcrickman** [comment]
[A user](https://app.hubspot.com/contacts/3888472/contact/11132301) 🔒  mentioned during a feedback call:

> We can only go forwards and not backward, it would be useful for the facilitator to return to previous phases.

**Comment by jordanh** [comment]
Adding to sprint board to prioritize this discussion

**Comment by mattkrick** [comment]
I see 2 options:

The completed group phase has an affordance that lets you reset the meeting to that point.
 - Discussion topic comments & tasks are all deleted (the alternative is they are _maybe_ deleted, and _maybe_ are now a part of the wrong group)
 - All votes are lost

OR

You can still move cards around in the vote phase
 - Any group that gains or loses a card gives back its votes (kinda confusing to the user)
 - participants can mess up the groups when the facilitator is trying to get people to vote
- You still can't go back from discussion to voting

My .02 is we should do everything we can to discourage this behavior. It should be possible, but you shouldn't be able to find it unless you go looking for it.

Proposal:
- If the meeting is not complete but the group phase is complete & the viewer is the facilitator, the group phase has a "Reset" button.
- Clicking the button pops up a modal, "This will reset the meeting to the group phase. all discussions & votes will be lost!" Are you sure?"
- All participants (both those in the vote phase & those in the discuss phase) are teleported back to the group phase

**Comment by ackernaut** [comment]
A reset may feel heavy-handed. I don’t like the idea of aiming for a quality UX until it’s a behavior we want to discourage, then we get unfriendly. If that is the moment the user if hitting the friction, then what UX is resonating? Not the quality UX that had before the moment, but the bad UX they’re having now including the clunky solution.

> Any group that gains or loses a card gives back its votes (kinda confusing to the user)

I’d say as long as the group exists the votes stick to it because the user story is probably more about refining. Only when the group goes from 2 cards to 1 do we give the votes back. Maybe we animate their vote count in some way or show a snackbar message to the affected users: ‘_Some votes were returned due to grouping_ :)’

> participants can mess up the groups when the facilitator is trying to get people to vote

I don’t think this will happen often.

> You still can't go back from discussion to voting

Once folks reach the discussion phase they can sort the topics, add comments, and add tasks. They’re not blocked in choosing what to talk about or in adding more color to the group topic.

I’m not sure many discover that you can sort the topics. Maybe we boost the signal for a tip about sorting? ‘_The votes are in_, _but you can discuss topics in any order you like_. _Just drag and drop to sort._’

It’d be nice to have illustrations from Freddi showing the 3 moves to have a good discussion: 1) sorting 2) adding comments 3) adding tasks

The juice is probably not worth the squeeze to make some of those things work. So, tradeoffs:
- Folks can still group during the Vote phase. We only give back votes when a group goes from 2 cards to 1.
- Voting is fixed when moving to Discuss. We defer on the option to reset to the Vote phase.
- Grouping is fixed when moving to Discuss. They can reshape groups if we build the option to reset to the Vote phase.

Some folks are probably more precious about what the groups are and who grouped e.g. the scrum master only groups. I bet we hear a request to lock down groups during the Vote phase if we opened it up.

**Comment by mattkrick** [comment]
> I bet we hear a request to lock down groups during the Vote phase if we opened it up.

i think our goal should be to make it hard to have a bad meeting. if i can move cards around while you're trying to cast votes, does that make it easier to have a bad meeting? i'd say yes

**Comment by ackernaut** [comment]
To be fair, there are tradeoffs as to what flavor of bad meeting. Right now folks are having a bad meeting getting stuck going too far ahead. So we’re working toward ‘less bad’.

Some reframing for myself:

If I accidentally go ahead a few times, chances are I learn and don’t do that anymore. The facilitator is the single variable. However, if folks can always goof grouping during voting I could have many bad experiences from any number of teammates, on any team, in any meeting.

Where we lose is that first impression where I look like a goof in front of my team. So if you give me a reset button to go back one phase at a time, maybe it saves me some grief?

**Comment by nickoferrall** [comment]
I think we should make it harder to accidentally skip ahead rather than make it easier to go back. Virtually all of the user feedback refers to accidentally skipping ahead. 

I really like Terry's suggestion in [this thread](https://github.com/ParabolInc/parabol/issues/2948#issuecomment-598339388). 

If it seems likely that the facilitator is accidentally skipping ahead, we can show a confirmation modal. We could do this for each phase, not just the Group phase. The confirmation model could display if:

- There are 0 groups in the Group phase
- 50% of votes haven’t been used in the Vote phase
- 50% of team is not present and the meeting is not on a async time limit in the Reflect phase
- Users are still typing in the Reflect phase
- Phase has lasted for < 1 min

If we implement this and users still want to go back, then I think we should add a reset button.

**Comment by mattkrick** [comment]
that's a fair point. We didn't have the "Tap again to continue" confirmation until June 10, so all the accidental clicks before then are probably moot.

that said, this comment shows there's still some tension: https://github.com/ParabolInc/parabol/issues/3701#issuecomment-651673941

**Comment by nickoferrall** [comment]
That's true, although that comment isn't necessarily about regrouping of cards in the vote phase, while I'm sure that could help.

> reflections/tasks sometimes surface later on in the meeting through the conversation/sudden realization and there is no way for the facilitator to go back and add/edit that in

This sounds to me like users want to go back to the Reflect phase which would be hard to do while maintaining anonymity.

[This feedback](https://github.com/ParabolInc/parabol/issues/3701#issuecomment-658486402) makes a case for regrouping but again I feel the main tension is that the user "accidentally hit next". 

It doesn't look like we have much feedback (at least here) that suggests that regrouping of cards in the Vote phase is a major tension. For me, that makes sense - if I've deliberately moved forward, there are two scenarios where I'd want to regroup:

1. A group could be divided into smaller groups to improve clarity and focus
2. Several different groups could be grouped together to increase the chance it gets enough votes for discussion

Those are valid tensions but they're not awful scenarios and resetting creates its own issues of disrupting the meeting and still causes the facilitator anxiety. 

My vote would be to wait until there's more feedback about regrouping before implementing anything. But if we do want to implement now, I like Matt's resetting proposal.

I do feel that there's more we could do to prevent accidental skipping, but perhaps that's out of scope considering the title of this thread.

**Comment by ackernaut** [comment]
Agreed, I’m seeing the value in the reset as it only happens because a facilitator went forward and didn’t intend to. They learn. They have an undo button.

Whereas allowing everybody to group during vote has the potential for many unintended affects from any participant. They don’t get an undo button.

**Comment by mattkrick** [comment]
Solid discussion.
So the approach is to stick an "Undo" button in the completed group phase?
TBH I agree this probably isn't eating our lunch, but having a solution lined up for when we do prioritize it feels good.

**Comment by nickoferrall** [comment]
Makes sense. An "Undo" button sounds good to me 👍

**Comment by jordanh** [comment]
Safe to try! Great discussion.

Opened: https://github.com/ParabolInc/parabol/issues/4151
