### ISSUE TITLE
Devops: Kubernetes deployment

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3718]
Been deep into k8s for the last couple days. Here's what a 3-month plan looks like. I feel comfortable doing it all, but our server is healthy as can be & can handle a LOT more traffic, so no real tension to fix what isn't broken. 

v1 - achieve dokku feature parity
- create a helm chart of parabol
- nginx ingress, cert-managed with let's encrypt
- service/deployment for web, 1 replica. PM2 removed
- service/deployment for redis, 1 replica
- service/deployment for rethinkdb, 1 repllica
- ready & liveliness listeners on all 3
- 1 Job that serves as the postdeploy hook
- Prometheus added to replace datadog
- github actions used as CI/CD
- 2 versions released with breaking DB migrations while prod still points to current deployment
- 1 control plane for prod, 1 for staging. additional dev envs can be created in the staging control plane by using namespaces. staging control plane can be shut down when not in use.
- deprecate action-chronos in favor of CronJobs (https://medium.com/@ksholla20/creating-a-cronjob-in-kubernetes-and-use-secrets-as-environment-variables-b8e0166f2d51)
 - Where to deploy? shouldn't matter too much. still tbd, wherever is cheapest, probably.

v2 - cluster rethinkdb, redis
- redis lock supports a redis cluster
- presence moved to redis #3259
- rate limiter moved to redis
 
v3 - cluster web
- full server audit for possible race conditions
- replicas scaled to 3
- autoscaling turned on

v4 - break out graphql execution service
- Execution service broken out into its own separate service
- prometheus added to execution service

v5 - TURN server & mediasoup deployments added
- 1 replica, each

### On Premise
- tbh, not sure if kubernetes is worth vs. docker-compose since we'll never need to scale. we'll need to use kubeadm & keep an eye on certs expiring.

**Comment by jordanh** [comment]
Quick update to capture current state and evolve thinking. After needing to add [additional capacity](https://www.parabol.co/blog/growing-capacity) we've bumped the priority of `v4 - break out graphql execution service` to now so that we can more easily take advantage of multi-core execution, even if we remain hosted on a single blade.

Open questions for discussion:

- Do we host database services inside or outside of k8s? (we are leaning toward in, using mounted volumes and stateful sets)
- Do we use a managed k8s service? (I am leaning toward yes)
- Do we define our architecture using Terraform? (I am leaning toward yes)
- How do we store key material? (I am leaning toward HashiCorp Vault)
- How are DB backups managed (possibly: a separately tagged rethinkdb replica set, both for backups and BI queries)?
- How do we manage *managed* private deployments?

Resketching the above:

v1 - achieve dokku feature parity

create a helm chart of parabol

- nginx ingress, cert-managed with let's encrypt
- service/deployment for web, 1 replica. PM2 removed
- service/deployment for redis, 1 replica
- service/deployment for rethinkdb, 1 repllica
- ready & liveliness listeners on all 3 via datadog agent checks
- 1 Job that serves as the postdeploy hook
- Prometheus logging piped to datadog
- github actions used as CI/CD
- 2 versions released with breaking DB migrations while prod still points to current deployment
- 1 control plane for prod, 1 for staging. additional dev envs can be created in the staging control plane by using namespaces. staging control plane can be shut down when not in use.
- deprecate action-chronos in favor of CronJobs (https://medium.com/@ksholla20/creating-a-cronjob-in-kubernetes-and-use-secrets-as-environment-variables-b8e0166f2d51)
- Where to deploy? shouldn't matter too much. still tbd, wherever is cheapest, probably.

v2 - cluster rethinkdb, redis; realtime data backup

- redis lock supports a redis cluster
- presence moved to redis #3259
- rate limiter moved to redis
- second rethinkdb cluster added via 2nd server tag for realtime replication, periodic cold-store backup, and BI

v3 - cluster web, database

- full server audit for possible race conditions
- web app replicas scaled to 3
- database sharding and replication used for production tag

**Comment by jordanh** [comment]
Some kind soul did this: https://github.com/helm/charts/blob/cbd5e811a44c7bac6226b019f1d1810ef5ee45fa/stable/rethinkdb/README.md

Note, it's 2.3.5 (why, I'm not sure)

**Comment by jordanh** [comment]
@adaniels-parabol this is in your capable hands now; more recent issues supercede this.

Iceboxing to archive

**Comment by carloslfu** [comment]
Hi @mattkrick. Is the Kubernetes config open source?

**Comment by jordanh** [comment]
Hi @carloslfu! We haven't released our internal k8s build pipelines (for GitLab) or configs.

We're working on some now for the US Department of Defense, that I *think* will be open source. @adaniels-parabol may have more details.

**Comment by carloslfu** [comment]
Thanks! @jordanh
