### ISSUE TITLE
Non-anonymous Reflect phase designed

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3772]
We've held a batting practice to enable folks to disable Reflect anonymity if they so desired (see Issue #3710 and PR #3738). We need a high-fidelity design in order to carry this over the line.

AC

- [ ] Reflection input refactored to similar pattern to comment input (bottom, chat style)
- [ ] Affordance created to toggle anonymous/non-anonymous

EE 6 hours

​

**Comment by ackernaut** [comment]
I’ve [outlined some thoughts here](https://www.notion.so/parabol/Non-anonymous-reflection-input-29c385fef7a5445c9429bd51a3249d5e) 🔒 (and the related [thread](https://parabol.slack.com/archives/C0A0MRZH6/p1589476386004600) 🔒 ) and want to change direction in the design if it’s safe to try.

**Comment by ackernaut** [comment]
**An update**: I’ve made [some iterations](https://www.figma.com/file/MZ1A8PG7aOuupJK0cxzEwmMn/Reflect-Phase?node-id=66%3A179) showing the toggle input in the reflect phase and [some options](https://www.figma.com/file/MZ1A8PG7aOuupJK0cxzEwmMn/Reflect-Phase?node-id=69%3A0) for including the author’s avatar on the reflection card

**Comment by ackernaut** [comment]
**Updates here**: I’m showing public cards to have a prepended, preferred name on the card, and how they would look in the Reflect, Group, and Discuss phases with mixed bags (some anon, mixed prompts, etc.). [See concepts in Figma](https://www.figma.com/file/MZ1A8PG7aOuupJK0cxzEwmMn/Reflect-Phase?node-id=64%3A0)

**Comment by ackernaut** [comment]
The 90% UI concept looks like this:

#### Reflect phase input
- The input has the avatar toggle, like the thread input
- The last mode selected persists across columns and phases until changed
- Submitting the input prints a card followed by an en dash and the preferred name – Terry

#### Group phase
- We can use the same input with the avatar toggle, but it prints a card appended by the name, which requires some hacky animation to account for card size differences
- We could offer a new card with the name already appended. They’d have to go back to the Reflect phase to toggle the mode which is a poor UX

#### Public reflection options
- The name that gets printed could be editable; folks could just remove it from the card if they want; otherwise, folks could delete and add the same content in the desired mode. This would apply to the phases where the cards are editable (i.e. Reflect, Group)

#### One toggle to rule them all
- We could give each participant a toggle to change what mode they are writing in. This toggle could be in the top/side/bottom bar and keep the input and card UI consistent and easy to animate
- We could give the facilitator the option to toggle showing the author meta which is a completely different UX. To make it safe, we could require it from the lobby and make it a 1-way decision for that meeting, that way it’s clear from the beginning which mode is 

#### Concerns
- Defaulting to anonymous means we add something to UI that most folks aren’t going to use. This is a strong argument for a 1-way switch in the lobby
- What we have today is an input that produces a persistent card shape, basically WYSIWYG. This especially helps with ✨  polished animation. It’s a challenge to devise an input UI that is going to represent the final results with a mode toggle on the input. We don’t want the default anonymous avatar on all reflection cards
