### ISSUE TITLE
Facilitator can't use left-hand nav to navigate before Agenda phase 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#3824]
## Issue - Bug

As a facilitator, I want to use the left-hand bar to navigate between different phases of the meeting. However, before we hit the Agenda phase, I have to navigate via the bottom bar. When I try to click on an agenda item to move there, I'm not given the option, and it's unclear why. 

Screenshare video: https://drive.google.com/file/d/1N6JiSePU2fT3NCix5Iiu1fHIsE4E37Ac/view?usp=sharing

- **OS:** macOS
- **Browser:** Chrome 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Facilitators can:
   - Navigate to items in the agenda using the left-hand sidebar

**Comment by mattkrick** [comment]
The flipside of this argument is a user accidentally advanced the meeting via the sidebar because they were just clicking around. 

The result is that you can _only_ advance the the meeting via the Next button. That adds friction to advancing, which helps ease the pain of the linear process.

Overall, I think this issue is the symptom of a larger problem, which is a linear flow to meetings. While a linear flow provides momentum & prevents meetings from getting derailed, it is more rigid. Finding that sweet spot of rigidity is difficult with the goal of making it hard to have a bad meeting.

**Comment by avivapinchas** [comment]
But in a check-in meeting, there's no consequence to moving from icebreaker to agenda back to icebreaker, right? It's not a one-way door

**Comment by mattkrick** [comment]
very true, folks are free to go back, although visually it'll show that the stage was already completed.however, we do have some weird logic. today, the agenda items are all blurred during the icebreaker & it also makes you at least visit the updates phase before moving on the agenda items,

**Comment by jordanh** [comment]
I am _sure_ this is going to come up again. I hear from @mattkrick we actually special-cased this to work the way it does today. I think the time to address this will be when we enhance check-ins for scrum/standup etc.

Going to icebox for now
