### ISSUE TITLE
Add friction for large teams

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3825]
Our business model encourages 5-10 person teams.
We designed our UX to support 5-10 person teams.
We are seeing teams range from 5-100+.

I'd like to come up with a strategy to nudge folks to have smaller teams.
Sure, it's great for business, but mainly because smaller teams are more effective, and a successful team is one that sticks with us.

Bad ideas to start with:
- on team dash have a "+25" avatar like in meetings, but don't show the rest
- only send the meeting summary email to the first 20 participants
- ??

**Comment by jordanh** [comment]
Thinking out loud: I wonder if teams of teams would help here...

**Comment by mattkrick** [comment]
i think that's the most elegant solution, and the pattern we want to encourage.
perhaps we should wait until we offer that until we start applying friction

**Comment by avivapinchas** [comment]
I have lots of thoughts here, so breaking it up with some headers :P 

*On encouraging smaller teams* 
We talked previously about adding a question at the end of a retro like 'Was that worth the time?' with a  straight up or down. I think we could use data from a question like that to help folks see how meetings and retros with larger teams are often less valuable. 

How this could work: 
- After a retro with a larger team (25+?), we show the facilitator something in the meeting UX, summary, Timeline or Team View along the lines of "Your last retro included XX people. Across Parabol, teams with 25+ report XX% less satisfaction with the time invested in meetings. Tips to improve your meetings: (1) smaller teams!, (2) something else...etc" If we could get really fancy, we might recommend how to split up their larger group into smaller ones, maybe based on who interacts together on tasks or comments. 
- Similar to the above, we could suggest something more personal, like "Since your team exceed XX members, you've seen a XX% decline in satisfaction with your meetings. Get back on track: (1) break up into smaller groups, (2) something else...etc" This would depend on their team growing as they used the tool, so it wouldn't work if they just started out with a  30-person team from the start. 

At the smallest/simplest, we could use a similar pattern but show existing benchmarks from reputable sources. I think this would be less effective because it doesn't feel personal and might feel kinda 'preachy'. 

*On team-of-teams* 
I've previously run a set of teams that rolled up into a team-of-teams. In that scenario, I wanted to run a specific cadence with the subteams, but also have a lighter rhythm with the full macro team to create cohesion and 'team-iness,' and to process cross-team tensions (ex: for running sales on the site, there were marketing pieces and also website pieces. These were run by 2 diff subteams, and I wanted them to have some context of working together and reflect on how to make that better). 

I imagine that a team-of-teams retro looks a bit different: 
- Maybe there are different templates that are geared towards more loosely connected teams? 
- Maybe there are different rules of engagement, like reflections are always async, or grouping happens in a different way so there's less chaos, or maybe you can break up into groups to discuss, perhaps even outside of the retro (continue this discussion later is maybe more valuable in that context) 
- Maybe there's a way to 'tag' groups with what subteams they're relevant for, and we automatically move topics to the relevant subteam. If they're truly for the whole group, that's what's actually discussed as a whole. 
- Maybe we have something heavier to guide the discussions, so it's not as much on the facilitator to wrangle 30+ people. 
- Maybe there's a shared Tasks dashboard, similar to how my personal Tasks board shows my cards from across multiple teams 

We could surface these 'team of teams' formats somehow, maybe based on how many people are on the "team"? 

*On making large teams work* 
If folks really do have one large undifferentiated team that they don't have any intention or desire to break up into smaller teams, I think that's an opportunity for research. I'd be curious about what they want to get out of those retros. I imagine it's different than other retros, and my hypothesis would be that they're meant to serve the leader more than the team. When we have a better understanding, we can decide if that's a thing we want to support or not.

**Comment by mattkrick** [comment]
the current thinking is to lean into this. let them have monster teams. we display team members in a vertical list instead of horizontal avatar list. we have breakout meetings where groups can work on a piece of the problem.

**Comment by jordanh** [comment]
+1 to this resolution
