### ISSUE TITLE
planning meeting lo-fi design pass

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3887]
### Acceptance Criteria (optional)
Lo-fi designs that:
   - Close off remaining design questions
   - Shared with team and internal discussion held

- **Estimated effort:** 6 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
**Update**: I’ve started to shape [some of the details and highlighted some items](https://www.notion.so/parabol/Story-Pointing-UX-notes-3805ea1665444ae38baff8d66f6745ba#965bee980eff448597a6113a2d329400) :lock: to look at more closely so that we can walk away with crisp direction for the story pointing prototype.

**Next**: I’ll add direct links to frames of existing sketches and concepts (or create new ones) for clarity. I’ll probably walk through the highlights in an async video and share for feedback. After that we can upgrade the bandwidth for the items that still aren’t clear.
