### ISSUE TITLE
Retro template sharing backend implemented

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3931]
## Issue - Enhancement

See: #3465 

### Acceptance Criteria (optional)
- A template has 1 of 3 scopes: `team`, `org`, or `public`.
  - team means it's only visible to the team
  - org means it's only visible to the teams inside it
  - public means anyone on the platform can see it. this is the first step to becoming a social network 🙈 
- If you belong to the team that owns the template, you are an OWNER, else VIEWER
- The owner can read, update, and delete the template
  - deleting a template hides it. if it has no subscribers, it may also be deleted (or marked inactive)
  - updating a template causes the template to change for all viewers, since they all use the same one
- The viewer can read the template. if they want to edit it, they must fork it.
 - forking a template clones it and adds the parentId. it unsubscribes from the upstream template.  The forker is the owner of the new fork. 

- **Estimated effort:** 30 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
Front end considerations:
- It should be dead obvious which templates are "by ref" which ones are "by value". Gut reaction is
  - owners get a dropdown box with "public, org, team"
  - viewers get a smallprint message saying "This template is managed by X. Click here to make it your own"
  - maybe we group by "My Templates" and "Managed Templates"
- there's probably one view for both "org" and "public" templates that shows Template & Owner that is sorted first by the org, then by public. that said, 2 different views may work, too.
- pushing a template to all teams in the org could be something useful, but would require some permission level that is higher than team leader but less than or equal to billing leader, so we can punt on that for now

**Comment by mattkrick** [comment]
How I see this whole thing working:
- When i create a team & my meeting settings get generated, an array of `managedTemplateIds` is created & the IDs point to templates that are created by a Ghost Team that is part of a Ghost Org (we can easter egg this if we want)
- The RetroMeetingSettings GQL type has a `managedTemplates` array where i can fetch up to 50 templates
- There is a `cloneRetroTemplate` mutation that takes in a managedTemplateId, checks its scope & then clones that template & sets the parentId, sets the scope to team & removed the managedTemplateId from the array
- we kick it off with a migration that creates a Ghost Org & Ghost Team. we don't migrate old templates to managed templates because they could still be in use

**Comment by jordanh** [comment]
First instinct (which might be wrong):

> disable going private when its public

^ this is the option I'd opt for, but still allow a "duplicate" option. These feels the most explicit

**Comment by mattkrick** [comment]
my concern is that folks don't like being told they can't do something (navigating backwards in a meeting, deleting their account, etc). if someone deletes their account, they probably expect their templates to be deleted, too, which would be the same as setting to private.

 
> when going private, clone the template for every subscriber.

this is the way i was leaning since it doesn't really affect the owner or the subscriber. part of me wonders if it's smart to allow a team to subscribe to a stranger's template. what if i make a popular template & then change the questions to something super duper racist? moderating the things that make it to the "Best Community Templates" is easy. moderating all changes to those templates is harder.

**Comment by mattkrick** [comment]
big picture, we want to the user to find a template that they want to use ASAP. this problem is analogous to youtube or netflix. i either come to the site with a video in mind, or i've come to explore.

here are some assumptions:
- if i used a template in the past, i am more likely to use it in the future, regardless of scope
- if i haven't used a template in a very long time, i'm probably not going to use it
- if my team owns the template, i'm more likely to use it than org/public
- if my org owns the template, i'm more likely to use it than public templates
- if a template is frequently used by others, i'm more likely to use it

i think the way is to break out lists on a per-scope basis. each list can then be individually sorted on how much they're used. 
if i template goes from public to private, it won't show up in the list anymore. the problem still exists that changing a template affects meetings in the past, but the only way to fix that is to clone a template each time it's changed.i think we can wait for signal to do that.

**Comment by jordanh** [comment]
> part of me wonders if it's smart to allow a team to subscribe to a stranger's template. what if i make a popular template & then change the questions to something super duper racist?

I agree. I think to get around this, users shouldn't "subscribe" to a public template. Rather, they should be forced to clone them. Changes a local. You don't get updates automatically.

Perhaps in the future we can signal if the template has been updated...but I don't expect these things to change much.

**Comment by mattkrick** [comment]
what happens with organization-scoped templates? Let's say you want 10 of your teams to run a retro using the same template so you can do a comparative analysis. if they clone the template, you can't guarantee that they're comparable. if we offer a clone affordance, folks may clone when they're not supposed to.

at the org scope, the problem is downstream trust-- i don't want a team going rogue & running a different template.
at the public scope, the problem is upstream trust-- i don't want an internet rando to change my template.


let's imagine a future where finding a template is like finding your next movie on netflix.
there are 3 categories, 1 for each scope & each has 10 templates in it.
you scroll through, when you click one you can see the prompts, colors, and descriptions.
if the template is yours, you can edit it.
if it belongs to your boss, you can use it, but not edit it. *can you clone it?*
if it belongs to the public, you can clone it?

**Comment by mattkrick** [comment]
Trying this again:
- [ ] when i reduce the scope of a template, it sees if the template has been used by anyone but me. if so, it inactivates the current template, & clones it. that way, old meetings that used the public template still work but the template is no longer advertised at a given scope.
- [ ] i can clone a template that i don't own
- [ ] i can use a template that i don't own w/o cloning

**Comment by mattkrick** [comment]
How to score clones:
Let's say I have a popular template A.
When someone clones it, called A prime & runs a meeting based off the clone, should the popularity of A increase?
Yes, if A' ~= A
No, if A' is nothing like A

We could check for similarity based on:
- # of prompts
- string similarity of each

For example, if A' has the same number of prompts as A & each prompt is 80% similar to the original, we could call it the same. We would perform this check when the scope of A' is increased

This works, but what about A''?
- We could say A'' is a child of A' but has no relation to A
- We could cut it off 1 level deep
- We could score it like ponzi schemes, weighting each clone a little less (turtles all the way down!)
 
My gut reaction is if we do this, we should do the first, to keep it cheap.
My concern with this is we're implicitly grouping clones into the "meetings run" scoring mechanism. 

Alternatively, we could just keep a clone count on the template. click "clone", the count increments & we score that as a 3rd factor (template age, meetings run, number of clones). This is nice because it makes the clone count discrete, but it's bad because someone cloning something & never using it should be worth 0. cloning something & using it 1M times should count a lot.
