### ISSUE TITLE
Support image uploads

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#3957]
Today, when a user wants to change their avatar, the flow is as follows:
- client calls `createUserPicturePutURL` with the size & extension of the file. server replies with a url specific to the file extension & bytelength
- client uploads their picture direct to S3

In the future, we should have the client upload directly to our server & then our server can forward to S3.
Doing so will
- allow us to normalize & shrink the image
- verify that the image is not nefarious (in the case of an SVG)
- support deployments that don't use S3

Acceptance Criteria:
- [ ] `uploadUserImage` and `uploadOrgImage` mutations are created
- [ ] those mutations are called over http instead of a websocket

Estimate: 30 hours

**Comment by jordanh** [comment]
[This customer](https://app.hubspot.com/contacts/3888472/contact/12401601) 🔒  _really_ wants this so they can support avatar images in their GCP environment. Since it's a fairly quick and contained one, and self-hosting customers are only going to increase, I'm going to raise the priority on this one a bit

**Comment by tiffanyhan** [comment]
@mattkrick 

What do you think of this self-hosted scenario:
- Client calls `createUserPicturePutUrl` off of **Parabol's server**
- Client uploads image direct to **Parabol's s3**
- `UpdateUserProfileMutation` and `CreateUserPicturePutUrlMutation` are called normally and avatar url fields updated accordingly

I worry that directing file uploads to our GraphQL server can introduce an unnecessary bottle relative to other traffic. Offloading uploads to s3 seems ideal to me, and it looks like we have already implemented the "signed upload url to s3" approach with validation of nefarious SVGs as well. 

Am I missing something that would make the above approach untenable? My opinion has been informed by [this article](https://www.apollographql.com/blog/apollo-server-file-upload-best-practices-1e7f24cdc050).

**Comment by mattkrick** [comment]
I wouldn't worry about congestion, we stream the body in 16KB chunks & account for backpressure if necessary.
 
I'm not sure I understand how your proposal is different than what we're doing today?

The reason it has to go through our server is because we have to build a solution that works without S3.
Some enterprise clients want to save the avatars to the same disk that parabol is deployed on.
Others want to deploy to their own S3 or a google/microsoft equivalent.

**Comment by tiffanyhan** [comment]
The only difference would be that any client would call `parabol.co` to get a signed put url to parabol's s3 bucket. I'm assuming that the issue with self-hosted deployment is the client calls the self-hosted server to get a signed put url, but that fails bc the self-hosted instance doesn't have s3 configured.

I think I may be missing context and so misunderstanding the AC:

I assumed the main point of the issue is to enable self-hosted deployments to upload avatar images without using their own s3. The issue says: `In the future, we should have the client upload directly to our server & then our server can forward to S3`. My thinking was that if we're still ultimately using Parabol's s3 bucket, why does the upload have to go through the server? 

If the ideal future state is to be able to make the target destination configurable e.g. to other cloud storage offerings or the server's own file system, then it makes more sense to me why it's necessary to route the upload through the sever first. Can you confirm if this is correct, and that the followup work would be implemented in additional issues? @mattkrick
