### ISSUE TITLE
RCA: Excessive Organization queries

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#3961]
## Issue - Bug

We had a bit of [FUN](https://dwarffortresswiki.org/index.php?title=DF2014:Fun&redirect=no) occur around 13:54PT where users reported the app was becoming unresponsive (for example, facilitating stage-to-stage in a retro).

Upon examination:
  - Redis had 128M cache space consumed, not the culprit
  - There >100k rethink queries per second happening

On the DB, running:

```javascript
r.db('rethinkdb').table('jobs').pluck({ 'info': 'query'}).sample(25)
```
It was most of the queries looked like:

![image](https://user-images.githubusercontent.com/103000/85797666-f1998d80-b6f0-11ea-8f38-1d634b9a7996.png)

The root causes is presently unknown. It may be related to resent query caching changes.

### Acceptance Criteria (optional)
   - Root cause of failure determined

**Comment by tiffanyhan** [comment]
Failure was due to myself using the secure tunnel script to open a connection to the live prod db. I used the connection to work on #3952 - optimizing weekly metrics queries. Correct course of action would have been to tunnel into the staging db, or copy remote db to local machine. A warning has been added to terminal output when using the tunneling script to connect to prod - https://github.com/ParabolInc/action-devops/pull/52 . Should also rename `backups.action-production.parabol.co` to remove `backups` in the name, if it's possible to do so.
