### ISSUE TITLE
Notify mentions in a thread

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4025]
### Background

If a thread is still active both technically (can add, edit, delete comments and replies) and in usage (folks are still jamming on the conversation) then I think folks should be notified when they’re @-mentioned. However, I’m aware of a few possible design concerns:
- When a meeting is over, is it clean UX for threads to linger? Do we close threads? Do we consider them living output? What if, one day, threads are on task cards, and the tasks cards were created in a meeting? Do we archive threads if they become first-class primitives in the object system?
- We still need to explore clear razors for distinguishing timeline events, notifications, and meeting activity alerts. I think that if meetings and threads share the role of being a first-class primitive that serves the purpose of being a guided format for input and output in async and/or sync fashion, then some activity on threads might feel like a meeting/thread activity alert.

### Acceptance criteria

- Discussed this issue
- Decided to notify users for @-mentions in a thread, or scoped more design around our object system and messaging razors
- The notification links to the view where the thread is and highlights the comment with the @-mention until viewed by the mentioned user ([see Figma](https://www.figma.com/file/UhuGb8dL15bf3ylXoVqS1m/Retro-Discuss-Thread-v1-Prototype?node-id=714%3A119513)). Bonus points for scrolling to the latest @-mention if possible.

**Note**: if we decide to notify users, I think this is a good candidate for the 20% bucket of a sprint.

### Estimated effort

- 3 hours

**Comment by ackernaut** [comment]
@jordanh @mattkrick @avivapinchas I know you folks have had thoughts about this in the past so boosting some signal at ya.

**Comment by avivapinchas** [comment]
I think there's kind of 3 layers to consider here: 
1. _Where do *conversations* live in Parabol?_ If we foresee unlocking more async discussion options, I could see a top-level Conversations item, similar to Tasks. I imagine you'd be able to filter by team, author, origin (retro group, check-in item, totally its own thing), etc. Conversations that were just added to would perhaps bubble to the top, and/or you could see some slightly different state. In that context, I'd see a thread from a meeting as another conversation. 

2. _How do users know when a thread or conversation either needs their attention or they might be curious about it?_ I imagine that's a standard around notifications, as you mentioned. Just a set of personal preferences and thoughts on this: 
-- I'd rather have 1 notification menu than 2, because it's easier to know what to look at
-- The red circle (or whatever 'unread' looks like) needs to clear in a logical way - Notion does this poorly, imo, where messages I've seen aren't cleared. Similarly, we currently keep that red circle on there even if I've seen the message, so it's kind of noise. 
-- Different types of notices have different priority levels, so they need to be treated differently. 'Meeting is happening' is an urgent thing (probably) cuz I should be in that space (red, loud). Being assigned or mentioned on a card is more of an FYI (green, quiet). Being mentioned in a comment is probably in the middle, I'd want to have almost a queue of these to reply to (yellow) - maybe that needed reply can be a flavor of task, so it's automatically in my to-do list. Similarly, comments in threads I've engaged in are probably more FYIs, that I might chose to respond to or not (green, quiet). I also imagine that different teams or topics have different levels of importance, and I'd love to be able to set that somehow - maybe I can star a team or a tag, and alerts from them are slightly louder or given more priority. 
-- Most folks aren't in our tool all the time, so they need to build a habit of coming back and do so in a useful way. In the near term, I imagine that looks like emails and Slack (or other chat tools) messages to draw their attention back. 
-- There should be some consideration for how messages from us fit into this framework. Examples include: new feature notifications, maybe outreach from Sales (per #4011), maybe special offers or research opportunities. I think these should feel like part of the experience, vs a separate thing, and ideally we'd have ways to target who we're putting things in front of so that they're useful messages. 

3. _What matters today vs later?_  Most of this is kind of long-term thinking. I don't imagine folks are going back into discussion threads after a meeting, except to review those as 'notes', because a meeting is a time-based thing (hence the confusion around `starting a meeting` before your real-time sync to process reflections). Where I personally feel tension is: 
-- How do we lay the groundwork for async conversations or discussion between meetings? What patterns can we work with today that will serve us in the future too? I imagine that's something around having 1 menu, and adjust loudness in a better way 
-- How do we get folks coming back into Parabol between meetings, when something might be interesting or valuable to them? I imagine that's something around considering how we work with email and Slack, alongside notifications, as appropriate

**Comment by jordanh** [comment]
> Where do conversations live in Parabol?  If we foresee unlocking more async discussion options, I could see a top-level Conversations item, similar to Tasks.

+1 to this idea to explore. One bit of thinking I've been doing is a meeting is just a Conversation thread that has special features. Meeting in progress? Conversation. Meeting completed and resolved to a summary? Conversation.

More on this to come when I've got the bandwidth to make some lo-fi designs

**Comment by mattkrick** [comment]
TBH, i'm against dedicating too much time in this for now. Without a doubt, we'll build this in the future, but this puts more emphasis on the tasking system vs. the meeting system, and I don't wanna play catch up to trello.

**Comment by jordanh** [comment]
@mattkrick clarifying question: which part of this puts emphasis on the tasking system?

The bit I think is useful is: when I want to prompt a specific user for input during an async meeting, I want to @mention them, so I can get their attention and participation

I feel like this feature weighs more heavily on meetings vs. tasking, so I'm curious for your take...

**Comment by mattkrick** [comment]
I think new meeting types, video, integrations, & synergies between meetings all add more value. I'm afraid this will distract us from those goals.

I consider it tasking because i see the notification system as part of the tasking system. it's not that delightful 30-60 minute meeting experience, which IMO is where our target demographic is.

**Comment by jordanh** [comment]
I roughly agree with the priorities here. I don't think we'd push any of this work beyond lo-fi IA at this point.

**Comment by mattkrick** [comment]
fully agree, we're pretty design constrained though, so i wanna make sure whatever IA work we do isn't blocking the big stuff.

**Comment by avivapinchas** [comment]
To me, the set of questions that this raises are around how we help folks build a repeat habit - how do we proactively give them a reason to come back (before they decide they should come back) and/or remind them that Parabol can help them? 

Looking at our data, we see that most of our drop-off in users is folks who don't get to a second meeting. I imagine a tool we could use to make it easier for folks to get over that hump is smarter notifications in that early part of their lifecycle, and I think this would help us have a framework for how those notifications should work. 

So it seems directly relevant to synergies between meetings and building a habit.

**Comment by ackernaut** [comment]
The more meaningful team activities can happen in our app, the more we’ll have repeat usage. Those activities should allow for async participation, sync participation, or a mix of both. If that’s the case we should see a broader span of usage. Any other activity in the app is just housekeeping and should be easy and fast: setting up an activity, forming a new team, inviting others, etc.

Most of the time spent in the app should be contributing to an activity in a meaningful and time-considerate way. Otherwise, folks should be jamming out in other spaces, getting their work done. The experience with our app should be mostly signal, little noise. We should be aggressive there and I bet it’ll be one more reason folks love us.

I think these problems will be sorted out when we have a richer library of activities.

But when I’m mentioned in a thread and not there to see it…doh! That’s just a utility that should be part of a thread UI, not a feature. Our curated team activities are the features.

**Comment by jordanh** [comment]
Related #3832 
Will explore a bit in #4321 

Trigger for this is on consideration of threads as more of a first-class citizen
