### ISSUE TITLE
Refactor gql2ts autogenerated enums into string unions

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4033]
A great source of sadness is that typescript doesn't think that an enum with the underlying value of `foo` is equivalent to the string `foo`. 
This makes coding less fun because the relay generated typescript file will return a string union & gql2ts returns an enum, which means when the 2 collide, they require a manual coercion.

To fix this, we should have gql2ts output string unions instead of enums.
Doing this is easy (I think), just remove this line: https://github.com/ParabolInc/parabol/blob/share-temlates-backend/packages/server/utils/updateGQLSchema.ts#L31

The hard part is refactoring everything because that'll create a bunch of ts errors.

AC
- [ ] gql2ts converts graphql enums to string unions

Estimate: 8 hours

**Comment by mattkrick** [comment]
still really, really want this. it is tech debt that is accruing

**Comment by nickoferrall** [comment]
Hey @mattkrick, the link in the description isn't working but I assume that [this is the line](https://github.com/ParabolInc/parabol/blob/73e4d3f7d6251a9f6f87b4f1ab26295981a1a245/packages/server/utils/updateGQLSchema.ts#L32-L33) to remove. 

After removing that line, the `graphql.ts` file removes the `export` from the `enum`s rather than converting them to string unions. 

Just using the `DEFAULT_EXPORT_FUNCTION` without a type builder doesn't work and it looks like the package doesn't currently support a [union type builder](https://github.com/amount/gql2ts/blob/master/packages/language-typescript/src/index.ts).

I'll keep searching and playing around with it and see if there's a good way of converting enums to unions. 

I suspect that the config files [here](https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/types/configGH.js) and [here](https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/types/config.js) will also need to be updated.

**Comment by mattkrick** [comment]
a better acceptance criterion might be to just remove all (or as many as possible) dependencies on the generated `/types/graphql` file. 

for example, see https://github.com/ParabolInc/parabol/blob/3775ac88bde64210f5e4f9e9f354c415e128432a/packages/client/components/DiscussionThread.tsx#L50. 

we can replace `meetingType === MeetingTypeEnum.poker` with `meetingType === 'poker'` and get the same benefit.
if we changed it to `meetingType === 'foo'` it'll still be an error because `meetingType` is already provided to us as a string union.


instead of using `MeetingTypeEnum.poker` we can simply use `poker` and still get full support because `meetingType` is a string union type. if you change L50 to `meetingType === 'foo'` it'll still be an error & we wont' rely on the types/graphql file.

This won't always work. For example, https://github.com/ParabolInc/parabol/blob/0e010565e6048c9eaffe73a282ba5cb5a798ff38/packages/client/components/TaskColumns/TaskColumns.tsx#L31. For those cases, you can grab the string union type from a mutation, e.g. `import {AreaEnum} from '~/__generated__/UpdateTaskMutation.graphql.ts`

**Comment by mattkrick** [comment]
This is a lot of files to touch & it looks very much like headphones-in-and-jam kinda work, but it's gonna yield some pretty cool benefits:
- we won't have to cast strings to enums and enums to strings in client files. This means all our errors will get caught as we refactor things
- we'll be able to build the server from scratch, without `types/graphql`. Today, that file is required by the server, but also in order to build that file we have to build the schema on the server, so it's a chicken & egg problem (https://github.com/ParabolInc/parabol/blob/cb897817cd1cb684577edecc6c64b26144d5e698/packages/server/email/newMeetingSummaryEmailCreator.tsx#L19)

**Comment by nickoferrall** [comment]
Thanks, I'm headphones-in-and-jamming away but I just want to find an example where a string !== the underlying value of an enum. 

You mentioned that `AreaEnum` needs to be imported from the mutation but if I continue to import from `type/graphql` and change [line 54](https://github.com/ParabolInc/parabol/blob/0e010565e6048c9eaffe73a282ba5cb5a798ff38/packages/client/components/TaskColumns/TaskColumns.tsx#L54) from an enum to a string, i.e. `area === 'meeting'`, it's true. 

In the [ReflectionCard](https://github.com/ParabolInc/parabol/blob/e321a6f72f515150a36d1c412bd798399daf535d/packages/client/components/ReflectionCard/ReflectionCard.tsx#L51), for example, the following all return true / false:
```
    phaseType === NewMeetingPhaseTypeEnum.group,
    phaseType === 'group',
    NewMeetingPhaseTypeEnum.group === 'group'
```
I've tried this in quite a few files and have been getting the same result so far. 

Also, wherever possible, shall I replace `type/graphql` enums with enums from mutations rather than strings? I figure it's best to use enums wherever possible in case the dev makes a typo with the string.

**Comment by mattkrick** [comment]
ReflectionCard is a great example!
In that file, the only thing I'd change is where I import the enum:

```ts
import {NewMeetingPhaseTypeEnum, ReflectionCard_meeting} from '~/__generated__/ReflectionCard_meeting.graphql'
```

Now that it's using a string union instead of an actual enum, i can use plain strings & get free typechecking:

```ts
  if (phaseType === 'reflect') return stackCount && stackCount > 1 // this works!
  if (phaseType === 'groupz' && isEditing) return false // this will show an error because groupz is not a member of the string union
```

> Also, wherever possible, shall I replace type/graphql enums with enums from mutations rather than strings? I figure it's best to use enums wherever possible in case the dev makes a typo with the string.

the enums from mutations (and anything else generated by relay) aren't actually enums, they're string unions. these give us the same type checking without having to worry about where we import.
actual enums get hairy because `NewMeetingPhaseTypeEnumFromRelay.reflect !== NewMeetingPhaseTypeEnumFromTypes.reflect` even if their underlying values are the same!

**Comment by nickoferrall** [comment]
Hey @mattkrick, it'd be great to get clarity on this:

Some mutations require an enum as an input. For example, 
 [updatePokerScope](https://github.com/ParabolInc/parabol/blob/380d44be2f674755c1385b8fedcd2a586bb60049/packages/server/graphql/mutations/updatePokerScope.ts#L27) requires [UpdatePokerScopeItemInput](https://github.com/ParabolInc/parabol/blob/75021d29756d05c01d1d73485abd24ae89f99e1c/packages/server/graphql/types/UpdatePokerScopeItemInput.ts#L9) which uses the [TaskServiceEnum](https://github.com/ParabolInc/parabol/blob/75021d29756d05c01d1d73485abd24ae89f99e1c/packages/server/graphql/types/TaskServiceEnum.ts).

Relay uses this server side mutation and successfully creates the union `TaskServiceEnum` on the client side which it uses in `UpdatePokerScopeItemInput`. In the client mutation, we require that the input variable is of type `UpdatePokerScopeItemInput` [here](https://github.com/ParabolInc/parabol/blob/4411bcf44eb9085e19b14a62526e53d6abff3417/packages/client/mutations/UpdatePokerScopeMutation.ts#L59).

I would therefore expect that in the client we can replace enum `service: TaskServiceEnum.jira` with string 'jira' [here](https://github.com/ParabolInc/parabol/blob/4411bcf44eb9085e19b14a62526e53d6abff3417/packages/client/components/JiraScopingSearchResultItem.tsx#L67). 

However, TypeScript doesn't like this. It says that the string is not of type enum which suggests that TypeScript is using `types/graphql` as the input type. I'm not sure why that's the case as the client mutation input variable type comes from Relay which uses a union and should accept strings. 

Possible solutions that I'm working on:

1. Checking if there's anywhere in the client mutation that could be using `types/graphql` instead of the types generated by Relay.
2. See if it's possible to use `GraphQLUnionType` instead of `GraphQLEnumType` in [TaskServiceEnum](https://github.com/ParabolInc/parabol/blob/75021d29756d05c01d1d73485abd24ae89f99e1c/packages/server/graphql/types/TaskServiceEnum.ts). Using `types: ['GitHub', 'Jira', 'Parabol']` doesn't work as `Type 'string' is not assignable to type 'GraphQLObjectType<any, any>'`. Using an object instead of a string doesn't seem ideal. I'll continue reading to see if I can find a better solution. 
3. Coercing the string to a union works, i.e. `service: 'jira' as TaskServiceEnum,`, but is far from ideal as we lose the type safety.

**Comment by nickoferrall** [comment]
Progress update:

Interestingly, in [ParabolScopingSearchResults](https://github.com/ParabolInc/parabol/blob/61a1917a062cbc21e2097ae38270f8c6ce8612c5/packages/client/components/ParabolScopingSearchResults.tsx#L46-L51) assigning `newTask` as `CreateTaskInput` does provide type safety and I can change the enum to a string. 

Perhaps the reason this doesn't work in `JiraScopingSearchResultItem` is because it's nested. I'll keep looking into this - no help required for now!

**Comment by nickoferrall** [comment]
Hey @mattkrick, I noticed that when defining argument types in our server side mutations, we don't get type safety. For example, in [setOrgUserRole](https://github.com/ParabolInc/parabol/blob/2711c3d0062577d0fe75a1d494221dac171c807d/packages/server/graphql/mutations/setOrgUserRole.ts#L29) we define `orgId`, `userId` and `role` but line 29 shows them all as `any`. 

I was wondering why that's the case? 

It'd be nice to get type safety for `role` so I've changed line 25's `GraphQLString` to import `OrgUserRole` from the database and I'm then using Relay's union to define the types on line 29: `{orgId, userId, role}: {orgId: string; userId: string; role: IOrgUserRole}`
