### ISSUE TITLE
Sent 'role' user property to Amplitude

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4040]
## Issue - Enhancement

We believe that team leads and team members will have somewhat different experience with Parabol. To understand how their experiences are different, we need to be able to segment by 'role' (ie team lead or team member) in Amplitude. This should be a User property. 

[Discussed on Slack here. ](https://parabol.slack.com/archives/C9519N85P/p1596235805086900)🔒

### Acceptance Criteria (optional)
Parabol team can:
   - `Is Team Lead` property added to HubSpot – set to true when user is lead of _any_
   - Segment identify enhanced to add property
      - Identify called when property updates (i.e. add or remove team lead role)

- **Estimated effort:** 4 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
AC added, above

**Comment by jordanh** [comment]
@avivapinchas so this came up as stale during the scrum because we didn't get it done. But, we don't want to icebox it because we think it's still valuable. However, we're wondering if the design should change a bit.

Revering this to be a discussion. Once resolved, we'll add it back to the backlog. Discussion follows:

Right now, _most_ people are team leads because if they are invited to a team, we'll set up a "Personal" team of which they are the only member, and the lead. So, we could either modify the AC to read something like:

* `Is Team Lead` property added to HubSpot – set to true when user is lead of any team of 3 or more members

Or:

* Create a property called something like `Team Lead Max` that is a integer value set to largest team of which they are the team lead

Which do you prefer? Or, is there some other option you might suggest?

**Comment by avivapinchas** [comment]
This makes sense to me! Option 1 would be my preference - I think it's easier to understand what the field is, and I can't think of a scenario where we'd segment based on the size or number of teams in the near-term.

**Comment by jordanh** [comment]
Are you extra sure? What if having this data in HubSpot would allow sales folks to prioritize their reach out?

**Comment by avivapinchas** [comment]
That's a Q for @gcrickman, though my guess is that who invited the most folks is a better indicator?

**Comment by jordanh** [comment]
Iceboxing. We will re-open if the tension re-presents itself
