### ISSUE TITLE
Add 'maxOrgTeamCount' as user property in Amplitude

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4051]
## Issue - Enhancement

The dividing line between our free and Pro tiers is the number of teams in the organization. Right now, we don't have a way to see in Amplitude when a user has crossed that threshold, so we can't easily see how much of our user base qualifies for the paid tiers and how the behaviors of those who qualify are or are not different than those who don't. 

Feedback from @jordanh in earlier discussion on this:
> Probably the easiest thing to do here would be to add a property that works like `highestTier`, named something like `maxOrgTeamCount` that would allow us to segment users by PQL and non-PQL status

Similar to #4048. 

### Acceptance Criteria (optional)
Parabol Pals can: 
- Segment funnels in Amplitude to see the differences between qualified and unqualified users 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
oh this is gonna be a big one.
this is a trait that has to get calculated on every company, not just every organization, because that's how PQL is calculated.
to calculate the change on company, we have to calculate the change to every org in that company

so, the company triggers are:
- an organization gets added to a company
- an org gets removed from a company

then, any change to an organization must trigger a change:
- a team is created on the org
- a team is archived on the org
- a team is moved from the org
- a team is moved to to org

then, any change to the team member must trigger another change:
- the user joins an org
- the user leaves an org


we can certainly do this, but i'm suspect if the juice is worth the squeeze for an ad-hoc query. we'll have to keep this code maintained as PQL logic changes & mutations are added.

a cheaper alternative would be a job that is run ad-hoc/nightly/weekly to update amplitude. that means the number won't get updated in real time, but i think that should be OK.

another option is to just hook into when an org turns into a PQL. I think that happens in hubspot? Anyways, when that flag gets set, it could trigger an update saying "OK, this company & all it's users are now PQLs, alert amplitude". that'd be the cleanest solution because to logic would only exist in 1 place

**Comment by avivapinchas** [comment]
> a cheaper alternative would be a job that is run ad-hoc/nightly/weekly to update amplitude. that means the number won't get updated in real time, but i think that should be OK.

Agreed - real-time isn't super important here, if we have the data relatively fresh. Nightly would be my pref.

> another option is to just hook into when an org turns into a PQL. I think that happens in hubspot? Anyways, when that flag gets set, it could trigger an update saying "OK, this company & all it's users are now PQLs, alert amplitude". that'd be the cleanest solution because to logic would only exist in 1 place

I don't like this as much, because this would be less specific and thus likely less useful. For ex, maybe we want to specifically look at folks in companies with lots of teams. 

I also don't love that it introduces jargon, because as you mention, those definitions can change. If we have more raw information in there, it'll be easier to understand when you're working with that property, and we can adjust to whatever our new need and definitions are.

**Comment by jordanh** [comment]
Going to icebox this for now. If we have a new tension arise where we wished we had this data at our fingertips we can reopen
