### ISSUE TITLE
All users unable to indicate 'ready'

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4052]
## Issue - Bug

🔐[customer](https://app.hubspot.com/contacts/3888472/contact/5397101) at [client company](https://app.hubspot.com/contacts/3888472/company/1778905215) reports the following
"After we'd grouped the cards together and wanted to move on to the voting stage, the little icon you click on to signal you're ready to move on stopped working for everyone. I clicked it multiple times, but it just didn't go to the "ready" state. The facilitator did something (refreshed? left and rejoined? not sure), and then it worked again, but for a while there it looked like we needed to abandon the retro as we were stuck. 

This happened with our Product team in Parabol, around 3 pm UK time (8/5)"

**Comment by jordanh** [comment]
Interesting. It looks like their connection state went dead. We'll need to be on the look out for more of this sort of thing

**Comment by jordanh** [comment]
Making a discussion until we have reproduction criteria, stake trace, or more information to go on

**Comment by shawneeatparabol** [comment]
Is this something I can gather?

**Comment by jordanh** [comment]
This kind of bug is _very_ tricky to gather more information on in a way that feels good to the customer. What our development team needs is a means of either reproducing it ourselves under our own logins or have the customer show us the bug happening "in the act."

If you feel your relationship with the user is strong enough where you can ask, "can you reproduce this bug at will and show us when it happens?" by all means, do so. It would be a help in getting this resolved.

Otherwise, we just have to wait until we run into it ourselves or other users report it happening, I'm afraid

**Comment by shawneeatparabol** [comment]
Thanks Jordan. In this case, I was able to gather some more details and it sounds like we'll all just have to wait and see if it happens again. From the [client](https://app.hubspot.com/contacts/3888472/company/1778905215):
"The bug happened for everyone in the meeting, and we are all remote, spread across different countries, so wouldn't have all lost our connections at the same time. I'm pretty sure some of the other PMs have macs, I'm on Windows 10 and use Chrome, which also rules out a browser issue in my mind."

**Comment by jordanh** [comment]
Without reproduction or further reports iceboxing for now
