### ISSUE TITLE
Add MediaSoup microservice

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4058]
We've decided on a SFU-first approach to video conferences.
After benchmarking SFUs & looking at capabilities, mediasoup v3 looks to be the best bet.
it's also the one that's used by daily.co, so we're in good company.

@tiffanyhan feel free to edit as necessary

AC
- [x] mediasoup set up as a microservice(e.g. /packages/sfu)
- [x] a signaling service is selected & used to connect to the SFU
  - could use protoo (recommended)
  - could alternatively adapt the pay-it-forward algo that is currently in use, but probably not recommended: https://github.com/mattkrick/fast-rtc-swarm#what-makes-it-so-fast
- [x] the existing P2P MediaSwarm & underlying full mesh architecture is removed from the application
- [x] the nuts & bolts of the mediasoup demo is added to the app (https://github.com/versatica/mediasoup-demo) so 2 different browsers can have a video call

- [x] validate user authentication and authorization upon entering room on mediasoup server
- [x] instantiate http server instead of https if env is a deployed env
- [x] move all console logs to logger module
- [x] deploy to development server and record demo against it
- [ ] deploy to staging
- [ ] deploy to prod (other issue?)

Estimate: 60 hours

**Comment by jordanh** [comment]
Groomed

**Comment by tiffanyhan** [comment]
**Steps taken to deploy to development server:**
- on deployed env, create http server instead of https server
- on deployed env, set up client to call a proxy https port
  - can be derived from `PROTOO_LISTEN_PORT` env var
- on dev server, add a new port proxy to dokku using `dokku proxy:ports-add`
  - nginx should redirect to the port that protoo is listening on 
- set `MEDIASOUP_LISTEN_IP='0.0.0.0'` and `MEDIASOUP_ANNOUNCED_IP=<:public dev ip address>`
  - use `dokku config:set web <:KEY>=<:VALUE>`

**For troubleshooting mediasoup on dev server:**
- set `DEBUG=mediasoup*` to output all logs related to mediasoup
- set `DEBUG=mediasoup-parabol*` to output all logs related to Parabol's SFU mediasoup server
- use `dokku logs web` to see the logs
- use `dokku config web` to see all env vars currently exposed in the runtime

**Comment by mattkrick** [comment]
probably won't get to this in the next 6 months, will re-open when we can
