### ISSUE TITLE
HubSpot contact-level data triage

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4086]
## Issue - Bug

@shawneeatparabol reported inconsistencies when looking at Hubspot Contact records.

Here's the specific chain of events:
   * Contacts at [Company](https://app.hubspot.com/contacts/3888472/company/3957503649) 🔒 complete a retrospective meeting
   * Segment emits a `Meeting Completed` event which is re-syndicated to Slack (see this [thread](https://parabol.slack.com/archives/C2K5ZM6PJ/p1597783234183900) 🔒)
   * [Company Hubspot record](https://app.hubspot.com/contacts/3888472/company/3957503649) 🔒 updates appropriately 🎉
   * However, not all [Hubspot Contact record](https://app.hubspot.com/contacts/3888472/contact/17528401) 🔒 properties update correctly
      * `Last met at` appears to update correctly 
      *  `Parabol meeting count` does not

A couple of impacts of this:
   1. We're sending emails to folks saying "you never met!" even when they had
   1. Growth won't be able to start her new email flows without this data being reliable

### Acceptance Criteria (optional)
Users can:
   - Triaged Contact updates on meeting completion, fix if possible or new issue created if not
   - Also checked code that updates other meeting-related Contact properties: `Monthly Meeting Streak Max`, etc.

- **Estimated effort:** 6 hours ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by avivapinchas** [comment]
Just adding a note to +1 the importance of this! Besides having existing email flows currently going out with incorrect information today, this blocks essentially all new email flows from starting, because they'll be inaccurate. That includes: 
- Inactive users flow - to re-engage folks who have met but then fell off (could be published this week) 
- Lapsed users flow - to gather data on why folks have wandered away (could be published this week) 
- Onboarding flow - to get folks from sign-up to running 2x meetings, one of the critical drop off points we're trying to address currently (early drafting stage)

**Comment by jordanh** [comment]
Capping effort on this to 2 hours – if this is deeper we'll need to discuss priority trade offs in delaying sprint poker any further

**Comment by mattkrick** [comment]
Problems:
- fetching company wasn't exiting early enough for generic domains like gmail.com
- didn't check for empty array before calling DB
- `Account Removed` is getting called after the account is deleted, so the email is set to `DELETED`.
- fetching the company is occurring before the contact is being created in hubspot. 
- sometimes segment treats timeouts as bad requests, which means it doesn't retry them until successful. (emailed segment)
- `payLaterClickCount` did not have a mapping to the hubspot field
- segment only saves logs for the last 20 so there may be many, many more. will keep stomping bugs & checking back to see what new ones appear

**Comment by mattkrick** [comment]
to fix,
- don't resolve a company if the email is generic
- return early if teamIds is empty
- schedule account deletion for 30 seconds out to give segment enough time to do what it needs to do
- if hubspot returns a 404 on a user for getting their company, wait 2 seconds & then try again
- emailed segment, awaiting response
- added pay_later_click_count to mapper

**Comment by avivapinchas** [comment]
Re-opening because we're still not seeing Parabol Meeting Count updating correctly on Contacts. @jordanh LMK if you'd prefer a new issue. 

Here's an example: 
For a [user](https://app.hubspot.com/contacts/3888472/contact/15124951/) 🔒,  the field 'Parabol Meeting Count' is set to '2'. If you look at 'details' for that field, you can see that was last updated on May 26, 2020. 
![image (37)](https://user-images.githubusercontent.com/11621016/94061402-f252c600-fdaa-11ea-95d4-fb305d5f36f4.png)

However, when we look at pages they've viewed, you can see that they've met multiple times since then: 
![image (35)](https://user-images.githubusercontent.com/11621016/94061604-39d95200-fdab-11ea-8b50-36872a86f95f.png)

You'll also note that the account was created on May 26, 2020, so it's strange for `Parabol Meeting Count` to have updated on that same day to show 2 meetings. 

If we look in [Amplitude](https://analytics.amplitude.com/parabol/chart/dyw0bm0)🔒, you can see that this user has completed 11 meetings, and all of these were _after_ May 26, 2020.

**Comment by jordanh** [comment]
![image](https://user-images.githubusercontent.com/103000/95246278-18c02a80-07c9-11eb-8f04-1f0cf0a94b7c.png)

AC
- Triage inaccurate `Meeting count` property and fix
- New issue opened if not fixed, but diagnosis is made

EE
- Effort capped at 2 hours this sprint

**Comment by mattkrick** [comment]
the reason this isn't updating is because it was never in the spec (yay easy answer!)
spec here: https://www.notion.so/parabol/Analytics-Data-Schema-1e311e3f1c4c44a3be59bfff8d8d954e
issue here: https://github.com/ParabolInc/parabol/issues/3854

we'll have to add it to the GraphQL schema in order to accomplish this.
If a user was invited to, but never attended, a meeting, I'm going to exclude that from the count.
That seems more accurate.
Plus, in the future it will be harder to track meeting that someone was invited to but never attended (https://github.com/ParabolInc/parabol/issues/4112).
