### ISSUE TITLE
Bulk email invitation

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4090]
## Issue - Bug

[User](https://app.hubspot.com/contacts/3888472/contact/7270101) 🔒 :

1. Opens a new Outlook message
2. Types in an email list alias
3. Expands the alias to (51) contacts
4. Select all and copy, paste into Parabol invite form
5. Manually edits to change format from "Lname, Fname <user@domain.com>; ..." to "user@domain.com, ..."
6. Hits send
7. Sees error text under the "Send 51 invitations" button

Steps to try and reproduce on our side:

1. Generate a list of 51-ish users in the form "user+bugtest1@parabol.co, user+bugtest2@parabol.co, ..."
2. Paste and try to send

My guess is we're getting throttled by mailgun and presently don't have a way to queue/retry requests.

### Acceptance Criteria (optional)
   - Triage and open new issue to fix
   - Consider enhancing parsing to allow for Outlook's "Lname, Fname <user@domain.com>;..." semi-colon delimited format
   - Communicate with user on findings an expections

Estimated effort: 4 hours

**Comment by tiffanyhan** [comment]
Copy and pasted directly from email list in Outlook. Send button is disabled at first because of formatting. She manually removes last name, first name, semicolons, so that input only contains a list of comma separated emails. After that, the send button is enabled. Upon clicking "Send" she gets an error message. However, emails actually went through which she discovered later from talking to invitees.

**Comment by mattkrick** [comment]
i don't think this is a mailgun throttling issue, if it were, we'd see an error in sentry.
@jordanh if i'm wrong, please include an email so we can dig into it further!
