### ISSUE TITLE
Support tasks without assignees

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4115]
This is blocking sprint poker SCOPE phase

A story is just a task without an assignee.
to keep our IA nice & tight, we should reflect that.

questions
- should a task without an assignee appear on the kanban?
- if so, we need a "UNASSIGNED" magic keyword as a filter criterion
- if so, do those stories get added after they've been added to the estimate phase? or after they have been assigned a point value?
- if we include integrated tasks (eg jira) then when the story gets assigned in jira, we'll have to update the assignee in parabol. if we do that, we need to create a jira user -> parabol user mapper & have a fallback if no parabol user exists for an assignation

this seems right, but it seems like a lot of work.
a simpler approach is to just exclude tasks w/o assignees from the kanban

AC
- [ ] the `Task` object is refactored to support null userId
- [ ] all task mutations are updated to support a Task with a nullable assignee (e.g. createTask, updateTask, deleteTask, etc etc)
- [ ] A Task card shows a question mark as the assignee if it doesn't have an assignee
- [ ] The Task assignee dropdown in the Task card footer includes the current assignee's name. if already selected & clicked again, the task becomes unassigned
- [ ] the `tasks` query returns only tasks that have assignees

Estimate: 16 hours

**Comment by ackernaut** [comment]
Some of my (non-clarifying, doh) questions:
- How often folks are estimating something that has been assigned in Jira or not?
- Do folks really expect Jira tasks to be tasks matched to the Parabol team and show up in the kanban query? It seems like the most likely trend is for folks to handle team meta work as Parabol cards but wouldn’t be inclined to create and/or sync tasks that really live somewhere else. I think the value add is more around showing a test of integrated tasks in the context of an activity rather than cluttering up a one-size-fits-all board for the team.
- I’m wondering if we hide the owner in this context
- I’m wondering if we separate the inclusion of integrated tasks in certain activities from inclusion on the kanban. For example, with the Hot Take #4107 idea, would we expect all those integrated objects referenced in a post to be added to a kanban?

**Comment by jordanh** [comment]
> How often folks are estimating something that has been assigned in Jira or not?

Quite often, it's fairly common behavior for assignments to be delayed until the work is "accepted" by a team member. It'll be a behavior we'll need to design for

> Do folks really expect Jira tasks to be tasks matched to the Parabol team and show up in the kanban query?

We don't know. I like @mattkrick's suggest of, "a simpler approach is to just exclude tasks w/o assignees from the kanban" as it feels like it doesn't pain us into a corner. We can ship and learn

> I’m wondering if we hide the owner in this context

Clarifying question: hide the owner in which context?

> with the Hot Take #4107 idea, would we expect all those integrated objects referenced in a post to be added to a kanban?

Unspecified at this time, but a good question to explore, for sure!

**Comment by ackernaut** [comment]
Clarification: we hide the owner in the context of Sprint Poker — I’d say it’s purely about understanding the story and estimating it. I think the next best thing would be to show the owner if there’s a clear mapping between Parabol and the integration and the task has been assigned to somebody, but that seems very conditional and also based on assumptions.

**Comment by mattkrick** [comment]
correct, i think we have an internal `Story` entity that is a `Task` without the `owner`.
So we'll have a `StoryCard` component that is just a wide Task card without the owner.
