### ISSUE TITLE
Recurring meeting prework

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4120]
Here are meetings & their prework:
- Check-in meetings: agenda items
- Poker: scoping
- standup: task status enumeration
- one-on-one: agenda items
- retro: thoughts*

* I say retros have thoughts because a reflection belongs in a column. since the column is non-deterministic before the start of a meeting, they can't be reflections.

A meeting can be recurring or one-time.
A meeting state can be OPEN or CLOSED. this is important. we want to avoid 3 states (open, in progress, ended) to keep things simple.
The big problem is if a retro meeting is recurring, then we want to auto-open the new one when the old one closes. but then how do we select which template to use?

bad idea: when the facilitator changes the columns, we move reflections to the new columns, although they may be mismatched. if we do this, we need the reflect phase to look more like the group phase so they can drag them across. or have a "columns changed, please map your columns" gross wizard.

bad idea 2: we have a "thoughts" phases where folks can enter thoughts & then the "reflect" phase where folks put thoughts into columns

bad idea 3: after a retro meeting is ended & before the next recurring one begins, we force the ex-facilitator or team lead to pick a template. light touch is to have that be on the team dash (e.g. your team can't reflect until you pick a template). heavy touch is a notification or modal.

**Comment by ackernaut** [comment]
I personally like a ‘thoughts’ bucket because they could probably fit into some ‘good, bad, missing’ connotation regardless of the flavor of the template. I could drag thoughts into columns from my private notes. I’d like to just make atomic notes as the day goes by without worrying about where they go. It’s up to me to add fidelity to the notes (tags, team, type).

I think if a recurring retro automatically opens when the last one is closed we could force the first person who wants to join the activity early to pick the template. That may be friction but it would increase the autonomy of teammates fitting our own opinionated culture.

Or yeah, we could do some drunken house drawing sorting of their reflections into new columns based on the what the AI thinks the sentiment is.

Or we could throw any reflections added back into a user’s thought bucket and they could drag them back out into the new prompt columns.

My vote is that I just add a reflection and stick it in a column later. If I need to rewrite it a little that’s probably helpful friction.

**Comment by mattkrick** [comment]
i wrote this before that pen & ink. i think a thoughts phase is a bad idea. it's 1 more step, it increases the amount of work it takes to get reflections into the system.

**Comment by mattkrick** [comment]
i'm happy closing this & continuing the discussion on wrt the meeting section in the Team View
