### ISSUE TITLE
Reflect Template Modifications

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4128]
Chatted with a possible enterprise client (my girlfriend). @ackernaut eager for your thoughts

Acceptance Criteria:
- [ ] The top list item is a control, [Create New Template](https://www.figma.com/file/wYDUg5qQMjbEllgxBY37sT/Template-Editor-Dialogs?node-id=591%3A40). This control is hidden when there’s a template called ‘[*New Template](https://www.figma.com/file/wYDUg5qQMjbEllgxBY37sT/Template-Editor-Dialogs?node-id=591%3A472)’
  - The "+" FAB is confusing. I'm told people think it means "Select & Start Meeting" based on its location. Let's get rid of it. On the Team tab, we have a "Create New Template" list item. clicking it turns it into a new item. this makes it impossible to create 2, which eliminates a possible error state.
- [ ] The floating button ‘Use Template’ is an explicit control to use the selected template for the meeting. If folks navigate to other templates (e.g. just browsing) but close the dialog instead of tapping the Use Template button, the template selection doesn’t change.
  - **Edited**: a new template can only be selected by using the Select button. Navigating to view other templates, and exiting the modal without selecting, doesn’t change the template for the meeting. ~Consider adding a "Select" button somewhere (maybe to replace the fab?). The only thing it does is close the modal. I'm told it feels weird that you select something & don't click anything after that.~ 
- ~Clone & Edit Template Icon is closer to the Template title (maybe 32px left padding vs. 200px+ away)~

Estimate: 8 hours

**Comment by ackernaut** [comment]
The solution ideas sound reasonable, and I’m glad you captured the feedback.

>On the Team tab, we have a "Create New Template" list item. clicking it turns it into a new item. this makes it impossible to create 2, which eliminates a possible error state

**Question**: if I create a new template, when do I see the option to create another new template?

**Reaction and light tension**: maybe we could add some friction here, reframe it as `user feedback`, take some verbatims and source, and list the bullets as possible solutions?

I think the better process is to capture feedback from many folks on the Retro template dialog instead of moving quickly to solutions on (assuming) 1 source of feedback. What if somebody else captures a different point of feedback and opens a solution issue that’s conflicting?

Otherwise, it’s safe to try as a fast 2-way decision.

**Comment by ackernaut** [comment]
@tianrunhe feel free to question me on the UI details. I can create visuals as needed.

**Comment by ackernaut** [comment]
This issue doesn’t solve for #4045 but sticking [the floating Use Template button in the bottom right of the dialog view](https://www.figma.com/file/wYDUg5qQMjbEllgxBY37sT/Template-Editor-Dialogs?node-id=591%3A1768) regardless of the inner view (list, details) would solve for any breakpoint
