### ISSUE TITLE
Triaged failing Cypress integration tests

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4235]
We’ve had to disable Cypress integration tests to ship. This issue proposes a way forward to fixing tests.

These tests are probably failing intermittently due to timing out or something else:

- demo_discuss.ts
- demo_group.ts
- demo_reflect.ts
- demo_vote.ts
- login.ts
- me.ts
- signup.ts

These probably require more effort to fix:

- archivedTasks.ts
- userTaskView.ts

### Acceptance criteria
- Triaged tests
- Made any quick fixes (timeboxing the effort)
- Noted any intermittent failures that require no change (e.g. test times out some of the time)
- Added each test that needs more work to `ignoreTestFiles` in `cypress.json`
- Created an issue per test that needs more work, including an acceptance criteria item for removing the test from `ignoreTestfiles` once it’s working

### Estimated effort
- 3 hours

**Comment by tianrunhe** [comment]
Test failures are caused by [resetDB](https://github.com/ParabolInc/parabol/blob/master/packages/cypress/plugins/resetDb.ts). It was intended to reset the test DB so each test starts at a clean slate. However a side effect is that the `QueryMap` table was also wiped out. The test [error](https://app.circleci.com/pipelines/github/ParabolInc/parabol/961/workflows/7fe42c57-2b14-4d16-b76e-6782a97a0ed5/jobs/9856/parallel-runs/0/steps/0-109) revealed this was the issue:

```
SEND TO SENTRY Error: DocumentID not found: s_Qy6wht0eUbEhB3HbBj5p_g
    at ge (/home/circleci/action/dist/web.js:1:966558)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) undefined
SEND TO SENTRY Error: DocumentID not found: s_ovYDcKBPeHyJJQ_ngVWKbw
    at ge (/home/circleci/action/dist/web.js:1:966558)
```

I tried to filter it out from the list of tables to reset [in this commit](https://github.com/ParabolInc/parabol/blob/master/packages/cypress/plugins/resetDb.ts#L18) but it doesn't work as `r.tableList()` does not return a list of strings.

**Comment by mattkrick** [comment]
this returns a RValue instead of a pure string, so you'd have to call `t.eq('Foo')` i think

**Comment by mattkrick** [comment]
goals:
- run tests in parallel
- get rid of the tarball
- be easy for new devs to start writing tests

proposal:
- create a `primeDB` function creates a new database called `cypress` and have a chain of tests that runs (e.g. sign up a new user, then add a new team). this is run before everything else
- before each test, we call a function called `clonePrimer(dbPrefix: string)`. this function will create a new DB (e.g. cypress-archiveTasks) and then clone the `cypress` tables to this new DB.

the above method will guarantee that tests can be run in parallel. the only problem is creating a new DB connection pool with the right dbPrefix. not sure how to do this

**Comment by tianrunhe** [comment]
Created #4249 , #4248 and #4247 to address the test failures.

**Comment by ackernaut** [comment]
Thanks @tianrunhe
