### ISSUE TITLE
Poker: Estimate: Deck of cards

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4257]
Given an array of scale values: `[{label: 0, value: 0, color: 'blue'}]`, create a deck of cards that looks like this: https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118425

Acceptance criteria:
- cards look like the figma design
- clicking a card puts it in a "selected" state which causes it to lift out of the deck
- the deck has a collapsed state (can be triggered via a cheat code or similar for now) where the deck collapses down to the width of a single card & the selected card is on top of the deck. this animation is smooth and abides by material design guidelines (ie the cards don't do anything that real life playing cards can't do)
- per the figma designs, for a deck of 11 cards, the resting state of the cards in the center are 12px higher than the cards on the edges. as the deck size increase & decreases, this delta should change, too. 
- for decks with fewer cards, they are more spread out, but they are always overlapping (e.g. overlap in figma is 100px for 11 cards, for 3 cards maybe it's 75px)
- BONUS: when hovering a card, it becomes the center of the curve of card heights. that is to say, given 11 cards, the card being hovered is 12 pixels higher than the card furthest from it. the cards next to the one being hovered are a few pixels lower (e.g. 9 pixels). the cards around those are slightly less (e.g. 5px)

Guidance:
- Achieving the slight curve that the cards have is a bit difficult because it has to look good whether there are 3 cards, 10, or 30. A naive approach would be to derive the max height from the number of cards and some coefficient (e.g. 11 cards * 1.1 = 12px) and set the height based on the index delta (e.g. if the tallest card is at index 3, then `heightOfIndex5 = 12px - (5 - 3)*3px = 6px`). this works, but implies a linear falloff. another approach might be to create a normal distribution & then match the centroid of each card to the curve of that distribution. beta distributions can look good, too.
- animating the deck from collapse/expand is difficult because we want the selected card to end up on the top of the deck, but it's somewhere in the middle. Just like real cards, the selected card should not be able to float through other cards like a ghost through a wall. it should be like real life. so, that means the selected card has to come out of the deck & then get put back in on top. should take ~300ms using the DECELERATE bezier curve. see ReflectionStacks in the group phase for inspiration. here are some options, not sure which would look best:
  - once the deck is collapsed, the selected card animates up from 60px to 175px (full height), box shadow increases to show elevation & then it slides down to 0px to sit on top of the stack
  - once the deck is collapsed, the selected card animates right 125px (full width), box shadow increases to show elevation & then it slides left to 0px to sit on top of the stack
  - while the deck is collapsing, the selected card moves to the right more slowly than the rest. once the selected card is at least 125px to the left of any other card, it can then go directly to the top (this is probably best because it has the least movement)

**Comment by ackernaut** [comment]
Thanks for writing out these AC. They’re very good. Here are a few of my thoughts:

- **Curvature**: for [this example hand of 11](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118425) (Fibonacci 0…34 + ? + Pass) I had raised each card 3px higher than the other.
  - The intent was for it to be the minimum amount indicating in a clear and crisp way that one card’s higher than the other.
  - I also didn’t want the hand to get too tall especially on mobile
  - I’m okay with a formula that has a nice min and max difference to give the curve effect. Not too little or too large of a difference.
- **Layout**: I set the top of the lowest card in the curve to be 56px above the bottom bar (56px is the size of a FAB excluding any margin of separation). I set the raised card to be 56px higher than the cards next to it. I’m matching FAB footprint in a sense. We may consider going tighter but I think too tight would reduce clarity and contrast. We should have enough room for this [on mobile because the stack is](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/Sprint-Poker?node-id=2689%3A118689): top bar, collapsed issue card, dimension column header, row of people who voted, maybe tip banner, the deck, the bottom bar. If there’s mobile browser chrome it’ll be tight but should work. In the review state, the list of vote rows will overflow beneath the bottom bar and be scrollable. 
- **Overlapping**: I set the edge of the overlapping card as close as I could to the number. I wanted to avoid the number being overlapped. A card with a single digit is more overlapped than a card with double digits.
  - I’m not sure we need to maintain a min-width, but if there are fewer cards, yeah we could add a variable for increased spacing.
  - I’d like to avoid overlapping the values when possible. Having a char max of 2 (e.g. ‘34’ or ‘SM’) will help. Since we are probably sticking to 2 it’s okay to space all cards equally.
- **Hover**: I like the idea of the curve moving to follow the mouse. I also think we could play with the card lighting up just a little, or raising up just a little in elevation (z-axis).
- **Selecting**: I think that if one selects a card, they can’t do anything else to that raised card. They can only select another card. If they didn’t really want to vote then they can hit the pass card. They’re locked into their feedback and can only change it.
- **Collapsed state**: I like the idea of the hand animating over quickly while the selected card remains behind. In reverse, maybe the deck animates back into place quickly, then the selected card slides into its position and z-index?
  - When the votes are revealed, the hand will collapse using the functionality described here. If a user taps on the collapsed deck it expands again so they can change their vote.

I’m okay with how we normalize and codify this (not attached to specific numbers, etc.), I just wanted to expose more of my nuanced thinking when making it.
