### ISSUE TITLE
Flood of MediaSoup errors sent to Sentry.io

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4290]
## Issue - Bug

We are currently sending a lot of [error events](https://sentry.io/organizations/parabol/issues/1957402732/?project=107196&query=is%3Aunresolved) to Sentry.io, so much that we have crossed the free tier. The error seems to relate to Mediasoup:

![](https://user-images.githubusercontent.com/1879975/97233467-40892980-179c-11eb-97cc-59bfca8dc793.png)

and it happens on Edge on Windows only:

![](https://user-images.githubusercontent.com/1879975/97233508-50a10900-179c-11eb-9f48-0f1589ecc017.png)

### Acceptance Criteria (optional)

*   Fix the error if possible
*   If not, supress the error so we don't overflow Sentry.io

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
edge doesn't yet support object property rest syntax. the error is throwing from library code. it looks like the mediasoup client library as-is isn't transpiled to use safely cross-browser. a possible solution is to un-ignore the library in webpack babel settings, so the heavy lifting of transpiling falls to us.

**Comment by tiffanyhan** [comment]
mediasoup-client `Device` class incorrectly parses edge browser as Chrome74. this is either a problem with mediasoup-client or bowser itself

**Comment by tiffanyhan** [comment]
After fetching the latest patch of mediasoup-client, `https://github.com/ParabolInc/parabol/blob/mediasoup-edge/node_modules/mediasoup-client/lib/handlers/Chrome74.js#L4` should not have any rest parameter syntax in it. This syntax was tripping up edge 18 even though the code wasn't being executed, because the browser wasn't able to parse the syntax when it loaded javascripts. This update brings in a patch that fixes the issue by targeting an older ES version in mediasoup-client's tsconfig file.

**Comment by tiffanyhan** [comment]
https://sentry.io/organizations/parabol/issues/1957402732/?project=107196&query=is%3Aunresolved

this error occurred 7 days ago, even though the fix was released to production before that. the same problematic destructuring syntax is shown in the sentry stack trace, even though that syntax no longer exists in the `5.23.0 2020-Nov-04`. Could the browser be somehow cacheing an old version of Parabol?
