### ISSUE TITLE
Support small/large poker decks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4314]
All designs today only support a defined number of cards.
We need to support anywhere from 2 - 20-ish cards.

AC
- [ ] a 20-card deck looks good on mobile and laptop
- [ ] a 3-card deck looks good on mobile and laptop
- [ ] provide a set of breakpoints, number of cards, tilt, and radius for the equation

Estimate: 8 hours

**Comment by ackernaut** [comment]
An update: I’m tracking along [here in Figma](https://www.figma.com/file/csERjrh67KZKgnT5VahFSb/?node-id=3855%3A176304)

#### Goals of the deck:
- We maximize scan-ability and legibility of the cards
- It’s clear when I’ve voted; which card is selected
- There’s good feedback on what’s happening (hovering a card, it collapses when discussing etc.)
- Animations are both delightful and purposeful
- The layout looks good, natural; there’s plenty of space for the rest of the view concerns

#### Some UX concerns with the deck:
- If there are too many cards it’s hard to scan the values; we don’t want folks to have to tap on cards just to verify the value
- If there are many cards the area to click or tap becomes annoying small
- Small decks like 3 cards may look funny but at least they’re usable (can see the label, can tap without collisions)
- On mobile, the edges may collide with the swipe zones of the sidebars (~20px) — first and last cards of large decks are virtually inaccessible
- On mobile, there’s no hover feedback

#### Some potential solutions
- We could calculate the overall width of the layout based on the number of cards. Ideally you can see 2 digits on the cards.
- We can increase the hover lift from ~8px to ~32px so that the value on the card raises above the other cards so that it’s not hidden in a large deck. This is not a strong solution. On laptops, we have room to spread the cards out and on mobile, there’s no hover stage.
- We could reduce the size of the value label so that more of it shows in tight decks. I like the current size as it feels proportional on the card-shaped surface so I don’t like this solution. We could change that font-size conditionally based on the number of cards. This still doesn’t help for larger decks without more separation between the cards.
- We could set an upper limit to decks, perhaps 10-13 cards meaning the user can define 8-11 cards because the deck includes ‘?’ and ‘Pass’ cards. One benefit is that we could see if folks comment on this limitation and then look good when we provide a solution for them (‘hey they listened!’)
- We could set a minimal separation between cards; for large decks, the overall container could be scrollable left to right when there’s overflow. I.e. I may not see all the cards all the time, but I could scroll the container over the other end of the deck. This is probably hard to get right. I think we’d want to automatically scroll to any end when loading a deck with an already selected card. Then users could explore.
- We could scale down the overall card size; we could do that conditionally for the number of cards or for mobile

#### Recommendations for v1
- We limit the deck to 10-13 and see what folks say
- We make sure there’s a minimal collision with the swipe zones; this is less of a problem with the limit of 10
- We set a min and max separation based on the number of cards

**Comment by ackernaut** [comment]
@mattkrick we should take 30 minutes to review this together

**Comment by ackernaut** [comment]
`(output) =>` #4408
