### ISSUE TITLE
Hubspot App Meeting Count Incorrect

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4315]
## Issue - Bug

Meeting count for Companies and Users in the Hubspot Parabol App is off. 

Sales is able to manually double-check and correct this information so it is not impacting our work very much. 

Marketing, however, builds automated workflows off of the Parabol App data (including meeting count and 'last met at') so these discrepancies can negatively affect their campaign efforts.

Loom videos for 2 accounts showing the discrepancy can be found in this 🔐 [ticket](https://app.hubspot.com/contacts/3888472/ticket/235964632) 

🔐 Accounts referenced in videos: 
[Account One](https://app.hubspot.com/contacts/3888472/company/2546790177) / [Contact Referenced](https://app.hubspot.com/contacts/3888472/contact/15334651)
In this instance, the top user at the company is showing a 0 meeting count despite being the highest team lead & user at her company in Org Stats. Her 'Last Met At Date' is also incorrect.
[Account Two](https://app.hubspot.com/contacts/3888472/company/2291923088) / Contacts Referenced: [1](https://app.hubspot.com/contacts/3888472/contact/10837451) and [2](https://app.hubspot.com/contacts/3888472/contact/13540251)
In this case, we are showing a 10 meeting discrepancy for contact 1 and a 2 meeting discrepancy for contact 2

**Comment by avivapinchas** [comment]
I wanted to check on whether timing as possibly the issue (maybe the numbers are off, but they hadn't completed meetings since we made updates to the integration). 

That doesn't seem to be the case - both Companies have held meetings recently: 
- For Account one, I'm seeing in Hubspot that the Company's 'meetings completed' field was last updated Aug. 28. In Amplitude, you can see that users with that company domain[held ~3 meetings in Sept and ~3 in October](https://analytics.amplitude.com/parabol/chart/oj90lpz)🔒 . So it looks like that field didn't update those times, for some reason. 
- Also for Account two, their Company 'meetings completed' was last update on Aug. 31, but they've [held ~25 meetings since then, according to Amplitude](https://analytics.amplitude.com/parabol/chart/krfuueo)🔒 .

**Comment by shawneeatparabol** [comment]
Purely for documentation purposes, reporting a similar discrepancy with🔐 [this ticket](https://app.hubspot.com/contacts/3888472/ticket/236152001/)
Likewise, Amplitude is showing recent activity, on Oct 27 2020 and Oct 22, 2020 but Hubspot was showing most recent meeting as 8/26/2020.

**Comment by avivapinchas** [comment]
It looks like `Last Met At` on the Company records is actually not updating at all: looking at Companies in Hubspot, sorting by `Last Met At`, I see no meetings logged in December or November, and only a handful in October.

**Comment by jordanh** [comment]
Thank you for finding this. We'll take a look next sprint
