### ISSUE TITLE
Accept snackbar can let multiple users in at once

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4326]
### Background
If we increase the likelihood that the snackbar can be used to let people in securely #4325 it should be a better experience to allow for a user to accept all instead of one a time, especially for a new team or first-time experience.

### Acceptance criteria
- [ ] Designed a UI that allows a user to accept one incoming user at a time, or to accept all

### Estimated effort
- 12 hours

### Related
- Invitation links always work for existing team members #4322 
- Invitation link expiration increased with domain verification #4323 
- Invitation email expiration increased to 30 days #4324 
- Expired invitation links trigger the accept snackbar for active team members #4325 
- Invitation dialog design updated #4327

**Comment by mattkrick** [comment]
i'd like to hit the brakes on this one.
When Grayson was logged in as someone else, it was very good that the email address popped up. if he was part of a batch accept, we would have let someone on the team that didn't belong. Our team permissions are _very_ permissive. we let 1 bad apple in, they spoil the bunch because they can invite infinite other people.

IMO, I'd rather compromise & just increase the expiration to 7 days.

**Comment by ackernaut** [comment]
I agree this one needs more thought but I was okay to capture the idea as design work, expecting discussion.

**Comment by jordanh** [comment]
Iceboxing
