### ISSUE TITLE
Poker Edge Case Tests 

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4369]
Here's a list of things that will probably break poker that we should fix before shipping: 
- [x] viewing the meeting as someone not integrated with jira
- [x] switching facilitators halfway through & the 2nd facilitator isn't integrated with Jira
- [ ] switching facilitators halfway through & the 2nd facilitator is integrated with jira but doesn't have access to the project
- [x] Jira doesn't respond. We need to put a timeout on it & make sure the response looks exactly like we want & if not, it returns null. If null, the client should handle it gracefully
- [x] updating issue/adding comment fails (or jira hangs). an error should be thrown & the client told that jira is down
- [ ] integrated with 2 jira clouds. the field "story points estimate" has a. different ID for each cloud, but it still works
- [x] for each method in `AtlassianServerManager` go through the poker meeting & make fail via timeout & fail by returning an error. make sure we handle everything gracefully
- [ ] de-authenticate with the jira integration after setting the scoping phase. it fails gracefully
- [x] join a team after a few rounds of voting. what does my vote look like?
- [x] limit to 50 tasks max
- [ ] change the template after the meeting ended. change the dimension name, delete a dimension. delete a few scale values. change their colors. after each change, check out the ended meeting. it shouldn't bork.
- [x] no announce hover when deck is collapsed

**Comment by ackernaut** [comment]
### Parabol user loses Jira access
I started a poker meeting with a user who added the Jira integration. Then I removed their Jira access in Atlassian.

- The left nav becomes keys e.g. TES-463
- The story card becomes an error message
- This person can’t add votes

Basically, the stories are unusable, the only thing to go by is a Jira ID.

I then became the facilitator with another user who still had Jira access and was integrated with Parabol.

- The stories that the previous user added weren’t usable by the new facilitator (still no description, can’t add votes)
- I had to remove those stories and re-add them

Overall, this is probably an edge case. However, if somebody lost access for some reason it might not be apparent what to do. If another person was keen enough to take over facilitation, could the stories as keys already added just work for that person if that person was integrated with Jira? Maybe the stories as keys could refresh (remove and readd) when facilitation changes? Since it seems there’s no description or ability to add a score, what would it hurt to find keys and replace them with a usable story behind the scenes?

Otherwise, folks need to know to remove those stories and re-add them. Just noting what the behavior is, not sure we need to prioritize.

**Comment by mattkrick** [comment]
Those 2 error messages are ugly. Do you have steps to reproduce?

Burndown:
- [ ] intercept those 2 ugly error messages & replace with something friendlier
- [ ] Change error story card to suggest re-adding in scope stage

**Comment by ackernaut** [comment]
### Integrated Parabol task cards
What do we think the user expectation is around a Parabol task card that is integrated with Jira? Does it show up on both Jira and Parabol tabs in poker? I asked the same question [re: GitHub here](https://github.com/ParabolInc/parabol/issues/4414#issuecomment-740880488)

**Comment by ackernaut** [comment]
@mattkrick the steps are in the original comment. Basically I added Jira to the poker tab with Jira user B and then with Jira user A I kicked Jira user B. Jira user B was still facilitator so was only able to add and see storys via the key hence the states above. Anything missing from those details?

**Comment by mattkrick** [comment]
> Integrated Parabol task cards

thanks for the headache. that's a good question.
i'd assume a single source of truth.
if you update a raw jira issue, it should update the integrated parabol task
and vice versa
adding both should not be possible. we should silently pick the parabol issue, since we should always prefer our system & they may keep extra metadata (ie story points) in parabol that they don't keep in jira

**Comment by mattkrick** [comment]
closing in favor of individual issues that we can handle post-beta
