### ISSUE TITLE
Implement poker deck size behaviors

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4408]
This is the output of #4314 

**Nota bene**: our fixed settings look good for our default Fibonacci deck that has 10 cards. It’s enough to get us testing. However, we want to support larger and smaller decks.

### Goals
- Labels of 2 characters are always visible
- Folks should be able to scan many cards without hovering or tapping
- Folks can access cards that are in the overflow or compressed
- There are gutters that allow the end cards to be scrolled or swiped out from under the swipe zones of the left and right sidebars
- The deck works well on mobile

### Acceptance criteria
- [ ] The radius is calculated as `cardCount` * `120` 
  - This is so that the labels are always visible
  - We could use up to about 150-160 instead of 120 if we want larger labels like ‘WW’ to be completely visible
  - With large decks, this may cause overflow which we’ll handle by scrolling or sliding, see below
  - The smaller tilt of 8 works well because it keeps the larger decks from getting too wide in order to show labels of 2
  - This keeps smaller decks from spreading out too far; they have card spacing like larger decks
- [ ] TBD a or b
  - a) we set an outer container to use a simple `overflow: auto` with gutters on the inner container on both ends to clear the swipe zone. This will allow folks to scroll to cards that fall out of the viewable area (width of the outer container)
  - b) we set an invisible slider that compresses and expands the card spacing. I imagine folks could hover with a mouse or slide their finger on a mobile device to a segment of the deck so that that segment of cards expands relative to the cards around it

### Estimated effort
- 20 hours

**Comment by mattkrick** [comment]
current deck feels bad when cards have labels that are bigger than 1 char.
i think this spec gives us something good to build on.
my trigonometry is rusty though, this will take a little time.

**Comment by mattkrick** [comment]
i don't think scrollbars will work since these cards are absolutely positioned.

alternatively, we could put a left/right arrow on either side of the deck. hitting the right arrow will collapse the leftmost 5 cards & expand the next 5 cards on the right. this could be good for mobile as it is really intuitive on how to see more.

a more beautiful way would be to have an invisible slider like you say.

either way, we'e basically got `visibleCards = Math.min(maxCards, totalCards)`. moving right will simply change the centroid 1 to the right & move the left penultimate on top of the leftmost. it'd be great to do this as a continuous distribution, so the centroid !== center of the middle card, and calculate offsets from there.

**Comment by mattkrick** [comment]
from a user: https://app.hubspot.com/contacts/3888472/ticket/286501924/

> We have ~20 options in our scale… I know it's a lot, but it works for us. One small problem is that when a card is not selected, we can only see the first digit, the second one is hidden behind the next card.

**Comment by mattkrick** [comment]
if we're getting called out on this in EAP, it's probably best to fix before GA. Promoting up the backlog

**Comment by mattkrick** [comment]
> Why are the cards so small and jumbled together? I like that they are color-coded but spread them out, will you!? :) Plus the story point votes were also very small. You have real estate - use it.
