### ISSUE TITLE
Hubspot `Monthly Meeting Streak Max` not updated sometimes

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4411]
## Issue - Discussion 

We funnel some data from Parabol into Hubspot to allow us to create and track Deals, manager marketing automation and so on. We've noticed that the `monthly meeting streak max` field is not updating. 

The examples are: 
[Company #1 ](https://app.hubspot.com/contacts/3888472/company/4290741113/) 🔒 has `Monthly Meeting Streak Max` at 1, but in [Amplitude we can see](https://analytics.amplitude.com/parabol/chart/80vv64e/edit/37yo1q1) 🔒  they've met consistently since August, including the same user meeting each month. I'd expect the streak to be at '4'. 

[Company #2](https://app.hubspot.com/contacts/3888472/company/3845448712/) has `Monthly Meeting Streak Max` as blank, but in Amplitude, we can see [they've met in both October and November](https://analytics.amplitude.com/parabol/chart/i51jemy/edit/1x0xgbr), so it should be 2. 

[Company #3](https://app.hubspot.com/contacts/3888472/company/4580725034/) also has `Monthly Meeting Streak Max` as blank, but again, in Amplitude, [we can see they've met in October and November](https://analytics.amplitude.com/parabol/chart/7evrcp8) 🔒 . I'd expect the streak to be at 2. 

In all cases, other fields on their record, like `active user count` _has_ been updated accurately and recently. 

### Questions to answer
The Hubspot field _seems_ incorrect to me, but I could imagine that due to some edge-case user behavior, the data might be coming in correctly, but how we've defined 'streak' needs to be tweaked. 

So my questions are: 
 1. How is a 'streak' defined in the code? Is it possible in the above examples that the Hubspot data showing streaking is correct? 

@mattkrick  I think this is one for you 

2. If the Hubspot data is incorrect, can we suss out why it's not syncing properly?

**Comment by mattkrick** [comment]
There's 3 kinds of streaks:
- There's a company team max streak (calculate the streak for each team in the org, then return the highest one): https://github.com/ParabolInc/parabol/blob/47cf7c46ead4c441a5d2fd9d5dc0e6788bef5e64/packages%2Fserver%2Fgraphql%2Ftypes%2FCompany.ts#L91
- A User's max streak (how many times has a user been in a meeting without taking a break for more than ~30 days): https://github.com/ParabolInc/parabol/blob/47cf7c46ead4c441a5d2fd9d5dc0e6788bef5e64/packages%2Fserver%2Fgraphql%2Ftypes%2FUser.ts#L159
- A User's current streak (starting today, log every previous meeting & keep going back until there is a gap greater than ~30 days): https://github.com/ParabolInc/parabol/blob/47cf7c46ead4c441a5d2fd9d5dc0e6788bef5e64/packages%2Fserver%2Fgraphql%2Ftypes%2FUser.ts#L172

do you know which kind amplitude uses?

**Comment by avivapinchas** [comment]
That's helpful! 

> There's a company team max streak (calculate the streak for each team in the org, then return the highest one) 

I think this is the streak that's being synced to the `Monthly Meeting Streak Max` field in Hubspot. 

> do you know which kind amplitude uses?

For the Amplitude links, I was just looking at `meeting completed' events for folks who had each company's email domain. 

Since the company team max streak is about which team had the longest streak, I just now segmented these by 'teamID', and here's what I'm seeing: 
- Company #1: one team has [met consistently for 4 months](https://analytics.amplitude.com/parabol/chart/ord9zna), so `monthly meeting streak max` should be 4 
- Company #2: one team [met in October and November,](https://analytics.amplitude.com/parabol/chart/k2wikmf) so `monthly meeting streak max` should be 2
- Company #3: one team [met in October and November](https://analytics.amplitude.com/parabol/chart/576bebz), so `monthly meeting streak max` should be 2

**Comment by mattkrick** [comment]
this is really helpful.
using the first customer as an example:
- the data is correct in our system
- the data is correct in amplitude
- the data is NOT correct in hubspot
- hubspot has received other updates, just not the meeting completed events

so, we are sure the event fires on our system & goes to segment. we know segment receives it because they forward it to amplitude. we know segment sometimes forwards things for this customer to hubspot. we just don't know why this message in particular didn't make it through. That means the message from segment to hubspot must have failed, but I have no way of finding out why.

i think this is the last straw for using segment functions. 
Here are segment function failures for the last 2 weeks:
<img width="428" alt="Screen Shot 2020-12-15 at 12 09 01 PM" src="https://user-images.githubusercontent.com/5514175/102267179-5b3f6b00-3ece-11eb-80af-cd34c3a222d9.png">

That makes the success rate 99.4%. That's TERRIBLE.

I think the segment functions experiment was successful. We've determined is sucks. I'll integrate the hubspot integration directly into the app & include error logging so if this happens again, we can figure out why.
