### ISSUE TITLE
Reactji count style mismatch fixed in Chrome

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4427]
## Issue - Bug

Emoji on reflection card needs some style refinement:

![](https://user-images.githubusercontent.com/1879975/101699974-18dedf80-3a31-11eb-8379-ab2bb3b22de9.png)

Chrome Version 87.0.4280.88 (Official Build) (x86\_64) on macOS 11.0.1 (20B50). Cannot reproduce it in Safari or Firefox though.

### Acceptance Criteria (optional)

Users can:

*  see Reactji nice and beautiful

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
@tianrunhe I’ve noticed this before. My old Apple display is not Retina and the count is close to the emoji. However, on the laptop’s hi-def display it looks good (same browser version). It seems on certain displays the emoji gets rendered larger than on others. I think the goal would be to normalize the emoji size but that’s probably hard to do, probably something related to font rendering and pixel density of displays. For such a small set of controls if we move the count too far away to account for larger rendering it may be confusing which emoji the number quantifies. Here I overlayed a screenshot from both displays. Notice the card and comment emoji count:

![Screen Shot 2020-12-10 at 10 12 10](https://user-images.githubusercontent.com/307286/101797965-30b97080-3ad0-11eb-8d72-5617a0000fe2.png)

The count also looks good on my Android phone. So I’ve had low tension on it. Maybe we just bump the count a pixel or 2 but then it looks too spaced in other displays 🤷

**Comment by mattkrick** [comment]
this can be achieved by explicitly setting the css width: e.g. `width: 24`

**Comment by ackernaut** [comment]
We still have the problem of fixing it for some displays making it wonky for others:

#### Setting 24px width
Note: the text alignment is left by default, the count looks closer to the emoji to the right than to the left
<img width="340" alt="Screen Shot 2020-12-15 at 11 44 32" src="https://user-images.githubusercontent.com/307286/102251979-1cf47c80-3ecb-11eb-8dd5-4c5f3a477c5a.png">

#### Setting 24px, removing padding on count
Better, but still kinda close to the wrong emoji
<img width="333" alt="Screen Shot 2020-12-15 at 11 44 53" src="https://user-images.githubusercontent.com/307286/102252082-401f2c00-3ecb-11eb-8d88-08009c4979b8.png">

#### Setting 24px, removing padding on count, setting text-align: center on the emoji block
<img width="350" alt="Screen Shot 2020-12-15 at 11 45 03" src="https://user-images.githubusercontent.com/307286/102252151-5a590a00-3ecb-11eb-8cf2-7087f5da9e34.png">

**Comment by ackernaut** [comment]
Updated ⬆️  — see the diff between 2 displays when changing properties.
>We still have the problem of fixing it for some displays making it wonky for others:

**Comment by ackernaut** [comment]
I’ll take a 2nd pass at getting this dialed in…

**Comment by ackernaut** [comment]
The emoji render bigger on lo-def displays. I think we lean toward how it renders on hi-def displays since this should be the majority. If we space the count farther away from the emoji, it’s too spaced out for the hi-def displays. A compromise moves it a little further and adds a little more space before emoji-count blocks. It’s really tight for older displays but looks good on newer displays. Shots (same browser, same computer, different displays) after some refinement:

Macbook Pro display
<img width="1366" alt="Screen Shot 2020-12-16 at 15 43 08" src="https://user-images.githubusercontent.com/307286/102410892-ce241100-3fb6-11eb-8c91-1926c425587e.png">

Old Apple display
![Screen Shot 2020-12-16 at 15 43 05](https://user-images.githubusercontent.com/307286/102410887-ccf2e400-3fb6-11eb-9b3a-d224f342f04f.png)
