### ISSUE TITLE
Spruce up credit card modal

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4460]
To improve readability and reduce the chance that a user incorrectly enters their card number, we should add a space after every 4th number, so `4242424242424242` becomes `4242 4242 4242 4242`.

We could also add padding above the Upgrade button and consider using [Stripe Elements](https://stripe.com/docs/stripe-js) so that there's only one input for the card number, expiry date & CVC rather than 3.  

![upgrade-to-pro](https://user-images.githubusercontent.com/39854876/102505537-06405800-407a-11eb-9d34-22ebf2c4750d.png)

**Comment by mattkrick** [comment]
this feels like a good item to tackle when we do a pricing update:
- add in option to pay annually
- add in option to pay via ACH
- add some spaces between every 4 CC numbers

**Comment by jordanh** [comment]
Scrubbed. Iceboxing

**Comment by nickoferrall** [comment]
Our credit card conversion rate seems really low: https://analytics.amplitude.com/parabol/chart/7mexl8a

Sprucing it up might help a bit. I suggest that we use Stripe Elements in our modal. As you can see in their example [here](https://stripe.com/docs/payments/payment-element), we could build something like this:
![stripe-elements](https://user-images.githubusercontent.com/39854876/193289012-87bdf127-7e57-438a-b1cb-2418afa8b733.png)

To keep it in line with our current functionality, from the example above, we could:

- Remove the card options
- Remove the country & postal code (although these help increase card acceptance rate, I don't believe that's an issue for us atm)
- Include Parabol's price count & button from our current modal

The benefits of doing this are:

- Stripe elements look better, in my opinion, as they show what the CVC is and what cards we accept
- Having a space separating every 4th character in the card number makes it easier to read & use
- You can find Stripe elements across many popular apps. Having a familiar checkout experience might give users a sense of security

**Comment by igorlesnenko** [comment]
I found that is is not very easy to use Stripe Elements in our case.

There are [2 possible ways](https://github.com/stripe-samples/accept-a-payment#accept-a-payment) to use stripe elements:

**Payment Element**

A single element that embeds a fancy payment form using iframe. The one that is shown on the [screenshot](https://github.com/ParabolInc/parabol/issues/4460#issuecomment-1263642257) above

It handles a lot of things automatically.

However, it is not just a set of inputs that we can use instead of our inputs. It requires complete refactoring and some backend work too, as it uses `PaymentIntents` that we currently don't use.

**Custom payment flow**

It is possible to use separate input elements. They also works using iframe. 

However, there is no any styling provided unlike for the solution above. We need to manually write all the CSS.

By default it looks like this:

<img width="336" alt="Upgrade to Pro" src="https://user-images.githubusercontent.com/466991/196188205-05aea255-afd4-4662-87ed-6088dbbfb488.png">

---

Based on this I think it is easier to add some CSS and credit card input formatting to our elements to made it look fancier and similar to stripe form

@nickoferrall what do you think?

**Comment by igorlesnenko** [comment]
@nickoferrall make sense, will add a formatting only

**Comment by BartoszJarocki** [comment]
At some point we should migrate to Stripe Elements one way or another due to legal issues. More info here: https://stripe.com/docs/security/guide#validating-pci-compliance 

```
We strongly discourage passing card information directly to Stripe’s API as it means your integration is directly handling card information. Even if you don’t store any payment information, we can only help simplify PCI compliance if you’ve integrated with [Checkout](https://stripe.com/docs/payments/checkout), [Elements](https://stripe.com/docs/payments/elements), or our [mobile SDKs](https://stripe.com/docs/payments/accept-a-payment).

If you continue to send card details directly to our API, you’ll be required to upload your [SAQ D](https://www.pcisecuritystandards.org/documents/PCI-DSS-v3_2_1-SAQ-D_Merchant.pdf) annually to prove your business is PCI compliant. SAQ D is the most onerous of all the SAQs, with over 40 pages of requirements you must implement to remain PCI compliant. We highly recommend you migrate to [client-side tokenization](https://stripe.com/docs/payments/elements) of card information to substantially reduce the scope of your PCI compliance.

In addition to the significant PCI burden that this method places on you, it isn’t supported by [Radar](https://stripe.com/docs/radar), our fraud prevention toolset. Radar’s functionality (for example, [risk evaluation](https://stripe.com/docs/radar/risk-evaluation), [rules](https://stripe.com/docs/radar/rules), and so on) is only available when using any of our methods of client-side tokenization.
```

It should be too hard to style a Card Element properly, too.
