### ISSUE TITLE
Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4482]
https://sentry.io/organizations/parabol/issues/1132332682/?referrer=github_plugin

```
Error: NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```

**Comment by jordanh** [comment]
## AC
- [ ] Triage
- [ ] Open new issue with root cause or fix

### EE: 6 hours

**Comment by jordanh** [comment]
Watermark: 85 users affected

**Comment by BartoszJarocki** [comment]
@jordanh @mattkrick We might want to investigate it, it happened [27 times last week](https://sentry.io/organizations/parabol/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A+NotFoundError%3A+Failed+to+execute+%27removeChild%27+on+%27Node%27%3A+The+node+to+be+removed+is+not+a+child+o...&project=107196&query=issue.id%3A1132332682&sort=-timestamp&statsPeriod=7d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1).

**Comment by mattkrick** [comment]
if it's fatal, absolutely! probably from removing a portal like a dragged reflection card

**Comment by Dschoordsch** [comment]
Sentry issue: [ACTION-PRODUCTION-3SN](https://sentry.io/organizations/parabol/issues/1639679203/?referrer=github_plugin)

**Comment by jordanh** [comment]
Keeping open as it still happens regularly

**Comment by jchandler-parabol** [comment]
This error is [reported daily](https://parabol.slack.com/archives/C20KZHH50/p1652254424616209) by Sentry in the #t_product_devops channel. There are 355 instances of it to date. This is an excessive amount of noise that could prevent us noticing when real issues arise. 

Sentry's Details about the exception.
https://sentry.io/organizations/parabol/issues/1132332682/?project=107196&referrer=slack



![Image](https://user-images.githubusercontent.com/99220260/167861777-dc424bef-7014-4e6c-b781-41cd76f06b49.png)



![Image](https://user-images.githubusercontent.com/99220260/167861934-ed8b637e-cb7f-464b-bb6a-48c95107a2f1.png)

**Comment by jordanh** [comment]
Watermark

EVENTS
[2.7k](https://sentry.io/organizations/parabol/issues/1132332682/events/?project=107196&referrer=github_plugin)
USERS
[160](https://sentry.io/organizations/parabol/issues/1132332682/tags/user/?project=107196&referrer=github_plugin)

**Comment by jordanh** [comment]
Bumping priority given the number of times this bug is occurring

**Comment by jordanh** [comment]
Watermark

3.3k events
145 users

**Comment by jordanh** [comment]
Assigning this to a squad in the hopes we can triage it

**Comment by BartoszJarocki** [comment]
The root cause of this issue is using Google Translate and possibly other translation tools either to translate the whole page or the content of the editor (ie. our comment editor, task editor etc). There's an open bug report in Chromium for that: https://bugs.chromium.org/p/chromium/issues/detail?id=872770

Here's what I did to find what's causing it:

1. I went through the issue occurrence list on Sentry [here 🔒](https://parabol.sentry.io/issues/1132332682/events/?project=107196); I mapped user ids from Sentry to some session replies from DataDog and watched a bunch of them.
2. After trying to reproduce some scenarios I've found and failing, I noticed that vast majority of users have their parabol app translated to other language
3. I used Google Translate to translate parabol app to polish, started typing various things and 💥 
![Image](https://github.com/ParabolInc/parabol/assets/1017620/ad602aac-f251-418c-8e0c-208a58648fba)
4. I googled it and [here's the comment from React core team member about it.](https://github.com/facebook/react/issues/11538#issuecomment-417504600 ); technically there are also some workarounds for draft js mentioned here: https://github.com/facebookarchive/draft-js/issues/1320 but I'm not sure if it's worth experimenting with.

**Comment by BartoszJarocki** [comment]
Unfortunately, it's affecting not only draft-js but also normal inputs, for example sometimes it happens during the login (typing email and pass). In our case is mostly visible within draft-js editor as it's used for reflections, comments and tasks ie. where our users spend most of the time

**Comment by mattkrick** [comment]
Could we do something like ` window.addEventListener('error', (e) => popToast('Google translate borked you'))`? It doesn't fix the error, but it removes the blame from us 😄

**Comment by BartoszJarocki** [comment]
This is actually a good idea! How about handling that in our [`ErrorComponent`](https://github.com/ParabolInc/parabol/blob/de71277fb633f37b866dae4a4f8664a3ff16f187/packages/client/components/ErrorComponent/ErrorComponent.tsx#L31) and showing a proper description?

**Comment by BartoszJarocki** [comment]
actually, the error is already handled by our error boundary, it'd be only a matter of checking the error and showing a proper message

**Comment by BartoszJarocki** [comment]
@mattkrick what about that?

![Image](https://github.com/ParabolInc/parabol/assets/1017620/218420c5-7b10-4842-915d-aaed32c7c376)

**Comment by mattkrick** [comment]
that's awesome! The only change I'd offer is to make it clear that it's Google's fault & there's nothing we can do to fix it. e.g. Oh no! Seems like you're using Google Translate or a similar extension, which has a bug in it that can crash apps like ours. If this continues, please disable the extension"
