### ISSUE TITLE
Error: invariant(...): Second argument must be a string

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4559]
Bug in the latest release in the Group phase

https://sentry.io/organizations/parabol/issues/2153463849/?referrer=github_plugin

```
Error: invariant(...): Second argument must be a string.
  at createProxyRecord (./packages/client/utils/relay/createProxyRecord.ts:28:27)
  at apply (./packages/client/mutations/EndDraggingReflectionMutation.ts:185:32)
  at Set.forEach (<anonymous>)
  at updateIsEditing (./packages/client/components/ReflectionCard/ReflectionCard.tsx:72:5)
  at c (./packages/client/components/ReflectionCard/ReflectionCard.tsx:83:18)
...
(45 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
this is because fbjs/lib/invariant.js has a process.env.NODE_ENV variable which != 'production'.
that tells me webpack DefinePlugin is not touching that file.



routes to take:
- do we need to include node_modules in the webpack config module.rules?
- or maybe we just need to fix resolve.modules because we don't actually need to babelify anything?
- i'm not sure how to make DefinePlugin touch node modules, need to see webpack docs

**Comment by nickoferrall** [comment]
FYI @mattkrick the webpack bundler analyzer suggests that there's only 1 `clientTempId` in the bundle. Still, hopefully the new unique id resolves this issue. 

The Sentry error hasn't yet been triggered in the latest release so that's promising.

![webpack-bundler-analyzer](https://user-images.githubusercontent.com/39854876/105368920-64f87480-5bd8-11eb-989d-f710878f52ea.png)

**Comment by mattkrick** [comment]
that looks strange, it's showing both server & client artifacts. that's being run for the prod.client config?

**Comment by nickoferrall** [comment]
I was using the analyzer in the toolbox config. Here's the screenshot from the client config - the `clientTempId` is appearing twice!

![client-webpack](https://user-images.githubusercontent.com/39854876/105760693-8cc54080-5f28-11eb-9741-abb20ea48481.png)

**Comment by mattkrick** [comment]
:partying_face: mystery solved!
