### ISSUE TITLE
Sign-up directly on homepage or other website pages 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#4567]
## Issue - Enhancement

Today, when they sign-up, users need to leave our website and get into the app - a sharp change in context, and an additional click. 

To reduce friction, we could include the sign-up directly in the homepage. As an example: 
![Screen Shot 2021-01-21 at 10 23 19 AM](https://user-images.githubusercontent.com/11621016/105381242-6b84ed00-5bd4-11eb-8231-a6d3c86c907d.png)

The email field is a module that's included in different pages, integrated directly into the content. 

### Acceptance Criteria (optional)
Users can:
   - Start the sign-up process before leaving our website 

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
Discussed during scrub. In order to execute, we need a page design(s) first showing how this would embed.

Backend implementation would be done as a raw HTML component (and therefore able to be embedded in Hubspot or Wordpress).

Component would:
   - [ ] Allow for signup via Google or collect email address (no password)
   - [ ] Generate a POST request to hit our existing GraphQL endpoint
   - [ ] Trigger a validation email to verify signup and—if signed up by email—set password

Doing this we expect to:
   * See a bit less drop off on our create-account page
   * Be able to retarget folks more easily

Note for @avivapinchas: this would probably make a great batting practice for a growth developer

**Comment by jordanh** [comment]
@avivapinchas: if you think this would be a good BP, too, please re-open and label with `Batting Practice`

**Comment by avivapinchas** [comment]
This would make a good batting practice!

**Comment by jordanh** [comment]
Going to keep this open as a growth developer BP

**Comment by jordanh** [comment]
Removing from our backlog
