### ISSUE TITLE
Active User count not updating in Hubspot

### ISSUE THREAD

**Issue by shawneeatparabol** [ParabolInc/parabol#4578]
## Active User count not updating on deals in Hubspot

Aviva made a great video explaining the issue🔐 [listed in the notes on a ticket here](https://app.hubspot.com/contacts/3888472/ticket/288978956/)

The active user count on deals has not automatically updated in over 30 days, causing deals to be marked as a score 0 

This is affecting Deal Score and sales' ability to effectively qualify and prioritize deals. It's being reported on at least 95% of our current pipeline.

**Comment by avivapinchas** [comment]
To add some more context here: 
- Deal Scores are updated by copying the associated Company's Lead Score property to the Deal
- Company Lead Scores depend on a number of factors, including the Company's Active User Count field being updated less than 30 days ago. We included this requirement so that we're only targeting companies that have been recently active. 
- AFAIK, Active User Count should update whenever users within a company complete a meeting. <- Is this accurate? 

For the majority of the companies associated with Deals, their Active User Count fields have not updated in 30+ days, looks like the last update for many was around mid December. Perhaps something changed there? 

Here's an example company: 
- [Company](https://app.hubspot.com/contacts/3888472/company/2291923088) 🔒 has ~125 active users, last updated on Dec. 18, 2020 
- [Users with an email address containing that company's domain have met ~8 times in January ](https://analytics.amplitude.com/parabol/chart/t0hmp54?source=redirect%3A+chart+saved) 🔒 

A possibly related issue for the `lastmet` field: #4581

**Comment by jordanh** [comment]
Prioritizing this to the top of the backlog
