### ISSUE TITLE
Poker: enhance story description to show rich media

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#4674]
## Issue - Enhancement

[A user](https://app.hubspot.com/contacts/3888472/contact/2531) writes 🔒 :
> images in the Jira issue description are displaying as broken placeholders. Not the end of the world but if it's possible to display them that would add luxury.

Opening as discussion to resolve to an issue with firm next steps.

**Comment by jordanh** [comment]
Before allowing folks to edit stories, I think it would be good to show rich media. I assume this would mean moving to something like Prosemirror first within this component. Right, @mattkrick ?

What do you think?

**Comment by mattkrick** [comment]
today, we ask jira for HTML & dangerously render that in the story.
if it's not showing images, i'm guessing it's because jira requires authentication to access user uploaded content. at least that was the case with avatars.
assuming the above is the culprit, we'll just need to request the HTML from jira, pluck out the image requests, request them using the access token & then patch them into the HTML as inline base64.

**Comment by mattkrick** [comment]
fixed in #5190
