### ISSUE TITLE
Sprint Poker: GitHub: Scope: Create new issue

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#4715]
AC
- [ ] Just like jira, a FAB exists. when clicked, it allows you to create a new issue & you can select the github repo for that issue

Estimate: 16 hours

**Comment by nickoferrall** [comment]
Hey @mattkrick, it looks like there's no ScopePhaseArea for GitHub so I'll create an empty `ScopePhaseAreaGitHub` component with a FAB unless there's an existing branch with that UI?

**Comment by mattkrick** [comment]
@nickoferrall in PR at #4777

**Comment by nickoferrall** [comment]
Hey @mattkrick, the existing [createGitHubIssue mutation](https://github.com/ParabolInc/parabol/blob/1cab023452901d164045bc38905a211b413fcfd7/packages/server/graphql/mutations/createGitHubIssue.ts#L22) uses a `taskId` to link the GH issue to the Parabol task. The rich text editor in the task also means we can add markdown to the body of the GH issue.

In our 1-1 I think we mentioned that I'd use the existing mutation but I'm now thinking it'd be best to create a new mutation, e.g. `createGitHubIssuePoker`, as it wouldn't be linked to a Parabol task. `nameWithOwner` and a `content` string would be the args. A GH issue title but no body would be created and it'd look like this (prob "New issue title" instead of "summary"):

<img width="654" alt="new-gh-issue" src="https://user-images.githubusercontent.com/39854876/111693396-910e2b80-87fe-11eb-9b8b-8b0cf2ca8e58.png">

Alternatively, I could use DraftJS and increase the height of the new issue to provide space for a body but it wouldn't be consistent with the other integrations and might not look so pretty. Still, I think it'd make sense to create a new mutation.

What do you think?

**Comment by mattkrick** [comment]
Correct me if I'm wrong, I think this is the same case as how jira is today?

- https://github.com/ParabolInc/parabol/blob/d5633f04cd1c8761232da7c132d5e63e7968efa9/packages/client/mutations/CreateJiraTaskIntegrationMutation.ts#L0-L1
- https://github.com/ParabolInc/parabol/blob/d5633f04cd1c8761232da7c132d5e63e7968efa9/packages/client/mutations/JiraCreateIssueMutation.ts#L39

one mutation is to create a new task & the other is to push an existing task to jira.
i think we could use the same strategy for github, but i'd also be open to architectural changes. for example:
- always create a parabol task? pros/cons?
- combine the mutations so they take either content or a taskId?
- ???

**Comment by nickoferrall** [comment]
OK great, I think using the same Jira strategy makes sense, i.e. a second mutation. 
When creating a new GH issue, we're not creating a Parabol task so I think that logic could be confusing. Combining mutations would save code but there'd be a bunch of conditionals which would increase the chance of bugs. 

I'll push ahead with the second mutation 👍
