### ISSUE TITLE
Bug: Selecting Jira issue fast enough will cause item missing

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#4719]
## Issue - Bug

Repro:
1. Start a poker meeting
2. In Scope phase, wait for Jira issues load
3. Quickly select two issues
4. Observe that both of the issues appear on the navigation column, but then the first one is removed

If you select issues slowly, it does not seem to have this issue.

![2021-02-25 16 46 30](https://user-images.githubusercontent.com/1879975/109238884-292d6d80-7789-11eb-893c-2b34d7360e3d.gif)

- **Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

### Acceptance Criteria (optional)
Users can:
   - [ ] Pick Jira issues from the list and see them show up on nav

**Comment by mattkrick** [comment]
The problem is here: https://github.com/ParabolInc/parabol/blob/78219edd7c4e46b9ce0b407f89caa0cbcf23ce48/packages/server/graphql/mutations/updatePokerScope.ts#L136

because for the 2nd checkbox mutation, `phases` is fetched before it is updated from the 1st checkbox mutation.
The solution is to do nested update that looks something like https://github.com/ParabolInc/parabol/blob/7a5171db532a5e9652b00914ef609dd655de4cd4/packages/server/graphql/mutations/joinMeeting.ts#L93-L96
