### ISSUE TITLE
TypeError: Cannot destructure property 'picture' of 't' as it is undefined.

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4735]
- A user started a Sprint Poker meeting
- When trying to join, other users see an issue

https://sentry.io/organizations/parabol/issues/2250142372/?referrer=github_plugin

```
TypeError: Cannot destructure property 'picture' of 't' as it is undefined.
  at None (./packages/client/components/MeetingSidebarTeamMemberStageItems.tsx:59:18)
  at Array.map (<anonymous>)
  at c (./packages/client/components/MeetingSidebarTeamMemberStageItems.tsx:50:29)
  at Set.forEach (<anonymous>)
...
(32 additional frame(s) were not displayed)
```

**Comment by tianrunhe** [comment]
Couldn't root cause it yet. Added [more info](https://github.com/ParabolInc/parabol/commit/74b81be2549d17ff3aa99b0a9d2373d91f8c0d98) in the Sentry error message to assist us in further investigation.

**Comment by jordanh** [comment]
Watermark: still only 1 user affected

**Comment by tianrunhe** [comment]
Since I updated the error message with more logging, it no longer showed the original error message (TypeError: Cannot destructure property 'picture' of 't' as it is undefined) in Sentry. Instead here's the [new issue](https://sentry.io/organizations/parabol/issues/2356139311/?project=107196&query=is%3Aunresolved+Team+member+is+undefined.&statsPeriod=14d). Affecting 30 users in last 2 weeks.

**Comment by jordanh** [comment]
No further instances in Sentry, closing
