### ISSUE TITLE
TypeError: Cannot destructure property 'atlassian' of 'r' as it is undefined.

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4736]
When other users try to join a Sprint Poker meeting during the Scope phase from the Dashboard they see this error (reproduced 3+ times). It clears up on refresh and they see the button to Add Jira.

### Steps
- I start a SP and go to the Scope phase; probably picked some Jira items
- From the dashboard another user joins the meeting via snackbar or meeting menu
- The other user sees a broken main view but intact meeting chrome
- On refresh the other user sees the button to add Jira and the tab for Parabol tasks

https://sentry.io/organizations/parabol/issues/2250151920/?referrer=github_plugin

```
TypeError: Cannot destructure property 'atlassian' of 'r' as it is undefined.
  at c (./packages/client/components/ScopePhaseAreaJira.tsx:19:10)
...
(7 additional frame(s) were not displayed)
```

### Acceptance criteria
- Triaged and fixed or updated/created an issue

### Estimated effort
- 1 hour

**Comment by ackernaut** [comment]
I reproduced this again. It seems consistent.

**Comment by mattkrick** [comment]
do you have some extra detailed steps? i can't seem to reproduce

**Comment by ackernaut** [comment]
### Steps
- I start a SP and go to the Scope phase; probably picked some Jira items
- From the dashboard another user joins the meeting via snackbar or meeting menu
- The other user sees a broken main view but intact meeting chrome
- On refresh the other user sees the button to add Jira or tab over to Parabol

**Comment by tianrunhe** [comment]
I found this particular weird in that user `local|1EY48WGsdq ` is in the same team with user `google-oauth2|104933228229706489335` but the former does not have an entry in the `AtlassianAuth` table (the former has). I think there might be some glitches when the integration was enabled? @ackernaut if you start with two fresh new accounts and enable the integration, can you still reproduce it?

**Comment by tianrunhe** [comment]
I think I fixed this by band-aiding `integrations?.atlassian?` as Matt suggested, in [this commit](https://github.com/ParabolInc/parabol/commit/f5342386d4af6db0c5e5fa6de17ee7552551e9a4). Please verify!

**Comment by tianrunhe** [comment]
Sentry issue: [ACTION-PRODUCTION-57K](https://sentry.io/organizations/parabol/issues/2221335986/?referrer=github_plugin)

**Comment by tianrunhe** [comment]
Sentry issue: [ACTION-PRODUCTION-578](https://sentry.io/organizations/parabol/issues/2212737127/?referrer=github_plugin)

**Comment by ackernaut** [comment]
@tianrunhe I’m still able to reproduce the error even after the band-aid. I realized this bug is already in productions, not a regression, so it won’t block shipping v6.2.0.

**Comment by mattkrick** [comment]
@ackernaut

**Comment by ackernaut** [comment]
Hello, I was still able to reproduce this, and I also confirmed that it was already on production. So I didn’t block ship with it. See the comment above

**Comment by ackernaut** [comment]
@mattkrick I was having trouble with Redis, again, locally so I’d have to sort that out again, first.

**Comment by ackernaut** [comment]
@mattkrick okay, up and running locally, and I was able to reproduce the error

**Comment by tianrunhe** [comment]
@mattkrick I think it is that I put the band-aid one line below the actual issue. I should have put conditional access on [this line](https://github.com/ParabolInc/parabol/blob/master/packages/client/components/ScopePhaseAreaAddJira.tsx#L47) rather than the one below coz the issue is the `integrations` are undefined to start with.

**Comment by mattkrick** [comment]
Here we go:
- This is caused by the optimistic updater
- It happens because the existing `TeamMember` object does _not_ have the field `integrations`
- We optimistically want an object like `{viewerMeetingMember: {teamMember: {integrations: {atlassian: null}}}}` but we don't get that because `TeamMember` doesn't have `integrations`
- In a perfect world, Relay should yell at us if, after the optimisticUpdater has run, the value not match what the server gives us
- This is done for `optimisticResponse`, so it should be possible

**Comment by tianrunhe** [comment]
@mattkrick Yes! I went as far as you to the third points and that's validating. I also noticed that it's a tricky bug because if the render happens a little bit slower when the mutation is finished already and the actual data returns, it would render fine. 

How do we wanna address it at this moment?

**Comment by mattkrick** [comment]
heh, isn't that a tricky one?  i made the server sleep for 500ms on every response to catch it in the act.

for now, i'm gonna write the optmisticUpdater to optimistically add the integrations record to the team member.

in the future, i'd like to validate the optimisticUpdater to make sure it's adding all the fields that the server is providing, but i'm not sure how yet.
