### ISSUE TITLE
Make task creation easier to find

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#4812]
## Issue - Enhancement

We are addressing #3901 by modifying the comment and task creation UI in the discussion thread. We identified that the confusion described in the issue comes from a need to improve the clarity of the controls.

This proposal involves moving the 'Add a task' button above the comment field, and adding a specific control to submit comments.

### Current vs. proposed solution

<img width="1233" alt="Screen Shot 2021-03-24 at 11 16 38 a m" src="https://user-images.githubusercontent.com/3276087/112354626-7d494600-8c92-11eb-87ec-cc2a51fdd6b2.png">

### Detailed views
<img width="1936" alt="new-add-task_2" src="https://user-images.githubusercontent.com/3276087/112358702-33625f00-8c96-11eb-824c-f36a465a066d.png">

[Please refer to the Figma file for a more detailed view of the design.](https://www.figma.com/file/Ia7SoJcudXUM3nvOYXOldR/comments-and-tasks?node-id=103%3A0)

### Acceptance Criteria
Users can:
   - Easily identify how to add a comment in the discussion thread.
   - Easily identify how to add a task in the discussion thread.
   - Easily distinguish the comment and task creation UI from the other.

**Estimated effort:** 
- 16 hours.

**Comment by ackernaut** [comment]
Thanks for drafting this enhancement issue @enriquesanchez . The only thing I would suggest is how specific to be about UI component criteria. Some issues need more definition, others less. It may be helpful to add something like:
- The ‘Add task’ control is always present and uses a flat button control. Like before it adds an auto-focused task to the thread. Note the hover state
- The ‘Send’ control is always present. It has a disabled state until there is text. Pressing enter will still submit. The enabled button has a hover state.
- The multiplayer typing feedback still shows immediately over the control space. The control space now has a greater height with the row that contains the flat add task control

**Comment by ackernaut** [comment]
Sometimes we’re using a known pattern that already has hover states, etc. so that information can be omitted. So the criteria may be as simple as ‘there’s a button that says ‘Add Meeting’ and tapping it takes a user to the New Meeting view’

**Comment by enriquesanchez** [comment]
Thanks @ackernaut, will make sure to be more specific going forward 👍

**Comment by ackernaut** [comment]
I wanted to leave a note here as I imagine this tying to other patterns that I’m wanting to explore regarding richer inputs and linking to other objects (like tasks etc.).

First, as we discussed, we may have more options for input like video, or referencing/unfurling an object from another integrated system.

As for the objects from integrated systems, how do we surface those quickly, share them, and talk about them? Can some things on the object be edited directly inline instead of read-only?

With that in mind, I imagine we”ll continue to iterate on these designs. (Background: I like to time box design efforts. I get through a few cycles, find something I want to propose, and write an issue for it. I see issues as proposals. Typically once we get closer to building we may go 100% as is, have more questions and do a little more iteration, or if it’s been on the backlog for a bit we may have new thinking and therefore go back to more questions and iteration. I could see that happening here.)

In the short term I think this is a good solution in the right direction, here’s why:
- Today we tap a control to add and edit a task inline. In skips the middle man of using a rich editor before publishing.
- I like the placement of this solution because it’s close to where the task card will be added.
- In the future I could see referenced objects or rich content being added at the top of a comment field, with the ability to comment below. We see this in many messaging apps or chat, you add a picture or reference a link and it gets added above or below the active comment field, and you may have some control over the appearance of that comment. ‘Add a task’ above the comment could move to an append pattern someday TBD.
- In the future I can imagine a bar of icons for the types of things that can be added. Maybe it’s below the comment field. Either way it will end up increasing the height similar to the footprint of this design. If we move the task control down to the icon bar folks will notice it’s missing but also notice new things were added and probably have few problems connecting the dots ‘ah it moved down here and there are new things’
- We use the plus ‘add’ icon in other places, like adding tasks on the kanban, or adding agenda items, so I like the continuity here
- I like that although there was a push for clarity and usability, you found a way to use a minimal aesthetic that matches the rest of the product and has a light footprint. The flat control has good placement.
- I admit the centered layout is nuanced, but it makes me think of a Trello column. It feels the horizontal space where that the card will take up. Before threads, we had a control that was the footprint of a card (roughly 1-2 lines tall) that simply said Add a task centered vertically and horizontally on the control. It works as a pattern.

Some things to address in the future:

- How do tasks appear in the thread? Today they are elevated cards. We probably need an inset styling that can be shared with other referenced and shared objects
- How can we surface things inline? Search and discover? Keyboard slash commands?
- How can we teach folks the editing options without it being in the way or some tips icon always in view? Once you learn it, it’s just noise after that

**Comment by ackernaut** [comment]
We’re going to check in with Enrique about making another iteration on the target version that supports multiple content types and/or input types.

**Comment by jordanh** [comment]
Closed by #4899 

@enriquesanchez please let me know if this needs to be reopened for any reason
