### ISSUE TITLE
Reduce Docker image size by using a multi-stage build

### ISSUE THREAD

**Issue by blimmer** [ParabolInc/parabol#4827]
## Issue - Enhancement

The current Docker image produced by `docker/Dockerfile.prod` is quite large. As of today, the resulting image was 3.59gb in size. By reducing the image size, users will be able to scale out more quickly and ultimately reduce their resource requirements to save money on cloud deployments.

I did a little experiment this afternoon to see how much space `devDependencies` were taking up and it looks like removing `devDependencies` alone gets the image down to 2.41gb (an ~33% decrease in size). For this hacky test, I applied this diff to `docker/Dockerfile.prod`. This isn't a good solution long-term but is good for demonstrating some of the opportunities we have by optimizing the Dockerfile from its current state.

```diff
diff --git a/docker/Dockerfile.prod b/docker/Dockerfile.prod
index a76e99856..b8d50a98a 100644
--- a/docker/Dockerfile.prod
+++ b/docker/Dockerfile.prod
@@ -10,8 +10,10 @@ ADD yarn.lock .
 COPY . .

 FROM base as prod
-RUN yarn install
-RUN yarn build
+RUN yarn install --cache-folder /tmp/.yarn-cache && \
+    yarn build && \
+    rm -fr node_modules /tmp/.yarn-cache
+RUN yarn install --cache-folder /tmp/.yarn-cache --prod && rm -fr /tmp/.yarn-cache
 RUN cp docker/entrypoint.prod.sh /bin/entrypoint
 RUN chmod +x /bin/entrypoint
 EXPOSE 80
```

It looks like there are a few `devDependencies` that're actually required at runtime (I was getting some errors when starting up the server), so we'll need to look into those.

After taking a look at the Dockerfile, there are a few opportunities I saw that could reduce the final size of the image.

### Implement a multi-stage build

Today, you do have two stages in your Dockerfile (`base` and `prod`), but the `yarn install` and `yarn build` is happening in your `prod` layer, instead of the `base` layer. To more effectively utilize a multi-stage build, we could hoist the installation of `devDependencies` and the `yarn build` up to the `base` layer. Then, in the `prod` layer, install only prod NPM dependencies and copy the built code from the `base` layer.

Here's a more concrete example of what this would look like:

```dockerfile
FROM node:14.10.0 as base
COPY . .
RUN yarn install --cache-folder /tmp/.yarn-cache && \
	yarn build && \
	rm -fr /tmp/.yarn-cache

FROM node:14.10.0
WORKDIR /parabol/

# Copy all files from the base image. This is all the `js` files transpiled from TS in the `yarn build` step.
# And any other supporting files needed (e.g., `package.json` & `yarn.lock`)
COPY --from=base <YOUR BUILT FILES> ./

# Only install prod dependencies
RUN yarn install --prod --cache-folder /tmp/.yarn-cache && \
	rm -fr /tmp/.yarn-cache

RUN cp docker/entrypoint.prod.sh /bin/entrypoint
RUN chmod +x /bin/entrypoint
EXPOSE 80
ENTRYPOINT [ "entrypoint" ]
CMD ["yarn", "start"]
```

There are more information and examples on this approach [here](https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/docker/multi_stage_builds.md).

### Consider another node image variant for your `prod` stage

Another benefit of running your build in a separate stage is that you may be able to use `alpine`, or another smaller [variant](https://github.com/nodejs/docker-node#image-variants) of the `node` image to further reduce the size of the image.

### Review `.dockerignore`

You'll get the most bang for your buck from the step above, but you can also reduce the final image size by reviewing your `.dockerignore` file. It looks like some files intended for humans (like `SECURITY.md`) and dev (`devTemplate.html`) are included in the final production image. Ignoring the `docs` folder will free up 19mb alone.

### Acceptance Criteria (optional)

The resulting docker image is:

- Significantly smaller than the current size (3.59gb)
- The application still runs properly

- **Estimated effort:** 11 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by jordanh** [comment]
❤️ 

Love this

cc @adaniels-parabol

**Comment by adaniels-parabol** [comment]
Adding some notes from slack:

- Over on the PPMI instances, the size of the image is 402.67MB. The image on our public saas hasn't been optimized.
- Would like to do more. For instance, we still need node_modules shipped with the build due to some filesystem level access by the app. Ideally webpack would be able to get everything packed down but we use nodeExternals and ignore parabol-client and parabol-server.
- If we could figure out those issues to get away from nodeExternals and truly have no binary dependency on node_modules and then couple that with getters for all env vars we could build once and use everywhere.
- I'd love for us to just be able to ship the code without node_modules, then we'd have a infra container build that only updates and could be broken away from the application completely.
- If you have any ideas on how to get away from node-externals, that would be awesome. Would make shipping way easier as we could ship the same build from master, to staging, to prod (if we also get build vars pulled in with a getter) MAGIC!
