### ISSUE TITLE
helping users who changed their email domains get rid of duplicate accounts

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#4860]
A [user ](https://app.hubspot.com/contacts/3888472/contact/25290201) 🔒  writes:

> Our company changed all emails domain from @ XXX to @ XXY. Most of us signed up to Parabol with Google. Because of how Parabol integrates with Google Sign In, now we are unable to login back to our original account. Trying to do so, we ended up with new accounts with @ XXY.
> 
> Fortunately, someone was still logged in original account and invited the rest of us to join again the organization. But it only duplicated everyone and we also lost some history.
> 
> We tried some things to fix it for the past few months but every time there is a new difficulty on the way. We are very unsatisfied and starting to lose hope in this.
> 
> Long story short, everything is a mess now. Could you help us to restore our original accounts and change them to use the new email address? Also, could you help us reorganize all those duplicated organizations?  

Hubspot ticket: https://app.hubspot.com/contacts/3888472/ticket/363691039/

**Comment by jordanh** [comment]
@ackernaut I added this to the Triage board. Please triage and communicate back with Mr. Housman

**Comment by ackernaut** [comment]
I had a few ideas here, most of them sound pretty bad:
- We write an issue to create a mutation that merges users and orgs and places them under the new domain. The users will probably have to validate via email to gain access again. They would have to validate the list (here are the old email addresses, here are the new) and the mutation would handle verifying matches
- We write an issue to explore what our options may be for detecting domain changes in existing users who are trying to sign in and somehow asking them to validate so that they don’t lose their prior data and membership
- We come up with a response for folks where this happens with our rationale for why or why not we can/will help and a timeline. Part of this may outline levels of support per tier (Free, Pro, Enterprise)

**Comment by ackernaut** [comment]
A few more details here [if I find good links I’ll add them]. There’s discussion of:
- having an improved pattern for how to identify a user that’s less dependent on their email or mode of authentication (e.g. via Google)
- a mutation for merging domains
- how we communicate with folks who can’t seem to get in

**Comment by ackernaut** [comment]
As for this ticket, customer success will tell them that we have work on our backlog to address the issue (but it may be a minute)

**Comment by mattkrick** [comment]
Problem case: someone is logged out when the email address is changed. That person logs in via Google OAuth.

The "right" way to do it:
- [ ] we hold on to their google ID & when they log in, we lookup that user via google ID. if their email address changed, then we update the email.
- [ ] for user/password users, The User Profile has a list of emails & they can add/remove. To add, they must verify their email.
- [ ] for SSO, we use SCIM?

The above isn't cheap & it feels bad to spend much time to build this out, but I'm afraid doing something half baked will have consequences.
