### ISSUE TITLE
Pen-and-ink created for scheduling a meeting phase reminder

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#4914]
Following the comments from #4820 

Let’s design a way that folks can schedule a reminder for adding reflections. The user story may sound something like this:

>When I’m setting up our next retro and I want folks to add comments in advance of the meeting, I want to schedule a reminder that notifies the team on Slack some time before our sync time (e.g. 1 hr before? 1 day before?) so that they can tap through and add comments in a timely but relaxed manner.

Today, if a team has Parabol connected to Slack, a lead may start a meeting ahead of time. The team will get a notification that the meeting has been started. Then if they set a time box for the Reflect phase, the team will get another notificaiton within a short window of the first. Two weeks go by and those notifs are water under the bridge. The link is lost. Folks have probably forgotten that a meeting was started.

In the future, what if a team lead could open the board but then schedule a notif to ping the team later? Maybe they want it to be a day or 2, or an hour or 2, before their sync time?

**Questions**: do we will still notify the team right away of the time box (like today’s behavior)? Do we make that optional inline (of the menu, not team settings) since the team was just notified of the meeting? To be fair, leads can dial in these settings today. What does the menu look like if they can add a notification? What if they could add many scheduled notifications, like adding alarms on your phone?

![Screen Shot 2021-04-26 at 17 29 36](https://user-images.githubusercontent.com/307286/116159353-b02d9200-a6b5-11eb-8b7f-ef57b89b9aa6.png)

Above: _Folks can opt in to different notifications under team settings_

![Screen Shot 2021-04-26 at 17 35 17](https://user-images.githubusercontent.com/307286/116159464-e8cd6b80-a6b5-11eb-9171-a38a317cb0d6.png)

Above: _Today folks can optionally notify Slack inline_

![Screen Shot 2021-04-26 at 17 36 07](https://user-images.githubusercontent.com/307286/116159465-e8cd6b80-a6b5-11eb-92eb-58068ec672b4.png)

Above: _A meeting will be broadcast twice in short notice if a lead opens a meeting and immediately sets up a time box_

### Acceptance criteria
- Sketched an end-to-end experience of scheduling a meeting reminder prompting folks to add reflections that could inform static concepts or a clickable prototype both of which could be shared for comments inside and outside our team
- Next-step issue written e.g. created a clickable prototype of scheduling a meeting phase reminder

### Estimated effort
- 8 hours

**Comment by enriquesanchez** [comment]
>Sketched an end-to-end experience of scheduling a meeting reminder prompting folks to add reflections that could inform static concepts or a clickable prototype both of which could be shared for comments inside and outside our team

I've been mocking up a few ideas [on this Figma file](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?node-id=0%3A1). 

I think we can add this functionality to the "Timer" menu in the meeting control bar. In order to do this we'd need to make the little modal a bit bigger and add a couple extra controls.

<img width="407" alt="Screen Shot 2021-05-05 at 5 24 06 p m" src="https://user-images.githubusercontent.com/3276087/117217271-ba8f1080-adc6-11eb-8a04-70dcd6653877.png">

### Here's what's happening in the mockup above:
#### New date and time picker

I added labels for clarity and structure and consolidated the date and time fields into a single field. This helps us save space and keeps these two values tightly together. When selecting this control, we'll show a date and time picker, very similar to what we currently have, but with the addition of a time setting. The "Notify team via Slack" checkbox is kept intact.

<img width="450" alt="Screen Shot 2021-05-05 at 5 13 58 p m" src="https://user-images.githubusercontent.com/3276087/117216385-4b64ec80-adc5-11eb-92c8-dc21121432e7.png">

#### Adding reminders

We now have the "Reminders" section next, where the user can add one or more reminders for when the phase is ending. We can have some sensible defaults for the values here: _24 hrs before, 10 hrs before, 2 hrs before, 1 hr before, 30 mins before_. Once a reminder is added, the user can remove it via the "X" button next to it, and can add additional reminders via the text button below.

<img width="574" alt="Screen Shot 2021-05-05 at 5 19 34 p m" src="https://user-images.githubusercontent.com/3276087/117216904-19a05580-adc6-11eb-9eb6-8f01f0f8eb80.png">

Lastly, there is a clear "Save" button to confirm changes.

#### The notifications in Slack

For this I'm borrowing from the recent design work done for Slack notifications over on #4911:

<img width="515" alt="slack reminder" src="https://user-images.githubusercontent.com/3276087/117217695-6a647e00-adc7-11eb-8847-8adfc38a6254.png">

We need to display that a phase is ending and in how much time. We also provide info on the team, the meeting and the shortened link. The notification ends with a CTA that lets the user open the meeting.

---

Would love to hear what y'all think, cc. @ackernaut

**Comment by ackernaut** [comment]
@enriquesanchez nice work and thanks for the update. I left most of my feedback in [this comment in Figma](https://www.figma.com/file/13hfEQOWIsaWc1pqfhoEnd?node-id=1:1101#79165379)

**Comment by enriquesanchez** [comment]
Iterated on this a bit more based on feedback and better understanding of the problem at hand. [Here's a walk-through of a little prototype](https://www.loom.com/share/72520c1b11b94a9fb8af5a01944ec5fc) I made to show the new time limit pop-up and the flow to add reminders. [The prototype can be found here](https://www.figma.com/proto/13hfEQOWIsaWc1pqfhoEnd/Schedule-phase-reminders?page-id=45%3A0&node-id=60%3A276&viewport=-294%2C145%2C1.2734375&scaling=min-zoom).

<img width="1318" alt="Screen Shot 2021-05-14 at 3 39 07 p m" src="https://user-images.githubusercontent.com/3276087/118326474-a3d57180-b4ca-11eb-8661-057a449750b9.png">

**Comment by enriquesanchez** [comment]
Closing now that we have an implementation issue over on #4994
