### ISSUE TITLE
Organization can be undefined in DashNavList

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4922]
Affected 20 users over the past year

https://sentry.io/organizations/parabol/issues/1648813501/?referrer=github_plugin

```
TypeError: Cannot destructure property 'id' of 'n' as it is undefined.
  at None (./packages/client/components/DashNavList/DashNavList.tsx:55:18)
  at Array.forEach (<anonymous>)
  at a (./packages/client/components/DashNavList/DashNavList.tsx:53:11)
  at c (./packages/client/components/DashNavList/DashNavList.tsx:50:25)
  at Set.forEach (<anonymous>)
...
(35 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Still a thing. Will bump in priority a bit

**Comment by jordanh** [comment]
This is still a thing. We didn't tackle it yet. Will keep it open

**Comment by jordanh** [comment]
Elevating in priority to at least assort higher on the list when I reprioritize the backlog

**Comment by igorlesnenko** [comment]
I found the root cause. Here are the steps to reproduce.

- As User_1 copy team invite link 
- As User_2 have a tab with parabol dashboard opened
- As User_2 paste invite link in **another** tab, see you joined the team successfully
- As User_2 go to the first tab, see **no** new team appeared in sidebar
- As User_2 click on `Tasks`, see the app crashed

In User_2 console there is an error:
```
NotificationSubscription.ts?8b09:294 NotificationSubscription case fail AuthTokenPayload
```
