### ISSUE TITLE
Add shareable link to task cards

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4923]
It'd be nice to be able to share a task card outside of Parabol, e.g. in Slack. 

Perhaps we could add a shareable link to the task card dropdown options here:

![task-card](https://user-images.githubusercontent.com/39854876/116608798-3980d680-a8f9-11eb-9048-87b1a57209f3.png)

The unique url could be the `/${teamId}/${taskId}`. 

When a user clicks on the link, the linked task card would be highlighted. For example, the card could have the same box shadow elevation as onHover but be blue instead of grey. 

We could use this blue highlighted card style when a user clicks on a "task assigned" notification too.

**Comment by mattkrick** [comment]
oh you're absolutely right!
We've talked about adding "card backs" to tasks, similar to what trello has when you click on a card.
that would let you see the task history, where it was created, maybe the discussions it was involved in, etc.

short of that, a highlight on a card seems ideal! it'll be especially fun because assuming it takes you to the task page, you'll have to make sure it appears on the page above the fold. that gets challenging if it's e.g. card 100 in a column, or archived, etc.

lots of fun details to work out on this one, but it's a great way to improve parabol's visibility outside the app!

**Comment by mattkrick** [comment]
github proejcts now does this, we could use it for inspiration.
iceboxing for now
