### ISSUE TITLE
Hide Team view if it's a blank page

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#4928]
If you didn't create the team and the team upgrades to Pro, the Team view in Settings & Integrations shows an empty page:

![team](https://user-images.githubusercontent.com/39854876/116630505-e159cc80-a918-11eb-9ab9-d63866f56db5.png)

### AC

If there's no Team view:

- [ ] Hide the Team and Integrations tabs
- [ ] Only show the Integrations view
- [ ] ~~Change the link "Settings & Integrations" to "Integrations"~~

**Comment by ackernaut** [comment]
I recommend 2 things:
- Use a current tab pattern when there are tabs. We could do this work in another issue, and perhaps update the old pill tabs on the Organization view while we’re at it
- I wouldn’t change the label of the link. ‘Settings & Integrations’ is general enough IMO and folks can use consistent language, like with customer success “just look under Settings & Integrations”

**Comment by jordanh** [comment]
Re-prioritizing as this was added to our Sprint Planning meeting

**Comment by nickoferrall** [comment]
**Include in next sprint?: N**
  [See the discussion](https://action.parabol.co/meet/aGjmYpJBIs/estimate/42) in Planning for Sprint #​​96

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by 87prashant** [comment]
Is the issue still active to work on?

**Comment by nickoferrall** [comment]
I think the settings, integration, and admin are getting a redesign - is that right @ackernaut? If so, I can close this issue

**Comment by ackernaut** [comment]
Yes, we intend to rework the navigation for these views. I’m not sure how soon we’ll get there.

I believe the `/settings/integrations` route is being used to send folks when onboarding so we need to keep that for sure. I’d be okay just switching the ‘**Settings & Integrations**’ link on the team kanban view to point to `/settings/integrations` instead of `/settings` and deferring any more work here until we get further on design. Not ideal, but I think that immediate awareness of the available integrations is the biggest win here. Team leads can switch to the Team tab if they need.

**Comment by Dschoordsch** [comment]
Will be addressed in #6894
