### ISSUE TITLE
Redis: Persist discussion commentors

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5022]
Today, discussion thread commentors are all managed via local updates. that means someone joining a discussion late won't actually see folks actively commenting until they stop & start again.

This is a good PR for someone who would like to learn more about redis & subscriptions

AC
- [ ] commentors is persisted in redis,  just like `pokerHover` is used today
- [ ] the editCommenting mutation logic is removed because it's all handled magically now

Estimate: 8 hours

**Comment by mattkrick** [comment]
ahhh yeah that AC could've been a bit clearer.

The logic I'd like to simplify is: https://github.com/ParabolInc/parabol/blob/91f51f6318d3a02efd588072e15cf3408dd92360/packages/client/mutations/handlers/handleEditCommenting.ts. If we can get rid of that whole file, great!

ideally the editCommenting fragment would look like:

```gql
  fragment EditCommentingMutation_meeting on EditCommentingPayload {
    commentors {
      id
      preferredName
    }
  }
```

then Relay will automatically handle the commentors array for us.

We can do that by including a field like `threadConnection: {type: ThreadableConnection}` in the `EditCommentingPayload`.
Then, we can add `commentors` of type `[User!]!` in addition to `commentorIds` here:  https://github.com/ParabolInc/parabol/blob/db45e3b5a4c27e917dcc267d33175bae8a04970b/packages/server/graphql/types/Threadable.ts#L88


there still might be some glue needed somewhere to link it to the proper discussion thread.

**Comment by Dschoordsch** [comment]
Since the commentors are tracked by [discussion](https://github.com/ParabolInc/parabol/blob/db45e3b5a4c27e917dcc267d33175bae8a04970b/packages/server/graphql/mutations/editCommenting.ts#L17), is there a specific reason, why they should be added to the `ThreadableConnection`? [`Discussion`](https://github.com/ParabolInc/parabol/blob/db45e3b5a4c27e917dcc267d33175bae8a04970b/packages/server/graphql/types/Discussion.ts) seems to be a more natural place. As far as I understand, the connection is used for pagination and somebody commenting is only indirectly connected. And a much more mundane reason, the parent of the [resolve function](https://github.com/ParabolInc/parabol/blob/db45e3b5a4c27e917dcc267d33175bae8a04970b/packages/server/graphql/types/Threadable.ts#L92) is the `ThreadableConnection` which does not have an id yet.

**Comment by mattkrick** [comment]
what you're saying makes a lot of sense!
Yeah, the `Discuss` object is a much more sensible place to put it. :+1: 
then we can remove this https://github.com/ParabolInc/parabol/blob/b3ad5ab723a1d512700e6dea0dc7267eb39b7192/packages/client/clientSchema.graphql#L109
