### ISSUE TITLE
Jira stories, can’t add points as a comment

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5028]
I looked and can’t see if this is on our radar:

### Reproduction steps
- Estimate a Jira issue in Sprint Poker
- Try selecting _As Comment_ or _Do Not Update_
- Nothing happens

![Screen Shot 2021-06-08 at 10 51 37](https://user-images.githubusercontent.com/307286/121217519-8b494480-c847-11eb-9681-eea8d5e5957e.png)

### Acceptance criteria
- The options _As Comment_ and _Do Not Update_ work as expected

### Estimated effort
- 8 hours

**Comment by BartoszJarocki** [comment]
Selecting these two fields doesn't work because the `UpdateJiraDimensionFieldMutation` fails with `Invalid field name error`.
<img width="1010" alt="Screenshot 2021-06-09 at 17 20 33" src="https://user-images.githubusercontent.com/1017620/121391435-a81c6f80-c94e-11eb-8339-e15571fc3e04.png">

I see these two fields are treated differently and use predefined values. `As Comment` uses `__comment` value as field name, where in Jira this field has `Comment` name and as a result it can't be found. @mattkrick do you recall why the field name for `Comment` is set to `__comment`? 

Also, what's the reason for having 'Do not update' menu option and what should happen when someone actually selects it and clicks `Update`?

**Comment by mattkrick** [comment]
@BartoszJarocki if you dig around the repo for `JIRA_FIELD_COMMENT` then that should help clear some things up.
basically, if they choose to push the new score as a comment, then we don't update a field, we just post a comment to the issue...so if we're still calling jira to try & update a field with that name then the logic broke somewhere.

the DO NOT UPDATE means they get a story estimate within paraobl but we don't push that change to jira

**Comment by BartoszJarocki** [comment]
PR: https://github.com/ParabolInc/parabol/pull/5041
