### ISSUE TITLE
hardDeleteUser mutation created

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5035]
## Issue - Enhancement

Today we have the `deleteUser` mutation which marks the user as deleted in our DB but does not remove the record from DB. We need a mutation to "hard" delete a user.

With this mutation exist, we can also better fulfill user privacy requirement in case there are requests for removing the data from a user.

### Acceptance Criteria (optional)
A private mutation exist, which takes `userId` or `email` and a reason text. The mutation will:
- [x] Hard delete the user record from `User` Table
- [x] Hard delete the user record from `TeamMember` table
- [x] Hard delete the user record from `MeetingMember` table
- [x] Hard delete the records in `AtlassianAuth` table with reference to the `userId`
- [x] Hard delete the records in `Notification` table with reference to the `userId`
- [x] Hard delete the user records from `OrganizationUser`
- [x] Hard delete the records in `SuggestedAction` with reference to the `userId`
- [x] Hard delete the records in `Task` with reference to the `userId`
- [x] Hard delete the records in `TimelineEvent` with reference to the `userId`
- [x] Hard delete the records in `AgendaItem` with reference to the `teamMemberId` that takes the form of userId:teamId for every team the user was on
- [x] hard delete Comment where createdBy == userId
- [x] if a meeting has a facilitatorUserId == userId AND another user is still on the team, then change facilitatorUserId to the other team member's userId
- [x] delete PushInvitation where userId === userId
- [x] delete RetroReflection where creatorId === userId
- [x] delete SlackNotification where userId === userId
- [x] delete TeamInvitation where invitedBy === userId

Note: this doesn't solve for Meeting stages, but that's OK for now.

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tiffanyhan** [comment]
@tianrunhe @mattkrick 

i assume we also want to delete all relevant rows from postgres too. if all tables had foreign key references to user (and team), this mutation will be easy. delete the parent user will automatically delete all child objects in postgres if `ON DELETE CASCADE` is specified. otherwise, we will have to delete everything manually just like we have to do for rethink.

today, we don't have foreign key constraints referencing backfilled tables. we made the decision to table it bc our rethink data was messy. we had dangling references and duplicate rows. now that we've achieved equality between rethink and pg user and team tables, should we try to add foreign key constraints? if so, it will be easiest to do it before routing reads to pg bc adding fk locks the table by default.

related: #4630, #4867

**Comment by tiffanyhan** [comment]
todo: add AC for postgres side

**Comment by tiffanyhan** [comment]
Related issue for FKs in PG: https://github.com/ParabolInc/parabol/issues/5334

**Comment by tianrunhe** [comment]
I find questions above quite interesting! Here's my thought:

> should we assign tasks to another team member if they exist?
I feel like the new assignee would feel confused when there's a new task shown up. Maybe we can just make the task unassigned?  
> Nor does the AC mention the `createdBy` field of `Task`
If the task was created by a now-deleted user but is assigned to someone else, then it should stay I think.
> Should we be deleting their comments?
Maybe we can make their comments anonymous?
> For `AgendaItem` and `RetroReflection`, same concerns as above for `Comment`
For `AgendaItem`, since we show the avatar of the creator and we can't 'unassign' it, we should probably just delete it? For `RetroReflection` it might be just fine as they are anonymous (in the UI) anyway.
> What about `TeamInvitation`?
I think we can keep it

Let's hear some thoughts from @ackernaut or @enriquesanchez !

**Comment by enriquesanchez** [comment]
I don't think we should delete any history or currently open tasks. That would cause more problems and/or confusion down the road.

For comments and activity, instead of using an anonymous user, can we specify that it is a deleted user? eg: "Jon Doe (Deleted)". It feels a little weird to change the history/context of an action because the user has been deleted. 

For tasks, I like the idea of unassigned tasks, and it makes senses that a task that was assinged to a now deleted user is now unassigned. We can add a filter option in the team tasks view for these.

**Comment by tiffanyhan** [comment]
+1 i like leaving the task unassigned.

i also think we should say "Deleted" in the UI instead of "Anonymous", as that's more accurate and less likely to be mixed up with actual anonymous but not content.

> I don't think we should delete any history or currently open tasks. That would cause more problems and/or confusion down the road.

+1 agree with this. for all children, (i.e. AgendaItem, RetroReflection, TeamInvitation) i think we should keep the objects and just set the relevant user fields to be null. in the UI, all content remains intact but we can show some text or other icon to show that the user was deleted.

**Comment by tiffanyhan** [comment]
- [ ] Calls `deleteUser` resolver to achieve the same side effects
- [ ] Hard delete the user record from `User` Table
- [ ] Hard delete the user record from `TeamMember` table
- [ ] Hard delete the user record from `MeetingMember` table
- [ ] Hard delete the records in `AtlassianAuth` table with reference to the `userId`
- [ ] Hard delete the records in `Notification` table with reference to the `userId`
- [ ] Hard delete the user records from `OrganizationUser`
- [ ] Hard delete the records in `SuggestedAction` with reference to the `userId`
- [ ] *Set `userId` with reference to the user to null  in `Task`, thereby un-assigning their tasks. Also set `createdBy` with reference to the user to null.
- [ ] Hard delete the records in `TimelineEvent` with reference to the `userId`
- [ ] *Set `teamMemberId` with reference to the user to null in `AgendaItem` for every team the user was on
- [ ] *Set `createdBy` with reference to the user to null in `Comment`
- [ ] if a meeting has a facilitatorUserId == userId AND another user is still on the team, then change facilitatorUserId to the other team member's userId
- [ ] delete PushInvitation where userId === userId
- [ ] *Set `creatorId` with reference to the user to null in `RetroReflection`
- [ ] delete SlackNotification where userId === userId
- [ ] *Set `invitedBy` and `acceptedBy` with reference to the user to null in `TeamInvitation`

**Comment by tianrunhe** [comment]
Looking at DB & GraphQL type definitions, you might not able to set `createdBy` for some of the objects to `null`, for example `Task`. How do you plan to address that?

**Comment by enriquesanchez** [comment]
>Set userId with reference to the user to null in Task, thereby un-assigning their tasks.

@tiffanyhan How would this look in the task UI?

**Comment by tiffanyhan** [comment]
> @tiffanyhan How would this look in the task UI?

Looking at the code in `packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterUserAssignee.tsx`, it looks like we default to a stock material icon for the avatar and show "Unassigned" as the name.

**Comment by tiffanyhan** [comment]
> Looking at DB & GraphQL type definitions, you might not able to set createdBy for some of the objects to null, for example Task. How do you plan to address that?

@tianrunhe i think we can just set to empty string.

**Comment by tiffanyhan** [comment]
@tianrunhe brought up a good point about graphql fields being non-nullable. even though we can set non-nullable id fields themselves to empty string '', (e.g. `Task.createdBy`), there are other non-nullable fields that those ids are used to resolve (e.g. `Task.createdByUser`).

i think we should make those graphql fields nullable, then change the UI components to do optional chaining where they used to expect a guaranteed field. this seems like the best way to hard delete a user and still maintain a UI that's not confusing to any remaining team members.

if we proceed with this direction, i think we should break up the UI changes to a separate issue/PR.

**Comment by tiffanyhan** [comment]
it looks like the soft delete user mutation already assigns tasks to a remaining team member when that user is soft deleted. i think we should have consistent behavior: either assign to a remaining team member for both hard and soft deletes, or just un-assign their tasks for both hard and soft deletes.

**Comment by mattkrick** [comment]
I'd first remove them from all their orgs & then do the hard delete. 
The logic inside removeFromOrg should do all the reassignments. If it doesn't, then we should fix that: https://github.com/ParabolInc/parabol/blob/85d7de0c376bff7c733b75cae27ee0d4da0a54a9/packages/server/graphql/mutations/helpers/removeFromOrg.ts

once the user has been removed from every org, all their assets should be reassigned & we can do a hard delete

**Comment by tiffanyhan** [comment]
@mattkrick made all the changes you suggested, would greatly appreciate it if you could take another look when you can.
