### ISSUE TITLE
Support postgres in backupOrganization mutation

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5043]
`backupOrganization` is a great way to clone just our team's data from the prod database so we can use it as mock data in local development.

We need it to backup our postgres data, too.

AC
- [ ] backupOrganization creates a DB dump that is filtered to only contain rows that pertain to the provided orgId. If possible, this dump happens directly without cloning the rows to a separate DB. 
- [ ] the tables it dumps include:  GitHubAuth, OrganizationUserAudit, PgMigrations, PgPostDeployMigrations, Team, TemplateRef, TemplateScaleRef, User
- [ ] The notion doc https://www.notion.so/parabol/How-to-Get-Mock-Data-To-Develop-Locally-fc0b90425a3049a3aa21abeb7ca88f23 is updated to include any extra manual steps

Estimate: 16 hours

**Comment by tiffanyhan** [comment]
**Approach:**

at first i looked into cloning tables and selectively populating them into same db different schema via `CREATE TABLE AS`. the problem is that even when adding `INCLUDING CONSTRAINTS` option, not all constraints are added-- notably foreign key constraints.

they only thing that reliably copies and recreates all constraints is `pg_dump`. unfortunately, `pg_dump` doesn't expose any way to selectively filter what do to dump.

My solution for the schema is to use `pg_dump` to only dump DDL, then restore it to a separate pg db. 

For rows, I first tried using `COPY` but the problem here is it doesn't update sequences for tables who have them. To get around this, I reverted back to using `INSERT` statements and removing ids in memory from relevant rows to be inserted so the postgres engine is forced to use the seq generator.

**Comment by tiffanyhan** [comment]
there is also a lot of annoying logic to get around empty arrs not failing in pgtyped functions; issue has already been logged in pgtyped here, but hasn't been prioritized by them: https://github.com/adelsz/pgtyped/issues/221

**Comment by tiffanyhan** [comment]
after this, need to refactor postgres backup job to accept dbname as param.

**Comment by tiffanyhan** [comment]
> big picture, this strategy reads ALL the data from PG, puts it in memory in node, then moves ALL that data back to PG.
this is a little dangerous:

> it will cause node to run out of memory & crash
inserts can only handle 16-bit params, so if it's more than a couple thousand rows it'll fail
i think what you want is to:

> clone the schema
SELECT INTO from the source schema to the table in the target schema

@mattkrick if memory and payload is a concern, which I agree it may be, we can:
- [ ] use `CREATE TABLE AS` and name the clone `tableName_orgBackup`
- [ ] find a manual workaround to clone foreign keys, or just table it until we need to since we don't have foreign keys yet
- [ ] write a script that will only dump the cloned orgBackup tables
- [ ] write a script that will rename the tables to the original once restored locally

**Comment by mattkrick** [comment]
i think this looks good! from what i can tell, we either use `CREATE TABLE AS` to get the data we want but no constraints, or we use `CREATE TABLE FOO (LIKE BAR INCLUDING INDEXES INCLUDING CONSTRAINTS)` to get the constraints we want but no data. I like your approach!

Only thing I'd change is to lump all the fresh tables into a new schema & that way we just have to rename a schema instead of having to rename a growing list of tables.

Big picture it'll be like:
- Dump schema: `pg_dump --file "orgBackupSchema.backup"--schema-only --schema=public`
- Create backup schema: `CREATE SCHEMA "orgBackup"`
- Copy data (I'd probably just write 1 big query for this, e.g.
```
DO $$
BEGIN
  CREATE TABLE orgBackup."TaskEstimate" AS SELECT * FROM "TaskEstimate" WHERE "userId" in :userIds;
  CREATE TABLE orgBackup."AtlassianAuth" AS SELECT * FROM "AtlassianAuth";
END
$$
```
- Dump data: `pg_dump --file "orgBackupData.sql" --schema "orgBackup"`
- Delete data: `DROP SCHEMA "orgBackup" CASCADE`

Then on the target we just need a script to:
- Restore public schema: `pg_restore --dbname "web"  "orgBackupSchema.backup"`
- Rename to orgBackup: `ALTER SCHEMA public RENAME TO "orgBackup"`
- Restore data: `pg_restore --dbname "web" "orgBackupData.sql"`
- Revert name to public: `ALTER SCHEMA "orgBackup" RENAME TO "public"`

**Comment by tiffanyhan** [comment]
to be specific, copying tables using either `AS` or `LIKE` syntax doesn't copy foreign key constraints.

@mattkrick thanks for the suggestion to create a new schema! i think that sounds really good, and i'll move forward with this approach.

fyi: i liked the suggestion to lump all queries into a `DO BEGIN END` block, but it looks like [pgtyped only supports single statement queries](https://github.com/adelsz/pgtyped/issues/142#issuecomment-663822520). i might just do this with node-postgres as an alternative.

after restoring the data and in addition to renaming the schema, we also need to manually set the next sequence values.

**Comment by mattkrick** [comment]
that workout seems pretty great! although if we wanted to do it without PG typed that's fine too because this will only be used in a single place.

keeping the sequences & FKs are also great constraints! i think they should live somewhere in the schema...
