### ISSUE TITLE
Postgres EHOSTUNREACH error

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5074]
## Issue - Bug

Looks like we've got a few minutes Postgres down time around Jun 24, 2021 08:50. Sentry captured the [error](https://sentry.io/organizations/parabol/issues/2473955167/?project=107196&query=is%3Aunresolved+migration%3Apostgres&statsPeriod=14d):

```
SEND TO SENTRY Error: connect EHOSTUNREACH xx.xx.xx.xx:25060
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: 'xx.xx.xx.xx',
  port: 25060
} {"migration":"postgres"}
```

This caused a few writes to PG failed. 

### Acceptance Criteria (optional)
- [ ] Connection to PG should be stable. Retries should be made if necessary.
Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by mattkrick** [comment]
well this is terrifying.
worth noting that it comes from https://github.com/ParabolInc/parabol/blob/2fdba987ef40a6afbb1f613e5fd814155612b007/packages/server/postgres/utils/catchAndLog.ts

next steps:
- [ ] see if DO did a migration or something else, because that EHOSTUNREACH is trouble. that means our web container couldn't talk to the PG container.
- [ ] add in extra tags like the args and/or name of riskyFn because we're not getting stack traces for this error
