### ISSUE TITLE
action-staging not accepting stripe webhooks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5089]
Since locking down action-staging, webhooks from stripe aren't making their way through.
this isn't a showstopper, but we should fix this so we can properly test stripe things.

@tiffanyhan @adaniels-parabol any ideas? maybe we whitelist stripe at the nginx level?

AC
- [ ] webhooks from stripe make it through to action-staging

Estimate: 8 hours

**Comment by jordanh** [comment]
> maybe we whitelist stripe at the nginx level?

I'm guessing we should probably have an easy way to whitelist lots of things so testing webhooks from other services (i.e. integrations) is easy too

**Comment by tiffanyhan** [comment]
Did a little digging on google, here's my thoughts:

If we're talking beyond stripe, the problem I see with whitelisting IP addresses is some webhook providers may only have dynamic IP addresses instead of static, and even static IP addresses can change over time.

> If you are hardcoding IPs into your firewall, you can use a script to receive updates when the A records for these hostnames change, or perform lookups on the aforementioned hostnames regularly to update your configurations.

We can use the above idea to automate checks, but effort seems high for the issue and we'd be constantly polling unnecessarily.

What if instead we hard coded basic auth username and password into the webhook URL? In general, this isn't the most secure practice. However, the creds in question are mostly used for the purposes of keeping the public and crawlers out of staging/dev and thus it's not really a big security concern.

Some webhook providers support adding arbitrary custom headers to the request which would be even better, but Stripe doesn't have this now.

References:
https://support.pagerduty.com/docs/safelisting-ips
https://stripe.com/docs/ips

**Comment by mattkrick** [comment]
basic auth in the url sounds like a wonderful idea! let's do that

**Comment by tiffanyhan** [comment]
solved by putting basic auth in staging and dev webhook urls. tested both staging and dev servers by successfully sending test requests.

https://dashboard.stripe.com/test/webhooks
