### ISSUE TITLE
summary review not working properly 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5099]
A [user ](https://app.hubspot.com/contacts/3888472/contact/21973751) 🔒 writes:

> The "Review a summary" isn't working anymore. Click to the link will be redirected back to the Meeting page, not the retro itself. Refer attached for the details.

https://user-images.githubusercontent.com/80418360/124321837-fb47a380-db43-11eb-8d0e-4167392cd704.mp4

Hubspot ticket:

https://app.hubspot.com/contacts/3888472/ticket/466585504/

**Comment by mattkrick** [comment]
@BartoszJarocki this will be a fun one we can triage for our one-on-one

**Comment by tianrunhe** [comment]
Duplicate issue with #5078. Bug is on empty discussion thread.

**Comment by BartoszJarocki** [comment]
@tianrunhe is right here. Related: https://sentry.io/organizations/parabol/issues/2449818299/?project=107196
One note: I can only reproduce that with Retro meetings.

**Comment by mattkrick** [comment]
ahh that makes sense.
for retro meetings we create a dummy discussion topic as a placeholder & then replace that with the first discussion topic after they advance from vote -> discuss.
if they never get that far, then i assume the meeting is left with a dummy topic that doesn't have certain necessary fields (e.g. a discussionId)

maybe we:
- create a helper that checks if no discussion topics were created & if so 
- the timeline event takes them to the group phase instead of the discuss phase 
- the summary fails gracefully by checking if it's a dummy & if so, treats the discussion topics as an empty array

**Comment by BartoszJarocki** [comment]
Sentry issue: [ACTION-PRODUCTION-80J](https://sentry.io/organizations/parabol/issues/2449818299/?referrer=github_plugin)
