### ISSUE TITLE
Retro: Discuss: Estimated time left per topic

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5122]
Being a facilitator is hard. You don't want to cut someone off, but you want to hit all the important topics.
If the software can be the jerk, then meetings will be better facilitated.
I propose we put a countdown timer on each discussion topic in the left nav.

- To calculate how much time each topic should get, we figure out how much time is left in the meeting (easy once we integrate with GCal, for now we can just guess 30, 60, 90 mins).
- We put a cute draggable pink bar where there is a dropoff on number of votes. Any topics below the line are assumed that we won't discuss
- To calculate how much time each topic should get, we take `discussion votes / total votes above the liine * time left`
- As time ticks down, the current issue estimate ticks down but the rest stay the same
- when the current issue hits 0:00, then the estimtae on the items below it starts ticking down

@ackernaut @enriquesanchez let me know your thoughts & if you can make sense of my bad drawing :sweat_smile: 
![IMG_1206](https://user-images.githubusercontent.com/5514175/125112782-7a852c00-e09c-11eb-9c25-970c0724e65d.jpg)

**Comment by enriquesanchez** [comment]
I think this would be a great addition, but once we have a calendar integration or have a way to be certain about the meeting length. 

As it currently stands, we really can't be certain of how long a meeting is going to be, and I worry that our best guess would not add much value in most cases, and instead cause confusion.

How would this work for async meetings that can be open for X days/weeks?
How would this interact with the currrent timer that facilitators can set per discussion topic?

Maybe instead of, or in addition to this, facilitators have the option to set a timer for the whole Discussion phase. That way we have a more exact time range to work with and calculate the time available for each topic?

**Comment by mattkrick** [comment]
that's sharp thinking!
let's revisit this once we've got phase-level timers in place
