### ISSUE TITLE
Spotlight: similarReflectionGroups query

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5182]
Predecessors: none

We need a way to suggest which reflections would make good groups.
We'll do this server-side because in the future we may make this logic a little smarter, but for now it'll be dumb

AC
- [x] `similarReflectionGroups` exists on the graphql User object (open to alternative locations e.g. on the RetrospectiveMeeting object. discuss below)
- [ ] `similarReflectionGroups` accepts 2 args: `{reflectionId, searchQuery}` both are nonnull, but searchQuery could be an empty string
- [x] the resolver makes sure the reflectionId is valid, then makes sure that the viewer has permission to view the reflectionId based off the reflectionId.meetingId & the user has a meetingMember that shares the same meetingId
- [x] the return type is `[ReflectionGroup!]!` 
- [x] to start with, the query simply returns all the active reflectionGroups in the meeting (we'll handle better logic in the next issue) 
- [x] when the spotlight modal is opened, it triggers this query

Estimate: 8 hours

**Comment by nickoferrall** [comment]
@mattkrick happy for me to work on this Spotlight issue next?

Rough plan / thoughts:

- I think it makes sense to add `similarReflectionGroups` to the User object. We could add it to the meeting object as it's related and we're currently querying the meeting and not the user object in the group phase. But, as Spotlight `similarReflectionGroups` are specific to only that user's view rather than everyone in the retro, I think the User object makes sense
- I plan on adding the query to the SpotlightModal component so that when it's opened, it triggers the query right away

**Comment by mattkrick** [comment]
> The meetingId doesn't exist in the User source object so I suggest that we add the meetingId as an argument along with reflectionId & searchQuery

Given the `reflectionId`, could you grab the reflection using a dataloader & get `reflection.meetingId`? That way the user can't pass in a reflectionId that doesn't exist in a meetingId. more client-supplied args = more ways for folks to "hack" us (or at least find gaps in our authorization) 

aside from that, looks great!
