### ISSUE TITLE
Meeting will not open to allow edits and cannot be ended 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5186]
A [user ](https://app.hubspot.com/contacts/3888472/contact/42190251) 🔒 writes:

> I have created two Sprint Poker meetings. Unfortunately, when I click on one of the meetings, the screen doesn't open the meeting. The other meeting opens and works fine. I have tried in several browsers and have cleared cookies, etc. I do not want the team to access this meeting if I cannot open it to facilitate. Can you please help me delete the meeting named "Alerts/Notifications"?

Hubspot ticket: https://app.hubspot.com/contacts/3888472/ticket/486891528/

**Comment by tiffanyhan** [comment]
This is happening bc the meeting `facilitatorStageId` does not exist as a stage in any of the meeting's stages. The redirect is happening in `useInitialSafeRoute`, where `fromStageIdToUrl` fails.

Next steps:
- for this user, we can simply set `facilitatorStageId` to the first not completed stage.
- we can try to find the edge cases where this bug can occur (harder)
- we can implement a fallback in app code, so that if no meet stage matches any current meeting stage, we just redirect them to the first not yet completed stage (easier, but may make it harder to pinpoint edge cases in the future)

**Comment by tiffanyhan** [comment]
dangling `facilitatorStageId=5d0F2RcKCG`
