### ISSUE TITLE
Replace RedisLock with a queue

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5268]
In our system, some functions cannot get called at the exact same moment by the same user.
A good example is a GraphQL mutation called `acceptTeamInvitation`. We wouldn't want the same user to accept the team invitation twice and trigger 2 new team members!

Normally, the mutation would check the database and only continue if the `TeamMember` is not found. However, what if both calls occur at the  _exact_ same time? They'd both query the database at the same time. They'd both determine that a `TeamMember` for that user doesn't exist, and they'd both continue on to create a new `TeamMember`!

To solve race conditions like this, we implement a locking mechanism using redis (https://github.com/ParabolInc/parabol/blob/4a7ef7030825bcd2133c69875ff1f90530a0ed15/packages/server/utils/RedisLock.ts)
- `Event 1` and `Event 2` both try to achieve a lock on a redis key called `acceptTeamInvitation:userId=123`.
- `Event 1` achieves the lock, completes the mutation, calls `unlock()`, & returns successfully
- `Event 2` fails to achieve a lock, retries after `Event 1` finishes, determines that the TeamMember already exists, and exits early

This system works well if it doesn't matter which event executes first.

However, if events needs to be executed in a deterministic order, this can cause problems.
If 3 events calls `RedisLock.lock()`, then it is possible that the events are executed: `1, 2, 3` or `1, 3, 2`

This is why:
- `Event 1` gets called & triggers a lock with a max duration of 3 seconds
- `Event 2` gets called, finds the lock has 2.9 seconds left & sets a timeout to check again in 2.9 seconds
- `Event 1` finishes & calls unlock
- `Event 3` gets called, finds there is no lock, and runs to completion
- `Event 2`'s 2.9 second timeout finishes, and it runs to completion

Even if `Event 2` repeatedly checked the lock every 100ms, or 10ms, or even 1ms, there is no guarantee that it will run before `Event 3`.

**We need a way to execute tasks in serial in the order that they were queued**

Acceptance Criteria
- [ ] the locking system must scale horizontally across multiple node instances & a cluster of redis instances
- [ ] items are executed in serial in the the same order that they are queued
- [ ] A list of options with their pros/cons is written out
- [ ] a proof of concept is built in code
- [ ] The following code is replaced with a call to the new proof of concept https://github.com/ParabolInc/parabol/blob/ae37f393991f245ba888f193a2c3c9e0ac7c766d/packages/server/graphql/mutations/updatePokerScope.ts#L75-L77

A few possibilities to get started:
- use an established package like https://github.com/OptimalBits/bull
- enhance RedisLock to include a redis pub/sub where every `unlock` triggers a publish and every failed lock triggers a subscription 

Estimate: 12 hours

**Comment by mattkrick** [comment]
### Igor, this is amazing!

Seriously, wonderful write-up. 

#### Option 1
I agree, the first feels a little heavy handed & as is still doesn't solve the problem. We _could_ possibly achieve deterministic order using some kind of clock like a lamport timestamp, but that feels needlessly complex.

 #### Option 3
I agree. I've been holding off introducing a job queue into our app because they introduce so much complexity. 

### Option 2
This looks wonderful! I think starting with a single queue is the right call. If handling failures becomes a problem, we could set up 2 queues & use `RPOPLPUSH`, but for now I say we assume every job runs to completion.

One note is I'd probably not implement a TTL on the list.

Imagine the following scenario:
- At time 0, 3 UIDs are added to the list
- Every 3 seconds, 1 UID is removed and 1 UID is added
- This continues indefinitely, where each job waits in the queue for 6 seconds before starting. This is OK!

IIRC, redis will garbage collect empty lists, so we can avoid a TTL without a memory leak.

The design looks great. On to the code!

**Comment by igorlesnenko** [comment]
@mattkrick 

Yeah, I see the issue with TTL. 

But now, if we have no TTL on the LIST, it is possible that LOCK will exists forever, preventing all other Events to run.
Feels dangerous, because if it happens even with a small probability, we will need to fix it by hands.

**For example:**

- 3 events added to a queue.
- Server crashes
- Now we have 3 events stuck in the queue forever
- Event 4 comes and added to a queue
- Event 4 periodically checks that his `UID` is first on the list (which will never happen)
- Event 4 and all subsequent events fails with `maxtime`

It is easy to solve this when we have only 1 crashed event — we may put every running event in a separate processing queue and set TTL only on it. But it won't work with multiple events stuck in a queue and their processes crashed.

We need to somehow detect this case and remove crashed UIDs or drop the whole queue.

I found 2 possible viable solutions:

**1) Set TTL on LIST creation and refresh TTL before running each Event**

So if TTL is not refreshed, it means the queue got stuck. 

- The queue will be removed after TTL
- New events will be added to a newly created queue
- Old events will fail with maxtime, as they will never find their UIDs

TTL should be selected to be bigger than the time required to process a single Event.

**2) Have a health check for each request**

Along with adding request to a queue, for each request we set a simple key `process:UID` with TTL on it.
Each request, when checks a queue, refreshes its TTL.
If `process:UID` key does not exists for the UID in a queue, we know that the corresponding process crashed.
So each event always checks the `process:UID` of the first item in the queue and removes the event if necessary.

I think the first approach is the easiest and seems to be reliable.

What do you think?

In the mean time I created a PR with a proof of concept using this TTL approach. 
For now, I don't use pub/sub for checking the queue — I think periodically checks are enough and pub/sub adds additional complexity. See: #5311
