### ISSUE TITLE
TypeError: Cannot read property 'phaseType' of undefined

### ISSUE THREAD

**Issue by tiffanyhan** [ParabolInc/parabol#5307]
134 events affecting 36 users, first seen in last release 6.24.0. seems related to older #4480

https://sentry.io/organizations/parabol/issues/2588956277/?referrer=github_plugin

```
TypeError: Cannot read property 'phaseType' of undefined
  at c (./packages/client/components/MeetingSidebarTeamMemberStageItems.tsx:57:58)
...
(13 additional frame(s) were not displayed)
```

**Comment by mattkrick** [comment]
still live in 6.25.0! upped to p1

**Comment by nickoferrall** [comment]
Sentry is being a bit misleading with this one.

It's merged two different `Cannot read property 'phaseType' of undefined` errors together. One is on the server and is not fatal. The other is on the client and is fatal.

Since 6.25.0 was released, there haven't been any fatal errors on the client - just a few non-fatal server errors: [see here](https://sentry.io/organizations/parabol/issues/2588956277/events/?cursor=0%3A0%3A1&project=107196&referrer=github_plugin).

@mattkrick happy for me to close this issue? We already have a p4 issue for the non-fatal server error https://github.com/ParabolInc/parabol/issues/4480

**Comment by mattkrick** [comment]
ah what the heck sentry!
yeah onward to bigger, uglier bugs!

**Comment by nickoferrall** [comment]
While the issue linked here is only referring to non-fatal server errors, there is another Sentry issue that does still show fatal client side errors: [see here](https://sentry.io/organizations/parabol/issues/2606465250/?project=107196&query=+level%3Afatal+timesSeen%3A%3E5+is%3Aunassigned&statsPeriod=14d).

Reopening this issue and will push a fix shortly

**Comment by nickoferrall** [comment]
Sentry issue: [ACTION-PRODUCTION-9GF](https://sentry.io/organizations/parabol/issues/2606465250/?referrer=github_plugin)
