### ISSUE TITLE
Error: Issue does not exist or you do not have permission to see it.

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5324]
https://sentry.io/organizations/parabol/issues/2529575750/?referrer=github_plugin

Affected 103 users, happened 4.7k times in the last 30 days. Not fatal, but worth looking into.

```
Error: Issue does not exist or you do not have permission to see it.
  File "./packages/client/utils/AtlassianManager.ts", line 317, in p.get
    return new Error(json.errorMessages[0])
  ?, in runMicrotasks
  File "./packages/client/utils/AtlassianManager.ts", line 553, in async p.getIssue
    const issueRes = await this.get
```

**Comment by mattkrick** [comment]
Definitely should fix, we access jira issues by using the credential of the person who added the jira issue. if that person can no longer access jira (they were removed from the team? they no longer use jira? etc) we should know why & create a fallback (remove the task, archive it, use the credentials of someone else)

AC
- [ ] find the root cause of why the permissions don't work
- [ ] use the `task.integration.accessUserId` to access the jira issue, figure out if that works
- [ ] report findings to @mattkrick and propose next steps

Estimate: 4 hours

**Comment by tiffanyhan** [comment]
**Background:**
Looking at the error occurrences, it seems to happen multiple times to the same person. E.g. one user had the error thrown ~20 times all exactly on Sep 10, 2021 18:18. The particular error also happens when fetching resources from Jira, as opposed to writing data.

According to Jira, each API request has an associated cost which is evaluated against a cost-budget. Since we are making requests to Jira from our app on behalf of the user, our cost-budget is by `App + user`. Unlike other APIs, Jira does not publish predetermined static numbers for rate limiting. Jira rate limiting is dynamic and constantly evolving based on available resources.

Since we don't have static numbers to go off of, our approach by necessity needs to follow a "best guess" line of thinking and also needs to be dynamic. What Jira may provide us with however, is `Retry-After` and `X-RateLimit-Reset` headers along with `429` responses. `Retry-After` indicates how many seconds we should wait before sending the request again, while `X-RateLimit-Reset` tells us an absolute timestamp when we can retry the request. We can base our handling logic off of these headers.

Pseudocode suggested by Jira for handling logic:
```
// Defaults may vary based on the app use case and APIs being called.
let maxRetries = 4; // Should be 0 to disable (e.g. API is not idempotent)
let initialRetryDelay = 5000; // milliseconds
let maxRetryDelay = 30000;
let jitterMultiplierRange = [0.7, 1.3];

// Re-entrant logic to send a request and process the response...
let response = await fetch(...);
if (response is OK) {
  handleSuccess(...);
} else {
  let retryDelay = -1;
  if (has Retry-After header) {    
    retryDelay = retryAfterDelay;
  } else if (statusCode == 429) {
    retryDelay = min(2 * lastRetryDelay, maxRetryDelay);
  }
  if (retryDelay >= 0 && retryCount < maxRetries) {
    retryDelay += retryAfterDelay * randomInRange(jitterMultiplierRange);
    retryCount++;
    retryRequest(...);
  } else {
    handleFailure(...);
  }
}
```

Client-side, we can implement the above **throttling** mechanism to make sure network requests don't even go out when the previous response was rate limited and we haven't waited enough time to try again. To account for users refreshing the browser, we might keep info from the last `429` response from Jira in local storage. 

We should also make sure each request is safe to try again. Since this error occurs when fetching from Jira, I assume this won't be a big concern. But it's possible some `GET` endpoints have side effects that make retrying the request unsafe.

_Pros and cons of client-side throttling approach:_ the pro is that it prevents each user from overloading the API on an individual basis. while waiting, we could even display a message such as "Waiting for Jira to respond...". the con is that it doesn't necessarily prevent us from overloading the API on a global app basis. E.g. each individual could be within their limits, but if enough people are trying to use their Jira integration at the same time, then we'd still reach an app-based rate limit.

To address the con above, another approach is to use a **proxy server** to relay API requests and responses. Since all API requests would be aggregated into one central location, we'd have more visibility to know if we're reaching an app-based rate limit. For instance, we could keep track of all requests to Jira from the last 5 mins. If the number of rate limited requests goes above a certain threshold (i.e. above 1 in 10), we could apply an additional global delay to each request accordingly.

_Pros and cons of proxy server approach:_ the pro is that it can respond to all aspects of the `app + user` cost-budget. Another pro is that all rate limit handling logic can be encapsulated by the proxy server. The client can just make dumb requests as per usual, just to a different endpoint. The con is we may have slower API responses in general, since we now have to go through a middle person. Another con is greater architectural complexity.

**Summary**
Since most error occurrences are happening multiple times for the same user around the same time, I think we should start with the client-side throttling approach first. The proxy server approach seems like overkill for now. The good thing is that handling user based rate limits will help us with any app based user limits anyway.

The other way to tackle this problem is prevention. This will involve triage and a combination of available methods: batching requests together, limiting requested fields, "side-loading" request resources, using a webhook to fetch updated info rather than polling, etc. I think we should also look at these techniques because prevention is always better than treating the symptom. But either way, we still need API rate limit handling so we should implement that right way for faster ROI.

Resources: https://developer.atlassian.com/cloud/jira/platform/rate-limiting/

**Comment by mattkrick** [comment]
This is interesting. Since we use `OAuth 2.0 (3LO)` I think we fall into the `App + user` category.
From the provided URL:

> App + user: the request was made by the app in association with a user interaction. Each combination of app and user has its own cost budget.

As I understand that, the limit is on the app + user combo, so we shouldn't run into a global limit.

What are your thoughts on server-side caching? For example:
- each issue we get from jira we cache in redis for a day or 2
- when a user queries an issue, we return the result from redis immediately & concurrently fetch the issue from jira
- when the fetch returns, the result is compared to what is in redis. if it is different, then we save the new value to redis & push the updated value to the client via subscription. if it's the same, we do nothing. if it's rate limited, we try again after `x-retry-after`. That way, the only way the user sees "Jira is down" is if they got rate limited AND there is nothing cached in redis

**Comment by tiffanyhan** [comment]
> As I understand that, the limit is on the app + user combo, so we shouldn't run into a global limit.

That's true, I just get paranoid bc Jira doesn't publish exactly how they calculate the cost budgets, so i feel like i wouldn't be surprised if it was mostly app+user but also a global limit or something.

@mattkrick  I think the cacheing approach you specified sounds great! I wasn't sure if we had any plans to implement cacheing with jira or any other integrations, but I think that approach sounds great.
