### ISSUE TITLE
Error: Stripe Quantity Mismatch

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5325]
https://sentry.io/organizations/parabol/issues/2436725787/?referrer=github_plugin

Not fatal, but we're getting it more and more since 6.14.0. Affected users so far: 246, happened 273 times

```
Error: Stripe Quantity Mismatch
  File "./packages/server/billing/helpers/processInvoiceItemHook.ts", line 116, in c
    sendToSentry(new Error('Stripe Quantity Mismatch'), {
  ?, in runMicrotasks
```

**Comment by mattkrick** [comment]
this is super bad. to the top!

AC
- [ ] root caused identified
- [ ] affected orgs fixed

Estimate: 8 hours

**Comment by tianrunhe** [comment]
In total 10 orgs/subscriptions were affected:

|count|subscriptionId|orgId|
|---|---|---|
|75|sub_JTXH2aqOINSAWL|3xAXbSQBhK|
|39|sub_GDsDWSZy73oep4|lgD5zFBKc|
|36|sub_HU9YIPdN5CQJ7Y|U7tF-1T_4|
|29|sub_JWej0pUlgO8eLg|LsrEKu3W_i|
|27|sub_IUWL2PqDxLaxjC|btUPPaZ9y4|
|21|sub_HQVlVqrvr5gOuK|VG9YijByqo|
|19|sub_GgdTrVOYLoGRHt|SyWOJ_56x|
|18|sub_JquZ798EHxQMkC|1sTbxPpn0s|
|10|sub_Fs3bsuEeNonTqr|H1K1euamX|
|1|sub_F9SgGyxI0a5P8a|DRMfsXZ_s|

**Comment by jordanh** [comment]
Given the limited impact, marking this p2

**Comment by nickoferrall** [comment]
- The difference between the mismatch totals is usually one or two users: https://sentry.io/organizations/parabol/issues/2436725787
- After looking into a few different invoices, I haven't found anything unusual
- The error first occurred in 6.14.0: https://github.com/ParabolInc/parabol/blob/production/CHANGELOG.md#6140-2021-jun-2
- We recently removed the option to manually pause users: https://github.com/ParabolInc/parabol/pull/6962. If manually pausing the caused the bug, we'll find out after the PR has been in production for one month

@mattkrick I suggest we move this issue to the backlog and review it when https://github.com/ParabolInc/parabol/pull/6962 has been in prod for one month. What do you think?

**Comment by mwermuth** [comment]
@nickoferrall what is the status of this? It looks like you wanted to check back in after a month. Is this one fixed?

**Comment by nickoferrall** [comment]
@mwermuth it looks like the Sentry errors are still showing up so this one is still active. I've added a Squad 2 label so it exists on our backlog and we can tackle it soon

**Comment by igorlesnenko** [comment]
Will try to investigate

**Comment by igorlesnenko** [comment]
This looks like a race condition to me.

* To check users count we query organization users [at the end of the function](https://github.com/ParabolInc/parabol/blob/master/packages/server/billing/helpers/processInvoiceItemHook.ts#L111) after 2 API calls to Stripe.
* For example, we used an invite link and several users clicked on it at the same time.
* If the function execution will take some time (could be because of API calls), at the end there will be mismatch error
 
**To reproduce:**

* Create organization and upgrade to PRO
* Put some sleep `await new Promise(r => setTimeout(r, 10000));` in the code [here](https://github.com/ParabolInc/parabol/blob/master/packages/server/billing/helpers/processInvoiceItemHook.ts#L101)
* Create and login with 2 users in 2 different browsers
* Copy and paste the invite link for those users at the same time
* See quantity mismatch error

Quick fix is to move `orgUsers` query before API calls. Here is the draft PR #7351. 

Not 100% perfect I think, but the error should be gone. If not, we will implement some other solution.

No need to fix any orgs as in case of race condition it is false alarm I guess.

@nickoferrall @mattkrick what do you think?

**Comment by mattkrick** [comment]
It appears that it isn't a false alarm, here is an example of a recent error where the quantity is off by 1: https://github.com/ParabolInc/action-devops/issues/101

**Comment by igorlesnenko** [comment]
@mattkrick Yes, you are right, my assumption was incorrect.

I checked the PROD data and did some additional research:

- There is a real divergence exits right now
- It could be more users in DB than Stripe, but vice versa too. (We need to think how to fix invoices correctly)
- I tried to find the very first error occurrence for specific subscriptions, to see if some specific action triggered it. I used `StripeQuantityMismatchLogging` table. I found that:
    - No specific action causes an error, I can see at least: `addUser`, `removeUser`, `autoPauseUser`
    - No specific count of users
    - There are new errors (So it is not possible that the error was fixed earlier, but we keep getting warnings as divergence exists)

So if not a race condition, I think it is possible that the divergence occurs somewhere else in the code long before the function with the quantity check is called. 

Will need to look more into this.

**Comment by mattkrick** [comment]
Yep! the trick is finding the first time that the DB count & the stripe count diverges, then seeing why. My guess would be that stripe took longer than 3 seconds to return? Ideally, we find a case where an organization just recently diverged within the last 14 days & then we can access all the webhooks sent from stripe's side, too.

**Comment by igorlesnenko** [comment]
@mattkrick Found one interesting case.
https://github.com/ParabolInc/action-devops/issues/101#issuecomment-1314322103

Will look into it more

**Comment by igorlesnenko** [comment]
Looks like only 12 organizations affected
https://sentry.io/organizations/parabol/issues/2436725787/tags/stripeSubscriptionId/?project=107196

**Comment by Dschoordsch** [comment]
This will be solved by #7409

**Comment by jordanh** [comment]
@Dschoordsch very exciting :)

**Comment by Dschoordsch** [comment]
#7409 was done, so this shouldn't happy anymore (in this way at least)
