### ISSUE TITLE
Audit PG User Table mutations

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#5384]
See https://github.com/ParabolInc/parabol/blob/7a0c2031dc2ce8b82ce31aeaa6e5c8d4ab2e7fe4/packages/server/billing/helpers/adjustUserCount.ts#L58-L65

Those 2 mutations aren't the same! 
We should check em all before we move to pg completely for the User table

AC
- [ ] audit all user mutations & maybe change them to be more explicit when needed

Estimate: 16 hours

**Comment by Dschoordsch** [comment]
I reviewed
* addFeatureFlag
* addNewFeature
* addTeamIdToTMS
* adjustUserCount
* bootstrapNewUser
* connectSocket
* deleteUser
* dismissNewFeature
* emailPasswordReset
* flagOverLimit
* helper/updateUserProfile
* loginSAML
* loginWithGoogle
* payLater
* removeTeamMember
* resetPassword
* safeArchiveTeam
* signUpWithPassword
* updateEmail
* updateWatchlist
* verifyEmail

Most of these don't write to Redis anymore since #5723. Therfore I compared the current PG writes with the pre-PR Redis writes.

Findings:
* dismissNewFeature does not update the updatedAt field anymore
* addFeatureFlag, payLater and removeTeamMember never updated the updatedAt field

**Comment by Dschoordsch** [comment]
@mattkrick I don't see the difference between PG and Rethink in the example in the ticket description, both update only 2 fields
https://github.com/ParabolInc/parabol/blob/7a0c2031dc2ce8b82ce31aeaa6e5c8d4ab2e7fe4/packages/server/billing/helpers/adjustUserCount.ts#L53-L56

I propose adding `updatedAt` to the 4 mutations mentioned above and then consider this resolved.

**Comment by mattkrick** [comment]
**Story Points: 21**
  [See the discussion](https://action.parabol.co/meet/8Kr615RAwE/estimate/10) in Sprint Poker #​​9

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
