### ISSUE TITLE
RelayNetwork: No data returned for operation `MyDashboardTimelineQuery`, got error(s):

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#5439]
Affected 7 users the last 8 days

https://sentry.io/organizations/parabol/issues/2660534760/?referrer=github_plugin

```
RelayNetwork: No data returned for operation `MyDashboardTimelineQuery`, got error(s):
Server error

See the error `source` property for more information.
  at Array.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
  at Set.forEach (<anonymous>)
...
(23 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
@mattkrick says, "this is ye old timeout problem." See issue #5406

**Comment by jordanh** [comment]
In addition to the above we need to understand _why_ these queries are taking so long to execute. That is no bueno

**Comment by jordanh** [comment]
Turns out, this still happens. Keeping it open as it is rather bad

**Comment by jordanh** [comment]
Wow. Still bad. Elevating in priority

**Comment by mattkrick** [comment]
Impersonated & attempted to reproduce the last few events of this issue. Couldn't reproduce. That tells me it's not necessarily a data integrity issue, but rather something with the infrastructure. Since infra is going to change in the next couple months I figure I'll revisit then & see if this is still an issue.

**Comment by jordanh** [comment]
Shall we close this one as Won't Fix then?
