### ISSUE TITLE
Removing people from teams and orgs not working properly 

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#5527]
A [user](https://app.hubspot.com/contacts/3888472/contact/16076401) 🔒  cannot remove people from his team or his org. 

> I am seeing a discrepancy between the lists of organizations members, and I need help resolving this and ensuring only the correct people are included in the team.
> 
> I have two organizations on the Parabol site, and in one of them we’ve had some team members leave and I need to update that list. When I select the “Manage Team” link on the organization page (that shows the task cards), I am able to remove the people who are no longer part of the team. However, when I go to the Organization details page and select the Members tab (next to the Billing tab), I see a different list of people that includes the people I removed on the prior screen. And when I select the Remove from Organization option on that screen, it prompts me to confirm, but when I do that nothing changes.
> 
> Please let me know the correct way to remove team members, and to ensure they are actually removed.
> 

Hubspot ticket [here](https://app.hubspot.com/contacts/3888472/ticket/609503509) 🔒

**Comment by tianrunhe** [comment]
> When I select the “Manage Team” link on the organization page (that shows the task cards), I am able to remove the people who are no longer part of the team.

^ Here he removed members from the team but those members could still be in other teams, that's why:

> I see a different list of people that includes the people I removed on the prior screen

Now, removing the member from organization **is** the correct way to completely remove members from all of the teams. The fact he saw nothing changed smelled like the incident we encountered this morning (I checked the timestamp he cut us tickets, seemed match too).

We should:

1.  confirm the customer the correct way to remove members, i.e., remove from the organization in the org page
2.  ask for emails of the members he'd like to remove and we could check if they are actually removed from our side

**Comment by jordanh** [comment]
Scrubbing this today.

This seems like an issue where Parabol is "working as designed" and for today we need to better explain the difference between a User on a Team and a User on an Organization. @drewhousman1010 do you agree?

Long term, we can implement enhancements such as #5669 to make this distinction even more clear.

If we're good for now, I'd like to close this Issue. Would that be ok?

**Comment by drewhousman1010** [comment]
@jordanh yeah that makes sense! Totally okay to close. I'm looking forward to #5669 😀

**Comment by tianrunhe** [comment]
Closing in favor of #5669
