### ISSUE TITLE
Link Parabol task with already existing GitHub / Jira issue

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5535]
## Issue - Enhancement

Currently, we can only create new GitHub / Jira issues. There should be a way to link Parabol task with the already existing GitHub / Jira issue.
Related conversation: https://parabol.slack.com/archives/C836NA350/p1634140455441800 

### Acceptance Criteria (optional)

- [ ] User can link Parabol task with existing GitHub / Jira issue

### Estimated effort
- 4 hrs for design explorations

**Comment by enriquesanchez** [comment]
I started exploring this concept and it occurred to me that we may have a broader use case if we instead think of this as "attachments".

I can start by attaching a Github issue to a task, for now—but maybe later on we add the ability to attach documents, images, etc. The mental model is a bit different than the one of linking, but it would open a whole lot more possibilities down the line.

I think this feature will play very nicely with what we have already explored around task details on #5063.

How does that sound to you, @BartoszJarocki and @jordanh?

**Comment by enriquesanchez** [comment]
Here's a mockup of what I've been exploring:

![imagen](https://user-images.githubusercontent.com/3276087/150234401-96f94534-8dd8-489d-a248-6798e2756638.png)

When a user pastes a link, we can prompt them to paste as link (regular text), or paste as an attachment, which in turn shows a more visual representation of the link's contents, like an embed.

If the user has added the respective integration, the embed will show richer and up to date info, like in the example above. Otherwise we show a more limited view:

![imagen](https://user-images.githubusercontent.com/3276087/150234242-41e974ce-6769-4219-88c7-d41f01d5987c.png)


We can decide which links we want to support, based on the integrations we support. That said, we don't have to limit these rich embeds to integrations. I imagine we can have rich embeds for things such as Loom videos, websites, etc.

**Comment by enriquesanchez** [comment]
A few ideas of how other types of URL-based attachments could look:

<img width="1422" alt="Captura de Pantalla 2022-01-20 a la(s) 4 16 33 p m" src="https://user-images.githubusercontent.com/3276087/150430938-ac379fa6-0705-4cff-8c1d-89cfd4b9091c.png">

**Comment by enriquesanchez** [comment]
Removing attachments and handling when more than one are added to a task:

<img width="1028" alt="Captura de Pantalla 2022-01-20 a la(s) 4 17 16 p m" src="https://user-images.githubusercontent.com/3276087/150431079-5953ab3c-bce7-432d-8532-5e32cb8d86a4.png">

**Comment by enriquesanchez** [comment]
Closing in favor of #5942.

@BartoszJarocki Feel free to reopen or add any additional comments or feedback you may have to #5942.
