### ISSUE TITLE
Newly created task not shown up with "All Teams" menu item selected

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#5573]
## Issue - Bug

Repo steps:
1. Go to [Tasks](https://action.parabol.co/me/tasks) page
2. Select a team from the team menu dropdown (by default it should show "All Teams")
3. Create a task for that team
4. Switch back to "All Teams" and observe that the newly created task is absent (a refresh would resolve this)

### Acceptance Criteria (optional)
Users can:
- [ ] see newly created tasks on Tasks page with "All Teams" selected for the team menu dropdown

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by RiyaNegi** [comment]
Hey I think I was able to identify the root cause of the issue. In the `UserColumnsContainer` component the GraphQL query on line 18 doesn't seem to return the right value. It always returns just the first task in the column, but on refreshing it will return all the tasks properly. @mattkrick

**Comment by Dschoordsch** [comment]
@RiyaNegi thanks for looking into it. You're right, the issue appears to be in that fragment. It does not update when a task is created. When you return to all teams filter, it will return what's in the relay cache. It appears as if we're not updating the relay cache properly after the mutation.

One note: we send out `taskSubscription` updates to other team members notifying about the change. The update logic there probably handles modifying the cache. The initiator of the change does not get those notifications though. That's probably intentional, but means we need to handle the cache update in the `createTask` mutation in the client.
