### ISSUE TITLE
User profile: Designed how to manage email and password

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5632]
This came up again in [User feedback retro 9](https://action.parabol.co/meet/7FSaKTbRdK/discuss/1). We opened 1 discussion item for each request: [folks want to change their email](https://github.com/ParabolInc/parabol/discussions/5630) and [folks report trouble resetting password](https://github.com/ParabolInc/parabol/discussions/5631).

Here it’d be great to see a fresh take on a user’s profile view `/me/profile` showing how they might change their email and reset their password.

### Acceptance criteria
- Designed a user’s profile view concept showing how folks can:
  - Update their avatar
  - Update their name
  - Change email
  - Reset password
  - Delete account
- Drafted 1 or many implementation issues and reviewed with a developer
- Not included:
  - How folks may be required to verify their email
  
### Estimated effort
- 8 hours

**Comment by gcrickman** [comment]
➕ for users being able to change their email in Parabol. I needed to do it for all of the users [this](https://app.hubspot.com/contacts/3888472/deal/5430962325) account 🔒 so they could switch to using SSO.

**Comment by drewhousman1010** [comment]
I had to change all email accounts when [this customer ](https://app.hubspot.com/contacts/3888472/company/3372192683) 🔒 was bought by [this company](https://app.hubspot.com/contacts/3888472/company/7303612031).

**Comment by gcrickman** [comment]
This [user](https://app.hubspot.com/contacts/3888472/contact/58425001) 🔒 requested to have their email changed.

**Comment by drewhousman1010** [comment]
Another [user](https://app.hubspot.com/contacts/3888472/contact/10839501) wrote in having trouble resetting their password:

> Hi,
> 
> This has happened before. I’m sure it will happen again.  Parabol won’t let me log in. And when I try to reset my password and click the link to have the email sent, I get a message that says "h no! Something went wrong. Try again or contact us.”
> 
> I don’t know what’s going on, but… help?

**Comment by drewhousman1010** [comment]
This [user ](https://app.hubspot.com/contacts/3888472/contact/70602151) 🔒 requested to have their email changed.

**Comment by avivapinchas** [comment]
**Value: 3**
  [See the discussion](https://action.parabol.co/meet/dHOSUUpFO8/estimate/17) in Sprint Poker #​​1

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by mattkrick** [comment]
From an IA standpoint, it'd be great to have an "Identities" section. An "Identity" is something like Google OAuth, Email/password, or SAML.

If they have an email/password identity, then we show that under the identities section.
If they haven't integrated with gmail, we allow them to add a google identity so they can log in with that instead of using email/password. (out of scope for now, but this is what most large saas tools do)

for security reasons, i'd like to remove the change password section. it's not enough to know the old password, chances are that password already exists on the darkweb. we want them to prove that they have access to the email address they provided. 

i'd propose the following (with better copy 😜):
- A link that says "click here to get a change password email"
- They get an email saying "Click here to change your password"
- It takes them to a page that asks them to type their new password

This is the exact flow that we use when they click "forgot password" so we won't have to build anything new on the backend.

PS
also under the email/password identity section, we can have a link that says "Verify email" if their email is not verified. The backend is already built to support this, we just have to add the button 🎉

**Comment by mattkrick** [comment]
any email provider, they just have to click a magic link that only exists in their inbox

**Comment by ackernaut** [comment]
@mattkrick 
- When they click to reset password, does it open to the current reset password page in a new tab?
- When they click verify email address, what happens? Do we say ’check your email and click the link’ inline or with a snackbar?

**Comment by ackernaut** [comment]
@mattkrick here’s [a quick exploration](https://www.figma.com/file/2Nj1y1KUfE2swHZuDY5Zxn/My-User-Account-Management?node-id=2%3A5) in Figma

**Comment by mattkrick** [comment]
> When they click to reset password, does it open to the current reset password page in a new tab?

nope, just sends an email

> When they click verify email address, what happens? Do we say ’check your email and click the link’ inline or with a snackbar?

i'd say inline, always nice to know what part of the app triggered the message 🙂

**Comment by jordanh** [comment]
Going to keep this one open

**Comment by jordanh** [comment]
I am sure this one will come back around
