### ISSUE TITLE
Designed: new meeting dialog supports stand-up v1

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5638]
We’ve got an MVP for the new meeting dialog #5589 but when we ship a v1 stand-up (roughly starting the scope here #5609) we’ll need proposals for how to present the UI for the nuanced settings (i.e. recurring, chat notifications).

### Acceptance criteria
- Updated the new meeting concept to show the view for opening a stand-up
- Shows how to update the single prompt
- Shows how to set one-time activity or recurring
- Shows how to set chat notifications
- Shows the different possible states

### Estimated effort
- 21 hours

**Comment by enriquesanchez** [comment]
### Updated the new meeting concept to show the view for opening a stand-up
![imagen](https://user-images.githubusercontent.com/3276087/146616408-19761dc2-743e-4f49-ac26-e199ff86e774.png)

A new meeting type for stand-ups is available on the meeting type selector. This will increase the number of meeting types from 3 to 4, requiring for us to introduce a sliding carousel pattern. (Related #5605).

When the stand-up type is selected above, the options below change to reflect the available settings.

- Instead of a template selector we have a prompt option.
- Instead of an Icebreaker option we have the Repeats settings.

### Shows how to update the single prompt

Clicking on the prompt opens a sliding sub-view:

![imagen](https://user-images.githubusercontent.com/3276087/146617240-a5373a36-cb0f-4382-b3be-8c76f748f5ef.png)

Here users can edit the prompt or select from any of the suggested alternatives below.

### Shows how to set one-time activity or recurring and how to set chat notifications

![imagen](https://user-images.githubusercontent.com/3276087/146616794-77d1607d-56ba-48f3-939a-f8a39bce5fb5.png)

When clicking on the Repeat options, a new sliding sub-view shows the settings for recurrence and notifications.

- Users can select the days of the week when the activity repeats, and below that a little summary clarifies what will happen.
- On the right side, users can select on which channel (if they have the Slack integration) the reminders will show up, and the time, as well as the time for the summary.
- Both the recurrence and notifications options can be turned off.

![imagen](https://user-images.githubusercontent.com/3276087/146617155-aef3fad9-a571-491c-9a22-d20987717bf6.png)

![imagen](https://user-images.githubusercontent.com/3276087/146617100-836d65b7-bc09-4682-b1d5-c73b4895e755.png)

### Shows the different possible states

In the case a prompt is long string of text, we'll need to truncate the text in the main view:

![imagen](https://user-images.githubusercontent.com/3276087/146617315-29b3d842-a4eb-48f8-bb49-a450a02a1a70.png)

![imagen](https://user-images.githubusercontent.com/3276087/146617337-198dda31-0391-4298-bca9-1bbb9c37b261.png)


## Next steps

- [ ] This issue requires #5589 to be done
- [ ] We need the help of a developer to scope the technical implementation (Related #5609)

**Comment by ackernaut** [comment]
This is excellent work!! Consider it reviewed by me and ready to mark as done/closed 🙌 

A few thoughts moving forward:
- It’d be great to see #5589 ship sooner than later but I think we can decouple starting to build the stand-up from needing this view
- I drafted [milestone 122](https://github.com/ParabolInc/parabol/milestone/122) to allow us to test starting stand-ups from the existing starting view
- I think as we build and design the new stand-up settings controls (per your designs), they can be added to that temporary beta view on the existing start meeting view to enable building and trying the settings. For example, they may build the un-styled controls first and add those to that feature flagged view. Then we can style them. Then we can reuse them. We can cross that bridge when and if we take that approach (see last bullet)
- If we get to any nuanced states, like errors for the prompt field, etc. you can provide some additional, light design support for the implementation issues
- Later those controls can be added to the start meeting dialog, if we don’t get there sooner or along a different path I’ve got a placeholder for a milestone to do this #5801
