### ISSUE TITLE
Atlassian Integration - Error: Unauthorized

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5690]
Affected 81 users in a couple of days, happened more than 1.5k times
We should double check if our token refresh mechanism works correctly

https://sentry.io/organizations/parabol/issues/2563520365/?referrer=github_plugin

```
Error: Unauthorized
  File "./packages/client/utils/AtlassianManager.ts", line 314, in p.get
    return new Error(json.message)
  ?, in runMicrotasks
  File "./packages/client/utils/AtlassianManager.ts", line 548, in async p.getIssue
    const issueRes = await this.get
```

**Comment by mattkrick** [comment]
Happening 2000x/day, this is borderline hotfix territory

**Comment by tianrunhe** [comment]
I think the issue is on `refreshToken`. Atlassian returned `invalid_grant` error on refresh:

```
Error: invalid_grant
    at Function.fetchToken (/Users/brucetian/Projects/parabol/dev/gqlExecutor.js:65349:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/brucetian/Projects/parabol/dev/gqlExecutor.js:58205:30
```

According to Atlassian's doc:

> Your app is using rotating refresh tokens, but the app is not replacing the existing refresh token with the new refresh token returned.

What I suspect is on `atlassianLoaders.ts` -> `freshAtlassianAuth`, where we get a new access token and write it into DB, but in the end we [still return the old access token](https://github.com/ParabolInc/parabol/blob/master/packages/server/dataloader/atlassianLoaders.ts#L68) (notice the variable `atlassianAuthToRefresh` was originally read from DB but never changes in the scope)? I didn't look into this part of code close enough but it'd be where I start.

**Comment by BartoszJarocki** [comment]
I reproduced the issue locally
```
ℹ ｢wdm｣: Compiled successfully.
🔥🔥🔥 Ready for Sockets: Port 3001 🔥🔥🔥

💧💧💧 Ready for GraphQL Execution: 2 💧💧💧
SEND TO SENTRY Error: Unauthorized
    at AtlassianServerManager.get (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:80595:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AtlassianServerManager.getIssue (/Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:80863:22)
    at async /Users/bjarocki/Work/parabol/web-parabol/dev/gqlExecutor.js:58266:28 {"cloudId":"5bf7b2f4-cec7-4f8a-85f3-5643792a9052","issueKey":"PAR-7","teamId":"8VJPIMJ5aF"}
```
It happens when the token is stale, we refresh it successfully but we return the old one from the data loader. As a result, the task that was previously integrated is showing as a normal Parabol task. After refreshing, or navigating somewhere and back to the tasks, the user will see the correctly integrated task. It's still important to fix, it's not as critical as I thought though. 

@tianrunhe great work on figuring out what's wrong, thank you!
