### ISSUE TITLE
Change iconology for delete on reflections

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#5692]
The icon used to delete a reflection is typical the icon used to close open items. Would a trash/garbage icon be a better choice of icon?

Concern with current icon (X) is accidently deleting the reflection.

Potential A/C

- [ ] Change icon from X to  trash/garbage icon

![image](https://user-images.githubusercontent.com/71724289/142679209-fd63c43a-3107-46fb-9cb7-527375326616.png)

- Estimated effort
- 3 hours

**Comment by ackernaut** [comment]
I took a first look at this:
- The delete icon may throw folks off during the Reflect phase, [they may mistake it for closing the dialog](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=106%3A730)
- During the Group phase, I will see the delete icon only if I tap into the content to edit my reflection. I can’t delete or edit others. The search icon appears on hover. If I’m editing [both the delete and search buttons are very close](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=106%3A731) for a 1 line card
- Not sure where to go with it just giving an update, [here’s the latest in Figma](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=106%3A489)

**Comment by ackernaut** [comment]
Here are some options:

1) [Just add a UI tooltip for now](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=117%3A1227)
2) [Hang a new button in the upper-right](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=117%3A1229)
3) [Stick an icon bar in the upper-right](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=117%3A1230) if the label is filling the left space via #5776

**Note**: the current behavior is that the search icon appears when hovering the card in the Group phase, and the delete icon appears when I tap into one of my cards to edit it during the Reflect and Group phases.

Thoughts @Dschoordsch @adaniels-parabol @enriquesanchez ?

**Comment by Dschoordsch** [comment]
@ackernaut I offer a 4th alternative, but still favour 2. because it's less work
1. adding a tooltip feels like a band-aid and doesn't solve it for mobile users
2. it's the simplest after 1. and resolves the issue at hand
3. adding actions at the end of cards feels more natural to me because it follows reading order and the button balances the group corner.
4. If we want to have the design more consistent and since we're only showing the button when editing, how about adding a bottom row in this case and put (trash)(spotlight) there, so spotlight stays bottom right? Delete should go there in reflect phase as well in this case.

**Comment by enriquesanchez** [comment]
> Just add a UI tooltip for now

The tooltip should be there regardless, but I agree that it's not a real solution, as Georg mentions.

> Hang a new button in the upper-right

This takes care of any potential confusion, but at that size I feel it's more distracting than helpful. While we can get away with a smaller X icon, I don't feel that's the case with the trash icon.

>

**Comment by Dschoordsch** [comment]
> > Hang a new button in the upper-right
> 
> This takes care of any potential confusion, but at that size I feel it's more distracting than helpful. While we can get away with a smaller X icon, I don't feel that's the case with the trash icon.
> 
I don't think it's a big issue to make the button bigger since it is not shown most of the time.

**Comment by ackernaut** [comment]
I want to get to next steps here. Thanks for all the questions and comments.

- Regarding the (x) icon. I agree with Enrique to a degree. It does seem to be a common pattern. However I think there may be a nuance about nesting objects here. Typically an X on a dialog (e.g. google calendar item) has meant to close an object. An X on an embedded component that is just part of the larger whole means it is removed. It’s not clear in our case. Am I closing it or removing it?
- I’m not sure this is eating our lunch. For this reason I think we could leave it as is until we suss out any other reflection card design concerns:
  - How will we resolve the upper left label design work?
  - I think an upper right bar is probably a better use of space than a lower right bar. We have concern about the growing height of the card. Using the upper space for both the label and the button needs seems more reasonable.
  - I don’t want the card to start looking like a task card
  - If we ever make it so that a card (driving reflections, comments, responses) can optionally be non-anonymous, where might we include information about the author on the card, if it needs to be on the card? Will we use an avatar, a name, both?
  - I will say it’s nice to keep the cards feeling light, minimal, and focused on the content so however we can achieve that is great
- My suggested next steps:
  - Do nothing yet (see bullet 2) or open an implementation issue [for this option](https://www.figma.com/file/sp3B3eQjrGKBS2tayJmlwY/Reflection-Card?node-id=117%3A1229) but I’ll let @Dschoordsch decide what next design he thinks we should implement, if any, and therefore open an issue pointing back to this
  - Meanwhile, let’s decide how we may want to resolve card hierarchy including label changes, making use of a proper icon button bar, and then as a stretch thinking about how comment cards may include author info (note: Enrique has also worked on how cards may included embedded and integrated attachments). Can this happen on reflections? Prompt responses? Thread comments? Task cards? I’d like @enriquesanchez to think about if he wants to pursue these questions, and how to break down that work into our backlog
  
Let me know if you need anything here.
  
  PS. example google cal item
  
![Screen Shot 2022-03-01 at 12 21 36](https://user-images.githubusercontent.com/307286/156227765-a23f8644-40d4-4453-bc7a-12d56e5b838a.png)
