### ISSUE TITLE
Sprint Poker not updating fields for Jira bug issue type

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#5705]
## Issue - Bug

A [customer](https://app.hubspot.com/contacts/3888472/contact/28771551) 🔒 reported the story points field in Jira on bug issue types was not updating.

I was able to reproduce the issue where Original estimate was not updating on a bug issue type. I did get the error message when I clicked 'update' and the 'fix it for me' window popped up but it timed out when I tried to give access to my Jira. You can see in the screenshot below that the original estimate field did exist for that issue type.

<img width="1214" alt="Screen Shot 2021-11-22 at 4 59 52 PM" src="https://user-images.githubusercontent.com/60167404/143056432-e2b53ab3-3b8f-4632-acaf-c06e1dfffbfa.png">

![Screen Shot 2021-11-22 at 4 59 41 PM](https://user-images.githubusercontent.com/60167404/143056863-64c79a16-7d9a-49c1-85d5-959dc3184ae9.png)

**Comment by BartoszJarocki** [comment]
This seems to be an old bug (or rather a missing implementation, depending on the perspective).

The `timeoriginalestimate` field depends on having `Time Tracking` field added to the issue fields. 
This means that if we want to update `timeoriginalestimate` through API, `Time Tracking` has to be added to the issue fields. See the screen below: 
![Projects  Bartosz's test project  Project settings  Issue types](https://user-images.githubusercontent.com/1017620/148566409-933e1800-e705-4c46-95d1-ca6b88123168.png)

If the issue has `Original estimate` field added but there’s no `Time tracking` field added (I’m pretty sure that’s the case in the reported issue), updating this field via API will fail with
``` Error: timetracking: Field 'timetracking' cannot be set. It is not on the appropriate screen, or unknown. ```
What’s more, to be able to update any of these fields, the [Jira API call](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-put) has to be a bit different 
Instead of having this
```
      const payload = {
        fields: {
          [fieldId]: storyPoints
        }
      }
```
We need to build it like this
```
      const payload = {
        update: {
          timetracking: [
            {
              edit: {
                originalEstimate: storyPoints 
              }
            }
          ]
        }
      }
```
So, basically the shape of the body will have to depend on the selected field. Another interesting fact is that if chooses, for example, 21 as a final result in Parabol, it’ll update the `Original Estimate` to `21m` ie. 21 minutes. To treat it as hours, we’d need to format is as 
```
      payload = {
        update: {
          timetracking: [
            {
              edit: {
                originalEstimate: `${storyPoints}h`
              }
            }
          ]
        }
      }
``` 
when calling the Jira API.

The same rules apply to `timeremaningestimate`, but the Jira itself makes it way harder to add the field to the issue screen, even with their own UI.

Possible solutions
1. Special treatment of `timeoriginalestimate` and `timeremaningestimate` fields
  a. Add custom handling of `timeoriginalestimate` and `timeremaningestimate` in `setTaskEstimate` mutation (ie. different shapes of body)
  b. Add custom handling of `timeoriginalestimate` and `timeremaningestimate` in `addMissingJiraField` mutation (ie. if `timeoriginalestimate` is missing, we also need to add `timetracking` field, otherwise it won’t work anyway)
  c. Properly format the input data, instead of sending just a number, use `${storyPoints}h` as I guess that’s the most desirable input

2. Remove `timeoriginalestimate` and `timeremaningestimate` from the list (not really a solution as it seems like some teams are using these fields)

@mattkrick please let me know if I should proceed and add a special treatment of these fields. If it's still not clear, we can sync or I can record a loom, just let me know. thanks!

**Comment by mattkrick** [comment]
holy dumpster fires what a wonderful API. thank you so much for digging into this & finding out why!

I think you solution is really solid.
Let's break it into 2 issues: fixing setTaskEstimate and fixing addMissingJiraField. Then you only have to tackle the first part for now. 

Since the problem is between us & Atlassian, I'd suggest that the fix exists in the `AtlassianServerManager.updateStoryPoints`. We could add the additional `fieldName` param to the method perhaps? One gotcha is the `fieldName` might be the display name, not the time tracking name (e.g. Original Time Estimate v. timeoriginalestimate), we'd have to explore that more. just put a conditional in there looking for those 2 field names & if they match, make sure the input is a number, then turn it into string with an `h` suffix, and adjust the body accordingly.

Great work!
