### ISSUE TITLE
Allow for specific URL in new release snack bar

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#5742]
## Issue - Enhancement

For most releases, the changelog is the best spot to see what's new. 

For larger updates, we write a[ blog post announcing the feature](https://www.parabol.co/blog/tag/new-features), which includes more detail on what's changed. In those cases, it would be nice to be able to include a link to the blog post in the 'new release' snack bar notification, so users get the best info about what's changed and why it matters. 

Per @adaniels-parabol, to do this, we would need to update this line of code to be changed to a ENV var that would get updated each release: 
https://github.com/ParabolInc/parabol/blob/master/packages/client/hooks/useServiceWorkerUpdater.ts#L25

### Acceptance Criteria (optional)
When new releases are shipped, users can see a link to an announcement blog post for new features, rather than a changelog link. 

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by nickoferrall** [comment]
Ahh great idea! @avivapinchas we could also change the `A new version of Parabol is available 🎉` line if you like?

So instead of `A new version of Parabol is available 🎉` `See what's changed`, it could be `Parabol has launched a new feature called Spotlight 🔍 ` `Check it out` with `Check it out` hyperlinked to the blog post?

**Comment by avivapinchas** [comment]
I really like that!

In general for copy, I like to avoid any jargon or terms that don't already have a definition - meaning we know what Spotlight means, but it doesn't mean anything to customers yet. 

So I'd suggest: 
> Finding the right reflection in the Grouping phase is now easier! 🔍  Learn how 

Or something like that. 🤔  We can probably make writing this part of the marketing process when leading up to a launch

**Comment by nickoferrall** [comment]
Makes sense! I'll check in with you and Gareth before updating this ahead of the launch 👍

**Comment by nickoferrall** [comment]
In the check-in meeting, I mentioned that it would be nice to ship the PR linked to this issue before moving Spotlight to general release. I now realise that we can actually ship Spotlight before this issue is fixed as we won't want to customise the snack bar until the blog is shared in January.

**Comment by avivapinchas** [comment]
@nickoferrall Once this ships, how would a team member on the Growth team define the copy and URL for the snackbar?

**Comment by nickoferrall** [comment]
@avivapinchas a Growth team member would need to let a dev on the Product team know what the release message should be, and the dev can then update the env variables with the message. [See here](https://www.notion.so/parabol/Release-Playbook-c3d1b146ea7c4f2fbf9501ae578ced25#d72b2f5c710943ca930d8d2dcdb817e1) for more info on how a dev would do that.

If you have a message in mind, I'd be happy to add it once the PR has been merged? Would [this](https://www.parabol.co/blog/search-retrospective-reflections-for-better-grouping) blog post be the one we would link to?

@mattkrick if you get the chance, it would be great if you could review this small PR (https://github.com/ParabolInc/parabol/pull/5743) so that we can announce the Spotlight feature in the next release.

**Comment by lorena-cure** [comment]
@nickoferrall 
Is there a possibility to know how this looks? I don't know if I should have a character limit or something for the copy.

The message I have in mind is something along the lines of:

> :new: Find and group similar reflections more quickly and easily. :mag: Learn how

Yes, [this](https://www.parabol.co/blog/search-retrospective-reflections-for-better-grouping) is the blog post we would link it to.

I would like to push this live for the week of the 17th of January, **is this doable?** 
I would like to release the email, notification, and this in the same week so we are a bit repetitive and people have it on their top of mind and use it.

Let me know your thoughts and thanksss :)

**Comment by nickoferrall** [comment]
@lorena-cure sure thing! Currently, the snackbar pops up the first time someone uses Parabol after we've released a new version, which usually happens every Wednesday. This is what it normally looks like:

![release-snackbar](https://user-images.githubusercontent.com/39854876/148435092-b7869c19-0b8d-42f2-acb0-7fc2f7361889.png)

Here is what it would look like with the suggested text:

![suggested-text](https://user-images.githubusercontent.com/39854876/148435399-f8113779-493f-459e-bf5d-f5e06be04a4e.png)

When using emojis at the beginning of the text, the spacing can look a little funky. How does this look to you?

![emojis-adjusted](https://user-images.githubusercontent.com/39854876/148435760-f1932514-f500-4044-9216-1084d0371ed6.png)

> I would like to push this live for the week of the 17th of January, is this doable?

That should be fine. Matt will need to review the PR before it's merged and he's away next week at the retreat. I'll work on the PR today and ping Matt requesting a re-review and letting him know we'd like it ready for the week of the 17th.
 
I mentioned to Aviva in [this comment](https://github.com/ParabolInc/parabol/issues/5742#issuecomment-1005060022) that a developer will update the env variables with the changes the Growth team wish to make. However, Matt left a comment on the PR [here](https://github.com/ParabolInc/parabol/pull/5743#pullrequestreview-845954877) suggesting that we can refactor how this works so that we would use a GraphQL mutation instead which a Growth team member could use (I'll write up a Notion doc with an example).

The way this would work is a Growth/Product team member would execute the GraphQL mutation which would include the desired copy & blog URL, and the snackbar would then pop up with the message until the user closes the snackbar. 

Are there any other business requirements or does that plan sound good to you?

**Comment by lorena-cure** [comment]
@nickoferrall thank you so much, this is very helpful!

- The emoji looks weird, you're right. I like your second version better :)
- Regarding the date, it doesn't have to be live exactly on the 17th, if it's delayed some days it's totally fine, don't worry.
- Thanks for the context on how it would work in the future, sounds great!

No other requirements on my end, everything sounds great 🙌🏻

**Comment by nickoferrall** [comment]
Perfect, thanks for letting me know! 

I've just pushed that update to the PR and mentioned that we'd like to have it ready for the week of the 17th. I'll let you know once it's merged and ready to be used!
