### ISSUE TITLE
Postgres connection issues

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#5759]
We had a brief outage that was fixed by restarting the web container.

Logs around that incident indicate we had some issues with postrgres connection

https://app.datadoghq.com/logs?query=host%3Aaction-production-web-nyc1-02&cols=host%2Cservice&event=AQAAAX2f-omc8xIpIwAAAABBWDJmLW9tdEFBRHl4Sjg5azU3TTNBQUE&index=%2A&messageDisplay=inline&stream_sort=desc&from_ts=1639066042595&to_ts=1639066942595&live=true

https://app.datadoghq.com/logs?query=host%3Aaction-production-web-nyc1-02&cols=host%2Cservice&event=AQAAAX2f-opC8xIqqQAAAABBWDJmLW9wWUFBRHl4Sjg5azU3WVVBQUE&index=%2A&messageDisplay=inline&stream_sort=desc&from_ts=1639065867476&to_ts=1639066767476&live=true

**Estimated effort:** 4 hour to triage. More if root cause is already identified.

**Comment by Dschoordsch** [comment]
The message matches with Datadog.
![Screenshot from 2021-12-09 17-29-03](https://user-images.githubusercontent.com/7331043/145436682-b28cfed7-d827-4d72-a3fe-f6805734fc02.png)

I think this spike of connections is related to the restart itself. I logged in around 11:13:09 EST and shortly after restarted. Since the outage started at 11:06 the issue is probably something different. Doesn't mean we shouldn't investigate, but it wasn't the cause of the outage.

**Comment by adaniels-parabol** [comment]
The outage appears to be related to redis. I put some more notes here under Notion outage page. The postgres issue looks like a red herring

**Comment by jordanh** [comment]
I am going to leave this on the `To Prioritize` list to discuss if we need to add to the next sprint. Else, please close

**Comment by jordanh** [comment]
We discussed during sprint pre-planning. We think this is safe to close. We will re-open if/when this happens again
