### ISSUE TITLE
Minimal stand-up experience architecture spec'd

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#5787]
Issue #5609 includes the details for a full end-to-end experience for standup. No doubt, we can refine this further to give us confidence to begin development. What we need is a spec and associated issues we are confident to begin building.

## AC
   - Reviewed extant stand-up designs
   - New GitHub or Notion page created
      - outlining definition of a broader experience (i.e. something too big to build) (#5609)
      - subset of above selected for implementation behind a feature flag (i.e. private beta)
   - Reviewed @ackernaut as Principal designer to capture intent
   - Reviewed with one other Product team member in Developer role (for feasibility)
   - Reviewed with Maintainer

**Comment by ackernaut** [comment]
I have questions and notes to contribute above, as I have spent some time with the overall concept of this activity, but just adding the placeholder issue for now. I’ll get back to add my thoughts when I can, but don’t want to block this from others pushing it forward.

**Comment by ackernaut** [comment]
Here I imagine a developer leading the discussion, inviting developers to join, processing decisions, and documenting so that the various components can be built out following the guiding high-level direction that is documented

**Comment by igorlesnenko** [comment]
I tried to draft the issue description and added some questions. Please let me know if this is the correct approach to write these. I tried to summarize what to include in the schema and API and what not to include.

## Background

- [Proposal](https://www.loom.com/share/449bb7e2934541d190635e602c1444c6) (Loom)
- [Prototype](https://www.figma.com/proto/bhiEOV4HK9Kv91HFsJmevV/Stand-up-Concepts?page-id=653%3A23925&node-id=795%3A45934&viewport=501%2C48%2C1&scaling=scale-down&starting-point-node-id=795%3A45934) (Figma)

## Scope

We need to define the database schema, types and the API for the following functionality:

**Team prompt activity**

- Start mutation
- Complete mutation
- Delete mutation
- Cancel series mutation (Closes current activity, and no future activities will be opened)
- Update mutation

**Fields:** 

- Team ID
- Activity name
- Prompt (Activity have a single phase, prompt belongs to a phase)
- Recurrence and integration settings:
    - Repeat (`repeat` or `prompt once`. Could be boolean)
    - Days (Multi-select: Mon, Tue etc.)
    - Time zone (e.g. UTC -8)
    - `Notify team in slack`. Boolean checkbox and sack channel dropdown
    - Send reminder time (e.g. 9:00 am — dropdown similar to timer in retro)
    - Share summary at (same as above)

For navigation, the API should be able to return:
 - Next activity
 - Previous activity

For date picker navigation it should be possible to fetch a list of activities for the specific month.

**Responses**

- CRUD mutations for responses
- Reaction mutations
- One activity could have multiple responses
- By default, responses are sorted so that the last responses come first 
- Responses are not anonymous and they have an author id, content and reactions (similar to reflections)
- For recurring activities, for each participant we need to show his last response date in previous meeting he participated.

**Replies**

- CRUD mutations for replies
- Each response can have a reply
- Replies are sorted by date by default
- A task could be created as a reply
- Response card can show number of replies

## Not in the scope

Separate issues would be created for:

- Work activity sidebar API
- Recurrence approach (cron or something)
- Notifications

## Additional notes

- For example, I created a standup at `Monday, 9:00, GMT+5`. In `GMT-8` it would be `23:00` of the previous day. But in the calendar picker we still should show the activity on Monday not relative to timezone.

## **Questions**

- Storing timezone as a number (e.g. -8) will not handle summer/winter time change automatically. Is it OK? Alternative approach is to use names e.g. `Europe/Paris` (see **[pg_timezone_names](https://www.postgresql.org/docs/current/view-pg-timezone-names.html)**)
- Should we consider possibility of adding multiple prompts when designing the architecture? 
- Should we store prompt as plain text? draftjs format?
- Any additional actions should be taken to consider mattermost here?

**Comment by Dschoordsch** [comment]
@ackernaut do I understand correctly that we want to have the architecture defined for the whole v1 standup experience, while the milestone is only about ["New activity type created"](https://github.com/ParabolInc/parabol/issues/5609#issuecomment-995025376)?
The architecture should in that case also be split into steps matching the smaller iterations.

@igorlesnenko I learned that architecture should include everything that's expensive to change later, thus we should also define the component tree (somewhat) to avoid having to do too much refactoring there.

**Comment by ackernaut** [comment]
@igorlesnenko and @Dschoordsch 

I realize I’m very late in replying to you both, as I was out for a bit and away for a team retreat. Sorry!

@igorlesnenko I really like how you bulleted out the specs around the experience. Nice work! I think as we take on each set of components and interactions, we can work out the finer details.

@Dschoordsch I think you’re right, we should take on the next bit of architecture as we build what it represents

Where my thoughts go back to our overall approach to building iteratively, and defining goals around an MVP…

As with design, I think sometimes you have to dial in enough of an idea so that folks can understand it and make high-level decisions. That has been my approach so far. I think we could make some high-level decisions about architecture quickly by time-boxing and not getting too deep in the details. I think the questions are how to design this simply but with enough flexibility to build in the future (e.g. @igorlesnenko asked about the possibility of multiple prompts). That is probably a tall order. Aside: my recent thinking has been it’s probably easier to reuse UX patterns than anticipate every use case and write highly reusable code in advance. Just a thought I’m simmering on. More on my latest thinking is in the updated MVP proposal ([Slack/Loom](https://parabol.slack.com/archives/C836NA350/p1642629808200000) 🔒 ).

**Comment by BartoszJarocki** [comment]
I've created implementation issues for our MVP here: https://github.com/ParabolInc/parabol/issues/5914. 
The plan was reviewed with @ackernaut and @mattkrick. Initial notes can be found here: https://www.notion.so/parabol/Bartosz-s-notes-a0e2f9fa79dd425985b6dbe69fb52832 

There's an ongoing Sprint Poker meeting where we can discuss if everything is clear: https://action.parabol.co/meet/aqdUGMTGbC

**Comment by jordanh** [comment]
@BartoszJarocki about how many hours do you think this took you? Asking for team metrics...

**Comment by BartoszJarocki** [comment]
@jordanh I'd guess it took up to 2 days including meetings with other team members, working on the initial draft, discussing that, then creating tasks etc.
