### ISSUE TITLE
Show inline embeds instead of regular links for connected integrations

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5941]
This is a child issue of #5939 and is a sibling of #5940.

## Enhancement

When a link from a connected integration is pasted, we display a richer version of the link.

## Example

Instead of displaying a good'ol regular text link...

<img width="331" alt="Captura de Pantalla 2022-01-24 a la(s) 4 53 53 p m" src="https://user-images.githubusercontent.com/3276087/150878467-f8d17210-7b25-4d27-a39c-668822ab2aae.png">

...we instead show a more streamlined version of that link.

<img width="322" alt="Captura de Pantalla 2022-01-21 a la(s) 3 42 36 p m" src="https://user-images.githubusercontent.com/3276087/150604004-190d5ee7-1b4f-428c-a106-71a52af57559.png">

The streamlined link format still works as a link, so when I hover it...

<img width="331" alt="Captura de Pantalla 2022-01-24 a la(s) 5 02 42 p m" src="https://user-images.githubusercontent.com/3276087/150879485-2bb7e814-426d-4d68-a628-8bd1e87f4138.png">

...I'm aware that it's clickable. The link behavior remains.

## Scope

- For now, we'll start by adding this feature only to GitHub links (or Jira, if we decide on #5940 to start with Jira instead)
- We will also keep for now the "rich version" of the link pretty basic (only logo and issue number).

Let's explore extending the functionality in a near future, once this is out in the wild and we learn how it's working for users. We can look at options such as showing the issue title and status, assignee, etc). 

## Acceptance criteria

- [ ] When a link from GitHub is pasted, _and_ the GitHub integration is connected, the link is replaced by an inline embed
- [ ] The inline embed behaves as a link, so it receives focus and hover states like any other link would
- [ ] The inline embed is composed of the GitHub logo and the issue number

### Estimated effort:
- 16 hrs

**Comment by Dschoordsch** [comment]
Is this only for GitHub? If this is also for Atlassian Cloud, do we show project avatars?

**Comment by ackernaut** [comment]
@enriquesanchez 
- Do users have a way to back out of the link formatting if they really want the long link text? For example, if it formats the link but they press a back or delete key does it go back to the unformatted link?
- I like the pattern of course because I’ve kicked it around. I like @Dschoordsch question and wonder what icons we show. It’s a pretty small footprint, I believe I was using the 18px (.75x) variants for this.
- What do we do if a user selects text and adds a link to GitHub via command K? I assume nothing since they have a bit of text they have specific intentions when formatting this way
- In the future I still think it would be cool to drag items from the Inspiration panel into a card but I wonder if folks would really use that behavior? In general I think it would be nice to be able to quickly refer to the work. I wonder if we ever introduce an autocomplete affordance with a similar link formatting. Folks could press some key as their type to quickly find an integrated link or task and add it to their text.
- Nice work capturing this enhancement!

**Comment by enriquesanchez** [comment]
Thanks for the feedback @Dschoordsch and @ackernaut 🎉

> Is this only for GitHub? If this is also for Atlassian Cloud...

To keep the scope small, I'm proposing to start with GitHub, and then do Atlassian and so on. I have really have no preference. If from a technical stand point turns out to be no additional effort to implement this feature for more than one integration at a time, then great! 

> do we show project avatars?

I want to start simple and then evaluate how much more useful info we can add to the inline embeds. I think prokect avatars make a lot of sense and provide very useful context.

I'm being mindful of how constrained the space is in task cards. For example, I like Notion's approach where they have the logo, issue number, title, and user avatar:

<img width="597" alt="Captura de Pantalla 2022-01-26 a la(s) 5 42 01 p m" src="https://user-images.githubusercontent.com/3276087/151265401-b3a8d6ec-37fb-47fd-87ca-fa1adc479bcc.png">

...but I worry that all that info wouldn't fit nicely in a task card.

> Do users have a way to back out of the link formatting if they really want the long link text? 

Oh, great question! There should definitely be a way for this. I need more time to explore, but the first idea that comes to mind is to repurpose the edit link popup we currently have, where you can edit or remove a link. What do you think?

> What do we do if a user selects text and adds a link to GitHub via command K? I assume nothing since they have a bit of text they have specific intentions when formatting this way

Correct, similar case that the one @tianrunhe prompted on https://github.com/ParabolInc/parabol/issues/5940#issuecomment-1021727419.

**Comment by ackernaut** [comment]
Re: backing out of formatting. Maybe the pop-up would work, but it would be nice to have a move that can be done quickly with the keyboard. I assume if the pop-up was there that would also go away if you backed out of the formatting.
