### ISSUE TITLE
Add integrations task for first-time users

### ISSUE THREAD

**Issue by enriquesanchez** [ParabolInc/parabol#5943]
This is a child issue of #5939.

## Enhancement

For first-time users, we add one more task that suggest to them to explore the available integrations.

## Example

![imagen](https://user-images.githubusercontent.com/3276087/150891023-e5e36c94-b5da-454c-87e9-b1964bba4dd8.png)

Users are presented with two initial tasks, one of them being about the integrations we support and where to find/add them.

`Parabol supports integrations for Jira, GitHub, GitLab, Slack and Mattermost. Connect your tools on Settings > Integrations.`

`Settings > Integrations` being a link to the integrations settings view.

## Scope

- While we can do much more for user onboarding, let's keep this focused to a single task card for integrations.

## Acceptance criteria
- [ ] First-time users get an additional task card as seen in the example above
- [ ] This task card behaves like any other task card and as such has all the same properties
- [ ] Measure if the user moves or deletes the card or clicks on the link

### Estimated effort
- 4 hrs

**Comment by avivapinchas** [comment]
In my experience, when we do something one way for one need, it starts to become _the_ way to address similar needs. I imagine this will become the way we do onboarding. 

If that's the case, I'd be curious: 
- How does this scale? 
- What are our principles for deciding what should be a task vs what shouldn't be a task? 
- What team is the task added on? I suppose most folks will only have one team. But does 'first-time user' mean literally just the first time, or what about when they create a new team?

**Comment by ackernaut** [comment]
I like @avivapinchas ’s point. In my opinion, if we did this, it would be because we wanted to try a pattern that probably doesn’t scale. When you’re looking for low effort with good impact, I think that’s okay. But you may not want to keep using the pattern later.

One question in the back of my mind is: where are the natural points in which somebody wants to do something that benefits from integrations.

In my opinion there are 2 top moments in the UX where we need to focus:
1) scoping for sprint poker
2) adding tasks during discussion (in the thread)

Later, we are making a bet that adding the Inspirations panel would become another key moment for using integrations.

Back to number 2 above. I think we’ve discussed this before, and I looked to see if I opened an issue or discussion (idea) around this. Some folks say they would like to pick where their tasks go during discussions and that preference be remembered, instead of having to add a task and integrate a task (2 steps every time). I’m gonna write a design issue around some thoughts I have but I would like your keen input on it since your head has been in this space.

**Comment by enriquesanchez** [comment]
Thanks for the excellent feedback, @avivapinchas and @ackernaut 🙌

>I imagine this will become the way we do onboarding. 

I think this pattern is an excellent way to do onboarding. I like it particularly because it helps new users to both learn how to use a feature (tasks), and how to get around the tool (invite team members, add integrations, set up xyz, etc). Other tools such as Notion and Trello have a very similar pattern for onboarding, and I think those are very successful experiences. 

> How does this scale?

This pattern obviously has its limits, we want to be useful for first-time users, but also not overwhelm them. A more integral focus on onboarding will help us answer this, but it's also something I intentionally kept out of scope for this particular issue. 

I see this as a low-effort opportunity to test if this pattern can work for us, before digging further down the land of user onboarding.

> What are our principles for deciding what should be a task vs what shouldn't be a task?

I think both Growth and Product should define these. It'll be a great cross-functional effort to tackle. What are the top X actions we want new users to take based on Y goals/metrics we are measuring against? Where do first-time uses get stuck more often? etc.

> What team is the task added on? I suppose most folks will only have one team. But does 'first-time user' mean literally just the first time, or what about when they create a new team?

I imagine onboarding looking a little different for a first-time initial user (the one who signs up and creates an org for the first time), than for a first-time user being invited to join an already existing org/team. 

> if we did this, it would be because we wanted to try a pattern that probably doesn’t scale

I actually like that it doesn't scale infinitely (what does?). It gives us some very useful constraints that can help us frame a good solution. 

To clarify, I don't think the only reason to try this is because it's low effort. On the contrary, good user onboarding is hard and this is a very easy experiment that will hep us on two fronts: 1) to test this pattern for user onboarding (near future need), and 2) to increase awareness of integrations (current need).

> In my opinion there are 2 top moments in the UX where we need to focus:

  >   scoping for sprint poker
  >   adding tasks during discussion (in the thread)

Totally, scoping for sprint poker was the moment where I first added an integration myself. I had to in order to be able to continue with the meeting flow. In my opinion we do a great job at that point, prompting users to add an integration front and center.

Adding tasks during a discussion is related to #5940, but in order to keep the scope manageable, I decided to start first with the tasks view. We can totally start with discussion threads instead if we think the effort is better spent there. Either way, what we do in one view will inform and get us more than half-way there when we decide to implement the feature in other places. What I want is for us to keep or steps short and focused.

**Comment by avivapinchas** [comment]
Having watched a[ couple replays of first time user sessions](https://www.notion.so/parabol/Session-replay-churned-e40b12411b354fb0987aa2cac7753865): this is a great idea. We should do this. 

Users seem to wander around some *very* empty views. I think having clear next-steps and support in the Meetings and their `so-and-so's personal team` Team view would realllllly help!

**Comment by JimmyLv** [comment]
I think so, just to double-check: does the "first-time initial user" defined here refer to when 1. first join Parabol, 2. or each time join each team.
![Google Chrome-Add integrations task for first-time users · Issue #5943 · ParabolIncparabol-002873-20220602](https://user-images.githubusercontent.com/4997466/171542654-3266ce53-5818-4e87-a9f8-514b9638b992.png)

The reason why I ask is: because our integration settings are **for each team level**, which means that each new team has a new task, at least for this task card, and the jump link to [Settings > Integrations](https://action.parabol.co/team/6VSEcEuGdy/settings/integrations) is different for each team.
![Google Chrome-Team Settings  Jimmy Test Team-002875-20220602](https://user-images.githubusercontent.com/4997466/171542646-1ce3dbe3-77c5-49c4-a3ac-7d013345202e.png)

**Comment by Dschoordsch** [comment]
@JimmyLv this task should be added just like the other placeholder task. It should be present in the onboarding team and thus lead to the integrations for said team.

**Comment by JimmyLv** [comment]
ok, cool. So the 'onboarding team' here is the first team that is automatically created, when a new user enters Parabol, am I understanding this correctly?

**Comment by JimmyLv** [comment]
I think I could start working on this task, and as a metric for how well it works subsequently, we should be able to know the conversion rate from `/me/tasks` (or the `/team/{teamId}` page) to `/team/{teamId}/settings/integrations` with the help of Amplitude, which I am going to try it out.
