### ISSUE TITLE
Use MaterialUI SvgIcons instead of Font

### ISSUE THREAD

**Issue by blimmer** [ParabolInc/parabol#6062]
## Issue - Enhancement

Today, we ship two quite large font icons for Material UI:

```console
> ll -h packages/client/styles/theme/fonts/MaterialIcons*
-rw-r--r-- 1 blimmer staff 103K Feb  1 09:49 packages/client/styles/theme/fonts/MaterialIcons-Regular.woff2
-rw-r--r-- 1 blimmer staff 113K Feb  1 09:49 packages/client/styles/theme/fonts/MaterialIconsOutlined-Regular.woff2
```

This pattern means that we ship every icon (used or unused) to the client, which is inefficient. If we switched over to the React `@mui/icons-material` package, we could use the SVG versions of just the icons we use in the app. This should result in a far smaller payload to deliver the icons we use.

Additionally, on slow internet connections, there's a strange behavior where you see the "name" of the icon in the DOM while the font is loading. This breaks the layout and overall looks a bit odd. Check out this Loom recording to see what I'm talking about: https://www.loom.com/share/9bde6426362d4c8ca97ff7a3d6039a83

## Accessibility

I noticed this issue while working on the follow-up to #5961. When I requested the text content of a submitted retrospective item, the string I entered oddly had `"cancelsearch"` appended to the end of string:

```
Error: expect(received).toHaveText(expected)

Expected string: "We should start doing this!"
Received string: "We should start doing this!cancelsearch"
Call log:
  - expect.toHaveText with timeout 5000ms
  - waiting for selector "[data-cy=reflection-column-Start] [data-cy=reflection-stack-Start]"
```

When I inspected the HTML element, indeed, the `<i>` element has the name of the element:

![Screen Shot 2022-02-15 at 12 59 18](https://user-images.githubusercontent.com/630449/154139442-fa270fd8-4fc9-4a37-905d-a96ee79a4a3c.png)

I listened to this with VoiceOver on my Mac and it wasn't announcing the `cancel` text, so I don't think there's necessarily an accessibility issue with the current pattern. However, some screen readers might also behave differently than VoiceOver.

### Acceptance Criteria

- SVG material icons are used instead of the MUI font icons.
- Unused icons aren't included in the final bundle (see https://mui.com/components/icons/#usage).

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
i've been wanting to do this forever! Surprised it takes a long time on 2nd page visit, i thought we were caching that in our service worker.

1 gotcha is changing colors of icons--it's harder to do with SVGs

**Comment by blimmer** [comment]
@mattkrick, yep we are caching it in the service worker. I explicitly cleared it out for the demo video to show the slowness on the initial load.

**Comment by 87prashant** [comment]
Hi everyone, I am working on this issue.
that's what I figured out:
Instead of using [Icon](https://github.com/ParabolInc/parabol/blob/master/packages/client/components/Icon.tsx) component we can import Svg Icon components from @mui/icons-material
![Screenshot 2022-06-26 190614](https://user-images.githubusercontent.com/106697681/175817113-5e20af12-f825-471c-8182-789a5308b703.png)
And use that component
![Screenshot 2022-06-26 190718](https://user-images.githubusercontent.com/106697681/175817058-13228354-02f7-4aae-bc43-402c231a7d15.png)
![Screenshot 2022-06-26 190643](https://user-images.githubusercontent.com/106697681/175817061-ed649017-caba-4909-b8ce-2a95ecb0763e.png)
Could you confirm that I am going in the right direction?
I want guidance on some things:
In the below component I am not able to figure out how to dynamically style the required component using the emotion.
https://github.com/ParabolInc/parabol/blob/78bb1a39ab083bebb2550a524a5d5efd526acff8/packages/client/components/NewMeetingSidebarPhaseListItem.tsx#L10
![Screenshot 2022-06-26 190759](https://user-images.githubusercontent.com/106697681/175817094-e01b4a71-f1d7-4cfd-9b5d-770ce290dbb9.png)
Also, suggest any other better way to perform that.
As far as I know, there are 147 files that are importing the font icons, apart from repeatedly performing the above work is there any optimized way?

**Comment by mattkrick** [comment]
> Could you confirm that I am going in the right direction?

maybe? the question is-- should we treat SVG like components or images? images cache better, components are more flexible. if you want to change the color of an SVG image you'd have to convert it to text, then turn that text to a DOM element, then edit the color. In your opinion, weighing the pros & cons, which is best?

> In the below component I am not able to figure out how to dynamically style the required component using the emotion.

you'd have to target child SVG elements using selectors

> As far as I know, there are 147 files that are importing the font icons, apart from repeatedly performing the above work is there any optimized way?

writing a codemod should make this real quick! (or maybe just a good regex with find & replace?)

**Comment by 87prashant** [comment]
Thanks @mattkrick for replying
> In your opinion, weighing the pros & cons, which is best?

I would choose images for performance.

**Comment by Dschoordsch** [comment]
@87prashant nice that you picked this up, I just wanted to prioritize this more, since currently our app is broken if the user translates the site.
![Screenshot from 2022-07-25 12-05-33](https://user-images.githubusercontent.com/7331043/180752397-1b03802d-1049-49f0-9629-6f02bd24a3ad.png)

Let me know if you need more help.

**Comment by 87prashant** [comment]
@Dschoordsch 
Could you check the current progress?
