### ISSUE TITLE
Migrate from Lerna to NX

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6212]
Lerna is basically deprecated & never really gave us much benefit.
Let's move to NX, which should give us better versioning flows, which will help as we move towards CI/CD.

https://nx.dev/migration/adding-to-monorepo

AC
- [ ] Issues written to lay out the path to move towards NX

Estimate: 8 hours

**Comment by mattkrick** [comment]
Options considered:
- rush
- turborepo
- vanilla yarn workspaces

the general vibe i get from the community is that nx is opinionated, but still the best & fastest, so i feel comfortable moving forward with it.

**Comment by JimmyLv** [comment]
Revisited this issue, starting with Lerna v5.1+, Lerna comes with the new possibility to integrate Nx directly. [Integrating Nx and Lerna | Nx](https://nx.dev/recipe/lerna-and-nx)

Lerna v5.1 which introduces a `useNx` flag. Adding that makes Lerna to be on par with Nx in terms of speed. Based on the benchmarks claimed in the blog [^1], enabling Nx on your existing Lerna workspace can speed it up in the range of 2–10 times.

Definitely, it is worthwhile to try this out in our codebase, and the exploring paths and ACs will be.

1. [ ] to add the `useNx` flag and do benchmarks
2. [ ] to enable the `cacheableOperations` with `nx.json`
3. [ ] switch to the Nx native commands (make sure build & release scripts work fine)
4. [ ] * might be try [Nx Cloud](https://nx.dev/nx-cloud/set-up/set-up-dte) for the distributed task execution & distributed caching

Note: 
1. Right now Nx does not handle version management and we need to continue using `lerna publish`.
2. Nx does not handle dependency management and we need safely keep using `lerna bootstrap`.

[^1]: [How Lerna just got 10x faster! | by Juri Strumpflohner | Nrwl](https://blog.nrwl.io/lerna-used-to-walk-now-it-can-fly-eab7a0fe7700)

**Comment by JimmyLv** [comment]
After playing with [nx affected](https://nx.dev/nx/affected) for a while in PR https://github.com/ParabolInc/parabol/pull/7187, the prerequisite for our monorepo to enjoy the benefits of nx caching [^1] is still requires splitting packages' scripts.

For now, we are compiling both client and server in one `build` script, and need to separate them into their own package https://github.com/ParabolInc/parabol/blob/9177909d9b3bc9cf2ba5d88a32c0ce53b1da177f/package.json#L26

Because `nx affected` supports [run scripts only on the affected files, for example:
Only the `pacakges/client` code has changed, so the `pacakges/server` build doesn't need to be re-run (with nx cache). [^2] https://github.com/ParabolInc/ parabol/pull/7187


![image](https://user-images.githubusercontent.com/4997466/190638938-046e1bad-5b93-4461-9c1f-8769f05efde2.png)

[^1]: https://nx.dev/concepts/how-caching-works
[^2]: https://nx.dev/concepts/mental-model
