### ISSUE TITLE
GitHub integrated tasks are not displayed correctly

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6221]
There are at least two places where showing integrated tasks does not work: in task dashboard and sprint poker.

## How to reproduce (Task dashboard)
Gina has GitHub integration and tries to push a task from the task dashboard

### Expected behaviour
Task is pushed successfully and is displayed correctly

### Actual behaviour
Task is pushed but error is shown. Pushing a second time shows the task is already integrated error message. The task is not displayed as integrated.
![Cannot push task to GH](https://user-images.githubusercontent.com/7331043/158764552-d8366098-f84c-4071-bc86-efe01f541290.gif)
![Task is ambivalent about being integrated](https://user-images.githubusercontent.com/7331043/158764565-02cbb735-3bb9-45c2-8974-8aef87195285.gif)

## How to reproduce (Sprint Poker)
Galaxy has GitHub integration, starts a Sprint Poker meeting and adds a GitHub task

### Expected behaviour
Task is added and shows up correctly

### Actual behaviour
Error content "Integration provider is down" is shown instead of the task. One time a participant could not even see the title.
![Screenshot from 2022-03-17 08-19-07](https://user-images.githubusercontent.com/7331043/158765097-b2aa0c29-7aea-4693-9c1d-65b9fe905328.png)
![Screenshot from 2022-03-17 08-03-52](https://user-images.githubusercontent.com/7331043/158765204-9080be37-4573-4387-9ece-d38652f32fe0.png)

**Comment by mattkrick** [comment]
Here's the mental stack trace of fixing the issue:
- the `id` field gets removed because `typeInfo.getFieldDef() === undefined`
- going into graphql/TypeInfo, `getFieldDef()` is undefined because `parentType()` is undefined
- So, we know the document AST we're traversing doesn't have a parent. This makes sense. Just look at the little orphan. It's just floating out there, waiting to get plugged into a schema 
```gql          
 {
    repository(owner: "${repoOwner}", name: "${repoName}") {
      issue(number: ${issueNumber}) {
        ...info
      }
    }
  }
```

So, the fix is easy, this snippet just needs a parent. So, we merge it into the request BEFORE we prune the extensions, then when the pruning function starts traversing, it finds a parent
