### ISSUE TITLE
TypeError: Cannot destructure property 'scale' of '_' as it is undefined.

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6247]
Affected 35 users, happened 46 times in the last 30 days. 

https://sentry.io/organizations/parabol/issues/2695406451/?referrer=github_plugin

```
TypeError: Cannot destructure property 'scale' of '_' as it is undefined.
  at c (./packages/client/components/PokerCardDeck.tsx:57:10)
  at Set.forEach (<anonymous>)
...
(32 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Affected 20 users in the past 30 days. Going to keep this one open

**Comment by mattkrick** [comment]
All of these bugs seem to get caused in the same way:
- a user is on an estimate phase, e.g. /estimate/5
- they navigate back to the scope phase /scope, stay there for 1-10 seconds
- they get this error from the PokerCardDeck
- this happens to facilitators & participants, and a click happens right before the route change, telling me that a user is doing this to themselves (vs. a subscription)
- happens when there is a single dimension

The PokerCardDeck component is only rendered in the estimate phase. How would such a component be rendered when the last route the user was on is the scope phase?

**Comment by mattkrick** [comment]
I was not able to reproduce this.
My theory is that React is suspending at an inopportune time. We don't have strict mode turned on, which would cause some functional components to get called twice to make sure we're suspense compatible.
This is the only way I can conceive that a computer belonging to the estimate phase is getting called while still on the scope phase.

to fix, I'm using fallback values for properties of the localStage.
we'll see if this fixes it
