### ISSUE TITLE
How-to paginate a nested connection

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6272]
relay doesn't allow refetches on connections that live in plural fields, including other connections.

We need to do this for GitLab though.
For example, gitlab returns a list of projects that the user has selected.
Then, for each project, it returns a list of issues.

These issues are flatMapped into an array so the user can see all the issues across all the projects.
When the viewer scroll to the bottom of the list & we want to load more, should we load more projects or issues?

My thinking is that we should _never_ load more projects. Projects are set by the `ids` argument, where it returns 1 project per id. if ids is null, then it'll return `first`.

So, when a user scrolls to the bottom of the page, it should load 20 more issues for each of the listed projects, but it should never load more projects, since that's determinate. But what if 1 project has already fetched all the issues it has? we shouldn't have to fetch that. More importantly, how is the variable `issueAfter` set? We only have 1 of them, but we need `n` of them, 1 for each issue connection.

__This is why we can't have nested connections__

So, how do we get around this?

My suggestion is the following:
- For the initial fetch, use the `projects` API with a set number of issues & projects. it can't be increased. if gitlab returns an error, we tell the user to pick a project from the dropdown menu. Scrolling to the bottom does nothing.
- When the user has at least 1 selected project, we call the `project(id)` API instead, since that returns a single object. we map over the `fitleredProjectIds` and trigger a new query for each. Put a `@connection` on the issues field in this refetchable query
- When the user scrolls to the bottom, we call `loadMore(20)` to load 20 more issues on each. This will be a noop if all the issues have already been fetched for a given project since `hasNextPage` will be false
- the results from each of the queries is flatmapped together, just like today

@nickoferrall whatcha think?

**Comment by nickoferrall** [comment]
I like it @mattkrick. I've mentioned an alternate solution below, but I prefer your solution as it's consistent with our other integrations. I'd prefer to create an issue to implement your suggestion in v2 of the GitLab integration though as I think the current solution is good enough to get in front of customers. 

Clarifying q: we'd loop through `filteredProjectIds` and query `project(id)` for each `id`. This would return an array of `paginationRes` which we'd use to get all issues. We'd also use the array in `useLoadNextOnScrollBottom` to trigger `loadMore(20)` for each project?  

A few small concerns with this approach:

1. With the initial query, to find the desired issues, a user may need to select a project from the filter menu. However, with the current UI, it's not obvious where the project dropdown menu is or that they would need to select a project. I would look at the GitLab issues initially rendered and assume that's all of my issues. If I searched for the issue I'm looking for and it didn't show up, I'd assume there's a bug. We could edit the no issues found message to say "Click on a project", but people don't always read the message. 
2. We have an issue to show the current filters under the search input, using Enrique's design: https://github.com/ParabolInc/parabol/issues/6138. With the initial query, would it say "Current filters: none" or would we not show that text? I'd say the latter. It _could_ be confusing that the UI indicates that there are no filters when we're actually grabbing the first 20 projects, but I imagine the user won't realise in the vast majority of cases.
3. We'd be making multiple `project` queries instead of one `projects` query. If a user has a bad network connection and GitLab is being laggy, things may feel slow. 
4. Maintaining two different queries means more surface area for bugs.

Alternatively, we could show no issues initially and open the project filter menu by default. 
Pros: 
- We would be able to remove the initial query and the UX might be less confusing to users

Cons: 
- Being able to immediately see issues without extra clicks is helpful
- GitLab's UI would be inconsistent with our other integrations

If a user has selected a project(s) previously, we should start with that projectId. I think we should do this for GH & Jira too. I'd be happy to create an issue for this if you agree. 

The work we do in this issue https://github.com/ParabolInc/parabol/issues/6007 to refactor `getPrevRepoIntegrations` could be helpful here. I'd love to work on #6007 after GitLab v1 is complete to get more Redis reps.

**Comment by mattkrick** [comment]
> With the initial query, to find the desired issues, a user may need to select a project from the filter menu. However, with the current UI, it's not obvious where the project dropdown menu is or that they would need to select a project. I would look at the GitLab issues initially rendered and assume that's all of my issues. If I searched for the issue I'm looking for and it didn't show up, I'd assume there's a bug. We could edit the no issues found message to say "Click on a project", but people don't always read the message.

Yep, directing them to the filter menu, either by highlighting it when no issues get returned or by using words

> We have an issue to show the current filters under the search input, using Enrique's design: https://github.com/ParabolInc/parabol/issues/6138. With the initial query, would it say "Current filters: none" or would we not show that text? I'd say the latter. It could be confusing that the UI indicates that there are no filters when we're actually grabbing the first 20 projects, but I imagine the user won't realise in the vast majority of cases.

With the initial query, I think the main message we want to send to the user is, "hey, look we can talk to gitlab for you. but the stuff down here is meaningless. but it'll look like this. click the filter button to make it meaningful" However you think best to get that message across is AOK with me

> We'd be making multiple project queries instead of one projects query. If a user has a bad network connection and GitLab is being laggy, things may feel slow.

yep, 1 query per selected project, which could ad up, but in real use cases, they will probably only have 1 or 2 projects selected. By breaking them in multiple queries, one is not dependent on the other, so it could feel faster because the list updates as queries get resolved. However, we can't really compare it to what is happened today because today it's impossible to paginate multiple pages of issues

> Maintaining two different queries means more surface area for bugs.

they'll use the same code, just different variables, unless I'm misunderstanding how you'll design it?

> Alternatively, we could show no issues initially and open the project filter menu by default.
Pros:

We would be able to remove the initial query and the UX might be less confusing to users

sure, i'm up for that!

> If a user has selected a project(s) previously, we should start with that projectId. I think we should do this for GH & Jira too. I'd be happy to create an issue for this if you agree.

i _think_ this is how it works today? if not we should fix that. the initial query should be the last one that you used to select an issue

**Comment by nickoferrall** [comment]
> i think this is how it works today?  

You're right! I typed into the search input, left the meeting, returned, and didn't see my previous search input. But now I see that the query only persists when you click on an issue to add it to the scope. I think that's the right behaviour as it indicates that the search query was useful.

Your responses make sense to me. Are you happy for me to create an issue and add it to GitLab v2 rather than v1 @mattkrick? The current projects query works, so I'd prefer to ship v1, get user feedback, and then refactor the projects query to a project query rather than vice versa

**Comment by nickoferrall** [comment]
I've created an issue following this discussion (https://github.com/ParabolInc/parabol/issues/6325) so I'll close this one
