### ISSUE TITLE
Delete a team doesn't work until page is refreshed

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#6424]
I noticed that when I try to delete a team, it looks like nothing happens. But once I refresh the page the team is gone. 

@tianrunhe is able to see the team disappear from the sidebar after waiting for a few seconds. I had no such luck. 

Maybe there could be a little message saying "your team was successfully deleted"? Or some sort of "poof" animation as it disappears from the sidebar? 😅

Here's an awful drunken house drawing: 

<img width="837" alt="Screen Shot 2022-04-19 at 5 11 33 PM" src="https://user-images.githubusercontent.com/80418360/164112358-c5880917-316b-45a0-93bd-61c49877038f.png">

**Comment by 87prashant** [comment]
@drewhousman1010 I am not getting the same behavior as stated above
The team is automatically archived after a few seconds with a snackbar message "team has been archived"

Btw, I am not able to find any option to see the archived teams.

**Comment by JimmyLv** [comment]
The 'delete team' feature should work, but the user interaction just makes it confusing, because: 
1. **The delete operation takes time**, but there is no indicator, like a loading effect when deleting. Only after deleted, there's a snackbar message "team has been archived"
2. **The confirmation button is not clear**, we use the text hint to confirm using the `Enter`, but using a red delete confirmation button like GitHub does might be clearer.

![Google Chrome-Team Settings  Yet Another Roam Team-000765-20221102](https://user-images.githubusercontent.com/4997466/199484943-4425376a-e9a9-4352-993b-4ae529c23689.png)

GitHub demo, to delete a repo:

https://user-images.githubusercontent.com/4997466/199484663-ba7fee3e-41bc-4228-94c7-8f67b94dc6f9.mp4

**Comment by JimmyLv** [comment]
I would like to suggest that we also add a confirmation red button: 
1. to make it clear to the user what they are doing, mouse hovering up will have a more visible effect. (and this button will only be clickable after the user has entered the correct team name) 
2. and the button will have a `loading` effect during the deletion process.

![Google Chrome-Team Settings  Yet Another Roam Team222-000774-20221102](https://user-images.githubusercontent.com/4997466/199486611-8fe41c5e-0ca7-4073-b1a5-702e7124671d.png)

**Comment by BartoszJarocki** [comment]
@JimmyLv this should be closed as well, right?

**Comment by JimmyLv** [comment]
@BartoszJarocki  This can be considered a feature improvement. I'm already working on this, and I'll use this issue as an Improvement and create a PR later, how does that sound?
