### ISSUE TITLE
refactor(frontend): usePaginationFragment

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6431]
The following components need to be refactored to hooks:
- [ ] ParabolScopingSearchResultsContainer (refactor pagination container)
- [ ] OrgBillingContainer (refactor refetch container)
- [ ] the other 4 components that use `createPaginationContainer`

Estimate: 4 hours

**Comment by JimmyLv** [comment]
Hey @mattkrick, I'm getting into Relay pagination requests and would like to ask a few questions:

1. what is the difference between `useLoadNextOnScrollBottom` and `useLoadMoreOnScrollBottom`?
2. and after refactoring into usePaginationFragment, is it straightforward to replace the `useLoadMoreOnScrollBottom` with the`useLoadNextOnScrollBottom`? 
3. I can see that only the GitHub integration uses `useLoadNextOnScrollBottom` to do scrolling and load data from a slice, neither Jira nor GitLab do this optimization for all the results in one request, is this intentional? Or is it just not done for now?
