### ISSUE TITLE
Bug: deleting team prevents reuse of deleted team's name

### ISSUE THREAD

**Issue by MindEvo** [ParabolInc/parabol#6484]
Steps to Reproduce:

1. Create a new team with name, 'X'
2. Delete team 'X'
3. Notice the notification in the red box that 'X' has been archived.
4. Create another new with same name, 'X'
5. Notice the bug

See video:

https://user-images.githubusercontent.com/35351786/166073866-44579273-4b96-4aa6-b53f-6a53552f93b3.mp4

Note: Not seen in the clip at the end, but after entering the name and being presented with the prompt, user cannot move forward and create the team.

## Acceptance criteria
* [ ] duplicate team name check only considers teams that are not deleted/archived

**Comment by jordanh** [comment]
I can't decide if this is a bug or a feature. In a world where we might provide "undelete" capability, this would be a bit useful. It certainly does "feel" like a bug now, tho.

**Comment by Dschoordsch** [comment]
Right now after someone deleted a team, the name is gone forever which might be very annoying for users because they cannot rename deleted teams anymore.
Team names don't need to be unique. We don't have this constraint and everything appears to work fine with duplicate names. The only reason we forbid duplicate team names is to not confuse the user.
