### ISSUE TITLE
More segments about poker meeting added

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#6516]
## Issue - Enhancement
We need to add the following events for Poker meetings:

1. When a user votes for an issue
    * userId
    * wasFacilitator?
    * meetingId
    * teamId
    * issueId
    * type of issue
2. When the votes are revealed
    * userId
    * meetingId
    * teamId
    * issueId
    * type of issue
3. When facilitator enters the final score after revealing the votes
    * userId
    * meetingId
    * teamId
    * issueId
    * type of issue
    * score entered
    * label name (As Comment, Do Not Update, Story point estimate, etc)
4. When facilitator click on "edit score" and enter something new
    * userId
    * meetingId
    * teamId
    * issueId
    * type of issue
    * old score
    * new score

### Acceptance Criteria (optional)
- [ ] Segment `User Voted` added
- [ ] Segment `Votes Revealed` added
- [ ] Segment `Votes Entered` added
- [ ] Segment `Votes Changed` added

**Estimated effort:** 3 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by tianrunhe** [comment]
@avivapinchas anything you wanna add here? Better to do it in batch

**Comment by avivapinchas** [comment]
Ooh thanks for the tag! I'll add some desired items, and you can feel free to let me know if they're not possible. 

> When a user add an issue to scoping
Something like 'issue source' - meaning jira, github or parabol (or gitlab, or jira server, etc.) 

> When a user votes for an issue
Something like, "vote value" - I want to know if folks are using the question and pass cards, and also if they are using fun scales 

>type of issue
What does this refer to? 

I'd also wanna know: 
- What scale are folks using - this might be for the 'meeting started' and 'meeting closed' events 
- Do the scores get edited - clicking on 'edit score' and entering something new
- Maybe an event like `score entered` - since people need to enter their decision, I want to see that action. 
- Maybe an event like `score sent` -  if and how that score is sent to an integration, so maybe the `issue source` (or similar) property, and then a property like 'as a comment, as a label, etc' 

If this is too much or any of these seem like a bad idea, just lmk! I err towards asking for everything, and accepting when you pull me back towards something more realistic.

**Comment by tianrunhe** [comment]
@avivapinchas 

> What does "type of issue" refer to?
yes by "type of issue" I meant issue source!

> Something like, "vote value"
It could be hard as the value is not necessarily numerical, e.g., people can vote 🍊🥥🍉. We have template/scale data today in BigQuery so we can join them with meeting table to get what you need!

> What scale are folks using - this might be for the 'meeting started' and 'meeting closed' events
We can modify those events while we are at the code!

> score edited, score entered, score sent
Yes we can add these.

**Comment by avivapinchas** [comment]
Awesome - sounds great!

**Comment by tianrunhe** [comment]
I updated the A/C. Note that:
1. score entered is the same as score sent. When you enter a score and press enter, it sends the score to the source based on the label selection (as comment, story point estimate, etc)
2. We already have `templateId` today in the meeting started & completed events. We can join that with template & scale table if needed
