### ISSUE TITLE
Pagination for archived Tasks is broken

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#6536]
Reproduction
* Navigate to any old team that should have hundreds/thousands of tasks
* Go to archived tasks
* Scroll down, note "That's all folks" comes way too quickly

Bonus bug:
* Navigate to any older team
* Set a search filter like "foobar"
* Navigate to archived tasks
* Note that the archived tasks also uses this filter

- **How serious is the bug?** P3

### Acceptance Criteria (optional)
Users can:
   - Scroll all their archived tasks
   - Search filters do not affect tasks in archived tasks view

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by shapel** [comment]
Hmm, I've added this note, so I'll going to look what's broken.

**Comment by shapel** [comment]
I checked pagination behaviour on a different amount of generated tasks (eg 300, 1000, more) and I only see problems when search was involved. @jordanh plz share some details about the case if I missed something here.

Speaking of the search filter, some items from the list below 🤯
1. it's inconsistent compared to other filters, like
* team
* team member
* archive checkbox. 
Because it's not passed as a URL parameter and therefore cannot be shared to others by copying and pasting the URL.
2. the search control disappears on the page for archived tasks, but still applies to them... 
3. the search filter is interpreted as a RegExp (so you can use hacks like `\d{3}`). Which can be potentially dangerous, especially if the system allows you to share this filter (as a URL parameter).
4. it applied to tasks & agenda items and sometimes can be confused. It looks like the system needs to highlight the fact that the user is not seeing the data because of the filter.

So, as far as I understand, we need to fix at least the 2nd item from the list right now.

**Comment by shapel** [comment]
Digging deeper, I see that the search filter only works on the client side, and it looks "normal" for task view since the system requests 1000 tasks without pagination. Which looks enough for real cases.

But for archived view, this can sometimes look odd due to fact the system requests small amount of tasks (only 10 items for the first page and  ~40 for each new page) and then loading more according to the scrolling.  As a result, the user might experience that some sort of search filter might filter out already loaded tasks, but the system does not load more data due to lack of scrolling interaction from user. 
So as a quick fix I increased initial page size for archived tasks to reduces the chances for the user to run into such a corner case.

What the real fix is, as I understand it, is to filter tasks (archived and not) only on the server side. As it already works when filtering a scope of sprint meeting.

@jordanh what do you thinks about it?
