### ISSUE TITLE
Designed meeting view with demo and video

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6652]
## Issue - Enhancement
Update the learning hub design for #6648 to also have a demo (#6649 ) so we can test both options at the same time

### Acceptance Criteria (optional)
Users can:
   - either go to a demo or watch a short tutorial video

This issue blocks #6648 implementation

**Comment by acressall** [comment]
Design concepts: https://www.figma.com/file/5qyWAMoB0jZAY195ECZDf7/Meeting-View?node-id=4%3A148
Please leave specific feedback in the Figma file, or feel free to vote below

**Comment by acressall** [comment]
Option 1: video featured
This option uses a lot of what we already have: the existing empty state container and a timeline event card. It should be easy to implement, but my concern is that the demo link will be missed, skewing our data to the video being the "preferred" option. 


![Image](https://user-images.githubusercontent.com/18582225/171433534-6e99898e-e4d9-4038-ae76-9936c2b16304.png)

**Comment by acressall** [comment]
Option two: equal weighting
This option has a bit of personalized copy and keeps the demo and video at an equal weight. It uses the existing meeting card for the demo, and a similar card style for the video. 


![Image](https://user-images.githubusercontent.com/18582225/171433762-25452c14-2ea3-4922-b55b-7b52bc46e2ef.png)

**Comment by JimmyLv** [comment]
I actually prefer Option 1, mainly because we might have more videos in the future, for example about presenting different kinds of meetings (retro, check-in, sprint poker, etc.), so we might want to have an "independent" area for scalability.

I got some inspiration from Loom's newly designed "Home" page, maybe we could have two main areas, for option 1,
 as @Dschoordsch mentioned, we could also make the `demo meeting` a bit bigger, or leave more white space like Loom does.

![Google Chrome-Home  Loom-002868-20220602](https://user-images.githubusercontent.com/4997466/171536150-cb8867a5-1750-4750-867f-4d8363f34de9.gif)

**Comment by ackernaut** [comment]
I like the equal weighting option. I like the personalized space above. Making these feel like the meeting cards may be helpful so that folks get used to interacting with those here.

**Comment by acressall** [comment]
Ok, I think we'll go with option 2 for this experiment! @JimmyLv I like the idea of a little video hub, but we don't have the content for it at the moment, so I think we can start small and then see if we go further in that direction!
