### ISSUE TITLE
More verbose redis, rethinkdb, and postgres logging

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#6692]
To further increase verbosity in logging, we need to increase log level for redis, rehinkdb, and postgres logging.

Current example of log related to rethinkdb from graphql executor:  _Error initializing master pool at MasterConnectionPool_

How do we increase log verbosity to a higher level?

Potential A/C:

- [ ] Increase log details related to data connections to redis, rethinkdb, and postgres
- [ ] Include IP in log (useful when determining if active connection was using old IP of any migrated connections e.g. when using containers)
- [ ] ENV VAR to increase and decrease log level
- [ ] Dump stack trace to log when log level is increased
- [ ] Potentially link errors to username value in log, so that we can easily correlate error to which user scope executed the code

**Comment by mattkrick** [comment]
thoughts
- getting userId is gonna be tricky sometimes, not always, just depends where the log occurs
- i'd like to make sure the logging strategy doesn't flood us with logs from the cloud instance, an ENV VAR seems reasonable here to run on PPMIs
- redis should have connection names already, so logs should be pretty useful
- determining the rethinkdb connection root cause is tricky...not sure if the driver includes any logs, probably just need to inject a log wherever the error message is propagating from, hopefully it's within the call to the driver
