### ISSUE TITLE
fix(invoice): Invoices include invoice items in the past

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#6810]
Using the parabol org as an example, look at an invoice, see the details for users added, notice that there are more users & the line items are for the previous invoice.

AC
- [ ] An upcoming invoice # of users should match the following query:
```ts
r.db('actionProduction').table('OrganizationUser').getAll('Skc7syWwNox', {index: 'orgId'})
  .filter((row) => row('removedAt').eq(null)).count()
```
- [ ] users added date range should match the date range of the invoice

Estimate: 13

**Comment by mattkrick** [comment]
related to #6827

**Comment by nickoferrall** [comment]
How invoices currently work:

- A user upgrades to Pro and we create a subscription for that org in Stripe in [upgradeToPro](https://github.com/ParabolInc/parabol/blob/4172e4446fb0b6206fa585a36d037476899e6330/packages/server/graphql/mutations/helpers/upgradeToPro.ts#L31). There could be more than 250 active users when they upgrade which would exceed [Stripe's limit](https://stripe.com/docs/api/invoiceitems/create) of 250 items per invoice.
- Creating a subscription automatically [creates an invoice](https://stripe.com/docs/api/subscriptions/create?lang=node) as we're using the default `collection_method=charge_automatically`.
- We save the `subscriptionId` in the `Organization` table in [upgradeToPro](https://github.com/ParabolInc/parabol/blob/4172e4446fb0b6206fa585a36d037476899e6330/packages/server/graphql/mutations/helpers/upgradeToPro.ts#L45).
- When an active user is added or removed from an org, we call [adjustUserCount](https://github.com/ParabolInc/parabol/blob/dc31d2c8a6eb15e5e1b637012ef02eb963919cf7/packages/server/billing/helpers/adjustUserCount.ts#L185). This creates an `InvoiceItemHook` for all pro orgs, and for each hook, we call `processInvoiceItemHook`.
- In [processInvoiceItemHook](https://github.com/ParabolInc/parabol/blob/4172e4446fb0b6206fa585a36d037476899e6330/packages/server/billing/helpers/processInvoiceItemHook.ts#L96), we update the Stripe subscription quantity with the new total. Currently, this update could exceed Stripe's limit of 250 items per invoice.
- When the billing leader goes to [OrgBillingInvoices](https://github.com/ParabolInc/parabol/blob/35800a9f1950dd0de09a5d35e7dccc518fa2d4fb/packages/client/modules/userDashboard/components/OrgBilling/OrgBillingInvoices.tsx#L34), we query `Invoices` which fetches the previous invoices from our db and the [upcoming invoice](https://github.com/ParabolInc/parabol/blob/8409e5ee0ab86c9effcb616dd82cdf30053c81ee/packages/server/graphql/queries/invoices.ts#L66) from Stripe.
- When we click on an [Invoice](https://github.com/ParabolInc/parabol/blob/8ebf6df2ce76ab40fab6fe4631594483c4861a5f/packages/client/modules/invoice/components/Invoice/Invoice.tsxL156), we query `InvoiceDetails`, which generates an [upcoming invoice](https://github.com/ParabolInc/parabol/blob/dc31d2c8a6eb15e5e1b637012ef02eb963919cf7/packages/server/graphql/queries/invoiceDetails.ts#L44) which finally [creates an invoice](https://github.com/ParabolInc/parabol/blob/4172e4446fb0b6206fa585a36d037476899e6330/packages/server/billing/helpers/generateInvoice.ts#L371) and stores it in our db.

Stripe offers a [few solutions](https://stripe.com/docs/billing/invoices/subscription#pending-items-frequently) to the 250 item limit problem:

1. Create a one-off invoice for the customer. 
2. `Charge a subscription whenever the amount due reaches a threshold`. This wouldn't work for us as we want the invoice to be sent each month, not when the user reaches the threshold.
3. Use [pending_invoice_item_interval](https://stripe.com/docs/api/subscriptions/object#subscription_object-pending_invoice_item_interval). `This is equivalent to having Stripe create a one-off invoice for the subscription on a recurring basis.`. We don't want the one-off invoice to recur, and we want the invoice to show up right away rather than after an [interval](https://stripe.com/docs/api/subscriptions/update#update_subscription-pending_invoice_item_interval-interval).


So, we want to create a one-off invoice for the customer. We could charge them right away and create an invoice for the remainder of that month, but it would be confusing for a user that they have an invoice from July 1-11th and 11th-31st. Instead, we want to create multiple invoices in our db and Stripe and we want the user to see July 2022 invoice and July 2022 Part 2 invoice.

To explore:

- Ideally, in `generateInvoice`, we would check the upcoming invoice quantity. If it exceeds the limit, create a new invoice one-off invoice with the same subscription. However, is it possible to have two upcoming invoices in one subscription?

**Comment by nickoferrall** [comment]
After speaking with Stripe, last night they increased our invoice item limits from 250 to 2,000. We should no longer need to create one-off invoices if the limit is exceeded so I'll close this issue.
