### ISSUE TITLE
Prompt user to drag cards in group phase

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6814]
Design: #6741 

Option 1: hinting at drag and droppable cards. 

https://user-images.githubusercontent.com/18582225/175152287-26501b7b-ac93-48de-985a-6baa6c8bfd19.mov

Animation details:
- Delay 30s
- Duration: 900ms (600ms to "lift"; 300ms to "drop")
- Iteration count: 2
- Transition timing: ease-out

AC:
- show the hint after 30s and repeat every 60s until there is at least one reflection group.

**Comment by 87prashant** [comment]
I am working on the issue, I feel like it is hard to animate the first reflection (when the above condition is true) unless we implement the same logic as the draggable reflection card (I could be completely wrong). Because the reflection card is getting clipped during the animation.

what are others' thoughts on a simpler version of the required animation?

https://user-images.githubusercontent.com/106697681/179703641-8c391d1c-189d-4111-9be2-ef0550116385.mp4

**Comment by JimmyLv** [comment]
👍 Do you mean when the reflection card animated move to the right, the right part of the card is cut off?

**Comment by 87prashant** [comment]
Yeah

**Comment by acressall** [comment]
Thanks for the demo video @87prashant! Here's what I'd like to try:

1. Can we adjust the z-index while it is in the "raised" state so it appears on top of the column?
2. If that doesn't work well, we can reduce the amount it moves so it just touches the edge of the column


If it's helpful, here's the positioning changes from the design file:
- y/top: -5px
- x/left: +20px

**Comment by 87prashant** [comment]
> Can we adjust the z-index while it is in the "raised" state so it appears on top of the column?

zIndex is not helping because the prompt column clips the content that goes outside (overflow:X hidden) 
> If that doesn't work well, we can reduce the amount it moves so it just touches the edge of the column

This is a good idea

**Comment by 87prashant** [comment]
This is how it looks on left +10px

https://user-images.githubusercontent.com/106697681/179886496-b786b63f-dcbe-4075-99a7-7d4d79575419.mp4

**Comment by acressall** [comment]
Looks good @87prashant! Thanks for adapting!
