### ISSUE TITLE
Discuss adding additional health-checks to intranet-graphql

### ISSUE THREAD

**Issue by adaniels-parabol** [ParabolInc/parabol#6835]
I'm concerned the intranet-graphql endpoint is returning a false positive. Whereas the endpoint returns a valid pong, but the system may be experience other issues. I'd like to use this issue to discuss adding additional health-checks to the intranet-graphql endpoint.

A few health-checks that could be added to increase health check confidence.

- SSO auth check
- Google auth check
- Local user auth check
- Load meetings check
- Create meetings check
- Load timeline check
- Return latency or check connection to redis
- Return latency or check connection to  rethinkdb
- Return latency or check connection to  postgres

Right now, I believe the intranet-graphql only checks to make sure graphql is functioning

**Comment by mattkrick** [comment]
We've got new pings that let you check the latency of rethinkdb, pg, redis. Pings on the other stuff won't give you any additional data

**Comment by mattkrick** [comment]
on private schema:

```gql
query {
  ping {
    rethinkdb
    postgres
    redis
  }
}
```

users, meetings, timeline, etc. are just tables on those DBs, so checking DBs should paint the full picture
checking SSO would require checking all SSO providers, but we'd have to use our users credentials to do that, so that's not cool
google auth check would be the same deal. i'm sure they have a service we could ask to see if it's up, but honestly if google oauth is down, the entire internet would be screaming about it before we'd get alerted :laughing:

**Comment by mattkrick** [comment]
i think we've got what we need here. For query-specific checks, I'd opt for a system that watches for errors (e.g. sentry) and if we see a sudden spike of loading timeline problems, then we know there's something specific to that query vs. a problem with 1 of our DBs
