### ISSUE TITLE
Standups: Design a reminder notification

### ISSUE THREAD

**Issue by BartoszJarocki** [ParabolInc/parabol#6870]
We need to remind team members to submit their standup response some time during the opened phase of standup.

Ideally, the reminder includes info on how many team members have already submitted their response: "X of your colleagues have already answered"

Context: https://action.parabol.co/meet/emVqryBPna/discuss/3

## Acceptance criteria
- Created a proposal for the standups reminder notification teams will see in their chat integrations.

**Estimated effort:**
- 4 hrs

**Comment by enriquesanchez** [comment]
Here's an initial proposal:

![image](https://user-images.githubusercontent.com/3276087/179122035-d0b5d1bd-256f-4723-b7ec-9a406775c862.png)

I'm intentionally avoiding direct language such as "_You_ have 8 hrs left to submit _your_ response..." because this will most likely be posted in a group channel, and I want to avoid any potential confusion making someone who has already done it think that it didn't work and they need to do it again.

@lorena-cure @BartoszJarocki @jmtaber129 How does this feel to you? I'm not sure how I feel about thebutton's CTA (Open Async Standup), should we have something else instead? I was trying to avoid "Submit _your_ response" but I'm short on better ideas.

**Comment by enriquesanchez** [comment]
Some more considerations that I need your feedback on:

1. When should we post this reminder? 8 hrs before the standup closes? 4? Some other time? Initially we won't have a setting to let folks tweak this, so I think we should pick a time and go with it.
2. Do we need anything special to have this notification also work in **MS Tems** and **Mattermost**?

**Comment by enriquesanchez** [comment]
Also, what should happen when no one has submitted a response?

> 0 colleagues have submitted theirs

...feels sad, how about:

> Be the first to submit a response!

?

**Comment by BartoszJarocki** [comment]
@enriquesanchez I'm sorry for the late response! 

> When should we post this reminder? 8 hrs before the standup closes? 4? Some other time? Initially we won't have a setting to let folks tweak this, so I think we should pick a time and go with it.

Rigth now, we only have a start date, I'd suggest to do it after ~8h after starting the meeting

> Do we need anything special to have this notification also work in MS Tems and Mattermost?

I don't think so, it'll take a little more of the dev time but I don't think we need separate designs

> Also, what should happen when no one has submitted a response?

`Be the first to submit a response!` is way better!

**Comment by enriquesanchez** [comment]
> I'd suggest to do it after ~8h after starting the meeting

@BartoszJarocki That sounds good to me 👍

**Comment by jmtaber129** [comment]
Agree with everything that's been so far, but for the CTA maybe we do "Open *Activity*"?

**Comment by enriquesanchez** [comment]
>for the CTA maybe we do "Open Activity"?

Oh, I had not thought about that. It's certainly shorter and easier to read than "Open Async Standup".

I'm OK with "Open Activity" 👍

**Comment by enriquesanchez** [comment]
@BartoszJarocki @jmtaber129 this one is ready for an implementation issue 👍
