### ISSUE TITLE
Move "add meeting" button to left sidebar

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#6941]
Slack convo for context: https://parabol.slack.com/archives/C03GZQJ27MG/p1658446224414069

Hypothesis: having the primary action placed at the bottom left follows more modern desktop patterns which could lead to it being clicked more frequently

**How to test:** 
Review clicks over a 1-month period comparing it to:

- - FAB in bottom right (compare to same period in previous year)
- Button in top bar (compare to previous month)

**Comment by Dschoordsch** [comment]
There were some concerns by @enriquesanchez that on small screens the left menu is automatically hidden, thus also the button. For such small screens we're currently showing the bottom right FAB, so we could omit it from the left menu.

**Comment by enriquesanchez** [comment]
Thanks for sharing that slack convo @acressall, I wasn't aware of it.

Those findings are very surprising to me. Normally, we humans read top to bottom, left to right. So it's common knowledge that having main actions on the top of the screen is better for discoverability. Even Google (who created the bottom FAB for Material Design) has moved away from the bottom FAB pattern on desktop views:

<img width="583" alt="Captura de Pantalla 2022-07-26 a la(s) 10 32 53 a m" src="https://user-images.githubusercontent.com/3276087/181048718-5e6ba4c6-8c5c-4693-9921-a4d50d40b0a8.png">

<img width="538" alt="Captura de Pantalla 2022-07-26 a la(s) 10 32 59 a m" src="https://user-images.githubusercontent.com/3276087/181048739-6abcb5b6-d62a-4f95-a78e-f9c74a4837bf.png">

As @acressall suggests, I think the sidebar is the best logical place to add it, but I will still recommend to stick to placing it on the top part of the view:

![imagen](https://user-images.githubusercontent.com/3276087/181049332-5fff81b2-284f-4c55-952a-9e8ddf3a4fe0.png)

 ...but we still have the issue of what to do with the button. Here's what Google calendar does:

<img width="350" alt="Captura de Pantalla 2022-07-26 a la(s) 10 34 04 a m" src="https://user-images.githubusercontent.com/3276087/181048755-32a6e215-8645-4d03-b91a-74fd589b76cb.png">

...so we could try a similar approach:

![imagen](https://user-images.githubusercontent.com/3276087/181049464-0a09c1ca-68e0-4522-ad28-4b781afb8f79.png)

If we go this route, ee'd need to add some left padding to the main dashboard views to accommodate the FAB.

**What do y'all think?**

**Comment by Dschoordsch** [comment]
Could we keep the FAB on the bottom right for small views? Do we assume small views are phones/tablets?

**Comment by Dschoordsch** [comment]
@acressall Once this issue has passed design review, please create an implementation issue in "Todo" for it.

**Comment by acressall** [comment]
@enriquesanchez thanks for chiming in! I'm not as fond of the btn at the top because it feels out of place to me. But that may just be personal preference. My references for other apps that use the bottom were Loom and Notion.
That said, some small adjustments to the sidebar could help the btn feel more contained.

For the top bar, I'm not _totally_ surprised. I think there's a certain amount at the top that we gloss over and don't read. The top bar is also where we put the "sign up" on the website, so for new users they may no longer pay attention to it, assuming it's the same. These are guesses though 🤷‍♀ 

I was thinking of keeping the mobile version in the bottom right. The top right is the hardest spot to reach on mobile, and most people are right handed (unlike me...), or even the center option Enrique tried before so it doesn't feel _too_ different

**Comment by enriquesanchez** [comment]
>That said, some small adjustments to the sidebar could help the btn feel more contained.

@acressall Agreed, this feels safe to try. Happy to help with any reviews if you need them 👍 

> The top bar is also where we put the "sign up" on the website, so for new users they may no longer pay attention to it, assuming it's the same. These are guesses though

Oh, I think you are right! I had not seen it from that perspective, thank you!

>I was thinking of keeping the mobile version in the bottom right. 

This feels right to me as well.

**Comment by acressall** [comment]
@enriquesanchez I made an update! I'd love your feedback on this. 
https://www.loom.com/share/d712c1f1fd12492cbb0a65721887b77b

**Comment by enriquesanchez** [comment]
@acressall This feels much much nicer! I like it.

You had made good arguments for placing it at the bottom, and I don't want my suggestion to keep us from exploring that option if you still feel strongly about it.

**Comment by enriquesanchez** [comment]
I also wonder how that lighter shade of gray would feel like in the meetings sidebar. I think we currently use white, but I'm liking the more subtle contrast here.

**Comment by ackernaut** [comment]
Thanks for the continued effort, here @acressall  I have some questions/thoughts:

1) What is the method for testing button performance? How are we going to test this button? What did we learn from the last test?

2) I noticed you made an iteration that uses the upper-left pattern, but then it switches to lower-left mobile pattern when closed? What’s the thinking there, opposed to the pattern Google uses where the button maintains its position, but gets smaller?

3) I think (as Enrique pointed out, and I’ve pointed out before) that the Google pattern is interesting. I can only imagine the data they have on their button placement. Hence, we’ve often referred to Material Design and patterns in Google as a strong baseline, seeing how they have a lot of people and development behind their design patterns. It may not be perfect in every case, but there are a lot of ‘wheels’ that don’t need reinventing. We can introduce novel patterns as needed, but then we have to come from good first principles etc. Here, [the variant that I can advocate for is one](https://www.figma.com/file/t6XK6kiLmVYhjDbTG80csb/FAB-placement?node-id=9%3A1823) where the button collapses to a smaller state, where the sidebar doesn’t have elevation or a different background

4) However, I would like us to figure out a things first:
   - what are we trying to learn about churn with button placement? Were folks having trouble finding it before?
   - what is our baseline and method for comparing yet 1 more button variant? How are we being empirical in comparing these variants? How long might we try the new placement?
   - if we do decide to try yet another position we should keep the button position fixed for desktop (at least the Google pattern is widely used), not jump down to the mobile position if the menu is closed. I would object to this detail otherwise

**Comment by acressall** [comment]
@ackernaut to answer your questions:

> What are we trying to learn about churn with button placement? Were folks having trouble finding it before?

The tension is stated in the [previous issue](https://github.com/ParabolInc/parabol/issues/6635), and I believe it remains the same. I _suspect_ the previous version didn't perform as we hoped because on the marketing site we have a login/signup in the same spot, so it may have been glossed over. 

> What is our baseline and method for comparing yet 1 more button variant?

I've drafted a test measurement (also in main issue description), but would like a review from Bruce to see if it would be reliable:
**How to test:**
Review clicks over a 1-month period comparing it to:

- FAB in bottom right (compare to same period in previous year)
- Button in top bar (compare to previous month)

> I noticed you made an iteration that uses the upper-left pattern, but then it switches to lower-left mobile pattern when closed? What’s the thinking there, opposed to the pattern Google uses where the button maintains its position, but gets smaller?

I've been having trouble finding the Google example in the wild. The issue I have with it personally, is it's floating on the left without a home. To me, it feels disconnected (which is the same struggle I have with the lack of separation between the sidebar and main content on desktop too)
The rationale for the bottom right is:

- The pattern stays the same on desktop and mobile
- The bottom right is easier to reach on mobile for most users (right handed people)

This is one area where I see Google is inconsistent and I think there _could_ be a case for breaking from Material here. 

That's my rationale and answer to your questions, but all that said, I think both are safe to try so can set aside my personal preferences. 
For the sake of debate, what do you think of this for the closed state?

![Image](https://user-images.githubusercontent.com/18582225/181281291-a08d1331-a4f9-4d75-ae2d-a621ac6b4f5a.png)

**Comment by ackernaut** [comment]
Hello, thanks for those notes! Very helpful.

#### How to conclude?
I suppose our original hypothesis was something like ‘folks are getting stuck starting meetings, let’s try a different place for the start button’? So with one more variant we might look for more started meetings than its original position. Two things: 1) I’d like to know how we conclude the experiment as we haven’t found the optimization yet. This upper-left variant might be an optimization, but it needs to be weighted fairly. I’m not sure if comparing to a year ago is a good baseline. 2) As part of our learnings I wonder if we get a better sense of when optimizations may be too small to spend this many cycles on the work. I for one, never felt that button was our greatest friction. Meanwhile there are other frictions from customers with more qualified and quantified data that need attention.

#### The patterns
I do see that Google is consistent for their desktop browser interfaces for keeping their main button in the upper left. I’ve only seen that it collapses to a round button on Calendar. My point was that if we collapse it to a smaller form when the menu is closed, it should stay in the upper left, not then move to the bottom right. I agree that at the breakpoint for tablet/mobile we can keep it bottom right the whole time. I would rather defer on the visual separation bit of the nav, I think it needs more iterations and slows down what we are trying to do with this design effort and experiment.

As for the recent iteration you shared, I personally like the hanging icons in the collapsed nav as they continue to provide the useful navigation. I see how they keep it tied together. It could probably stand for one more, the icon for teams, and if they tap it it opens the menu so that they can see their teams. However, I don’t like 2 ways to open the menu. I wonder how many people collapse that menu in the first place?

**Comment by acressall** [comment]
Alright, I don't think we're entirely on the same page about things and I don't want this to go into discussion limbo. Instead, since it's not entirely design questions we're trying to solve, I'd like to bring it back to the squad + Bruce.

@tianrunhe can you provide some feedback on the proposed way to test this, and if you think the timing of it will work? Or propose alternatives if you have other ideas!

@Dschoordsch as squad lead, I think it's your call whether or not we do this. We can implement it if you think we could learn more about usage, or park the design for later if you'd rather focus on larger tasks.

**Comment by tianrunhe** [comment]
I feel like with a lot of more experiments we want to do and want to do correctly, we need to have a proper [A/B testing framework](https://github.com/ParabolInc/parabol/issues/6650) setup first.
For now, sure, we could manually assign a feature tag to some users. But then we need some [more work from Amplitude](https://github.com/ParabolInc/parabol/issues/6952) side in order to compare performance by cohorts

**Comment by Dschoordsch** [comment]
I think we should move forward with this.

I trust that google had probably looked into this and that the top of the side bar is a prominent place. From replays new users spend a lot of time on the left sidebar, so it looks like a good place.
Assuming long term users still find the button, the metric we're interested in is new users clicking on the start meeting button, i.e. drop off before first meeting.

For mobile I don't have a strong opinion. I wouldn't mind having the button less reachable, people facilitating meetings from mobile is not our core audience. It's difficult anyways having Zoom + browser open on mobile.

I'm a bit behind on Android, but with 11 they introduced new gestures for navigation which feels to me as if the phone usage shifts from hand+thumb at the bottom to hand + thumb on the right making the reachability problem less severe.
Don't know about Apple side of things, but their phones are usually less high making this less of an issue from the beginning.

**Comment by acressall** [comment]
Thanks for the direction!
Here's what we have for desktop now: (mobile will stay the same as it is currently)

![Image](https://user-images.githubusercontent.com/18582225/181783442-b928a73e-401e-41dd-80b3-39bbabd5db52.png)
![Image](https://user-images.githubusercontent.com/18582225/181783441-035c6c80-4b36-4627-9d26-dc5195b91121.png)

Experiment details in Notion: https://www.notion.so/parabol/Squad-2-Notes-515904adde5441febd81750e4c7a1e65?p=b6b35077e9e4492e9c0d631d2f964a90&pm=s

**Comment by jordanh** [comment]
Done!
