### ISSUE TITLE
Bug: Demo started in grouping cannot advance to next

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#6947]
## How to reproduce

When accidentally starting the demo in `/group` phase, the demo cannot be advanced with the next button

## Expected

Demo can be advanced

**Comment by Dschoordsch** [comment]
Relates to: #6946

**Comment by JimmyLv** [comment]
Just want to double confirm: If the user goes directly to the `/group` route with the disabled refresh to start a new demo meeting in https://github.com/ParabolInc/parabol/issues/6946. What's the phase does the user click the `Start Demo` button to start? start the demo directly from the `Group` stage, or should start with the `Reflect` stage?

![Google Chrome-Retro Meeting  Demo Team-003916-20220809](https://user-images.githubusercontent.com/4997466/183664483-a761cfc5-e574-4c28-807d-69c7937c54b7.png)

**Comment by Dschoordsch** [comment]
If the demo did not start correctly, i.e. there are no reflections and the user goes to group directly (no existing local demo state), we should show the "Start Demo" button and start from reflect.

**Comment by JimmyLv** [comment]
I made the bugfix for the demo state in the PR at https://github.com/ParabolInc/parabol/pull/7131, which means that it will show the "Start Demo" button in `/group` and thus start normally.
Just except for one small issue: the Group dragging effect will not appear immediately, because the BotScript would need to enter everything first before starting the Group.

**Comment by Dschoordsch** [comment]
Seems like this is solved with #7131, is that correct @JimmyLv?

**Comment by JimmyLv** [comment]
Yes, correct! this issue is already fixed, closed.
