### ISSUE TITLE
Bug: template name overflows it's container

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7095]
In the new meeting lobby, when I select a template with a long name it overflows the container. 

@enriquesanchez should this truncate?

![Image](https://user-images.githubusercontent.com/18582225/185654190-99cee047-f45e-4c50-a1d4-822fa6e5ad75.png)

**Comment by Dschoordsch** [comment]
@enriquesanchez I played around with this and there are basically 3 options:
1) truncate the text
![Screenshot from 2022-08-22 14-43-18](https://user-images.githubusercontent.com/7331043/185925006-05b92c91-f2ad-41ed-be54-5aa6d0118714.png)

2) wrap the text
![Screenshot from 2022-08-22 14-43-41](https://user-images.githubusercontent.com/7331043/185925030-4568a87c-5347-4ba1-8e25-099abf0f3616.png)

3) make template picker and "Include Icebreaker" flex and allow the template area to grow first until the content doesn't fit anymore.
    1) this could be combined with flex-wrap but that would create lots of edge cases, so simply growing inside the one row is preferable.
![Flex+ellipses](https://user-images.githubusercontent.com/7331043/185932460-371660df-0cdc-42a5-9866-b7d6619f26f7.gif)

I would prefer option 3) since it makes best use of screen real estate without shifting the layout around too much.

**Comment by 87prashant** [comment]
I would choose option 2 since the design looks consistent every time with the complete name

**Comment by enriquesanchez** [comment]
Thanks for the ping @acressall and @Dschoordsch.

All of these fields (including the selected template) should truncate. So option 1 is the correct solution.

**Comment by Dschoordsch** [comment]
Ok, so no squashing of the settings field to gain some space before truncating.

**Comment by enriquesanchez** [comment]
Correct. We want to avoid the layout from changing in size or position.
