### ISSUE TITLE
Misleading error message when inviting existing team mate with different casing

### ISSUE THREAD

**Issue by 87prashant** [ParabolInc/parabol#7146]
When inviting an existing member via a capitalized email address, a misleading error "Could not send and invitation to the above email" appears.

### Discussed in https://github.com/ParabolInc/parabol/discussions/6994

<div type='discussions-op-text'>

<sup>Originally posted by **87prashant** August  3, 2022</sup>

https://user-images.githubusercontent.com/106697681/182592418-38932d97-d0da-4e51-9393-3f61742cc3b0.mp4

I was writing the email name with the first capital letter many times and thinking that there is some issue in the app then I understand the situation so I think it would create an issue for some users if they do not care about the casing during typing the email.
I guess it should not consider casing here for validation.

</div>

## Acceptance criteria
* [ ] when a team member address is entered (regardless of capitalization) the dialog should show the "... is already on the team" message

Estimated effort: 4h

**Comment by Dschoordsch** [comment]
Just to clarify, the bug you're describing is that when you've entered an existing team members address with capital letters, you're getting the error message above instead of "... is already on the team" message?
![Screenshot from 2022-09-05 12-16-37](https://user-images.githubusercontent.com/7331043/188426628-b0c21faf-7b49-47a1-849c-b566db84ab92.png)
![Screenshot from 2022-09-05 12-16-27](https://user-images.githubusercontent.com/7331043/188426635-dae5b26b-fde8-4743-8236-95f85191eb26.png)

**Comment by 87prashant** [comment]
Aha! I have not checked with non-existing emails. Thanks @Dschoordsch for clarifying

**Comment by Dschoordsch** [comment]
@87prashant good find, I modified the description as I think it's still a valid bug.
