### ISSUE TITLE
Discussion topics are missing when going from Group to Discuss

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#7265]
Steps to reproduce:

* Create a retro meeting
* advancing to "Vote"
* go back to "Group"
* go to "Discuss"

I could advance, but no discussions were available
![Peek 2022-10-11 12-54](https://user-images.githubusercontent.com/7331043/195072300-863f3900-702c-4698-92c9-66a1674a43a4.gif)

### Acceptance Criteria
- Users can see discussion topics if they exists when advancing from any phase

**Estimated effort:**  5h

**Comment by jmtaber129** [comment]
I did a bit of investigation into this and found that this is due to the `vote` phase never being marked as "completed" by our logic. The current navigation logic will mark the facilitator's current stage as completed iff the navigation reflects forward movement in the meeting, and then navigate to the new stage. So if you navigate backward, then skip ahead, the phase the facilitator is implicitly completing is not marked complete.

Without the `vote` phase being marked complete, the side effect of creating discussion stages doesn't happen.

A similar bug is if you navigate from reflect -> group -> reflect -> vote -> group: The groups should be frozen because voting has started, but this is not the case because we didn't trigger the side effects of completing the `group` phase.

**Comment by 87prashant** [comment]
@jmtaber129 
So, it means every phase should be marked as completed if we reached it at least once.

**Comment by 87prashant** [comment]
Hi, @igorlesnenko @jmtaber129  I am working on this issue.
Could you define the difference between the phase and stage by considering a retrospective meeting? Does every phase have at least one stage?

Also, could you check out the PR for once if it could be the appropriate/potential solution?

**Comment by jordanh** [comment]
@87prashant are you still working on this one per chance, or may I reassign it to a Parabol team member?

**Comment by 87prashant** [comment]
Yes, I am working. But I was waiting for a review of the work I did till now, if it could be a potential solution.

**Comment by igorlesnenko** [comment]
@87prashant Sorry for the late reply, I completely missed it. Feel free to mention again if there is no response for a long time.

> Could you define the difference between the phase and stage by considering a retrospective meeting? Does every phase have at least one stage?

Phase is like discussion, stage is like discussion topic. Each phase has at least one stage

I looked at your PR. Not sure I fully understand how would you use the `maxPhaseIndex `to solve the issue. Can you explain a little bit more please?

If I understand the [investigation](https://github.com/ParabolInc/parabol/issues/7265#issuecomment-1360508194) described by @jmtaber129 correctly, the problem is that we don't mark the vote phase as completed. Should we in this case check if we jump over some phases when going to the new phase, and mark them as completed? i.e. not only mark the 'current' phase as complete, but phases in between too.

**Comment by jmtaber129** [comment]
@87prashant It might be reasonable to refactor+rename [`handleCompletedStage`](https://github.com/ParabolInc/parabol/blob/0480bc9ce25800e51ca8f63363c09af69dc967f6/packages/server/graphql/mutations/helpers/handleCompletedStage.ts) to execute side effects for navigating _to_ a new stage, rather than navigating _from_ a previous stage. Then we'd just move [this line](https://github.com/ParabolInc/parabol/blob/0480bc9ce25800e51ca8f63363c09af69dc967f6/packages/server/graphql/mutations/navigateMeeting.ts#L84) to around [here](https://github.com/ParabolInc/parabol/blob/0480bc9ce25800e51ca8f63363c09af69dc967f6/packages/server/graphql/mutations/navigateMeeting.ts#L101).

That way, instead of saying "we just finished the REFLECT phase, so let's execute some side effects we need for the GROUP phase", we're saying "we're moving into the GROUP phase, so let's execute some side effects we need for this phase".

**Comment by 87prashant** [comment]
@igorlesnenko sorry for the late reply
Here, through `maxPhaseIndex` I am tracking the maximum phase the meeting has gone till now ( like reflect phase has index 1, group phase has index 2 and so on ). Then on the basis of that I decide should I mark this phase completed like when I move back or forth I check is `currentPhaseIndex` = `maxPhaseIndex` + 1 if yes then I mark that phase completed.

**Comment by 87prashant** [comment]
Sorry guys☹, I am not getting time to work on the issue, but I will work on this soon. If the delay is hurting you then you can work on this.

**Comment by jordanh** [comment]
Scrubbed. Reassigned the squad. @87prashant we'll take ownership of this one.

@jmtaber129 let's add this to our next sprint for triage and/or fixing

**Comment by jordanh** [comment]
Scrubbed. I see a fix is pending! Wonderful
