### ISSUE TITLE
Meeting history limit: Design direct meeting access lock message

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#7359]
If a meeting older than 30 days is accessed directly, we shall show a message pointing them to upgrade

## Acceptance criteria
* [ ] designed a dialog to show when accessing locked meetings directly

**Comment by Dschoordsch** [comment]
I propose showing the same message as in #7358 as a Dialog above the actual meeting which we blur just enough so no details are visible.

![Screenshot from 2022-11-22 13-04-04](https://user-images.githubusercontent.com/7331043/203309749-87c76e42-909a-460c-94d5-1939b5dd216a.png)

There is no link to the dashboard or similar because the locked meeting could only be reached by a direct link, most likely from an email and there should only be one CTA.

**Comment by Dschoordsch** [comment]
@acressall, @avivapinchas could you please check the proposed design?

**Comment by acressall** [comment]
I like the design! 

> There is no link to the dashboard or similar because the locked meeting could only be reached by a direct link, most likely from an email and there should only be one CTA.

I wonder if we should still have a link to the timeline so they can view the meetings they _do_ have access to? Not a dealbreaker though

**Comment by Dschoordsch** [comment]
@ackernaut could you please review this design?

**Comment by ackernaut** [comment]
Hey @Dschoordsch 
- If they upgrade can they see all meeting history? If so I’d like to edit the copy a little ‘Your plan includes 30 days of meeting history. Unlock all meeting history by upgrading.’
- I assume tapping that button takes them to the billing view?
- Are we planning to track interactions with this dialog?
- Small visual design details:
  - The lock icon is okay IMO. I wonder if there is some upgrade or account-like custom illustration we have in our library by Freddy. cc @acressall Maybe nothing to do here
  - The heading ‘Past Meetings Locked’ could use a 1.2–1.5x increase to help type hierarchy
  - I like to avoid a single word on a line (aka a _widow_) when possible. With edited copy that may change. Breaking a line can look bad on mobile-sized viewports if it wraps in a new, undesired way due to an adaptive change in container width. Maybe nothing to do here
  - What button size is that? It looks a little small, but the large size might seem too big. However, with a larger heading it may balance out to have a bigger button. Maybe nothing to do here

**Comment by Dschoordsch** [comment]
@ackernaut I missed the summary when designing this. A user could go to a past summary directly from an email or similar. We have 2 options here:
1) do nothing and just show the summary because they most likely have the email anyways
2) overlay the summary with the same lock message
![Screenshot from 2022-12-05 16-05-26](https://user-images.githubusercontent.com/7331043/205671144-b4a8c03f-765d-4761-9791-37bc4c123f18.png)

**Comment by ackernaut** [comment]
Sorry for the delay here. Yeah I think causing a little more friction here with no 2 can be good learning etc. It does seem like a slightly darker dialog overlay may help with the effect, but I leave that to you if you haven’t shipped it yet.
