### ISSUE TITLE
Clicking emoji will scroll down the screen in a stand up meeting

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7458]
![2022-11-18 15 06 11](https://user-images.githubusercontent.com/1879975/202817729-ea814a1d-a6b3-4013-8774-0bfba66531cd.gif)

### Acceptance Criteria (optional)
- [ ] Clicking emoji won't scroll down the screen in a stand up meeting

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by gitstart-parabol** [comment]
@Dschoordsch After doing a thorough spec of this solution, we found out that the problem is a result of the way the emoji status updating logic was implemented. Apparently, the logic causes the entire chat component to re-render, thereby resetting the scroll position of the component. Hence, our proposed solution would involve reimplementing the entire emoji status update logic. What do you think? Cc @mwermuth

**Comment by Dschoordsch** [comment]
That sounds like the right approach. I would like to see an outline first of what logic you're going to move where.

**Comment by jmtaber129** [comment]
This bug is still present, see [slack](https://parabol.slack.com/archives/C042HTVBH8D/p1697135212185169) 🔒
