### ISSUE TITLE
using saved filters in Jira in Sprint Poker

### ISSUE THREAD

**Issue by drewhousman1010** [ParabolInc/parabol#7556]
A [user](https://app.hubspot.com/contacts/3888472/contact/78285451) 🔒 said if they could pick one of their saved filters in Jira as a filter to run in Poker that would save them time.

**Comment by jordanh** [comment]
@drewhousman1010 these are distinct enough asks where I would prefer to keep them separate

**Comment by jordanh** [comment]
Wait! Similar functionality already exists, as it turns out:

<img width="705" alt="image" src="https://user-images.githubusercontent.com/103000/208751236-3b35d27b-1c0d-41e9-9240-d76755245393.png">

Steps to use it:

1. Navigate to Scope phase of Poker meeting
2. Click on the Filter icon and check the box "Use JQL"
3. Paste in the JQL filter from Jira that you would like to use
4. Select an issue
5. Click on the magnifying glass icon and see that the filter has been saved for use next time

So, while we don't import the filters automatically from Jira the user can save time each time they use poker by finding the filters they've used before in Parabol

**Comment by jordanh** [comment]
@drewhousman1010 is this is sufficient wold you close this issue?

**Comment by jordanh** [comment]
Closing this one for now
