### ISSUE TITLE
Jira two-way sync via webhooks

### ISSUE THREAD

**Issue by mattkrick** [ParabolInc/parabol#7653]
Today, 3900 users have integrated their Jira accounts.
It's pretty common for users to have parabol open in one tab & jira open in another.
For example, during Sprint Poker, they may notice a typo, open the task in jira, and edit the description.
When this happens, we want that updated jira description to propagate back to Parabol in real time.
To accomplish this, we'd like to use [Jira's webhook API](https://developer.atlassian.com/cloud/jira/platform/webhooks/#registering-a-webhook-using-the-rest-api--for-connect-and-oauth-2-0-apps-).

  
Acceptance Criteria: 
- [ ] Create a GitHub issue with the proposed architecture for building this solution
- [ ] Write a PR that is a proof of concept to get the feature working

Estimate: 10-20 hours 
It doesn't have to be complete, this is to test how you work through a complex problem and how we work together.

**Comment by eirelav-codes** [comment]
# Parabol: Jira WebHook Architecture

👉🏼 We want to use Jira’s Webhook API so that we can push updates which the user makes on Jira into the Parabol UI immediately. Example flow: A user updates a ticket title in Jira → the new title gets automatically updated on the Parabol Sprint Poker dashboard.

🎯 For this proposal I focussed on:
- Jira Webhook events of `issue:updated` (no JQL filtering)
- The `summary` and `description` properties of an issue

# Approach

In order to implement Jira’s Webhook API, I propose to follow the steps below:

**Server**

- Create a new POST endpoint that can receive Jira’s Webhook events
- Point Jira Webhook to this new endpoint, e.g. `parabol.co/webhooks/jira`
- Receive and verify hook in a `jiraWebhookHandler` method
    - Deconstruct request body params with `jiraManager.constructEvent()` method
    - Construct GraphQL query to update issue
    - Call mutation query `updateTask` with `UpdateTaskInput` params (e.g. `description`)

**Client [tbc]**

# PR Architecture

💬 Outline below is meant to illustrate the implementation approach, some of it is pseudo code and more of a rough direction as a base for discussion.

`packages/server/server.ts`

```jsx
/*...*/

uws
  .App()
	/*...*/
  .post('/webhooks/github', githubWebhookHandler)
  .post('/webhooks/graphql', webhookGraphQLHandler)
  .post('/webhooks/jira', jiraWebhookHandler)
```

`packages/server/integrations/jiraWebhookHandler.ts`

```jsx
/** Types just for reference, I omitted lots of properties and they might be
declared somewhere else in the codebase. Full example for Webhook payload can be found here:
https://developer.atlassian.com/cloud/jira/platform/webhooks/#webhook-payload
 **/
type JiraWebhookPayloadIssue {
    id: string
    fields: {
      summary: string
      description: string
    }
}

export type JiraWebhookPayload {
    timestamp: number
    webHookEvent: string
    issue_event_type_name: string
    issue: JiraWebhookPayloadIssue
}

const jiraWebhookHandler = uWSAsyncHandler(async (res: HttpResponse, req: HttpRequest) => {

    // TO DO - Authentication
    // Get Jira Signature from req header

    const parser = (buffer: Buffer) => buffer.toString()
    const str = (await parseBody({res, parser})) as string | null
    res.end()

    if (!str) return
    const manager = getJiraWebhookManager()
    const verifiedBody = manager.constructEvent(str)
    if (!verifiedBody) return
  
    const {query, variables} = verifiedBody
  
    publishWebhookGQL(query, variables)
})

export default jiraWebhookHandler
```

`packages/server/integrations/jira/JiraWebhookManager.ts`

```jsx
export interface JiraWebhookVerfiedBody {
    id: string
    query: string
    variables: Variables
}

class JiraWebhookManager {

  static constructEvent(payload: JiraWebhookPayload): 
  JiraWebhookVerfiedBody {

  const { issue } = payload
  const { id, fields } = issue
  const { summary, description } = fields

  const query = 
  `
      fragment UpdateTaskMutation_task($id: string!, $description: string,
	 $summary: string) {
            task {
              # Entire frag needed in case it is deprivatized
              ...CompleteTaskFrag @relay(mask: false)
              id: ${id}
              description: ${description}
	                    summary: ${summary}
            }
            privatizedTaskId
      }
  `
    const variables = {
      id,
      summary,
      description
    };
		
    return {
      query,
      variables
    }
}
```

# Next steps

- Add more advanced authentication from Jira Webhook request (e.g. add header signature)
- Test & finalise logic that updates client UI after task was updated via GraphQL query

# Questions

- Server: Am I right to assume that all issues are stored in our DB (even tickets integrated via Jira)? Which data source should be our “universal truth”?
- Server: Where should the logic to deconstruct the Jira Webhook request body sit? I created a new method called `JiraWebhookManager` but it might be easier to re-use existing Atlassian methods server-side.
- Client: I didn’t have too much time to dive into the UI side in depth. Does a mutation query cause a re-render of the UI so that updated issue information gets updated (e.g. WebSockets?) We will probably need to consider caching (cache invalidation)?

# Workflow Gotchas

- If you are running Parabol locally and you are exposing your port publicly via `ngrok`, you need to set the `host-header` to so that the Jira Webhook request body can come through
    - `ngrok http -host-header=rewrite localhost:3000`

**Comment by Dschoordsch** [comment]
> Server: Am I right to assume that all issues are stored in our DB (even tickets integrated via Jira)? Which data source should be our “universal truth”?

No, we don't store the content from integration issues (i.e. Jira issues), but just fetch it when needed. When we get updates from the webhook, we would need to [publish an update to the corresponding subscription](https://github.com/ParabolInc/parabol/blob/0afa16a3fbc1b3827c171d03e6ee9e5f2855cb7e/packages/server/graphql/mutations/updateTask.ts#L157)

> Server: Where should the logic to deconstruct the Jira Webhook request body sit? I created a new method called JiraWebhookManager but it might be easier to re-use existing Atlassian methods server-side.

Both seem ok.

> Client: I didn’t have too much time to dive into the UI side in depth. Does a mutation query cause a re-render of the UI so that updated issue information gets updated (e.g. WebSockets?) We will probably need to consider caching (cache invalidation)?

If we send updated data via the subscription, there should be no change needed on the client side.

## Questions
* How do we automatically register our webhook for a project used by a user?
* How do we avoid getting updates for issues where we don't have any parabol tasks for?

**Comment by igorlesnenko** [comment]
What happens if our application goes down for a long time? Do we need to handle this situation in some special way?

**Comment by eirelav-codes** [comment]
> How do we automatically register our webhook for a project used by a user?

Hi @Dschoordsch,

A great question which lead me into an entirely new rabbithole to examine. I will share a baseline proposal and all information I could compile for the time being. This surely would require some more research in order to implement.

Overall I would propose to extend the `JiraWebhookManager` class with a couple of additional methods, aiming to:

- Check if our Webhook is registered at the users project already
- If not, register our Webhook with the project
- Pass an array of task ids to observe into the `Jql` filter

**Outline**

`packages/server/integrations/jira/JiraWebhookManager.ts`

```
/* Needs to get assigned dynamically per user to point to correct project space */
const webhooksRestUrl = 'https://valerie-parabol.atlassian.net/rest/api/2/webhook'
const projectKey = 'EXAMPLE-PROJECT-KEY'

interface registerWebhookResponseBodyValue {
  id: string
  jqlFilter: string
}

interface registerWebhookResponseBody {
  values: registerWebhookResponseBodyValue[]
}

export default class JiraWebhookManager {
  private async isWebhookRegistered(projectKey: string) {
    const res = await fetch(webhooksRestUrl, {
      method: 'GET',
      headers: {
        Authorization: `Basic ${Buffer.from(`email@example.com:<api_token>`).toString('base64')}`,
        Accept: 'application/json'
      }
    })
    if (res) {
      const {values} = res
      /* Not happy with this filtering logic, we might need to set a custom field on our hook
      when we register it for the first time, to be able to filter for it in a more reliable way */
      const webhookForProject = values.filter((value) => value.jqlFilter.includes(projectKey))
      return webhookForProject
    }
    return false
  }

  private async getTasksToObserve() {
    // fetch all Parabol tasks that were created via Jira integration
    // map through them and create list of issue ids
    // return array of issue ids
  }

  private async registerWebhook() {
    const isWebhookRegistered = this.isWebhookRegistered(projectKey)
    const tasksToObserve = this.getTasksToObserve()

    if (!isWebhookRegistered) {
      const bodyData = `{
        "webhooks": [
          {
            "jqlFilter": "project = ${projectKey} AND issueIds = ${tasksToObserve}",
            "events": [
              "jira:issue_updated"
            ]
          },
        ],
        "url": https://parabol.co/webhooks/jira/webhook-received"
      }`

      const res = await fetch(webhooksRestUrl, {
        method: 'POST',
        headers: {
          Authorization: `Basic ${Buffer.from('email@example.com:<api_token>').toString('base64')}`,
          Accept: 'application/json',
          'Content-Type': 'application/json'
        },
        body: bodyData
      })
      if (res) {
        // do nothing
      } else {
        // throw error
      }
    }
  }
```

### To Do/Questions

- I didn't manage to find the correct syntax to pass an array of `ids` into the `jql` filter property, so the query above won't work - needs further research
- Whenever the user creates a new Jira issue and imports it into Parabol, we also need to update the `tasksToObserve` property and update the Webhook. This would require to add another `updateTasksToObserve()` method into the manager.
- Follow up documentation about dynamically registering Webhooks via Rest can be found [here](https://developer.atlassian.com/cloud/jira/platform/webhooks/#registering-a-webhook-using-the-rest-api--for-connect-and-oauth-2-0-apps-)

**Comment by eirelav-codes** [comment]
> What happens if our application goes down for a long time? Do we need to handle this situation in some special way?

Hi @igorlesnenko,

I found a couple of pointers regarding lifespan and availability limitations for Jira Webhooks in the documentation.

If our app wouldn't be available for a long time, Jira's Webhook requests to our API endpoint `api/webhooks/jira` would fail due to not being able to get delivered after the max amount of retries (more details below).

In that case, we would need to:

- Fetch a list of failed Webhooks 
- Extend those Webhooks lifespan

### Fetch list of failed Webhooks (note this is marked as experimental)

- Send `GET` request to `'https://your-domain.atlassian.net/rest/api/2/webhook/failed'`
- Full documentation can be found [here](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-webhooks/#api-rest-api-2-webhook-failed-get)

### Extend lifespan

- Send `PUT` request to `https://your-domain.atlassian.net/rest/api/2/webhook/refresh`
- Full documentation can be found [here](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-webhooks/#api-rest-api-2-webhook-refresh-put)

### Other remarks

- According to the documentation, Webhooks registered through the REST API expire after 30 days
- This means we'd need to call the refresh endpoint frequently, not only if our application goes down

**Comment by jordanh** [comment]
Closing this one as it had been worked on for a BP. If we want to do this one again, we can re-open a fresh Issue
