### ISSUE TITLE
Design promp to join org

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#7728]
Design the flow for a user to join an org that already exists within the same domain. 

AC:

- [x] User flow for new user 
- [x] User flow for existing domain billing leaders and team leads

**Comment by acressall** [comment]
Loom demo : https://www.loom.com/share/b6e3377146804ddebb7e8f87e06d1fe2

Figma: https://www.figma.com/file/yV4ESaWZIb5DaNXSTwlNqh/Join-org-prompt?node-id=0%3A1&t=hEsPY77RSJJm7H3u-0

Notion Brief: https://www.notion.so/parabol/Did-you-want-to-join-X-Org-Prompt-104a6a8bbb2b4addbb5fed632b53a3c6?pvs=4

Race conditions: 

- if someone else selects teams before me, I am then adding them to _additional_ teams. I can't remove them from a team, so there should be no conflicts
- If someone clicks "deny" before me, I can still accept the request from the notifications menu. These would be from my own list of teams
- If I click "accept" from the notifications menu after they have already joined, it allows me to add them to more teams (teams they are already a part of should be disabled)

@igorlesnenko in considering the race conditions, I'm leaning towards only showing the snackbar/ notification to team leads, so we can limit their list of teams to only the teams they are team lead of. WDYT?

**Comment by igorlesnenko** [comment]
@acressall After a request has already been processed, accepted or rejected by someone, should we allow the request to be processed again? If so, that means that once a request is sent, it gives permission to add the user anywhere and indefinitely. Is it ok? Example:

- There is a single requests attached to the `orgId`
- User who wants to join the org will see the request status in the sidebar (we wanted implement that later)
- If one billing leader has denied the request, request is marked as denied and disappeared from the user sidebar. Now if we add the user somewhere (for example by another billing leader), it will be made without the user's permission.
- If the request was accepted by one billing leader, request is also marked as accepted and gone from the sidebar. If other billing leader adds a user to another team, it will be made without the user's permission.

What do you think?

**Comment by acressall** [comment]
Thank you for clarifying! It helps to think of it as a single request. WDYT of this scenario:

1. New user sends request
2. Team lead A opens dialog to add to teams
3. Team lead B rejects the request
4. Team lead A clicks "add to teams" on their dialog, not knowing someone else rejected them
5. The "add to teams" now acts as a team _invitation_ and triggers invite emails to New User

This would keep the UX the same on the front end. Does it add too much complexity to the back end?
Alternatively, this could be a V2 scenario, and v1 would show a snackbar error "Sorry, [Team Lead B] denied the request to join"

**Comment by igorlesnenko** [comment]
@acressall I tried to think one more time on this:

- The user knows nothing about organizations within the domain
- Therefore, it does not matter to him that one organization has rejected the application, and the other is still not. 
- Even if we show him the names of organizations, it probably won't tell him anything, and it wouldn't make sense for him to withdraw the request from some organizations and leave it with others

What if we do the following:

- We have a single "Join request" that is attached to the whole domain, not to specific orgs
- However, we still send push notifications to the specific users, to billing leaders/team leaders of organizations that match our criteria:
  - At least 1 active team, More than 1 active user, Is not enterprise, has a feature flag
- The request has an expiration date, for example 1 week.
- In future, request can be canceled by the sender before the expiration date
- While the request is active (not expired or canceled), any team leader or billing leader can add the user to any of the leader's organization on the specified domain (except enterprise). They can even create a new org and add the user in it.
- We show some teams in grey if the user is already added in it
- Deny button closes the snackbar, but other billing/team leaders can still add the user
- If the request was canceled or expired, instead of adding a user we send invites as you suggested.
  - Is it ok to send 10 invites to a user if I selected 10 teams? 
  - For V1 we can show "request expired" error instead.

What do you think?

**Comment by acressall** [comment]
> We have a single "Join request" that is attached to the whole domain, not to specific orgs
However, we still send push notifications to the specific users, to billing leaders/team leaders of organizations that match our criteria:
At least 1 active team, More than 1 active user, Is not enterprise, has a feature flag

This is roughly what I was imagining, so it sounds good to me

> The request has an expiration date, for example 1 week.

This is a great addition

> While the request is active (not expired or canceled), any team leader or billing leader can add the user to any of the leader's organization on the specified domain (except enterprise). They can even create a new org and add the user in it.

I like this, but would want to do the adding to a new org as a v2 enhancement

> We show some teams in grey if the user is already added in it

👍 discussed this with Terry, and we came to the same conclusion

> Deny button closes the snackbar, but do not cancel the whole request, other billing/team leaders can still add the user

I like this. The snackbar would be closed for others too, right? They would be able to still add the user via the notifications menu?

> If the request was canceled or expired, instead of adding a user we send invites as you suggested.
Is it ok to send 10 invites to a user if I selected 10 teams?

I think it's ok -- it would be good if we can track this and see if there's an average # of teams a user gets added to. In future, we could see if we can create a new version of the invite that includes multiple teams if we find there are a large number

> For V1 we can show "request expired" error instead.

Yep, good with this!

**Comment by igorlesnenko** [comment]
> I like this. The snackbar would be closed for others too, right? They would be able to still add the user via the notifications menu?

I would probably keep their snackbars, as they probably have different set of available orgs and teams and can react on the snackbar differently. They always will be able to go to notifications menu too.

> I like this, but would want to do the adding to a new org as a v2 enhancement

Even without special functionality, they still can create an org through the usual interface and then open the add to team dialog again.

**Comment by acressall** [comment]
> I would probably keep their snackbars, as they probably have different set of available orgs and teams and can react on the snackbar differently. They always will be able to go to notifications menu too.

Sounds good!

> Even without special functionality, they still can create an org through the usual interface and then open the add to team dialog again.

Yes, that's true! I just wasn't ready to add that to the dialog yet ;)
