### ISSUE TITLE
When I'm in the meeting, I don't need to see the mention notification snackbar

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#7876]
I was right there in the meeting so I think it's a little bit annoying to see the notification:

<img width="623" alt="Screenshot 2023-03-07 at 08 23 22" src="https://user-images.githubusercontent.com/1879975/223484978-f1591bcc-a2c0-4704-896b-1d290f8ddda3.png">

### Acceptance Criteria (optional)
Users can:
- [ ] When the user is in the meeting, don't show the mention notification

**Estimated effort:** X points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by ackernaut** [comment]
This makes me wonder what notifications we should show in the meeting views? In the dashboard context, I would expect to see any activity. While in a meeting (sync or async) I’m not sure I want to see notifications about another meeting.

What would I expect to see in a meeting? Maybe if somebody is trying to join the team/meeting? Maybe if somebody mentioned me or commented on a thread in some other phase or stage of the meeting?

I think we should think about this and come up with some general parameters around where notifications show up.

**Comment by ackernaut** [comment]
I wonder what use cases we should think about it and how we want to handle them?

In the dashboard I would expect to see notifications from any context.

Within a meeting I wouldn’t expect to see notifications unless it had to do with the meeting:

- Somebody is trying to join the team/meeting
- If the activity has many phases and stages, what if somebody had mentioned me on some thread, especially in an async context? It might be helpful to have a way to see where people responded so that I can go answer questions or understand feedback. Maybe the snackbar is too obtrusive and can’t handle assumptions about sync/async?
- I agree it’s annoying to see a notification when you were there in the moment

**Comment by jmtaber129** [comment]
This will be solved by **https://github.com/ParabolInc/parabol/issues/7627**. I'll leave this open in case there's a small thing that will fix this but not https://github.com/ParabolInc/parabol/issues/7627.
