### ISSUE TITLE
Parabol emails going to spam

### ISSUE THREAD

**Issue by ayo-yemi** [ParabolInc/parabol#7948]
Whenever I email [my contact](https://app.hubspot.com/contacts/3888472/contact/60782151) at Omnicell, my emails go into his spam. And whenever I email him, I get an immediate error message saying "Message not delivered". 

{

![Image](https://user-images.githubusercontent.com/112553277/227996016-55de13b8-f706-45e0-89e9-33a0e6f558b1.png)

![Image](https://user-images.githubusercontent.com/112553277/227996105-d80fa196-2520-4979-8ef1-45a2db22ab89.png)

Screenshots attached}

**Comment by mattkrick** [comment]
Problem: we had 2 SPF records in our DNS. 
I merged them, but that resulted in 12 DNS lookups (max allowed is 10). So I removed mailgun.net since both.net & .org resolve to the same _spf subdomain.
This should fix it!

**Comment by mattkrick** [comment]
The problem still existed so I removed the `mail.parabol.co` domain since that didn't have an SPF record (and doesn't need one it should inherit from the parent domain).

According to mailgun, all we need in mailgun.org (see table below from https://app.mailgun.com/app/sending/domains/mail.parabol.co/dns)


Status | Hostname | Enter this value | Current value |  
-- | -- | -- | -- | --
Verified | mail.parabol.co | v=spf1 include:mailgun.org ~all | v=spf1 include:mailgun.org ~all

**Comment by jordanh** [comment]
@mattkrick would this one be safe to close now?

**Comment by mattkrick** [comment]
This is still ongoing unfortunately... https://parabol.slack.com/archives/C4JAUUZ9P/p1681242341461739?thread_ts=1679566674.572709&cid=C4JAUUZ9P

**Comment by mattkrick** [comment]
Fixed! 

Here's how we fixed it:

> I added an SPF record for [mail.parabol.co](http://mail.parabol.co/) & only included mailgun in the SPF.

This works because mailgun only sends from mail.parabol.co subdomain, where hubspot, et al send from parabol.co.
