### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getLinkedRecord')

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8090]
https://parabol.sentry.io/issues/4079926867/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'getLinkedRecord')
  at acceptTeamInvitationNotificationUpdater (./packages/client/mutations/AcceptTeamInvitationMutation.ts:110:24)
  at value (./packages/client/subscriptions/subscriptionUpdater.ts:1:440)
  at fn (./packages/client/subscriptions/subscriptionUpdater.ts:17:51)
  at _optionalChain (./packages/client/subscriptions/subscriptionUpdater.ts:1:418)
  at updater (./packages/client/subscriptions/subscriptionUpdater.ts:17:5)
...
(17 additional frame(s) were not displayed)
```

**Comment by Dschoordsch** [comment]
88 events, 48 users

**Comment by jmtaber129** [comment]
I can reproduce this locally with the following steps:
* Open two windows with Parabol logged into User A's account
* Navigate to a meeting User A doesn't have access to.
* As user B, approve of User A joining the team
* The main window of User A behaves properly, but the other window throws the error.'

I haven't tracked down the root cause, but this likely only recently surfaced because we were previously always checking that the `payload` passed to `acceptTeamInvitationNotificationUpdater` was non-null, but this is not guaranteed with the current subscription updater added as part of the relay upgrade (see https://github.com/ParabolInc/parabol/blob/05f27d1510368eec2d60e0b861071ed51f0c7ba6/packages/client/subscriptions/subscriptionUpdater.ts#L15-L17).

We could change the `subscriptionUpdater` to check that `field` is non-null as a bandaid solution
