### ISSUE TITLE
User can still access the meeting if the organization was deleted

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8140]
Steps to reproduce:

- Create a meeting
- Then delete the whole org
- The meeting is still accessible using URL and you can't end it

AC:

- Meetings from removed org should not be accessible

**Comment by mattkrick** [comment]
Ah, this is because we explicitly allow ex team members to view the meeting as long as they were a part of it.  https://github.com/ParabolInc/parabol/blob/9177909d9b3bc9cf2ba5d88a32c0ce53b1da177f/packages/server/graphql/queries/newMeeting.ts#L29-L32

however we don't extend this same permission to _doing_ things in the meeting, like ending it.

maybe we just end all meetings when a team gets archived?

**Comment by igorlesnenko** [comment]
Hi @Shivanshu-09! Yes, all the bugs are listed in the issues. Did you try searching using "bug" label?https://github.com/ParabolInc/parabol/labels/bug

**Comment by Shivanshu-09** [comment]
@igorlesnenko, Yes found with the "bug" label, but guess most have been taken up.

**Comment by igorlesnenko** [comment]
@Shivanshu-09 below filter might work, these are bugs that are not assigned to anyone: https://github.com/ParabolInc/parabol/issues?q=is%3Aopen+label%3Abug+no%3Aassignee

We also have a separate label "help wanted":
https://github.com/ParabolInc/parabol/issues?q=is%3Aopen+label%3A%22help+wanted%22+no%3Aassignee

For example, this might be good issue to start with: https://github.com/ParabolInc/parabol/issues/6093
