### ISSUE TITLE
Docker build consistency

### ISSUE THREAD

**Issue by rafaelromcar-parabol** [ParabolInc/parabol#8213]
## Description

Docker images are built using either the `docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile` or the `docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile`. In both cases, during the build process, there is a step where the security checks will run and update packages on the OS of the image (Red Hat 8.6 right now). This leads to unconsistent builds where you could build the application, on a given commit, in two different moments (say today and in 3 months) and the resulting images wouldn't be the same.

This is part of the process due to the improvements it brings on security, but security cannot go against consistency and best practices. We might want to produce our own base images from Red Hat and NodeJS images, and use them a base image for our application builds. We could built those images every two or three weeks, and then change the tag on the dockerfile used to build the application.

Thanks to that, at a given commit, every time the image is built, it will produce the SAME image as result, unless specified otherwise.

**Estimated effort:** 12 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by mattkrick** [comment]
> This leads to unconsistent builds where you could build the application, on a given commit, in two different moments (say today and in 3 months) and the resulting images wouldn't be the same.

This is a feature, not a bug! There's a new vulnerability called Spectre-HD that was discovered in February. If we built a commit from January, we should absolutely include the 0-day patch to mitigate the new Spectre attack. If we didn't, it would be irresponsible & open us up to attack. 

This is also unavoidable for many parts of the app:
- external services can change their API, which would cause our app to break
- the list of polyfills we include are generated automatically based on what browsers currently support (see browserslist). Building in 6 months from now could very possibly include fewer polyfills because the majority of browsers would be able to support the new feature natively

tl;dr IMO, simple & secure is better than consistent
