### ISSUE TITLE
Users can't join meetings if part of a locked team

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#8238]
Currently, if a user is part of any locked teams they can't join new meetings or teams, this is an issue for orgs that upgrade 1 or 2 teams to a Team plan and we don't merge the rest of the teams for their domain. This has also been an issue when a sales rep unlocks 1 or 2 teams and some of the users are not able to join meetings on the unlocked teams.

There have been 2 instances of this for paid accounts so far, this [customer](https://app.hubspot.com/contacts/3888472/company/2985895289) 🔒 and this [customer](https://app.hubspot.com/contacts/3888472/company/992592285) 🔒

**Comment by lilicaruso** [comment]
[Instance 1 ](https://app.hubspot.com/contacts/3888472/contact/96101251) 🔒 
[Instance 2](https://app.hubspot.com/contacts/3888472/company/3378227929) 🔒 
[Instance 3](https://app.hubspot.com/contacts/3888472/contact/111430251) 🔒 
[Instance 4](https://app.hubspot.com/live-messages/3888472/inbox/4544379288#email) 🔒 

All of mine occurred following a lock out where the customer did wanted to return to a Starter plan but because some members were already on locked teams they could not join new teams or meetings.

**Comment by charlesmathias** [comment]
One idea around this: could we make "Manage Team" visible for a user when a team is locked? This would mean a user could remove themselves from locked teams

**Comment by mwermuth** [comment]
@gcrickman and @lilicaruso has this come up again? Or where the only instances this happened occurring in May?
