### ISSUE TITLE
Incorrect pending invoice on Billing page

### ISSUE THREAD

**Issue by charlesmathias** [ParabolInc/parabol#8380]
A recently-upgraded Enterprise org is seeing an incorrect history of their invoices on the Billing page of their upgraded organization. See attached the screenshot.

The [user](https://app.hubspot.com/contacts/3888472/contact/61964701) 🔒  logs into Parabol with this email but relevant correspondence can be found [here](https://app.hubspot.com/contacts/3888472/contact/146342351) 🔒 .

![Image](https://github.com/ParabolInc/parabol/assets/101657889/44709cb7-4ce8-4ece-8561-88afc7ac711f)

**Comment by jordanh** [comment]
Wow. That's a hefty bill. I will assign this a `p2` and hand it to the squad that is closest to revenue operations

**Comment by tianrunhe** [comment]
This is not an active bug within the app. It'd due to a malformed Stripe subscription. More details [here](https://parabol.slack.com/archives/C029ZTH0EL9/p1686851549350349?thread_ts=1686844072.398209&cid=C029ZTH0EL9). TLDR: We will manually delete that invoice item from our DB so it won't show up for the customer.
