### ISSUE TITLE
Translate json / xml / po files in spanish and italian

### ISSUE THREAD

**Issue by johnfelipe** [ParabolInc/parabol#8490]
I want to know if this app have i18n support, i want to contribute to translate strings to spanish and italian
stay alert

**Comment by Dschoordsch** [comment]
There once was a [PoC](https://github.com/ParabolInc/parabol/pull/7155) of translating the app, but we've decided to not move forward with it back then because we wanted to focus on other features and this requires ongoing effort.
We track user requests however and I've added your request to it, so we get a better picture of how big demand is and we might reprioritize this in the future.

**Comment by johnfelipe** [comment]
I think you only create english strings in any file format po / json / xml / ts, etc
i want to become contributor or collaborator for spanish and italian translation

**Comment by johnfelipe** [comment]
I18n support then is not a feature still?

**Comment by Dschoordsch** [comment]
I18n is not implemented on our side. We did not extract all strings yet to be able to just exchange the translation. There is some discussion around prioritizing this feature.

**Comment by mwermuth** [comment]
Came up during our backlog grooming session. We have this noted down in our Problems & Ideas Backlog and noted down another vote from you @johnfelipe. 

If we start this work we'll let you know.

**Comment by mwermuth** [comment]
@johnfelipe sorry I don't understand?

We had a meeting (session) going through our backlog to sort through open issues. And we closed this one down, as we took note of this in our internal documentation. It is on our future list of things to look at.

**Comment by johnfelipe** [comment]
Any progress for translate to Spanish and Italian?
