### ISSUE TITLE
Remove "Need to cancel? It's painless. Contact Us" 

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8515]
If the user upgrades to Team, it says "Need to cancel? It's painless. Contact Us" even though we've built the "Downgrade" logic in the Plans section. 

I suggest we remove this or replace "Contact Us" with "Downgrade". Clicking "Downgrade" would then downgrade their account, although we'd probably need to give them feedback after clicking it. 

![Screenshot 2023-07-14 at 15 57 28](https://github.com/ParabolInc/parabol/assets/39854876/310f6742-1417-448a-99c7-3cc95e99dc2c)

Also, if you're not the billing leader and you go to the Org Settings, you see an empty page (this happens in the old checkout flow too). 
![Screenshot 2023-07-14 at 15 20 13](https://github.com/ParabolInc/parabol/assets/39854876/862c64d1-3440-464f-ac51-3a5b1d165f70)

But this should be resolved when we implement the AI Toggle: https://github.com/ParabolInc/parabol/issues/8021

### AC

- [ ] Remove "Need to cancel? It's painless. Contact Us"

**Comment by nickoferrall** [comment]
@acressall it'd be great to get your thoughts on whether we should remove this or come up with a new downgrade view here?

**Comment by acressall** [comment]
Good catch @nickoferrall! I think we should update to something like this:

> Need to make a change? It's painless. View plans [link to plans section of billing & plans view]

How does that feel to you?

> Also, if you're not the billing leader and you go to the Org Settings, you see an empty page (this happens in the old checkout flow too).

I think it's a _little_ better in the new flow because it's no longer the _first_ thing you see. We could consider hiding this tab altogether for non-billing-leads, but I'd want to make sure future settings we add here are billing-lead-only before we do that. I think we should leave it as-is for now and consider updating it when we add more settings here
