### ISSUE TITLE
Add invite to team button to the Teams View

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8518]
On the Teams View, it could be helpful if there's an invite to team button so that users can quickly invite colleagues to their team.

At the moment, we’re only showing the Teams View to billing leaders in case users don’t want their teams to be visible to everyone in the org. We could:

- Show the Teams View to everyone in the org, but only billing leaders see all the teams. Others only see the teams they belong to (we could clarify this in the UI).
- Include an invite to team link or button in each table row. Clicking on it would open the “invite to team” modal that already exists in the app.

Perhaps we should add the Invite icon above the Team Lead email?

![image](https://github.com/ParabolInc/parabol/assets/39854876/0310558f-15d7-424b-a23f-0ee633592ba4)
![image](https://github.com/ParabolInc/parabol/assets/39854876/eed2124b-9f4f-4880-874c-e8f7fc434b5c)

Will make this a design issue to start with as I'm not sure what the best view would be. See [Slack thread](https://parabol.slack.com/archives/C042E8PGPD4/p1689345875449659) for further context. 

### AC

- [ ] Design created adding an "Invite to Team" button to the Team View

**Comment by acressall** [comment]
Curious what you think of [this concept](https://www.figma.com/file/bjpKrqtAf3zO2UMe6QoA17/View---Org-%3E-Teams?type=design&node-id=201-387&mode=design&t=MAjQBFsXzD3WKiFu-4) @nickoferrall

- Viewers can invite members to teams they are on, team lead or not
- Billing leads can not invite to teams they are not on -- I think a future version would give them the ability to join the team first
- The "invite to team" link is near the member count and manage team, since it's a related setting
- I've added a link to "add team" at the top right of the table, because why not? I think this would link to the normal add team view
<img width="1280" alt="Desktop - org - teams - birthday cake (1)" src="https://github.com/ParabolInc/parabol/assets/18582225/18830206-5d4d-4c0f-b66b-6b350a7718f0">

**Comment by nickoferrall** [comment]
I like it! It's possible the user wouldn't like seeing two blue links or might think they're the same link, but I don't think there's an obvious "invite" icon, so it would probably need to be a hyperlink. It's a very easy change to implement, which is also a big plus.

I think it's a good idea to let users add a new team from the teams view. It feels obvious in hindsight 😄 But I don't love having two header rows on the table, partly from a UI perspective and partly because it's harder to implement. 

What do you think of a stand-alone "Add Team" button on the same rows as the "Teams" title but on the right-hand side?

Here's how the table currently looks in prod:

![Screenshot 2023-08-22 at 15 27 31](https://github.com/ParabolInc/parabol/assets/39854876/d23ca307-8b10-4f26-82c9-4f8913a2ef40)

**Comment by acressall** [comment]
Good catch @nickoferrall ! I forgot we removed that extra header

> What do you think of a stand-alone "Add Team" button on the same rows as the "Teams" title but on the right-hand side?

I like this solution!
