### ISSUE TITLE
User get's error when trying to start a meeting

### ISSUE THREAD

**Issue by gcrickman** [ParabolInc/parabol#8609]
This [user](https://app.hubspot.com/contacts/3888472/record/0-1/6949001) 🔒 reported they could not start a meeting. Here's the [link to the Slack thread](https://parabol.slack.com/archives/C4JAUUZ9P/p1690897413727269) with the screenshot. The error appears whenever they click on the "add meeting" button.

Additional context:  

> First - I'm running into an issue where the interface is getting really slow (on an iMac on Safari - but also on my iPhone 12) when dragging cards from one column to another. I'm wondering if it is because I have a lot of unarchived cards (635 in one column). If this is the case, is there a way to mass archive a bunch of cards at once?

**Comment by mwermuth** [comment]
This came up during Backlog Grooming.

@gcrickman it might be related to the performance due to having too many tasks. We'll classify this as a P3 as this not happening for a lot of users.
But you could let the user know that, if they are able to start a Check-In Meeting, all tasks that are in done will be archived once that meeting concludes. Maybe something they could try.
