### ISSUE TITLE
Gcal Integration: handle error state

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8635]
If you click the CTA in the gcal modal, you create both the gcal event & the meeting. However, if there's an error and the gcal event can't be created, we need to give the user feedback.

See Matt's Loom example: https://www.loom.com/share/025b4d6d67734a52afab73c04ddfdb21

A few options I can think of:
- Create the meeting, take the user to the meeting, and show a snackbar letting them know that the gcal event wasn't created
- Create the meeting, but don't take the user to the meeting. Show an error message in the modal letting them know the gcal event wasn't created
- Don't create the meeting, show the error message in the modal
- Separate the button so that you create the gcal event and meeting separately

I prefer the first two options, leaning towards the snackbar.

### AC

- [ ] Design created or agreed upon to handle gcal errors

**Comment by nickoferrall** [comment]
@acressall it'd be great to get your thoughts on this one when you get the chance. It's not urgent, but I'd like to implement it within the next week or so

**Comment by acressall** [comment]
@nickoferrall what do you think of showing the auth flow for gcal if they 1. hit the create meeting & send invite btn and 2. don't have the integration already connected? I think the great thing about showing the schedule btn even when there integration isn't added is the awareness it creates -- so could we connect in this context? I would expect that once I've authed the meeting will start. If, for some reason, I decided _not_ to authenticate when prompted, then the meeting can start and we can let them know via snackbar that the invite was not created because they didn't connect to gcal
