### ISSUE TITLE
Empty Meeting View: card to 'invite team members' 

### ISSUE THREAD

**Issue by avivapinchas** [ParabolInc/parabol#8639]
### Design issue

_Describe the goal of your work or the problem you are solving._

When users initially sign up for Parabol, they land on the empty meeting view. The next step in onboarding is to invite team members, but this isn't explicit on the screen. We should make the next step explicit. 

[Background in this Slack convo](https://parabol.slack.com/archives/C03DSA15H9C/p1691593977162249) 🔒 

## Design checklist

- [ ] Is the end-to-end flow complete?
- [ ] Have you considered all possible states and scenarios? ([See our UI State Checklist](https://www.notion.so/parabol/UI-State-Checklist-a90cc393612f4a0588144f897dee848a?pvs=4))
- [ ] Have you confirmed that the interactive components in your work have all the necessary states designed? (focus, hover, disabled, etc)
- [ ] Have you considered all the breakpoints required for a responsive interface? (S, M, L)
- [x] Have you had a design peer or maintainer review your work?
- [x] Have you had a developer review your work?

**Comment by acressall** [comment]
Rather than adding an invite card to the meeting view, I'd like to change the screen new users land on. Rather than landing on the empty meetings view, they can go to their default team dashboard, with the manage team panel open (which will have an invite link). This gives them the context of a "team" in Parabol and possible next steps:

1. explore the meetings (demo, poker tutorial), or
2. invite team right away

Here's a figjam of possible routes https://www.figma.com/file/OQ5pKo7ei2NaWQ58QTep21/Login-routes?type=whiteboard&node-id=0%3A1&t=d1ldi7GVnRETV8oM-1

**Comment by acressall** [comment]
@ackernaut can you give this a quick review? There's no visual design changes, only the flow

**Comment by ackernaut** [comment]
I left some questions on the FigJam. Overall, I think the flows make sense 👍
