### ISSUE TITLE
Delay on processing Stripe invoices

### ISSUE THREAD

**Issue by tianrunhe** [ParabolInc/parabol#8744]
## Issue - Bug

It looks we have a couple of examples recently where we have huge delay on processing Stripe invoices.
### Example 1
[This user](https://dashboard.stripe.com/events/evt_1Nk34iFLaFINmHnB9VVXw2VK) had an invoice finalized 08/28 10:53AM UTC but it was not created until 1 day later in our DB:

<img width="894" alt="Screenshot 2023-08-29 at 11 23 15" src="https://github.com/ParabolInc/parabol/assets/1879975/a7349baa-d9ec-4edd-8f69-48452863f970">

### Example 2
[Parabol](https://dashboard.stripe.com/invoices/in_1NihlWFLaFINmHnBykTX69PF) had an invoice finalized 08/24 12:01PM UTC but it was not created until almost **5 days** later in our DB:

<img width="923" alt="Screenshot 2023-08-29 at 11 25 24" src="https://github.com/ParabolInc/parabol/assets/1879975/0d986d95-9dee-4483-9318-3580d6846b42">

### Acceptance Criteria (optional)
- [ ] When an invoice was paid & finalized in Stripe, Parabol should receive & process the notification in near real-time, and create the invoice in our DB immediately

Triage is performed to find the root cause of the bug, timeboxed to ~1 hour. 

**Estimated effort:** 1 hour to triage. More if root cause is already identified.

**Comment by nickoferrall** [comment]
- Most invoices are created in our db within ~10 minutes of them being created in Stripe
- For invoices that are created in our db at the right time and for invoices that are created several days late, the `invoice.created` webhook event doesn't exist in Stripe, so that's probably not the issue
- [Here's](https://dashboard.stripe.com/payments/pi_3O0voPFLaFINmHnB0U0Cffat) another example of an invoice created 3 days late. [Here's](https://dashboard.stripe.com/payments/pi_3O1CMUFLaFINmHnB1CFjIn1I) an example of an invoice created on time
- On the [dashboard](https://dashboard.stripe.com/developers), there are many requests using the 2017 API version, but they're all from a python request, so I imagine that's being used in some internal tooling. The [application](https://dashboard.stripe.com/logs?direction[0]=connect_out&direction[1]=self&created[gte]=1697068800&created[lt]=1697155200&api_version=2020-08-27) is using the 2020 API version 

I'll pause work on this as implementing the template limit test is higher priority.

**Comment by nickoferrall** [comment]
I haven't made progress on this for a while so I'll unassign myself for now

**Comment by mattkrick** [comment]
I'm happy to pick this one up, but before I do, I'm curious about the future of invoices!
I noticed that when a user clicks an invoice, we redirect them to the stripe invoice. It looks like we do this for all invoices except upcoming invoices.
The original purpose of the Invoice object was to handle the complexities of paused accounts, proration, etc. If those complexities are gone, perhaps we should just nuke `Invoice` all together?

**Comment by nickoferrall** [comment]
> The original purpose of the Invoice object was to handle the complexities of paused accounts, proration, etc. If those complexities are gone, perhaps we should just nuke Invoice all together?

I think that makes sense! We can just query Stripe directly instead

**Comment by mattkrick** [comment]
Invoice table is no more, closing as we let stripe handle this stuff for us now
