### ISSUE TITLE
Activity Library track search queries

### ISSUE THREAD

**Issue by ackernaut** [ParabolInc/parabol#8756]
### Background
It could be useful to know what folks are searching for in the Activity Library:
- Are they finding what they’re looking for? How often does a query yield no results?
- What words do they use to describe what they’re looking for? Are we labeling things well?
- What activities might they expect to be in the product that are not there?

**Here’s an example** from today (Wed Aug 30 2023). I typed ‘sprint poker’ and got **_no results_** 👻 but when I typed ‘poker’ I got many results if not all activities from the Estimation category.

### Acceptance criteria
- Developed a spec for a first version of search tracking
- Picked what’s in, what’s out, and what’s deferred to a later version

### Estimated effort
- 8 hours

**Comment by mwermuth** [comment]
Hey @ackernaut - @tianrunhe had a good point when we looked at that during Backlog grooming.

Tracking the pure search queries isn't really helpful from a data perspective, as there can be any kind of input. But rather maybe save all the search results in PG or any other data storage. So that we can look and search that if we wanted to. 

Any thoughts on this?

**Comment by tianrunhe** [comment]
My point was mainly from data architecture perspective: `searchQuery` is not a good column to key on because its cardinality is too high. But I guess we won't index on that column, will we? So I think we can just emit to Amplitude like other metrics we have.
