### ISSUE TITLE
Share summary: disable default slack notifications if initially connected from share topic

### ISSUE THREAD

**Issue by igorlesnenko** [ParabolInc/parabol#8763]
- I had no slack integrated
- I integrate it for the first time from share topic and select default channel
- I'm starting to get meting started etc notifications in this channel, but maybe I don't want too

AC:
- If there was no slack integration and user first integrating it using share topic, do not enable default slack notifications

**Comment by Dschoordsch** [comment]
From my perspective I would opt for more notifications to increase visibility. The user can still disable it if they're annoyed. Unless we get a lot of feedback from customers.
@acressall what do you think?

**Comment by acressall** [comment]
I lean towards @Dschoordsch's point, that they could disable if they wanted. I think we should keep an eye out for any complaints while testing and treat this as an enhancement if users do get frustrated.

Related: I _think_ I saw the other squad discussing adding more detailed settings for the Slack integration, so that might help

**Comment by igorlesnenko** [comment]
I agree, we can wait for complaints if there are any.
