### ISSUE TITLE
Self serve SAML can throw error "Requested query string is too long"

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8894]
A [customer](https://parabol.slack.com/archives/C4JAUUZ9P/p1695823767339129) 🔒 was having trouble setting up SAML with Microsoft. It appears sending the metadata as payload can be too long.

Proposed fix is:
* [ ] modify `parseSAMLMetadata` to store the new metadata in a temporary table (redis?) and only encode the key
* [ ] in `loginSAML` check the db

**Comment by mattkrick** [comment]
I dug around to see what other apps do for this.
It looks like both IdPs and SPs pass around metadata URLs instead of metadata itself. This makes sense because pasting a link is so much nicer vs. pasting a blob of XML. Of course passing a link also means we won't come anywhere near the AAD limit of 2048 chars. That also means we don't have to persist state anywhere.

So, if we request the metadata URL & then on the server we fetch the XML blob, we can persist that to the DB. However, if we don't persist the URL to the DB then we can't display the current URL that they are using. Basically the UI will be kind of like a env secret is treated in github or circleCI where we show the presence, but not the value itself. That's kind of annoying, so I'll just add `metadataURL` to the DB so we can let them update that, but we also don't have to fetch the underlying metadata on every login. The metadata will not change for a given IdP<->SP connection.

<img width="594" alt="Screenshot 2023-10-02 at 11 15 22 AM" src="https://github.com/ParabolInc/parabol/assets/5514175/c299c3d8-0879-4ec5-ae2d-8b784cfa73a7">

<img width="687" alt="Screenshot 2023-10-02 at 11 15 36 AM" src="https://github.com/ParabolInc/parabol/assets/5514175/5d7124ec-9b3e-4bba-87ed-9defbca23fab">
