### ISSUE TITLE
Shutdown: kick off users from websocket server in batches

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8903]
When receiving `SIGTERM` we need to properly disconnect all users from the websocket server. We should do it in batches to not overwhelm the replacement with new connections. The default grace period is 30s but should be configurable from the environment

## Acceptance criteria
* ​add a sigterm handler
  * stop accepting new connections
  * cuts websocket connections in batches based on configured grace period (like for 30s grace period kick off 1/25th every 1s)

**Comment by mattkrick** [comment]
2 strategies:
- when a client disconnects, wait randomly from 0 - 2 seconds until trying to reconnect
- when k8s is about to take down a pod, it sends a SIGTERM to the server. we listen to that & send a message to all clients. Then, we disconnect anywhere from 0 -60 seconds.

the 2nd is more complex, but spreading the reconnections across 60 seconds is 🤌

**Comment by rafaelromcar-parabol** [comment]
[Useful doc](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace) about how Kubernetes manages will send the signals

**Comment by mattkrick** [comment]
After going through the new release playbook it's clear that this is the biggest issue facing DevOps today-- we should release at any time of day.

For that reason, I'm going with the 2nd option. One day, we'll have so many users that a 2 second window won't be enough, so supporting an arbitrarily large window seems like the right move.

Here's how i envision it:
- K8S sends a SigTerm to the webserver pod
- the pod sends a message to each of its connected sockets. Options:
  - keep a Map of connection contexts & iterate over it
  - build our own event emitter (`addEventListener`) since all we're given is a single callback `process.on("SIGTERM')`.
  - publish to the user channel on redis & have the client ignore duplicate messages. if they have multiple tabs open. I like this the best since it's 1 less stateful object to worry about leaking memory
- the server decides when each client should reconnect. 
  - we could do this intelligently by seeing if they are in a meeting & if they are, deterministically turning the meeting ID in a number from 0-30 and that's how long they wait until they disconnect. That guarantees all meeting participants reconnect at the exact same time. Then all others could reconnect in the 31-60 second window. 
  - We could do it naively by picking a random number. That could cause meeting disruptions, especially if new, large features are introduced
