### ISSUE TITLE
SAML UI: missing entries for config

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#8908]
Previously we had send the customer 3 URLs:
* ACS URL: https://action.parabol.co/saml/${slug}
* Entity ID: https://action.parabol.co/saml-metadata/${slug}
* Start URL: https://action.parabol.co

Currently we're only showing the first, which leads to wrong configs by the customers.

**Comment by mattkrick** [comment]
Related #8894, which will replace the metadata text area with a metadataURL input.

Here's a BAD version. I want to get @enriquesanchez to check it out & see what would look good

<img width="676" alt="Screenshot 2023-10-02 at 2 09 39 PM" src="https://github.com/ParabolInc/parabol/assets/5514175/65922988-a45c-48bd-a451-e1a549adae67">

**Comment by enriquesanchez** [comment]
Here's a first pass at this:

![image](https://github.com/ParabolInc/parabol/assets/3276087/f974512b-2774-4bff-98ea-f5e5adfe9211)

You can [find the Figma here](https://www.figma.com/file/okoRD7I7lZR08V4Zk7O7G6/random?type=design&node-id=1702-1148&mode=design&t=D3xfXOAZ60P0Cr15-4).

One question: do we change the heading "SSO Enabled" to something else when this is disabled? If so, what does the disabled status currently looks like?

One note: I don't think the configuration URLs should be links, users are expected to copy those and not click on them, so remove the link avoids any confusion or accidental clicks to weird URLs.

@mattkrick how is this looking?

**Comment by mattkrick** [comment]
Yep! If it's not set up it looks like this https://www.figma.com/file/veEiStrSPlBvKgLNVgRNQg/Org-Settings?type=design&node-id=536-1284&mode=design&t=r02kjexmXLLg4OJH-4

I may just leave that top part the same since it'll take some time redoing a couple states & handling a list of domains

The biggest difference I see between this one & the other designs in figma is the padding for the headings. You want to have everything line up on the left?

**Comment by enriquesanchez** [comment]
>I may just leave that top part the same since it'll take some time redoing a couple states & handling a list of domains

I intended this to be a small change to improve hierarchy: a bigger check icon and flipping the order of the list of domains and the contact text, but I'll let you decided what's the best approach.

>The biggest difference I see between this one & the other designs in figma is the padding for the headings. You want to have everything line up on the left?

Yes, otherwise the eyes have to zig-zag while scanning each sub-section. I see you want to align the text, but the text area borders are also part of what the eye scans.

Another difference is how we display the URLs, I think this table view is an improvement.

I'm happy to iterate more on this, just let me know if you had something else in mind 👍

**Comment by mwermuth** [comment]
I think we can close this out as it has been merged to production already. Thanks @mattkrick
