### ISSUE TITLE
Template Limits v2: add template limit flag to new users

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#8971]
Predecessor: https://github.com/ParabolInc/parabol/issues/8914

### AC

- [ ] If any shared `orgUsers` have the feature flag, add the feature flag
- [ ] Half of new users are added to the feature flag

**Comment by nickoferrall** [comment]
@tghanken is there an example we can follow for this? Do you have thoughts on how we can determine which new users will be added to the feature flag?

**Comment by nickoferrall** [comment]
@tghanken I'm wondering if you have a pattern in mind for A/B testing with new users or whether that's up to the implementer?

We could make this an org feature flag. We'd store an A/B boolean flag in Redis. When a new user is created (excluding new users that are accepting an invite to a team), we add the flag to their newly created default org. We'd toggle the boolean, so the next new user gets the opposite flag. 

All users that are accepting an invite to an existing team/org would have the template limits as all Starter orgs currently have template limits.

A problem with this approach (and any approach, I think) is a user creates a free account, doesn't have any template limits, and then joins a team that does have template limits.

**Comment by tghanken** [comment]
Here's how I was thinking about it:
1. When the user signs up, we pull the list of orgs with a matching domain
2. We check to see if any non-removed orgUsers on those domains have Template Limits enabled.  If so, enable template limits for the new signup, if not disable template limits
3. For the remaining signups where we don't have a domain match, simply randomize them roughly 50/50 into limit/noLimit cohorts (no need for something as precise as a flag in Redis)

With this, limits should be fairly viral throughout a domain and any associated domains, while keeping almost all of the assignment logic as a one-time run at signup.

There are likely going to be some edge cases like you mentioned where a user won't have template limits, then later joins an org with template limits, but I don't think it'll be too significant and there's still things we can learn from that.  Does that user start to create more meetings for that org, since they have access to the templates? That validates there's some need/desire to use templates, but the org hasn't hit the level of tension where they're willing to pay.

**Comment by nickoferrall** [comment]
Sounds good to me! The user flag means a more inefficient query, but there usually aren't _that_ many users per org. 

I agree that we should do what we can to prevent users at the same company getting a different template experience, but it's not the end of the world if there are some edge cases. We would learn from them.

**Comment by tghanken** [comment]
If we see this affecting a significant number of users, we could always revisit the logic and/or run a manual mutation daily/weekly to change the flags for the users.  I don't think we'll see enough users hitting the edge case during the test to make that worthwhile, but I could always be wrong!
