### ISSUE TITLE
Audit onboarding flow

### ISSUE THREAD

**Issue by acressall** [ParabolInc/parabol#9028]
### Design issue

To review:

- [x] Flow for P0
- [x] Flow for invited user

Outcomes:

- [x] List of ideas, sorted by impact & complexity added to Notion doc https://www.notion.so/parabol/Onboarding-Improvements-e02cce5464fa42f88a31b0ac9955adc7?pvs=4

**Comment by acressall** [comment]
Audit https://www.figma.com/file/xu8fHBxsck1SPmOzxnyiVf/Onboarding-Audit?type=whiteboard&t=TWj1EqJMo3xIwRdx-0

**Comment by jordanh** [comment]
Adding a note here:

- We've considered augmenting the onboarding flow in order to get demographic information in order to tailor the onboarding process
- One additional observation we've made is that folks who have exposure to tools with radically different UXes (Easyretro, Miro, etc.) sometimes struggle when the expect us to be "another X"
