### ISSUE TITLE
Activity Library v2: favourite activities UI

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9114]
Figma designs: https://www.figma.com/file/PmE9A2ryODVzFPjZFJn7qi/Parabol-Activity-Library?type=design&node-id=1036-28426&mode=design&t=EUnFT9A69gLQn38c-0

![Screenshot 2023-11-03 at 13 10 37](https://github.com/ParabolInc/parabol/assets/39854876/145c505d-94d2-49db-a155-7d09d6a2dfb1)
![Screenshot 2023-11-03 at 13 08 30](https://github.com/ParabolInc/parabol/assets/39854876/f2685bc1-2fe3-4b0f-a22b-af2c82952361)
![Screenshot 2023-11-03 at 13 11 24](https://github.com/ParabolInc/parabol/assets/39854876/60710921-efa8-4a4c-ad6c-fa906539b7da)
![Screenshot 2023-11-03 at 13 11 17](https://github.com/ParabolInc/parabol/assets/39854876/18a45e9a-76fb-441a-824e-b981aaf2ee63)

### AC

- [ ] Add favourites section next to "Quick Start" with a heart emoji
- [ ] Add empty state
- [ ] Add heart button to activity cards
- [ ] Add heart button to selected template
- [ ] Move heart button to toolbar on mobile
- [ ] Clicking the heart icon updates the UI but doesn't do anything more than that. Logic will be handled in a subsequent PR
- [ ] Include tooltip when hovering over heart button

**Comment by nickoferrall** [comment]
@enriquesanchez just want to check whether the heart button would appear at the bottom right of all activity cards? I see the design below doesn't have them:

![Screenshot 2023-11-03 at 13 17 01](https://github.com/ParabolInc/parabol/assets/39854876/0909dc7a-2ae9-4255-93d7-8d23daf2547d)


I'd imagine it would show the heart button in red. Clicking it would remove it from the favourites section?

**Comment by enriquesanchez** [comment]
@nickoferrall Ah yes, you are correct! The heart should be there for any activity you have favorited. Apologies, the heart in the card idea came after I worked on those mockups.

One thing that was left inconclusive and we need to revisit as part of this effort is the fact that the current hover interaction for cards shows the activity's contents:

![Captura de pantalla 2023-11-06 a la(s) 5 39 22 p m](https://github.com/ParabolInc/parabol/assets/3276087/6761df4f-1be9-45e4-a43b-76220027a4e9)

This hover effect clashes with the action of favoriting an activity, since both trigger on hover.  This is something we can look into together and find a better solution, @acressall would you be interested? I can't remember who nor where, but it was suggested to use the side-sheet pattern for showing activity details instead. I think there may be potential for a better solution there.

**Comment by nickoferrall** [comment]
Makes sense, thanks!

@enriquesanchez I saw this design for the hover: https://github.com/ParabolInc/parabol/issues/9116

Would that work with the heart action?

**Comment by enriquesanchez** [comment]
> Would that work with the heart action?

I think it'll be tricky, since the tooltip would sit on top of the heart toggle. This is one we need to pause and think more about. One immediate solution I can think of is to move the heart toggle to the left (bottom or top), since that's an are where it'll be unlikely for the tooltip to cover.

This is one where ideally we can sit together and find a better solution. Maybe Alicia, you and I can schedule some sync time?

**Comment by acressall** [comment]
@enriquesanchez feel free to put some time in my calendar!

**Comment by nickoferrall** [comment]
Perhaps the tooltip could open to the left instead of the right? That way, the heart could remain in the same place, and it wouldn't be covered by the tooltip?

Also, happy to chat sync!

**Comment by nickoferrall** [comment]
@enriquesanchez & @acressall just checking if this came up in the design meeting? Perhaps I could implement the tooltip opening to the left as a starting point and it could be changed later on?

**Comment by enriquesanchez** [comment]
@nickoferrall We didn't review this, but I prefer the heart to the left (this also avoids conflicts with the Premium tag placement) and the tooltip opening as expected to the right.

I still want to look at the side sheet pattern I mentioned above but I need a little more time. I will try to carve some time tomorrow to look at it.

**Comment by nickoferrall** [comment]
@enriquesanchez & @acressall sounds good. I think we should ship the activity library card UI (this PR https://github.com/ParabolInc/parabol/pull/9168) asap, but we'll need to have a tooltip or some UI that shows the template prompts first.

Perhaps I can implement the tooltip UI that you designed (see below), we ship the tooltip and card UI to production, and then I pause development until the designs that factor in the heart UI & premium label are ready? 

![image](https://github.com/ParabolInc/parabol/assets/39854876/a7425895-ea79-4149-b708-e38ae30b369c)

**Comment by enriquesanchez** [comment]
>but we'll need to have a tooltip or some UI that shows the template prompts first.

I think it's worth trying the tooltip. We did have one concern around timing between hover and displaying the tooltip, we want to make sure it's not annoying, as in you see tooltips all over the place as you move the pointer around. Maybe a short delay helps with this.

>Perhaps I can implement the tooltip UI that you designed (see below), we ship the tooltip and card UI to production, and then I pause development until the designs that factor in the heart UI & premium label are ready?

I like this plan 👍

**Comment by jordanh** [comment]
I feel it would be safe to release the AL to everybody, and then follow on with this. Will prioritize accordingly to the backlog now

**Comment by nickoferrall** [comment]
Hey @ackernaut, for the empty state, is there a good way to export the image from figma? When I click on the image and click export PNG, I see this:

<img width="839" alt="Screenshot 2024-04-24 at 20 45 18" src="https://github.com/ParabolInc/parabol/assets/39854876/ff9d2199-fbef-4ac3-ae32-876b04c5f675">


If not, I can work on recreating it with CSS.

Also, in the design, the heart emoji is white with a purple background, but this is the background colour for "Quick Start", so I think we need something else. Maybe the heart could be red? Not sure about the background colour. 

![Screenshot 2024-04-24 at 20 47 42](https://github.com/ParabolInc/parabol/assets/39854876/07d54b06-84a3-4638-af9f-c3925664f0c1)

![Screenshot 2024-04-24 at 20 48 44](https://github.com/ParabolInc/parabol/assets/39854876/d1065591-1817-4a8e-b4d7-1ce19728b0a9)

**Comment by ackernaut** [comment]
@nickoferrall thanks for asking!

Re: fav background image

It looks bad in preview because of the transparency. It should look good over a white background in the app. Here are a couple of files where I rasterized the image in Figma. (2x and 3x sizing)

<img width="840" alt="activity-library-favs-empty-2x" src="https://github.com/ParabolInc/parabol/assets/307286/e3c04e25-6aa4-4d30-83da-72adaa918788">

![activity-library-favs-empty-3x](https://github.com/ParabolInc/parabol/assets/307286/41e4be17-10c2-4f15-91fa-14e129f1d97a)

That makes it simple enough to drop in but the text isn’t HTML. We could consider just using the background shape and making the heart, circle, and text in code.

<img width="696" alt="al-favs-background-vector-2x" src="https://github.com/ParabolInc/parabol/assets/307286/585ccbd4-25f6-46a5-86ee-08ad24cbf776">

![al-favs-background-vector-3x](https://github.com/ParabolInc/parabol/assets/307286/67f21cdb-d15e-465f-9123-544f21dc48d1)

**Comment by nickoferrall** [comment]
Thank you, Terry! That's very helpful 🙏
