### ISSUE TITLE
embedder: CPU instance of embedding model ran on staging/production

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9462]
## Issue - Enhancement

@mattkrick and I did some napkin math to weigh using OpenAI's API vs.  Cloudflare AI workers and found we'd be paying mid-to-high five-figures ($10,000s) to embed our existing document set. It makes _great_ economic sense to host our own model.

### Acceptance Criteria (optional)
   - text-embeddings-inference (see docker/dev.yml) hosted in our production environment
      - future: plan to support running multiple instances of text-embeddings-inference running concurrently
         - future: plan to support running multiple instances of the same model-id behind a load balancer
         - future plan to support instances running with a different model-id param

**Estimated effort:** 13 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by rafaelromcar-parabol** [comment]
Ongoing PR to [add the Embedded to our Helm chart](https://github.com/ParabolInc/helm-charts/pull/61).

I'm also working on deploying the model you shared with me in our 1-1.

**Comment by rafaelromcar-parabol** [comment]
Text Embeddings Inference is already running in our Staging 🎉 We created our own Helm chart allowing us to easily deploy it.

Some notes:

> future: plan to support running multiple instances of the same model-id behind a load balancer

Supported by default in Kubernetes. The Helm chart is prepared to increase the number of replicas, and all pods are internally exposed through a Kubernetes Service.

> future plan to support instances running with a different model-id param

Also done. We would just need to deploy multiple releases of the same Helm chart. Each one called by the name of the model we set on them.

This issue is DONE 📕
