### ISSUE TITLE
Bug: creating a threaded reply in the demo crashes

### ISSUE THREAD

**Issue by Dschoordsch** [ParabolInc/parabol#9672]
Start the demo and advance to discussion. Reply to the first task created by the bot

https://parabol.sentry.io/issues/5254489567/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading '__typename')
  at map (./packages/client/components/ThreadedRepliesList.tsx:65:16)
  at Array.map (<anonymous>)
  at ThreadedRepliesList (./packages/client/components/ThreadedRepliesList.tsx:64:17)
  at Set.forEach (<anonymous>)
...
(30 additional frame(s) were not displayed)
```

**Comment by jordanh** [comment]
Prioritizing for triage this cycle

**Comment by Dschoordsch** [comment]
From tests it looks like #8094

**Comment by mattkrick** [comment]
Confirmed, this is broken using relay v14.1.0.
Upgrading to relay v18 has fixed this problem, and it does not require upgrading react to v18.
I need to do more QA before upgrading to v18 since there's a lot of breaking changes between v14 & v18.
My suspicion is that relay wasn't using react's scheduler, so react could render a child component before rendering its parent. See https://github.com/facebook/relay/issues/3514#issuecomment-988303222
