### ISSUE TITLE
Admin Nav: public teams toggle

### ISSUE THREAD

**Issue by nickoferrall** [ParabolInc/parabol#9793]
From https://github.com/ParabolInc/parabol/issues/9781

### Public Teams Toggle
- [This toggles](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=39-2965&t=XlnNDmMHL9H69kaK-11) the [full list of public teams](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=39-2965&t=XlnNDmMHL9H69kaK-11)
- Optional: instead of showing public teams in an expanded nav area, why not just show the list in a dialog? Folks could tap a team to see [the view to request joining the team](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=68-2355&t=XlnNDmMHL9H69kaK-11). We might want to add the team name to the request to join area for context.

**Comment by ackernaut** [comment]
Here’s an initial look at a dialog ([see Figma](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=214-2505&t=UKiC0gYG7bVGXFDu-11))

**Comment by ackernaut** [comment]
@nickoferrall a couple of ideas:
- [We give inline feedback](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=270-2544&t=nr7rsBan2Mx6KNqW-11) when they tap the Request link. They can then send a request for another team if they’d like. They have to manually close (tap outside of the dialog, the X, hit esc, etc.) otherwise
- Upon tapping the Request link, we close the dialog for them and [pop up a Snackbar notification](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=270-2702&t=nr7rsBan2Mx6KNqW-11)

What do you think?

**Comment by nickoferrall** [comment]
I prefer the first option as a user might want to request to join multiple teams. 

I also think users might not know what "Public Teams" mean, so we could include a subtitle? Something like: "These teams exist in [ORG_NAME], but you're not a member of them yet"

**Comment by ackernaut** [comment]
I took a pass to [add a description](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=214-2505&t=YR9iudEbMVfQicRu-11). Also, I’m starting to think what it might look like [to subscribe to a team](https://www.figma.com/design/eGGewFjqfNpfU3TUgaBSDo/Insights-UI-Views?node-id=418-2874&t=YR9iudEbMVfQicRu-11) in the future. That’s just a first bad idea and something to work out later.

**Comment by nickoferrall** [comment]
Love it!
