### ISSUE TITLE
Env var to disable integration providers

### ISSUE THREAD

**Issue by jordanh** [ParabolInc/parabol#9879]
## Issue - Enhancement

Most deployments at elevated security levels disallow the usage of Jira Cloud vs. Jira Server. Removing this integrations from the product would be beneficial to the user experience. Folks are already clicking Jira Cloud and getting an error when they should be clicking "Jira Server" instead.

### Acceptance Criteria (optional)
Admin/SREs can:
   - Set an environment variable that blacklists certain integrations
   - Refer to documentation to tell them what the env var is and how to set it

**Estimated effort:** 8 points ([see CONTRIBUTING.md](https://github.com/ParabolInc/parabol/blob/master/CONTRIBUTING.md#points-and-sizes))

**Comment by rafaelromcar-parabol** [comment]
This could be an opportunity to manage the available integrations per organization or team, instead of per Parabol instance. Using flags in the database. In the future this could even be managed through an admin backoffice or directly by the lead of the organization.

Example using our own SaaS: we also have organizations that use Jira Server instead of Jira Cloud. An enterprise support might want to disable that integration (or any other) from one or more teams.

WDYT?

**Comment by Dschoordsch** [comment]
@rafaelromcar-parabol I think that's a good idea for the future. For this issue however I would say we should do the minimal effort to reach the goal.
Right now we have 2 main ways of adding integrations:
1. GCal, Azure DevOps, Gitlab and Jira Server are implemented as integration providers and these show up only if they are configured for the instance, organization or team. Usually we configure this via `primeIntegration` on deployment based on environment variables.
2. The rest (including Atlassian Cloud) is always available, even if the environment variables are not set up correctly. Ideally we would convert these to 1., but for now we should just hide the rows if the required OAUTH variables are not set.
